### PR TITLE
Robustify detection of changes during initialization

### LINKED ISSUE #11803: [BUG] Message containing ModelChangeEvents for all properties sent back to server on initialization
Starting in Bokeh 2.4.0 the frontend has started sending back ModelChangeEvents to the server containing basically all the changed model properties after initialization resulting in a huge dump of data being sent back to the server. In the worst case this message is larger than the allowed websocket size, breaking the application entirely. This can easily be reproduced by creating a plot with a decent amount of data and serving it, e.g.:

```python
import numpy as np

from bokeh.io import curdoc
from bokeh.plotting import figure

xs = np.linspace(0, np.pi, 20000)
sin = np.sin(xs*2)
cos = np.cos(xs*4)

p = figure()

p.line(xs, sin)
p.line(xs, cos)

curdoc().add_root(p)
```

In this example you can watch the websocket and see this huge event being sent back:

Screen Shot 2021-11-15 at 8 02 29 PM

if you instead use Bokeh 2.3.x you see only a very small message being sent:

Screen Shot 2021-11-15 at 8 03 16 PM

This seems like a **huge** regression causing a whole lot of unnecessary network traffic.

### PR DESCRIPTION
**Pull request by mattpap**
This is a proof of concept. This removes `Document._compute_patch_since_json()` and changes when document is attached to models during initialization. This way we can use ordinary handling of model change events to propagate changes, that happen during initialization of models, to server.

- [x] API design
- [x] tests

fixes #11803

### CODE REVIEW

File: bokehjs/src/lib/core/has_props.ts [hunk 1]
```diff
@@ -536,8 +522,12 @@ export abstract class HasProps extends Signalable() implements Equatable, Printa
...
   attach_document(doc: Document): void {
     // This should only be called by the Document implementation to set the document field
-    if (this.document != null && this.document != doc)
-      throw new Error("models must be owned by only a single document")
+    if (this.document != null) {
+      if (this.document == doc)
+        return
+      else
+        throw new Error("models must be owned by only a single document")
+    }
```
Comment (bryevdv) [inline bokehjs/src/lib/core/has_props.ts:530]: Why prefer a nested conditional here?

File: bokehjs/test/unit/document/document.ts [hunk 2]
```diff
@@ -123,45 +122,6 @@ class ModelWithConstructTimeChanges extends Model {
...
-    this.define<ComplicatedModelWithConstructTimeChanges.Props>(({Array, Dict, Ref}) => ({
-      list_prop:         [ Array(Ref(AnotherModel)) ],
-      dict_prop:         [ Dict(Ref(AnotherModel)) ],
-      obj_prop:          [ Ref(ModelWithConstructTimeChanges) ],
-      dict_of_list_prop: [ Dict(Array(Ref(Model))) ],
-    }))
-  }
-}
-
-Models.register("ComplicatedModelWithConstructTimeChanges", ComplicatedModelWithConstructTimeChanges)
```
Comment (bryevdv) [inline bokehjs/test/unit/document/document.ts:163]: Why not preserve a test for the complicated model?

File: bokehjs/src/lib/document/events.ts [hunk 3]
```diff
@@ -76,6 +91,12 @@ export class MessageSentEvent extends DocumentChangedEvent {
     super(document)
   }
 
+  override [equals](that: this, cmp: Comparator): boolean {
+    return super[equals](that, cmp) &&
+      cmp.eq(this.msg_type, that.msg_type) &&
+      cmp.eq(this.msg_data, that.msg_data)
```
Comment (bryevdv) [inline bokehjs/src/lib/document/events.ts:97]: It would be good for these comparators to themselves have tests

File: bokehjs/src/lib/core/has_props.ts (hunk 1 above)
Comment (mattpap) [reply bokehjs/src/lib/core/has_props.ts:530]: I'm not sure how else would you write this.

File: bokehjs/test/unit/document/document.ts (hunk 2 above)
Comment (mattpap) [reply bokehjs/test/unit/document/document.ts:163]: I don't see a need for a complex test here, because the purpose of testing this PR is to make sure we can collect change events, whatever they are. A simple tests suffices for this. We don't need to test here whether `HasProps` can detect changes and generate appropriate events. That should be tested in `HasProps`' unit tests, if it's not already.

**Comment by mattpap** [comment]
Test failure is unrelated.
