### PR TITLE
use correct zoom scale factors

### LINKED ISSUE #11838: [BUG] incorrect scalling for the zoom-out tool
### Software versions

Python version : 3.9.7
IPython version : 7.28.0
Tornado version : 6.1
Bokeh version : 2.4.0

### Browser name and version

_No response_

### Jupyter notebook / Jupyter Lab version

_No response_

### Expected behavior

Pressing the Zoom-out button should zoom out by 10% by default or by the provided factor.

### Observed behavior

The scalling resulting of a zoom-out does not match the zooming factor.
Zooming in and out successively will result in a different scalling.

* Observed ranges with a **10%** zoom in and out :
`[0, 100]` -> Zoom-in `0.1` -> `[ 5, 95 ]` -> Zoom-out `0.1` -> `[ 0.49999, 99.5 ]`

* Observed ranges with a **50%** zoom in and out :
`[0, 100]` -> Zoom-in `0.5` -> `[ 25, 75 ]` -> Zoom-out `0.5` -> `[ 12.5, 87.5 ]`

* Observed ranges with a **50%** zoom in and **100%** zoom out :
`[0, 100]` -> Zoom-in `0.5` -> `[ 25, 75 ]` -> Zoom-out `1` -> `[ 2.5, 97.5 ]`

### Example code

```Python
from bokeh.plotting import figure, show
from bokeh.models import ZoomInTool, ZoomOutTool

p = fig(width=700, height=200, tools='reset')
p.y_range.start, p.y_range.end = (0, 1)
p.x_range.start, p.x_range.end = (0, 100)
p.line([0, 50, 100], [0, 1, 0])

p.add_tools(ZoomInTool(dimensions="width", factor=0.5))
p.add_tools(ZoomOutTool(dimensions="width", factor=0.5))
show(p)
```

### Stack traceback or browser console output

From the source, the zoom-out tool doesn't apply the multiplicative inverse of the factor:

https://github.com/bokeh/bokeh/blob/ca239b9a92605710f4ea6681da29696979d98824/bokehjs/src/lib/core/util/zoom.ts#L9-L15

This is a simplified example with the current implementation :
```
zoom-in  : amplitude *  (1 - factor)  =  100  * (1 - 0.1) = 90
zoom-out : amplitude *  (1 + factor)  =  90   * (1 + 0.1) = 99
```

With a multiplicative inverse, the result would be better :
```
zoom-in  : amplitude *  (1 - factor)  =  100 * (1 - 0.1) = 90
zoom-out : amplitude /  (1 - factor)  =  90  / (1 - 0.1) = 100
```

Is there a reason as to why the zoom-out was not implemented with a multiplicative inverse ?

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by bryevdv**
- [x] issues: fixes #11838
- [x] tests added / passed

Proper inverse factors for the way we compute things (about a center):

```python
# zoom in, factor = 0.1
# low = 0 - (0 - 10) * 0.1 = 1
# hi = 20 - (20 - 10) * 0.1 = 19

# zoom out, factor = 0.1
# low = 1 - (1 - 10) * -0.1/(1-0.1) = 0
# hi = 19 - (19 - 10) * -0.1/(1-0.1) = 20
```

I have updated the zoom-in and zoom-out tests to mirror each other as inverses.

### CODE REVIEW

File: bokehjs/src/lib/core/util/zoom.ts [hunk 1]
```diff
@@ -49,9 +48,6 @@ export function scale_range(frame: CartesianFrame, factor: number,
    *   ScaleRange
    */
 
-  // clamp the  magnitude of factor, if it is > 1 bad things happen
-  factor = clamp(factor, -0.9, 0.9)
```
Comment (bryevdv) [inline bokehjs/src/lib/core/util/zoom.ts:53]: This does not seem necessary, and in fact interferes with large scale values for the zoom out tool, which easily end up > 1
