### PR TITLE
delay match_aspect adjustment

### LINKED ISSUE #7128: When embeding bokeh server to flask, AttributeError: 'NoneType' object has no attribute '_id' shows up
I just want to embed the bokeh server into flask

I tried the following simple example but just cannot understand what's going on...

(python version = 2.7.12)
(bokeh version = 0.12.10)
(flask version = 0.12.2)

app.py
```
from flask import Flask, render_template
from bokeh.embed import autoload_server
from bokeh.client import pull_session

app = Flask(__name__)

@app.route("/")

def index():
	session = pull_session(url="http://localhost:5006/test_for_animation")
	bokeh_script = autoload_server(None, url="http://localhost:5006/test_for_animation", session_id=session.id)
	return render_template("index.html", bokeh_script=bokeh_script)

if __name__ == "__main__":
	app.run(debug=True)
```

test_for_animation.py
```
from bokeh.models import HoverTool, CrosshairTool, ColumnDataSource
from bokeh.layouts import widgetbox, row
from bokeh.plotting import figure, curdoc
from bokeh.models.widgets import TextInput, Button
from random import randrange

f=figure(x_range=(0,11), y_range=(0,11))
source = ColumnDataSource(data=dict(x=[], y=[]))
f.circle(x="x", y="y", size=8, color="olive", source=source)

def update():
	new_data = dict(x=[randrange(1,10)], y=[randrange(1,10)])
	source.stream(new_data, rollover=15)
	print(source.data)

curdoc().add_root(f)
curdoc().add_periodic_callback(update, 1000)
```

index.html
```
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Document</title>
<body>
	<h3>I am a heading</h3>
	<div>
		{{bokeh_script|safe}}
	</div>
	<h3>I am a footer</h3>
</body>
</html>
```

The error is

 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 291-452-623
/usr/local/lib/python2.7/dist-packages/bokeh/util/deprecation.py:34: BokehDeprecationWarning: bokeh.embed.autoload_server was deprecated in Bokeh 0.12.7 and will be removed, use bokeh.embed.server_document or bokeh.embed.server_session instead.
  warn(message)
127.0.0.1 - - [30/Oct/2017 12:57:09] "GET / HTTP/1.1" 500 -
INFO:werkzeug:127.0.0.1 - - [30/Oct/2017 12:57:09] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/bigmoumou/Desktop/python/bokeh/tutorial/animation/app.py", line 10, in index
    bokeh_script = autoload_server(None, url="http://localhost:5006/test_for_animation", session_id=session.id)
  File "/usr/local/lib/python2.7/dist-packages/bokeh/embed/__init__.py", line 62, in autoload_server
    return server_session(model, session_id, url, relative_urls, "default", arguments)
  File "/usr/local/lib/python2.7/dist-packages/bokeh/util/api.py", line 190, in wrapper
    return obj(*args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/bokeh/embed/server.py", line 188, in server_session
    modelid   = model._id,
AttributeError: 'NoneType' object has no attribute '_id'

### LINKED ISSUE #7218: circle not circular
#### Version Information:

On Mac OS X 10.13.1 (High Sierra)
Python:  2.7.13 |Continuum Analytics, Inc.| (default, Dec 20 2016, 23:05:08) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]
IPython:  5.3.0
Bokeh:  0.12.10

#### Problem: 

When using `p.circle(...)`, the rendered circle is not perfectly circular.  The `x` dimension seems to render according to the supplied radius argument, but the `y` dimension is visibly short of the specified radius.

#### To reproduce:

The following code creates the screenshot below:

```
    from bokeh.plotting import figure, output_file, show

    output_file("circle_v1.html")

    p = figure(plot_width=400, plot_height=400, match_aspect=True, tools='save')
    p.circle(0, 0, radius=1.0, fill_alpha=0)
    p.line((0, 1), (0, 0))
    p.line((0, -1), (0, 0))
    p.line((0, 0), (0, 1))
    p.line((0, 0), (0, -1))
    #p.rect(0, 0, 2, 2, fill_alpha=0)

    show(p)
```
bokeh_plot 9

Note: When you uncomment the line beginning with `#p.rect(...` the dimensions of the rendered circle seem fine.  e.g.:

bokeh_plot 10

Best,

Travis

### PR DESCRIPTION
**Pull request by bryevdv**
The commit moves the aspect ratio adjust (for a single plot update) to after the unioned bounds are computed for the DataRange renderers. Previously the aspect correction happened on all the individual renderer bounds, before the call to update. This could result in incorrect aspect-corrected overall bounds in some situations.

Note: use of match_aspect with linked DataRange1d across multiple plots will probably yield undefined/undesirable behavior and should be considered unsupported.

- [x] issues: fixes #7218
- [x] tests added / passed
- [x] release document entry (if new feature or API change)
#

### CODE REVIEW

**Comment by bryevdv** [comment]
Want to see how CI report looks, do additional local testing, and update docs to warn about `match_aspect` usage with linked data ranges.

File: bokehjs/src/coffee/models/plots/plot_canvas.coffee [hunk 1]
```diff
@@ -216,43 +216,24 @@ export class PlotCanvasView extends DOMView
     follow_enabled = false
     has_bounds = false
 
+    unioned_bounds =
+
+    r = null
     if @model.plot.match_aspect != false and @frame._width.value != 0 and @frame._height.value != 0
       r = 1/@model.plot.aspect_scale*(@frame._width.value/@frame._height.value)
```
Comment (bryevdv) [inline bokehjs/src/coffee/models/plots/plot_canvas.coffee]: @mattpap Is there a better way to do this / communicate an optional ratio to the subsequent calls to `update` below?

**Comment by bryevdv** [comment]
With this change the original issue code looks as expected:

screen shot 2017-12-21 at 12 33 21

File: bokehjs/src/coffee/models/plots/plot_canvas.coffee [hunk 2]
```diff
@@ -216,43 +216,22 @@ export class PlotCanvasView extends DOMView
     follow_enabled = false
     has_bounds = false
 
+    r = null
```
Comment (bryevdv) [inline bokehjs/src/coffee/models/plots/plot_canvas.coffee]: @mattpap  is there a better way to subsequently communicate this optional value to `update` ?

Comment (mattpap) [reply bokehjs/src/coffee/models/plots/plot_canvas.coffee]: No, this is idiomatic javascript.

File: bokehjs/src/coffee/models/ranges/data_range1d.ts [hunk 3]
```diff
@@ -180,14 +206,19 @@ export class DataRange1d extends DataRange {
...
     if (this.have_updated_interactively)
       return
 
     const renderers = this.computed_renderers()
 
     // update the raw data bounds for all renderers we care about
-    this._plot_bounds[bounds_id] = this._compute_plot_bounds(renderers, bounds)
+    let total_bounds = this._compute_plot_bounds(renderers, bounds)
+
+    if (r != null)
```
Comment (mattpap) [inline bokehjs/src/coffee/models/ranges/data_range1d.ts]: This should have resulted in an error, because `r` is a `number`, not `number | null` (or similar), but apparently it compiles. Looks like another bug in the compiler. Anyway, given `r` optional nature, the signature of this method should be changed to `r?: number`. I would also change `r` to something more meaningful (`ratio`, `aspect_ratio`).

File: bokehjs/src/coffee/models/ranges/data_range1d.ts [hunk 4]
```diff
@@ -93,6 +93,32 @@ export class DataRange1d extends DataRange {
     return result
   }
 
+   adjust_bounds_for_aspect(bounds: Rect, r: number) : Rect {
+    let result = bbox.empty()
```
Comment (mattpap) [inline bokehjs/src/coffee/models/ranges/data_range1d.ts]: `const`.

File: bokehjs/src/coffee/models/ranges/data_range1d.ts [hunk 5]
```diff
@@ -93,6 +93,32 @@ export class DataRange1d extends DataRange {
     return result
   }
 
+   adjust_bounds_for_aspect(bounds: Rect, r: number) : Rect {
```
Comment (mattpap) [inline bokehjs/src/coffee/models/ranges/data_range1d.ts]: Whitespace.
