### PR TITLE
Correctly process ImageStack data for hover tooltips

### LINKED ISSUE #13452: [BUG] ImageStack hover tooltip shows incorrect numbers
### Software versions

Python version        :  3.10.12 | packaged by conda-forge | (main, Jun 23 2023, 22:41:52) [Clang 15.0.7 ]
IPython version       :  8.15.0
Tornado version       :  6.3.3
Bokeh version         :  3.4.0.dev1+8.g6022971e.dirty
BokehJS static path   :  /Users/iant/github/bokeh/src/bokeh/server/static
node.js version       :  v18.17.1
npm version           :  9.6.7
jupyter_bokeh version :  (not installed)
Operating system      :  macOS-13.6-arm64-arm-64bit

### Browser name and version

_No response_

### Jupyter notebook / Jupyter Lab version

_No response_

### Expected behavior

See example code and screenshot below.  The underlying `image` data under the cursor has values `5, 7` but the hover tooltip shows `0, 2` instead.

### Observed behavior

Data values are displayed after the NaN-aware minimum has been subtracted.

### Example code

```Python
import numpy as np
from bokeh.models import EqHistColorMapper, WeightedStackColorMapper
from bokeh.palettes import varying_alpha_palette
from bokeh.plotting import figure, show

colors = ["red", "blue"]
stack = np.asarray([[[5, 5], [5, 6]], [[5, 7], [5, 8]]])

p = figure(width=400, height=300, tooltips=[("values", "@image")])

alpha_mapper = EqHistColorMapper(
    palette=varying_alpha_palette(color="#000", n=10, start_alpha=40),
    rescale_discrete_levels=False,
)
color_mapper = WeightedStackColorMapper(
    palette=colors, nan_color=(0, 0, 0, 0), alpha_mapper=alpha_mapper
)
im = p.image_stack(image=[stack], x=0, y=0, dw=1, dh=1, color_mapper=color_mapper)
p.add_layout(im.construct_color_bar(), "right")

show(p)
```

### Stack traceback or browser console output

Thanks to @Hoxbro for first identifying this.

The problem actually occurs in `WeightedStackColorMapper` which modifies the `data` passed to it. This data should be considered constant/readonly as it is actually the original supplied data not some intermediate data that can be modified.

### Screenshots

Screenshot 2023-10-17 at 11 30 27

### PR DESCRIPTION
**Pull request by ianthomas23**
FIxes bug in `ImageStack` colormapping where we were modifying the user-supplied `image` data directly to deal with the `color_baseline` (user-specified or minimum of supplied data). The `ImageStack` rendered correctly but the hover tooltip was wrong. There was also a similar incorrect offset in color bar limits. This avoids changing the supplied `image` data and corrects the color bar limits. I have changed the existing tests which rather simplistically always had a minimum value of 0 so subtracting the minimum value had no effect.

- [x] issues: fixes #13452
- [x] tests added / passed
- [ ] release document entry (if new feature or API change)

The image produced by the example listed in the issue is now:
first

A more complicated example directly comparing Bokeh and Datashader doing the colormapping:
```python
from bokeh.models import EqHistColorMapper, WeightedStackColorMapper
from bokeh.palettes import varying_alpha_palette
from bokeh.plotting import figure, row, show
import datashader.transfer_functions as tf
import numpy as np
import xarray as xr

n = 20
min_alpha = 40
color_baseline = None
colors = ["red", "green", "blue"]

def categorical_data():
    samples = 1000
    rng = np.random.default_rng(92478)

    centers = [(0.3, 0.3), (0.7, 0.5), (0.3, 0.7)]
    radii = [0.2, 0.3, 0.15]
    ncats = len(radii)

    dx = 1.0/n
    data = np.zeros((n, n, ncats), dtype=np.uint32)

    for k in range(ncats):
        x = rng.normal(centers[k][0], radii[k], samples)
        y = rng.normal(centers[k][1], radii[k], samples)
        i = (x / dx).astype(int)
        j = (y / dx).astype(int)
        for ii, jj in zip(i, j):
            if 0 <= ii < n and 0 <= jj < n:
                if np.isnan(data[jj, ii, k]):
                    data[jj, ii, k] = 1
                else:
                    data[jj, ii, k] += 1
    return data

data = categorical_data()
data += 5

ps = []
for i in range(2):
    title = "Bokeh" if i == 0 else "Datashader"
    kwargs = dict(width=420, height=350, title=f"Colormapping in {title}")
    kwargs["tooltips"] = [("values", "@image")]
    if i > 0:
        kwargs["x_range"] = ps[0].x_range
        kwargs["y_range"] = ps[0].y_range
        kwargs["width"] = 350
    p = figure(**kwargs)
    ps.append(p)

    if i == 0:  # Bokeh colormapping
        alpha_mapper = EqHistColorMapper(palette=varying_alpha_palette(color="#000", n=10, start_alpha=min_alpha))
        color_mapper = WeightedStackColorMapper(
            palette=colors, nan_color=(0, 0, 0, 0),
            alpha_mapper=alpha_mapper, color_baseline=color_baseline,
        )
        im = p.image_stack(image=[data], x=0, y=0, dw=1, dh=1, color_mapper=color_mapper)

        color_bar = im.construct_color_bar()
        p.add_layout(color_bar, "right")
    else:  # Datashader colormapping
        coords = np.arange(n, dtype=np.float64)
        cat = ["A", "B", "C"]  # <U1 "F" "M"
        da = xr.DataArray(data=data, dims=["y", "x", "cat"],
            coords=dict(x=coords, y=coords, cat=["A", "B", "C"]))
        im = tf.shade(
            da, color_key=colors, min_alpha=min_alpha,
            color_baseline=color_baseline,
        ).to_numpy()
        p.image_rgba(image=[im], x=0, y=0, dw=1, dh=1)

show(row(ps))
```
second

### CODE REVIEW

File: bokehjs/src/lib/models/mappers/weighted_stack_color_mapper.ts [hunk 1]
```diff
@@ -125,7 +121,7 @@ export class WeightedStackColorMapper extends StackColorMapper {
       }
 
       values[i] = this._mix_colors(palette_as_rgba, nan_color, weights, total)
-      totals[i] = total
+      totals[i] = total + baseline*ncolor
```
Comment (ianthomas23) [inline bokehjs/src/lib/models/mappers/weighted_stack_color_mapper.ts:124]: Note to self: need to consider if this is correct in the presence of NaN.

Comment (ianthomas23) [reply bokehjs/src/lib/models/mappers/weighted_stack_color_mapper.ts:124]: Yes, this is correct.

**Review by mattpap — APPROVED** [review]
