### PR TITLE
Canavandl/6521 deprecate tool events

### LINKED ISSUE #6521: Deprecate ToolEvents
The `ToolEvent` class does not work well at all. It should be replaced with new style events from `bokeh.events` that tools can generate when appropriate. 

Adding this to `0.12.7` because we should try to mark all planned deprecations by `0.12.7` if possible. 

ping @jlstevens

### PR DESCRIPTION
**Pull request by canavandl**
- [x] issues: fixes #6521 
- [x] tests added / passed
- [x] release document entry (if new feature or API change)

### CODE REVIEW

File: bokehjs/src/coffee/models/tools/gestures/select_tool.coffee [hunk 1]
```diff
@@ -59,16 +60,7 @@ export class SelectToolView extends GestureToolView
...
-      tool_events = @plot_model.plot.tool_events
-      if append
-        geoms = tool_events.geometries
-        geoms.push(g)
-      else
-        geoms = [g]
-
-      tool_events.geometries = geoms
-    return null
+    @plot_model.plot.trigger_event(new Selection({geometry: g}))
```
Comment (bryevdv) [inline bokehjs/src/coffee/models/tools/gestures/select_tool.coffee]: We might want to include `final` in the event? That would provide a way for event handlers to filter and ignore intermediate selection geometries if desired.

Comment (canavandl) [inline bokehjs/src/coffee/models/tools/gestures/select_tool.coffee]: that's a good idea. I'll add it now.

**Comment by bryevdv** [comment]
@canavandl is `Selection` the best name? I think it might be better to be more specific `SelectionGeometry` or something that conveys that it conveys the geometry information (and not e.g. the selection indicies)
