### PR TITLE
BokehJS API fixes

### LINKED ISSUE #2306: Fix issues preventing BokehJS 0.9 working on JSFiddle site

### PR DESCRIPTION
**Pull request by bryevdv**
issues: fixes #2306

### CODE REVIEW

File: bokehjs/src/coffee/renderer/guide/categorical_axis.coffee [hunk 1]
```diff
@@ -13,6 +9,7 @@ class CategoricalAxis extends Axis.Model
 
   initialize: (attrs, objects) ->
     super(attrs, objects)
+    Collections = require("../../common/base").Collections
```
Comment (fpliger) [inline bokehjs/src/coffee/renderer/guide/categorical_axis.coffee]: to better understand, are you moving this here for a technical reason or just for scope isolation?

**Comment by fpliger** [comment]
LGTM

File: bokehjs/src/coffee/renderer/guide/categorical_axis.coffee (hunk 1 above)
Comment (bryevdv) [inline bokehjs/src/coffee/renderer/guide/categorical_axis.coffee]: I moved it to make it work. `.Collections` is undefined if I put it at the top. Not entirely sure why. It would be nice to at least understand, though. @tswicegood any ideas?

Comment (tswicegood) [inline bokehjs/src/coffee/renderer/guide/categorical_axis.coffee]: As an abstract (I didn't dig into the code), I believe it's an import order issue.

* Start loading common/base
* Leave common/base while trying to load this file
* This file references common/base, but it hasn't finished loading and Collections isn't defined

Moving this to execute at runtime instead of import time means that `.Collections` has been added to the common/base module.
