### PR TITLE
Fix scoping issue for box edit tool coordinates

### LINKED ISSUE #13500: [BUG] Box edit tool using all supported glyphs
### Software versions

Python version        :  3.10.13 | packaged by conda-forge | (main, Oct 26 2023, 18:07:37) [GCC 12.3.0]
IPython version       :  8.17.2
Tornado version       :  6.3.3
Bokeh version         :  3.4.0.dev3+9.gd6201574.dirty
BokehJS static path   :  bokeh/src/bokeh/server/static
node.js version       :  v20.8.1
npm version           :  10.1.0
jupyter_bokeh version :  (not installed)
Operating system      :  Linux-6.5.9-arch1-Ototsuku-T2-1-t2-x86_64-with-glibc2.38

### Browser name and version

N/A

### Jupyter notebook / Jupyter Lab version

N/A

### Expected behavior

All supported glyphs would allow for box editing to happen.

### Observed behavior

As can be seen in the below video, some glyph types do not allow for adding new glyphs.

[box-edit-bug.webm](https://github.com/bokeh/bokeh/assets/60523020/128abe7a-d549-4e89-bd35-c58aebed3c0b)

### Example code

```Python
# box_edit.py
import numpy as np
import panel as pn

from bokeh.layouts import gridplot
from bokeh.models.sources import ColumnDataSource
from bokeh.models.tools import BoxEditTool
from bokeh.plotting import figure

pn.extension()

glyphs = ["rect", "block", "quad", "hbar", "vbar", "hstrip", "vstrip"]
figures = []
for glyph in glyphs:
    fig = figure(
        x_range=(0, 10),
        y_range=(0, 10),
        width=400,
        height=400,
        title=f"Box Edit Tool using glyph type: {glyph}",
    )
    if glyph == "rect":
        data = {
            "x": [5, 2, 8],
            "y": [5, 7, 8],
            "width": [2, 1, 2],
            "height": [2, 1, 1.5],
            "alpha": [0.5, 0.5, 0.5],
        }
        cds = ColumnDataSource(data=data)
        renderers = fig.rect(x="x", y="y", width="width", height="height", source=cds, alpha="alpha")
    if glyph == "block":
        data = {"x": [1, 2, 3], "y": [1, 2, 3], "width": [0.2, 0.5, 0.1], "height": [1.5] * 3}
        cds = ColumnDataSource(data=data)
        renderers = fig.block(x="x", y="y", width="width", height="height", source=cds)
    if glyph == "quad":
        N = 9
        x = np.linspace(-2, 2, N)
        y = x ** 2
        data = {
            "left": x,
            "top": y,
            "right": x-x**3/10 + 0.3,
            "bottom": y-x**2/10 + 0.5,
        }
        cds = ColumnDataSource(data=data)
        renderers = fig.quad(left="left", top="top", right="right", bottom="bottom", source=cds)
    if glyph == "hbar":
        N = 9
        y = np.linspace(-2, 2, N)
        x = y**2
        data = {"left": [0] * N, "y": y, "height": [0.5] * N, "right": x}
        cds = ColumnDataSource(data=data)
        renderers = fig.hbar(left="left", y="y", height="height", right="right", source=cds)
    if glyph == "vbar":
        N = 9
        y = np.linspace(-2, 2, N)
        x = y**2
        data = {"x": x, "top": y, "bottom": [0] * N, "width": [0.5] * N}
        cds = ColumnDataSource(data=data)
        renderers = fig.vbar(x="x", top="top", bottom="bottom", width="width", source=cds)
    if glyph == "hstrip":
        data = {"y0": [4.5, 6.0, 8.0], "y1": [5.0, 7.0, 9.5]}
        cds = ColumnDataSource(data=data)
        renderers = fig.hstrip(y0="y0", y1="y1", source=cds)
    if glyph == "vstrip":
        data = {"x0": [4.5, 6.0, 8.0], "x1": [5.0, 7.0, 9.5]}
        cds = ColumnDataSource(data=data)
        renderers = fig.vstrip(x0="x0", x1="x1", source=cds)

    draw_tool = BoxEditTool(renderers=[renderers], empty_value=1)
    fig.add_tools(draw_tool)
    fig.toolbar.active_drag = draw_tool
    figures.append(fig)

layout = gridplot(figures, ncols=3)

app = pn.pane.Bokeh(layout)
app.servable()
```

### Stack traceback or browser console output

_No response_

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by ndmlny-qs**
This commit modifies the name of the x & y coordinates that use the box edit tool, as the original name collided with a few glyph types.

All pull requests must have an associated issue in the issue tracker. If there
isn't one, please go open an issue describing the defect, deficiency or desired
feature. You can read more about our issue and PR processes in the
[wiki](https://github.com/bokeh/bokeh/wiki/BEP-1:-Issues-and-PRs-management).

- [ ] issues: fixes #13500 
- [ ] tests added / passed
- [ ] release document entry (if new feature or API change)

### CODE REVIEW

**Comment by ndmlny-qs** [comment]
The changes all for all supported glyph types to add boxes using the box edit tool. The linking issue shows the issue, and the below video shows the fix in action.

[box-edit-fix.webm](https://github.com/bokeh/bokeh/assets/60523020/dbb2fcfd-a2ac-43d4-b2f5-27ba550c7ac5)

**Comment by bryevdv** [comment]
Honestly a little surprised this doesn't cause a compile error. Solution LGTM but I think @mattpap is back tomorrow so I'll give him a little more time to chime in with any comments. Otherwise we'll want to get this in 3.3.1 as well.

**Comment by bryevdv** [comment]
@ndmlny-qs maybe it's just a video artifact, the new hbar case in video seemed a little off (the drawn hbar did not seem to correspond to your cursor) can you confirm that it functions correctly in actual practice?

**Comment by ndmlny-qs** [comment]
@bryevdv you are correct, the `hbar` and `vbar` cases do have an offset when drawing. I'll investigate further.

**Comment by bryevdv** [comment]
@ndmlny-qs hbar and vbar are center-positioned along their "axis" so my first guess is that those coordinate computations were wrong to begin with, and need to be averages (e.g `(ry0 + ry1) / 2` for `hbar`)

File: bokehjs/src/lib/models/tools/edit/box_edit_tool.ts [hunk 1]
```diff
@@ -59,73 +59,73 @@ export class BoxEditToolView extends EditToolView {
       return
     const {glyph} = renderer
     const cds = renderer.data_source
-    const [x0, x1] = renderer_view.coordinates.x_scale.r_invert(sx0, sx1)
-    const [y0, y1] = renderer_view.coordinates.y_scale.r_invert(sy0, sy1)
+    const [rx0, rx1] = renderer_view.coordinates.x_scale.r_invert(sx0, sx1)
+    const [ry0, ry1] = renderer_view.coordinates.y_scale.r_invert(sy0, sy1)
```
Comment (mattpap) [inline bokehjs/src/lib/models/tools/edit/box_edit_tool.ts]: `r` in `r_invert` stands for "range", but the conversion is from screen to data coordinates, so it would make more sense to use `d` prefix.

File: bokehjs/src/lib/models/tools/edit/box_edit_tool.ts [hunk 2]
```diff
@@ -59,73 +59,73 @@ export class BoxEditToolView extends EditToolView {
...
     const fields = (() => {
```
Comment (mattpap) [inline bokehjs/src/lib/models/tools/edit/box_edit_tool.ts]: This would have caught the problem at the type-level:
```suggestion
    const fields: {[key: string]: number} | null = (() => {
```

**Comment by ndmlny-qs** [comment]
There is still an issue around the cursor being off going in the opposite direction of where you start to add the box in the `hbar` and `vbar` cases; see below. I'm not sure what the fix for this is, as the cursor position for the screen and data always have `[s|d]x0 < [s|d]x1` or `[s|d]y0 < [s|d]y1`.

[hbar-vbar.webm](https://github.com/bokeh/bokeh/assets/60523020/f1a5818c-06dc-4c00-912f-fb008f9889a6)

**Comment by bryevdv** [comment]
@ndmlny-qs did you try averaging the "center" coordinate as I suggested earlier? I don't see that in the latest commit. I am also not sure about doubling the width/heigh fields I think it just needs the averaged center coordinate

**Comment by ndmlny-qs** [comment]
I did, here is what averaging does `(d[x|y]0 + d[x|y]1)/2` for `[v|h]bar`.

[avg.webm](https://github.com/bokeh/bokeh/assets/60523020/eb50c757-a234-4c2f-baa6-8575e82012a6)

**Comment by mattpap** [comment]
```
✗ Widgets
 └── should allow CategoricalSlider
images differ by 8px (0.02%)
```
I fixed this in PR #13497.

**Review by mattpap — APPROVED** [review]

**Comment by mattpap** [comment]
@ndmlny-qs, thanks.

**Comment by bryevdv** [comment]
This no longer applies cleanly so I'll skip it for 3.3.1
