### PR TITLE
Push to server only actually changed properties

### LINKED ISSUE #10621: [BUG] [MINOR]  2.3.0dev3, plot's inner_width property always sent on redraw even if unchanged
#### ALL software version info 
Bokeh 2.3.0dev3
Chrome Version 79.0.3945.79 (Official Build) (64-bit)
Windows 7 Pro SP1

#### Description
If you force a re-draw by, say, adding a new css_class somewhere, then the inner_width field for plots is always communicated from browser to server, even if its value is unchanged.

I spotted this is 1.4 (where all 4 of the experimental inner/outer width/height fields are affected), but in 2.3.0dev3 it just seems to be inner_width.

It has no real down-side, other than being an unexpected thing to see while observing the protocol messages.  I report it only for its unexpected nature!

Screenshot of the messages below, and a minimal test case below (just press the button and a do-nothing css class is added or removed from the column).  We see a ModelChanged event at the protocol level indicating a change to the plot's inner_width, even though the value is unchanging.

image

#### Complete, minimal, self-contained example code that reproduces the issue

```
from bokeh.layouts import column
from bokeh.models import Button, MultiSelect, Select
from bokeh.plotting import curdoc, figure

# Get a reference to the document we will be creating
doc = curdoc()

# Create simple plot
# prepare some data
x = [1, 2, 3, 4, 5]
y = [6, 7, 2, 4, 5]

# create a new plot with a title and axis labels
plot = figure(title="simple line example", x_axis_label='x', y_axis_label='y')

# add a line renderer with legend and line thickness
plot.line(x, y, legend_label="Temp.", line_width=2)

# Create a column
col = column()

# Add a button with a callback that just sets a css class on the col
button = Button(label='Press Here')

# Add a python callback on the Button to disable the MultiSelect/Select.
def button_handler():
    if 'some_funky_css_class' in col.css_classes:
        col.css_classes = []
    else:
        col.css_classes = ['some_funky_css_class']

# Add callback
button.on_click(button_handler)

# Add plot and col to the column
col.children = [plot, button]

# Put the column into the document
doc.add_root(col)

```

### PR DESCRIPTION
**Pull request by mattpap**
This seems like a big omission and it always worked like this. Maybe there was historically a reason for this? Testing locally didn't show any issues with this change.

- [x] tests

fixes #10621

### CODE REVIEW

File: bokehjs/src/lib/core/has_props.ts [hunk 1]
```diff
@@ -394,13 +396,14 @@ export abstract class HasProps extends Signalable() implements Equals, Printable
...
-    this._setv(changed, options)
+    const updated = this._setv(changed, options)
 
     const {document} = this
     if (document != null) {
       const changed: [Property, unknown, unknown][] = []
       for (const [prop, value] of previous) {
-        changed.push([prop, value, prop.get_value()])
+        if (updated.has(prop))
+          changed.push([prop, value, prop.get_value()])
```
Comment (bryevdv) [inline bokehjs/src/lib/core/has_props.ts:406]: Why can't this just loop over `updated` directly, rather than loop over `previous` and check `updated` each iteration?

**Comment by bryevdv** [comment]
> Maybe there was historically a reason for this? Testing locally didn't show any issues with this change.

I'm not aware of anything, the Python side explicitly avoids events for no-change property setting

File: bokehjs/src/lib/core/has_props.ts (hunk 1 above)
Comment (mattpap) [reply bokehjs/src/lib/core/has_props.ts:406]: This definitively can be simplified. There was too much shuffling there even before this change.

**Comment by mattpap** [comment]
Looks like only edit tools broke, but this is because they use the following:
```ts
cds.data = cds.data
cds.properties.data.change.emit()
```
code to force push changes, which assumes too much about the implementation details of `setv()`. This should have been implemented with `setv({data}, {check_eq: false})`.

**Comment by bryevdv** [comment]
> code to force push changes

There may be similar things in `DataTable`
