### PR TITLE
Resolve issues with high DPI GridPlot exports

### LINKED ISSUE #13252: [BUG]  plots in png generated by SaveTool on gridplot layout overlap
### Software versions

Python version      :  3.11.1 (main, Jan  6 2023, 16:08:28) [Clang 14.0.0 (clang-1400.0.29.202)]
IPython version     :  8.8.0
Tornado version     :  6.2
Bokeh version       :  3.2.0
BokehJS static path :  /Users/ryanolf/.pyenv/versions/3.11.1/envs/jupyter/lib/python3.11/site-packages/bokeh/server/static
node.js version     :  v19.7.0
npm version         :  9.5.0
Operating system    :  macOS-13.4-arm64-arm-64bit

### Browser name and version

Chrome 114.0.5735.198 (but also tested in Firefox)

### Jupyter notebook / Jupyter Lab version

Jupyter notebook 6.5.2

### Expected behavior

I have a layout generated with gridplot that looks like this in a Jupyter notebook:
Screenshot 2023-07-13 at 23 45 32
When I download a png with the SaveTool, I expect it to look similar.

### Observed behavior

Instead, the downloaded image shows the plots overlapping, like so:
bokeh_plot

### Example code

I run this in a jupyter notebook cell:
```Python
from bokeh.plotting import figure, show, output_notebook
from bokeh.layouts import gridplot

output_notebook()

plots = []
x = list(range(100))
y = list(range(100))
for (x, y) in [(x,y)]*4:
    p = figure(width=300, height=300, tools="pan,box_zoom,save,reset")
    p.line(x, y)
    plots.append(p)

layout = gridplot(plots, ncols=2)

# Show the plot
handle = show(layout, notebook_handle=True)
```

### Stack traceback or browser console output

_No response_

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by mattpap**
fixes #13252

### CODE REVIEW

File: bokehjs/test/integration/regressions.ts [hunk 1]
```diff
@@ -3457,4 +3457,43 @@ describe("Bug", () => {
...
+            [plot("blue"),   1, 0],
+            [plot("purple"), 1, 1],
+          ],
+        })
+      }
+
+      // TODO Allow to generate additional baselines for image diff.
+      it.dpr(1)("with devicePixelRatio == 1", async () => {
+        const {view} = await display(gridplot())
+        await view.export("png").to_blob()
```
Comment (mattpap) [inline bokehjs/test/integration/regressions.ts:3485]: This is hardly a test currently. The testing framework needs the ability to generate multiple baselines. This blob needs to be stored and participate in image diff.

**Review by bryevdv — APPROVED** [review]
