### PR TITLE
Write promise API calls into async/await

### LINKED ISSUE #9621: [BUG] Bad document JSON data leads to a dangling promise returned by `pull_session`
Suppose I have created a document with a non-existing model. When the `pull_session` is called, I see these messages in the JS console:
```
[bokeh] Got an event for unknown model  {id: "1053", type: "LinearColorMapper"}
Document.apply_json_patch @ bokeh.js?v=1.3.4:8503
ClientSession._handle_patch @ bokeh.js?v=1.3.4:528
ClientSession.handle @ bokeh.js?v=1.3.4:477
(anonymous) @ bokeh.js?v=1.3.4:317
Promise.then (async)
ClientConnection._repull_session_doc @ bokeh.js?v=1.3.4:299
ClientConnection._awaiting_ack_handler @ bokeh.js?v=1.3.4:405
_current_handler @ bokeh.js?v=1.3.4:347
ClientConnection._on_message @ bokeh.js?v=1.3.4:365
_this.socket.onmessage @ bokeh.js?v=1.3.4:217
```
```
21:37:36.553 backend.js:6 Error: event model wasn't known
    at Document.apply_json_patch (bokeh.js?v=1.3.4:8504)
    at ClientSession._handle_patch (bokeh.js?v=1.3.4:528)
    at ClientSession.handle (bokeh.js?v=1.3.4:477)
    at bokeh.js?v=1.3.4:317
r @ backend.js:6
(anonymous) @ bokeh.js?v=1.3.4:338
Promise.catch (async)
ClientConnection._repull_session_doc @ bokeh.js?v=1.3.4:336
ClientConnection._awaiting_ack_handler @ bokeh.js?v=1.3.4:405
_current_handler @ bokeh.js?v=1.3.4:347
ClientConnection._on_message @ bokeh.js?v=1.3.4:365
_this.socket.onmessage @ bokeh.js?v=1.3.4:217
```
```
21:37:36.553 bokeh.js?v=1.3.4:339 [bokeh] Failed to repull session Error: event model wasn't known
(anonymous) @ bokeh.js?v=1.3.4:339
Promise.catch (async)
ClientConnection._repull_session_doc @ bokeh.js?v=1.3.4:336
ClientConnection._awaiting_ack_handler @ bokeh.js?v=1.3.4:405
_current_handler @ bokeh.js?v=1.3.4:347
ClientConnection._on_message @ bokeh.js?v=1.3.4:365
_this.socket.onmessage @ bokeh.js?v=1.3.4:217
21:40:08.999 
```

It's pretty clear what the culprit is in my particular case.
However, the issue in Bokeh is that in this case the promise returned by `pull_session` is never resolved or rejected. And it makes it seem like `add_document_from_session` is still busy.

The root cause, I believe, is that `ClientConnection._repull_session_doc` does not call any callback if it fails - it just logs the error and that's it.
The constructor of `ClientConnection` doesn't even have any such callback for errors not related to a closed connection.
It's not really related to the issue itself, but there's also some strange code that:
1. Uses both the 2-argument form of `Promise.then` and the `Promise.catch`, which makes no sense
2. Makes it possible to call `reject` after `resolve` has already been called

With that being said, this is probably a very low priority issue since only some specific errors can trigger it, and even then it's should be clear to the developer what to do. It's just that the custom error handling code that someone's app may rely on will never be called.

### PR DESCRIPTION
**Pull request by mattpap**
fixes #9621

### CODE REVIEW

File: bokehjs/src/lib/client/connection.ts [hunk 1]
```diff
@@ -21,28 +23,25 @@ export class ClientConnection {
   closed_permanently: boolean = false
 
   protected _current_handler: ((message: Message) => void) | null = null
-  protected _pending_ack: [(connection: ClientConnection) => void, Rejecter] | null = null // null or [resolve,reject]
-  protected _pending_replies: {[key: string]: [(message: Message) => void, Rejecter]} = {} // map reqid to [resolve,reject]
+  protected _pending_replies: { [key: string]: [MessageResolver, Rejecter] } = {}
```
Comment (mattpap) [inline bokehjs/src/lib/client/connection.ts]: On the stylistic level we don't use spaces in this context, so the original is preferable. However, given the extent of changes to this module, let's switch from using plain objects as maps and use `Map<K, V>` instead.

File: bokehjs/src/lib/client/connection.ts [hunk 2]
```diff
@@ -214,47 +186,34 @@ export class ClientConnection {
...
-  protected _on_close(event: CloseEvent): void {
+  protected _on_close(event: CloseEvent, reject: Rejecter): void {
     logger.info(`Lost websocket ${this._number} connection, ${event.code} (${event.reason})`)
     this.socket = null
 
-    if (this._pending_ack != null) {
-      this._pending_ack[1](new Error(`Lost websocket connection, ${event.code} (${event.reason})`))
-      this._pending_ack = null
-    }
+    Object.values(this._pending_replies).forEach(([, reject]) => reject("Disconnected"))
```
Comment (mattpap) [inline bokehjs/src/lib/client/connection.ts]: After switching to `Map<K, V>`, this can be changed to `for (const [, reject] of this._pending_replies) ...`.

File: bokehjs/src/lib/client/connection.ts [hunk 3]
```diff
@@ -108,51 +103,35 @@ export class ClientConnection {
...
   }
 
-  protected _repull_session_doc(): void {
-    if (this.session == null)
-      logger.debug("Pulling session for first time")
-    else
-      logger.debug("Repulling session")
+  protected _repull_session_doc(resolve: SessionResolver, reject: Rejecter): void {
+    logger.debug(this.session ? "Repulling session" : "Pulling session for first time")
     this._pull_doc_json().then(
```
Comment (mattpap) [inline bokehjs/src/lib/client/connection.ts]: I think it would be good to rewrite this code with async/await as well, just don't use await at the call site of `_repull_session_doc()`. This would make any unit testing easier, as we would be able to access the promise.

File: bokehjs/src/lib/client/connection.ts (hunk 1 above)
Comment (p-himik) [reply bokehjs/src/lib/client/connection.ts]: Sure.
Heh, after seeing the linter complaining so often, I started to trust it too much.
Is it possible to add the rule about spaces to the linter as well?

File: bokehjs/src/lib/client/connection.ts (hunk 2 above)
Comment (p-himik) [reply bokehjs/src/lib/client/connection.ts]: I would still have to write `this._pending_replies.values()`. But the map, `forEach` won't require calling `Object.values`.

File: bokehjs/src/lib/client/connection.ts (hunk 1 above)
Comment (mattpap) [reply bokehjs/src/lib/client/connection.ts]: Yes, but I've been postponing such rules (and especially their fixes) till I get to splitting up bokehjs, which will introduce enough churn to allow this.

File: bokehjs/src/lib/client/connection.ts (hunk 2 above)
Comment (mattpap) [reply bokehjs/src/lib/client/connection.ts]: There are two options, either use `.values()`:
```ts
for (const v of this._pending_replies.values()) {
  ...
}
```
or 
```ts
for (const [, v] of this._pending_replies) {
  ...
}
```
which is equivalent of using `.items()`. This is due to `Symbol.iterator` support:
```ts
interface Map<K, V> {
    /** Returns an iterable of entries in the map. */
    [Symbol.iterator](): IterableIterator<[K, V]>;
}
```

Comment (p-himik) [reply bokehjs/src/lib/client/connection.ts]: With the latest commit, I switched to `this._pending_replies.forEach`. It seems like the most clean and clear version. And also the shortest one.

Comment (mattpap) [reply bokehjs/src/lib/client/connection.ts]: That's fine, though `forEach` has a peculiar order of arguments when it comes to the `Map` type. However, all those "functional" methods, `forEach`, `map`, `filter`, etc., are also usually the slowest option, so if performance is at stake, then one has to be wary of this choice. In this case it shouldn't matter though.

**Comment by mattpap** [comment]
This looks very good compared to the original code. I will do some testing with examples, as those aren't well represented on CI, before merging this.
