### PR TITLE
Fix bokehjs/examples/hover

### LINKED ISSUE #14328: Blank tooltips at bokehjs/examples/hover
### Software versions

Python version        :  3.12.4 | packaged by conda-forge | (main, Jun 17 2024, 10:13:44) [Clang 16.0.6 ]
IPython version       :  8.26.0
Tornado version       :  6.4.1
NumPy version         :  2.0.0
Bokeh version         :  3.7.0.dev4+5.g8ee0249b.dirty
BokehJS static path   :  /Users/gabalama/dev/bokeh/src/bokeh/server/static
node.js version       :  v22.11.0
npm version           :  10.9.0
jupyter_bokeh version :  (not installed)
Operating system      :  macOS-15.3-arm64-arm-64bit

### Browser name and version

_No response_

### Jupyter notebook / Jupyter Lab version

_No response_

### Expected behavior

[Line 56 of bokehjs/examples/hover/hover.ts](https://github.com/bokeh/bokeh/blob/dd4747fa6419fa76f2fe6aa25866457a74e384d6/bokehjs/examples/hover/hover.ts#L56) suggests that the tooltip should have some background color that depends on the data point, rather than always being white.

### Observed behavior

All the tooltips are blank white.

### Example code

```Python
git checkout branch-3.7
cd bokehjs
node test/devtools server
open http://127.0.0.1:5777/examples/hover
```

### Stack traceback or browser console output

No errors in the browser console

### Screenshots

Top portion of a plot, showing that when the mouse is hovered over a data point in the plot, the tooltip for that point is just a blank white box

### PR DESCRIPTION
**Pull request by gabalafou**
Fixes https://github.com/bokeh/bokeh/issues/14328.

### How to test

```
cd bokehjs
node test/devtools server
```

Go to http://127.0.0.1:5777/examples/hover, and hover over the dots. The tooltip should be box with no text whose background color matches the color of the hovered dot.

### CODE REVIEW

File: bokehjs/examples/hover/hover.ts [hunk 1]
```diff
@@ -53,7 +53,8 @@ export namespace HoverfulScatter {
     div.style.width = "200px"
     div.style.height = "75px"
     if (info.index != null) {
-      div.style.backgroundColor = ds.get("colors")[info.index] as string
+      const [r, g, b] = ds.get("colors")[info.index] as [number, number, number]
+      div.style.backgroundColor = `rgb(${r}, ${g}, ${b})`
```
Comment (mattpap) [inline bokehjs/examples/hover/hover.ts]: It would be even better to use `color2css()` (from `core/util/core`).

Comment (mattpap) [reply bokehjs/examples/hover/hover.ts]: Though accessing individual modules isn't ideal, but there's fortunately `Bokeh.plotting.color()` alias.

**Comment by mattpap** [comment]
Can you start a trivial issue for this? Our new emerging policy is to always start issues for all PRs.

File: bokehjs/examples/hover/hover.ts [hunk 2]
```diff
@@ -47,14 +47,14 @@ export namespace HoverfulScatter {
...
+  hover.tooltips = (data_source: typeof source, info) => {
     const div = document.createElement("div")
     div.style.width = "200px"
     div.style.height = "75px"
     if (info.index != null) {
-      const [r, g, b] = ds.get("colors")[info.index] as [number, number, number]
-      div.style.backgroundColor = `rgb(${r}, ${g}, ${b})`
+      div.style.backgroundColor = Bokeh.Plotting.color(
+        (data_source.get("colors") as typeof colors)[info.index],
+      )
```
Comment (mattpap) [inline bokehjs/examples/hover/hover.ts]: I would say this is a lot to parse, especially in an example, thus I would suggest this:
```suggestion
      const color = data_source.get[typeof colors]("colors")[info.index]
      const css_color = Bokeh.Plotting.color(color)
      div.style.backgroundColor = css_color
```

Comment (gabalafou) [reply bokehjs/examples/hover/hover.ts]: I was getting errors in my editor with this suggestion, so I modified it a little bit

**Review by mattpap — APPROVED** [review]
