### PR TITLE
Restore mixed deserialization of dicts

### LINKED ISSUE #13637: [BUG] Regression handling glyph border_radius that is a dict
### Software versions

Python version        :  3.11.6 | packaged by conda-forge | (main, Oct  3 2023, 10:40:35) [GCC 12.3.0]
IPython version       :  8.17.2
Tornado version       :  6.3.3
Bokeh version         :  3.4.0.dev4+15.gf821f2c5
BokehJS static path   :  /home/iant/github/bokeh/src/bokeh/server/static
node.js version       :  v18.13.0
npm version           :  10.2.3
jupyter_bokeh version :  (not installed)
Operating system      :  Linux-6.5.0-14-generic-x86_64-with-glibc2.38

### Browser name and version

_No response_

### Jupyter notebook / Jupyter Lab version

_No response_

### Expected behavior

Prior to commit f821f2c549c95 (PR #13618) on `branch-3.4` it is possible to use `p.rect(..., border_radius=dict(top_left=50))` to have just one of the rect corners rounded. But with that commit nothing renders. It was a big PR so is probably an accidental regression (and the functionality is experimental) and evidently we don't have an appropriate python-level test for this situation.

### Observed behavior

Nothing is displayed. In JS console:
```
Uncaught (in promise) Error: Rect(p1036).border_radius given invalid value: {}
    at N.validate (issue_new.html:200:2223)
    at N._update (issue_new.html:200:1963)
    at N.initialize (issue_new.html:200:1283)
    at m.initialize_props (issue_new.html:196:4318)
    at p._decode_object_ref (issue_new.html:229:4678)
    at p._decode (issue_new.html:229:1739)
    at p._decode_plain_object (issue_new.html:229:2300)
    at p._decode (issue_new.html:229:1026)
    at p._decode_object_ref (issue_new.html:229:4654)
    at p._decode (issue_new.html:229:1739)
```

### Example code

```Python
from bokeh.plotting import figure, show

p = figure(width=300, height=300)

#p.rect(x=0, width=2, y=0, height=1, border_radius=50)  # Works
p.rect(x=0, width=2, y=0, height=1, border_radius=dict(top_left=50))  # Fails

show(p)
```

### Stack traceback or browser console output

See above.

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by mattpap**
This PR restores deserialization of Python `dict` as either a plain object for string keys or a `Map` for other kinds of keys. This allows to maintain compatibility, especially for panel and other extensions. All other changes introduced in PR #13618 were kept, allowing for seamless operation on plain objects (as pseudo dicts) and `Map` at the same time.

This PR also adds `settings.serialize_include_defaults` for testing/debugging, which is used in this PR in new cross integration tests for issue #13637.

fixes #13637
addresses #13055

### CODE REVIEW

File: bokehjs/src/lib/core/kinds.ts [hunk 1]
```diff
@@ -637,7 +637,12 @@ export const Color = new Kinds.Color()
...
-export const Float = Number
+export const FontSize = Str
+export const Font = Str
+export const Angle = Float
+
+// backwards compatibility aliases
+export const Boolean = Bool
+export const String = Str
+export const Number = Float
+export const Map = Mapping
```
Comment (bryevdv) [inline bokehjs/src/lib/core/kinds.ts:662]: Only comment is that these could be under minimal test (e.g. at least for existence) if they are intended to be supported (noting since all the tests were updated to only use the new names)

**Review by bryevdv — APPROVED** [review]

File: bokehjs/src/lib/core/kinds.ts (hunk 1 above)
Comment (mattpap) [reply bokehjs/src/lib/core/kinds.ts:662]: I renamed all conflicting names and added tests. In a later PR I will update the codebase to use the new naming convention and and deprecate these aliases. In the long term this should help with resolving issue #13055.
