### PR TITLE
Convert CSS4 colors to CSS3 in SVG backend

### LINKED ISSUE #14164: SVG backend uses RGB colors in CSS4 notation
### Software versions

Python version        :  3.12.4 (tags/v3.12.4:8e8a4ba, Jun  6 2024, 19:30:16) [MSC v.1940 64 bit (AMD64)]
IPython version       :  8.25.0
Tornado version       :  6.4.1
NumPy version         :  1.26.4
Bokeh version         :  3.6.1
BokehJS static path   :  ~/Envs/fbpinn/Lib/site-packages/bokeh/server/static)
node.js version       :  v20.17.0
npm version           :  10.8.2
jupyter_bokeh version :  4.0.5
Operating system      :  Windows-10-10.0.19045-SP0

### Expected behavior

I expect, that I can save a figure to a file as svg and when I open it another program, it is displayed correctly.

### Observed behavior

When I save a plot as a figure using the latest version ob bokeh `3.6.1` and open this file in `inkscape` or in python using `reportlab`, colored areas are defected. The color is not evaluated correctly and mostly shown in black.

Please notice, that this defect is not visible, if I open the file in a modern browser. Then the newer version is displayed in the correct from.

Reading the source code of the older and the newer versions shows, that the values inside an `rgb` call is changed. The older was `rgb(222,222,222)` which looks like valid CSS, while the newer is `rgb(222 222 222)` which looks like SCSS/SASS.

|3.4.3|3.6.1|
|--|--|
|Image|Image|
|`<path fill="rgb(202,178,214)" stroke="rgb(202,178,214)">`|`<path fill="rgb(202 178 214)" stroke="rgb(202 178 214)">`|

### Example code

```Python
import bokeh
from bokeh.io import export_svg
from bokeh.plotting import figure

v = bokeh.__version__

p = figure(title=f"SVG export in {v}", tools="")
p.rect(x=[1, 2, 3], y=[1, 2, 3], width=1, height=1, color="#CAB2D6")
p.output_backend = 'svg'
export_svg(p, filename=f"export_svg_{v}.svg")

```

### Screenshots

Image

### LINKED ISSUE #14263: [BUG] Exporting SVGs in bokeh 3.6+ produces rendering errors in some renderers
### Software versions

Python version        :  3.12.2 (main, Apr 11 2024, 14:55:43) [Clang 15.0.0 (clang-1500.1.0.2.5)]
IPython version       :  8.31.0
Tornado version       :  6.4.2
NumPy version         :  1.26.4
Bokeh version         :  3.6.2
BokehJS static path   :  /Users/feliciaan/.pyenv/versions/3.12.2/envs/env/lib/python3.12/site-packages/bokeh/server/static
node.js version       :  v22.9.0
npm version           :  10.8.3
jupyter_bokeh version :  (not installed)
Operating system      :  macOS-15.1-arm64-arm-64bit

### Browser name and version

All Selenium web drivers (Chrome, Firefox and Safari tested)

### Jupyter notebook / Jupyter Lab version

_No response_

### Expected behavior

Rendering like in version 3.5.2, now artefacts exist when viewing in Inkscape, thumbnails on finder Mac, see added screenshot for the add black fills. These are not visible in the browser for example. See the legend, but also the scatter points are black.

The SVG file:
The svg file

How it renders in Inkscape (and other places like powerpoint):
Screenshot same file in Inkscape

### Observed behavior

SVG generated with version 3.5.2 and it renders correctly on all these platforms.
Image

### Example code

```Python
from bokeh.plotting import figure

from bokeh.io import export_svg

p = figure(width=400, height=400)
p.line([1, 2, 3, 4, 5], [6, 7, 2, 4, 5], line_width=2, legend_label="Temp.", color="#ff0000")
p.scatter([1, 2, 3, 4, 5], [6, 7, 2, 4, 5], line_width=2, legend_label="Temp.", color="#ff0000")
p.line([1, 2, 3, 4, 5], [3, 4, 1, 6, 15], line_width=2, legend_label="Other.", color="#0000ff")
p.scatter([1, 2, 3, 4, 5], [3, 4, 1, 6, 15], line_width=2, legend_label="Other.", color="#0000ff")
p.output_backend = "svg"


export_svg(p, filename="test.svg")
```

### Stack traceback or browser console output

_No response_

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by mattpap**
- [x] unit tests

fixes #14164

### CODE REVIEW

File: bokehjs/test/unit/regressions.ts [hunk 1]
```diff
@@ -1744,4 +1744,26 @@ describe("Bug", () => {
...
+      const blob = await view.export().to_blob()
+      const svg = await blob.text()
+
+      expect(svg.includes('"rgb(14 15 16)"')).to.be.false
+      expect(svg.includes('"rgb(17 18 19 / 0.877)"')).to.be.false
+      expect(svg.includes('"rgba(20, 21, 22, 0.577)"')).to.be.false
+
+      expect(svg.includes('"rgb(14,15,16)"')).to.be.true
+      expect(svg.includes('"rgb(17,18,19)"')).to.be.true
+      expect(svg.includes('"rgb(20,21,22)"')).to.be.true
```
Comment (bryevdv) [inline bokehjs/test/unit/regressions.ts]: test for separate opacity?

**Review by bryevdv — APPROVED** [review]

File: bokehjs/test/unit/regressions.ts (hunk 1 above)
Comment (mattpap) [reply bokehjs/test/unit/regressions.ts]: I replaced the test with a more robust one.
