### PR TITLE
fix spinner precision

### LINKED ISSUE #13064: [BUG] Spinner in float mode with int step will increment to int
### Software versions

``` yaml
Python version      :  3.10.10 | packaged by conda-forge | (main, Mar 24 2023, 20:08:06) [GCC 11.3.0]
IPython version     :  8.12.0
Tornado version     :  6.2
Bokeh version       :  3.1.0
BokehJS static path :  /home/shh/miniconda3/envs/holoviz/lib/python3.10/site-packages/bokeh/server/static
node.js version     :  v18.15.0
npm version         :  9.5.0
Operating system    :  Linux-6.2.6-76060206-generic-x86_64-with-glibc2.35
```

### Browser name and version

_No response_

### Jupyter notebook / Jupyter Lab version

_No response_

### Expected behavior

I expect the Spinner to increment with `value + 1` when the spinners mode is float and the step is an int. 

### Observed behavior

The increment is done to the (I think) `int(value + 1)`.

### Example code

```Python
from bokeh.io import output_notebook, show
from bokeh.layouts import column
from bokeh.models import Spinner

output_notebook()

a = Spinner(value=0.3, low=0, mode="float", step=1.0000000001, format="0.0")
b = Spinner(value=0.3, low=0, mode="float", step=1, format="0.0")
show(column(a, b))
```

### Stack traceback or browser console output

_No response_

### Screenshots

https://user-images.githubusercontent.com/19758978/230146082-032c9d2c-324d-42d6-b9f9-415752df7c0c.mp4

### PR DESCRIPTION
**Pull request by msalem99**
- [x] issues: fixes #13064 
- [ ] tests added / passed
- [ ] release document entry (if new feature or API change)

It seems that when the precision of the value is larger than the precision of the step ex value=1.333 step=1.22, the value will be truncated when incremented or decremented due to the precision of the step applying, I proceeded to save the initial value precision and took that value into consideration when calculating the precision of the incremented/decremented value.

tests have been added that test in the case of the precision of the value is larger than the step or vice versa

Please provide any feedback if things should be done differently. I am aware that setting the initial_precision_value in the render may not be best, can this be done in a better way?

### CODE REVIEW

**Comment by bryevdv** [comment]
Hi @msalem99 quick note: the selenium tests under `tests/integration` are currently disabled due to extreme flakiness, and it's unclear what their future is. If they are kept at all I expect it will be solely for testing that applies to Bokeh server cases specifically.

For testing BokehJS changes, there are pure JS integration tests here nowadays:

https://github.com/bokeh/bokeh/tree/branch-3.2/bokehjs/test/integration

That's going to be the appropriate place to add tests for this. @mattpap can offer specific guidance if needed.

File: bokehjs/src/lib/models/widgets/spinner.ts [hunk 1]
```diff
@@ -104,9 +105,9 @@ export class SpinnerView extends NumericInputView {
   }
 
   get precision(): number {
-    const {low, high, step} = this.model
+    const {low, high, step, initial_value_precision} = this.model
```
Comment (bryevdv) [inline bokehjs/src/lib/models/widgets/spinner.ts]: Do we actually need to save and and only use the precision from the initial value? Would it not simply work to just always consider the precision of the current value? (if the initial value is a float then adding an int to it should not change its precision, for not-extremely large values at least, and if we are in that regime we won't be able to honor the step anyway)

Comment (msalem99) [reply bokehjs/src/lib/models/widgets/spinner.ts]: If I understand you correctly, you mean to apply the precision on this.model.value directly? if so then I actually did do that in the beginning (see first commit https://github.com/bokeh/bokeh/pull/13078/commits/a0b749ada68f6f64f110bdc2030ef9a162f891ac) but that meant floating errors in some cases, for instance when decrementing, the value would end up showing as 1.299999999998 or so. Please correct me if I am wrong

Comment (msalem99) [reply bokehjs/src/lib/models/widgets/spinner.ts]: Ex: Spinner(value=1.3, low=0, high=10, mode="float", step=1)

increment once: value = 2.3
decrement once: value = 1.2999999999999998

**Comment by mattpap** [comment]
> https://github.com/bokeh/bokeh/tree/branch-3.2/bokehjs/test/integration

> That's going to be the appropriate place to add tests for this. @mattpap can offer specific guidance if needed.

Unless we need baselines for this, in particular image baselines, then `unit` tests are a better place. Both `unit` and `integration` tests are a bit of a misnomer in bokehjs due to their history. `unit` tests are both true unit and integration tests that involve no persistent baselines (`*.blf` files or image baselines), whereas `integration` tests are tests that produce and verify baselines. By integration tests in this context, we mean integration within bokehjs. Cross bokeh bokehjs integration tests should be performed in `tests/integration`, assuming those tests will be restored to function.

File: bokehjs/src/lib/models/widgets/spinner.ts (hunk 1 above)
Comment (mattpap) [reply bokehjs/src/lib/models/widgets/spinner.ts]: Properties are meant for configurability or for computed values of significance to the user, so if that's not the case then this shouldn't be a public property, and possibly a property altogether. If we really need to store this, then a view private member should be sufficient.

Comment (msalem99) [reply bokehjs/src/lib/models/widgets/spinner.ts]: If it isn't stored do you suggest doing this another way? As I mentioned , taking the value's precision right away resulted in large precisions, or am I doing something wrong?

Thank you for your feedback

Comment (mattpap) [reply bokehjs/src/lib/models/widgets/spinner.ts]: However, I'm not sure if we actually need all of this complexity. What's the point of handling precision in this widget, trying to hide the fact that it uses floating point numbers? If looks are the goal, then one can use a formatter for this. If one actually wants non-fp behavior, then we should provide appropriate number types, which then could be reused in other widgets to get equivalent behavior.

**Comment by msalem99** [comment]
> > https://github.com/bokeh/bokeh/tree/branch-3.2/bokehjs/test/integration
> 
> > That's going to be the appropriate place to add tests for this. @mattpap can offer specific guidance if needed.
> 
> Unless we need baselines for this, in particular image baselines, then `unit` tests are a better place. Both `unit` and `integration` tests are a bit of a misnomer in bokehjs due to their history. `unit` tests are both true unit and integration tests that involve no persistent baselines (`*.blf` files or image baselines), whereas `integration` tests are tests that produce and verify baselines. By integration tests in this context, we mean integration within bokehjs. Cross bokeh bokehjs integration tests should be performed in `tests/integration`, assuming those tests will be restored to function.

Hello,
I managed to write tests for this in https://github.com/bokeh/bokeh/blob/branch-3.2/bokehjs/test/integration/widgets.ts 
I wasn't sure of commiting though to obtain the CI baselines as I am not sure how you want to move forward with this fix

File: bokehjs/src/lib/models/widgets/spinner.ts (hunk 1 above)
Comment (bryevdv) [reply bokehjs/src/lib/models/widgets/spinner.ts]: I would definitely be more comfortable with computing an initial  (internal) "max precision" if that value fed into a formatter, rather than actually futzing with values.

**Comment by msalem99** [comment]
I tried to implement a max_precision but after writing unit tests in bokehjs/test/unit/models/widgets/spinner.ts it seems that sometimes the initial value entered has a precision of 16 so fp issues emerge (this can be seen in the failing tests in https://github.com/bokeh/bokeh/pull/13078/commits/0452e448faab7a9295151b3e837e7c9691021f1c) even from the value inputted by the user. I am not sure why the initial inputted value has a precision of 16 so any feedback is appreciated.
Thank you

**Comment by bryevdv** [comment]
> I am not sure why the initial inputted value has a precision of 16 so any feedback is appreciated.

Well, if the initial value is not an exact fp value that seems about right.

I am really tempted to more or less punt on this: 

* add a public property to control (not compute) the *formatting* precision
* just add the values step values as-is without any other consideration. 

As @mattpap suggests, we are more or less trying to magic away the intrinsic behavior of floating point values, and that is just a hopeless task.

cc @bokeh/dev

**Comment by msalem99** [comment]
I figured maybe I could obtain the max precision through the format_value string by counting the decimals after the dot from the string, this would work but I think it would mean that using the format property for approximating values would be useless since the values are truncated. Not sure if this is considered clean enough. Any feedback would be appreciated.
Thank you

**Comment by bryevdv** [comment]
@msalem99 the more I think and look at this, the more I think perhaps we should simply abandon the precision complexity altogether. Doing a quick survey online:

* an old MS API only supported int spinners and advised to use a formatter to divide the presentation by a power of 10 for display
* the actual built-in HTML number input with float and `step=1` actually behaves they way our existing spinner does AFAICT, i.e it always steps to an integer, regardless of what the start value is!
* For arbitrary decimals, must set `step=any` -- which actually means a step of 1 but allow any decimals in the input value (?!)
* Various different weirdness and complains for other JS spinners

I don't think there is any standardization of consistency at all in this space, and every option seems to have some drawback or other. 

IIRC all the precision computations came about as a result of some problem with rounding. But we were only rounding because there was no option to add a formatter at that time in the early days. I think now that a format can be supplied, the actual best thing to do is:

* rip out all precision and rounding in the spinner. Just add the step as-is to the current value, as-is.

Then the only possible "problem" is that floating point precision may cause the min or max values to be "missed" but that's just how fp works. I think we can just reiterate that fact of life in the docs, and not worry about it.

**Comment by msalem99** [comment]
> * rip out all precision and rounding in the spinner. Just add the step as-is to the current value, as-is.

Thank you for your feedback, I think this is definitely the most suitable course of action, I was hoping I could implement the max_precision correctly to use it as a default format if a format is not given but I am not sure how to do that since the precision function that returns max is essentially useless since the step could also be a floating point, same goes for the high and low.

any suggestion regarding a default format? or just leave it as fp incase no format is provided?

Thank you

**Comment by jbednar** [comment]
I agree with making it simpler, but I worry if floating point precision issues could cause the value to exceed the upper bound by even the smallest amount. E. g. if the value is used to compute an index into an array, now there might be out of bounds access, despite the spinner bounds seemingly being safe against that. Send like that could lead to some dangerous apps!

**Comment by bryevdv** [comment]
@jbednar by "miss" the max/min values, I meant "might never be able to attain those values" (even if in a "perfect math sense" they should be able to).  I agree that a strict comparison against min/max is always needed to prevent any overshoot or undershoot due to fp precision loss.

**Comment by bryevdv** [comment]
@msalem99 I think improvements to default formatting is a perfectly reasonable thing to look at but let's save it for a follow-on issue separate from this one

**Comment by msalem99** [comment]
I am not sure where to go from here regarding this fix. Also I am also not sure why the Bokeh-CI macos unit-tests and windows minimal-deps are failing, any feedback is appreciated.

Thank you.

**Comment by bryevdv** [comment]
@msalem99 I don't think the failures are related to your PR. The documentation job is failing everywhere due to a recent downstream package update. I think the others were conda env network failures. I've restarted all the failed jobs. 

I am going to look over the PR (especially tests) tomorrow but I think it should be close and/or ready

File: bokehjs/test/unit/models/widgets/spinner.ts [hunk 2]
```diff
@@ -0,0 +1,119 @@
...
+    expect(input.value).to.be.equal("2.36")
+
+    await mousedown_mouseup(increment_button)
+    expect(input.value).to.be.equal("3.36")
+
+    await mousedown_mouseup(increment_button)
+    expect(input.value).to.be.equal("4.36")
+
+    await mousedown_mouseup(increment_button)
+    expect(input.value).to.be.equal("5.00")
```
Comment (bryevdv) [inline bokehjs/test/unit/models/widgets/spinner.ts]: Is this the desired behaviour? I think I might have expected that in this case the increment button simply had no effect at all. Perhaps it should be configurable whether a "partial step" is allowed at the bounds (to exactly attain the bounds) or whether the step is strictly respected at all times (even if it means the bounds values can never be attained)

Same questions for lower bound, of course.

cc @bokeh/dev

Comment (msalem99) [reply bokehjs/test/unit/models/widgets/spinner.ts]: in-case of the presence of a reach_bounds property and set to true, if a partial step is made to reach the bound exactly, should this partial step be preserved in the followed opposite step and then back to the original step? or should the original step be applied right away?
ex:
high: 5 step:0.5 value 4.7
increment -> 5
2x decrement -> 4.7 , 4.2 or 4.5 , 4.0?

Comment (bryevdv) [reply bokehjs/test/unit/models/widgets/spinner.ts]: @bokeh/dev thoughts on a preference? It could be made configurable I suppose, but I'd rather just pick a good default to start and only add a configuration if it becomes needed.

File: bokehjs/src/lib/models/widgets/spinner.ts [hunk 3]
```diff
@@ -201,13 +187,21 @@ export class SpinnerView extends NumericInputView {
...
     super.change_input()
     this.model.value_throttled = this.model.value
   }
+
+  override bound_value(value: number): number {
+    let output = value
+    const {low, high} = this.model
+    if (low != null && output < low) output = this.model.value ?? 0
+    if (high != null && output > high) output = this.model.value ?? 0
+    return output
```
Comment (bryevdv) [inline bokehjs/src/lib/models/widgets/spinner.ts]: We try to avoid `let` in the codebase wherever possible, suggest:
```suggestion
    const {low, high, value} = this.model
    if (low != null && output < low) return value ?? 0
    if (high != null && output > high) return value ?? 0
    return value
```

**Review by bryevdv — COMMENTED** [review]
Hi @msalem99 apologies for the delay, I have not had as much time for Bokeh in the last few months. I'd like to get this merged for 3.3 so that we can also add the formatter option along with it. Can you fix the small merge conflict, and submit an issue regarding adding a formatting property to the spinner?

**Comment by msalem99** [comment]
Hello @bryevdv, 
Is there any chance this could still be considered?
Thanks.

**Review by bryevdv — APPROVED** [review]

**Comment by bryevdv** [comment]
Thanks for you patience @msalem99 the tests all look good to me so i will go ahead and merge this now.
