### PR TITLE
Fix regression in legend location

### LINKED ISSUE #6142: Regression in Legend positioning
I've been running into issues with legend positioning recently and it seems this is a regression in 0.12.5. Comparing the docs Styling Visual Attributes guide section for positioning legends outside the plot area between 0.12.4 and 0.12.5 reveals this:

[0.12.4](http://bokeh.pydata.org/en/0.12.4/docs/user_guide/styling.html#outside-the-plot-area)

screen shot 2017-04-14 at 1 16 53 am

[0.12.5](http://bokeh.pydata.org/en/0.12.5/docs/user_guide/styling.html#outside-the-plot-area)

screen shot 2017-04-14 at 1 17 23 am

### PR DESCRIPTION
**Pull request by canavandl**
All pull requests must have an associated issue in the issue tracker. If there
isn't one, please go open an issue describing the defect, deficiency or desired
feature. You can read more about our issue and PR processes in the
[wiki](https://github.com/bokeh/bokeh/wiki/BEP-1:-Issues-and-PRs-management).

- [x] issues: fixes #6142 
- [ ] tests added / passed
- [ ] release document entry (if new feature or API change)

This change makes the origin for legends in the left/right panel be based on the top left corners of the left/right side panels instead of the bottom left corner. This matches the behavior from 0.12.4.

### CODE REVIEW

**Comment by canavandl** [comment]
demo: examples/models/files/legends.py

As was in 0.12.4:

screen shot 2017-05-31 at 2 07 18 pm

This PR:
screen shot 2017-05-31 at 2 07 09 pm


I think the placement of absolute positioning of legends within a frame was also incorrect (because it included the left/bottom panel dimensions), so the change seems more correct.

**Comment by bryevdv** [comment]
@canavandl please make a separate issue to investigate further improvements/fixes.

File: bokehjs/src/coffee/models/annotations/legend.coffee [hunk 1]
```diff
@@ -88,8 +88,12 @@ export class LegendView extends AnnotationView
           y = (v_range.end + v_range.start)/2 + legend_height/2
     else if isArray(location) and location.length == 2
       [x, y] = location   # left, bottom wrt panel
-      x += h_range.start
-      y += v_range.start + legend_height
+      if panel.side?
```
Comment (mattpap) [inline bokehjs/src/coffee/models/annotations/legend.coffee]: This is a likely to break in future. I would use `if panel.side in ['left', 'right', 'above', 'below']`.
