### PR TITLE
Fix regression in wheel_zoom_tool zoom origin

### LINKED ISSUE #5235: Wheel zoom is centers on center-of-plot, not mouse
When on master (49b632960b73a299c596efccb656b986eec8c9f3) I find that wheel zoom zooms in on the center of the plot, not the location of the mouse cursor.

### PR DESCRIPTION
**Pull request by canavandl**
Fixes regression in wheel_zoom_tool where zoom origin wasn't around scroll cursor. Added tests to prevent future regression.

- [x] issues: fixes #5235
- [x] tests added / passed
- [ ] release document entry (if new feature or API change)

### CODE REVIEW

**Comment by canavandl** [comment]
should merge after #5225

File: bokehjs/src/coffee/models/tools/gestures/wheel_zoom_tool.coffee [hunk 1]
```diff
@@ -26,19 +26,11 @@ class WheelZoomToolView extends GestureTool.View
...
-
     dims = @model.dimensions
 
     # restrict to axis configured in tool's dimensions property
-    if dims.indexOf('width') == -1
-      v_axis_only = true
-    if dims.indexOf('height') == -1
-      h_axis_only = true
+    v_axis = 'width' in dims
+    h_axis = 'height' in dims
```
Comment (mattpap) [inline bokehjs/src/coffee/models/tools/gestures/wheel_zoom_tool.coffee]: This is in reverse. Horizontal is `height` and vertical is `width`.

Comment (mattpap) [inline bokehjs/src/coffee/models/tools/gestures/wheel_zoom_tool.coffee]: I fixed this during `master` merge.

Comment (mattpap) [inline bokehjs/src/coffee/models/tools/gestures/wheel_zoom_tool.coffee]: Tests fail after this change.

Comment (canavandl) [inline bokehjs/src/coffee/models/tools/gestures/wheel_zoom_tool.coffee]: fixed

File: bokehjs/src/coffee/models/tools/gestures/wheel_zoom_tool.coffee [hunk 2]
```diff
@@ -51,13 +46,7 @@ class WheelZoomToolView extends GestureTool.View
...
     factor  = @model.speed * delta
 
-    zoom_info = scale_range({
-      frame: frame
-      factor: factor
-      center: [vx, vy]
-      v_axis_only: v_axis_only
-      h_axis_only: h_axis_only
-    })
+    zoom_info = scale_range(frame, factor, h_axis=h_axis, v_axis=v_axis, {x: vx, y: vy})
```
Comment (mattpap) [inline bokehjs/src/coffee/models/tools/gestures/wheel_zoom_tool.coffee]: @canavandl, by name arguments don't work in coffeescript. This will be translated directly and it will result in whatever else behavior than you expect. If you want "by name arguments", you should have left the original API with a plain object and its destruction.

Comment (mattpap) [inline bokehjs/src/coffee/models/tools/gestures/wheel_zoom_tool.coffee]: The same applies to other instances.

Comment (mattpap) [inline bokehjs/src/coffee/models/tools/gestures/wheel_zoom_tool.coffee]: This misunderstanding is a courtesy of dynamic typing and making assignment an expression in coffeescript.

**Comment by mattpap** [comment]
Apologies for spamming this PR, but I had to fix yet another issue introduced in #5225, before I could test this.

File: bokehjs/src/coffee/models/tools/gestures/wheel_zoom_tool.coffee (hunk 2 above)
Comment (mattpap) [inline bokehjs/src/coffee/models/tools/gestures/wheel_zoom_tool.coffee]: And apparently in JavaScript. I went ahead and changed this appropriately.

**Comment by mattpap** [comment]
@bokeh/dev, we reached nice, round 10k travis ci builds in https://travis-ci.org/bokeh/bokeh/builds/163826822.

File: bokehjs/src/coffee/models/tools/gestures/wheel_zoom_tool.coffee (hunk 2 above)
Comment (canavandl) [inline bokehjs/src/coffee/models/tools/gestures/wheel_zoom_tool.coffee]: thanks for catching that

**Comment by mattpap** [comment]
New, fun, recurring and unrelated test failure:
```
=================================== FAILURES ===================================
________________________________ test_log_stats ________________________________
    def test_log_stats():
        application = Application()
>       with ManagedServerLoop(application) as server:
bokeh/server/tests/test_tornado.py:71: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
bokeh/server/tests/utils.py:68: in __init__
    self._server = Server(application, **server_kwargs)
bokeh/server/server.py:119: in __init__
    self._http.bind(self._port, address=self._address)
../../../miniconda/lib/python2.7/site-packages/tornado/tcpserver.py:176: in bind
    backlog=backlog, reuse_port=reuse_port)
../../../miniconda/lib/python2.7/site-packages/tornado/netutil.py:194: in bind_sockets
    sock.bind(sockaddr)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
name = 'bind', self = <socket._socketobject object at 0x7f33aba593d0>
args = (('::', 5006, 0, 0),)
    def meth(name,self,*args):
>       return getattr(self._sock,name)(*args)
E       error: [Errno 98] Address already in use
../../../miniconda/lib/python2.7/socket.py:228: error
```
