### PR TITLE
Fix dynamic layout update for `min_border*` properties

### LINKED ISSUE #15004: Cannot update min_border of figure with CustomJS callback
### Software versions

Python version        :  3.11.15 | packaged by conda-forge | (main, Mar  5 2026, 16:59:26) [Clang 19.1.7 ]
IPython version       :  9.10.1
Tornado version       :  6.5.5
NumPy version         :  2.4.3
Bokeh version         :  3.10.0.dev2+32.g6bfcb24b.dirty
BokehJS static path   :  ~/bokeh/src/bokeh/server/static
node.js version       :  v24.14.1
npm version           :  11.12.1
jupyter_bokeh version :  (not installed)
Operating system      :  macOS-26.3.1-arm64-arm-64bit

### Browser name and version

_No response_

### Jupyter notebook / Jupyter Lab version

_No response_

### Expected behavior

The figure shrinks as the min_border increases when moving the slider from left to right.

### Observed behavior

The figure does not change when the value of min_border is updated.

### Example code

```Python
from bokeh.models import CustomJS, Slider
from bokeh.io import curdoc
import numpy as np
from bokeh.models import (ColumnDataSource, HoverTool, NodesAndLinkedEdges,
                          StaticLayoutProvider, TapTool)
from bokeh.palettes import Set3_12
from bokeh.plotting import figure, show
from bokeh.sampledata.airport_routes import airports, routes
from bokeh.sampledata.us_states import data as us_states

airports.set_index("AirportID", inplace=True)
airports.index.rename("index", inplace=True)
routes.rename(columns={"SourceID": "start", "DestinationID": "end"}, inplace=True)

lats = [np.array(v["lats"]) for v in us_states.values()]
lons = [np.array(v["lons"]) for v in us_states.values()]
source = ColumnDataSource(data=dict(lats=lats, lons=lons))

graph_layout = dict(zip(airports.index, zip(airports.Longitude, airports.Latitude)))
layout_provider = StaticLayoutProvider(graph_layout=graph_layout)

p = figure(x_range=(-180, -60), y_range=(15,75),
           x_axis_label="Longitude", y_axis_label="Latitude",
           width=800, height=600, background_fill_color=Set3_12[4],
           background_fill_alpha=0.2, tools='box_zoom,reset')

p.patches(xs="lons", ys="lats", line_color='grey', line_width=1.0,
          fill_color=Set3_12[10], source=source)

r = p.graph(
    airports, routes, layout_provider,
    ## node style props
    node_fill_color=Set3_12[3], node_fill_alpha=0.4, node_line_color="black", node_line_alpha=0.3,
    node_nonselection_fill_color=Set3_12[3], node_nonselection_fill_alpha=0.2, node_nonselection_line_alpha=0.1,
    node_selection_fill_color=Set3_12[3], node_selection_fill_alpha=0.8, node_selection_line_alpha=0.3,
    ## edge style props
    edge_line_color="black", edge_line_alpha=0.04,
    edge_hover_line_alpha=0.6, edge_hover_line_color=Set3_12[1],
    edge_nonselection_line_color="black", edge_nonselection_line_alpha=0.01,
    edge_selection_line_alpha=0.6, edge_selection_line_color=Set3_12[1],
    ## graph policies
    inspection_policy=NodesAndLinkedEdges(), selection_policy=NodesAndLinkedEdges(),
)

hover = HoverTool(tooltips=[("Airport", "@Name (@IATA), @City ")], renderers=[r])
tap = TapTool(renderers=[r])
p.add_tools(hover, tap)
p.background_fill_color = "red"

curdoc().add_root(p)

custom_min_border = Slider(start=0, end=200, value=0, title="min_border")
buggy_callback = CustomJS(args=dict(elem=p, min_border=custom_min_border),
                    code="""elem.min_border = min_border.value;""", # This fails to update the min_border of the figure
)

custom_min_border.js_on_change("value", buggy_callback)
p.add_layout(custom_min_border, "above")
show(p) # Bug: moving the slider causes the min_border to update, but the figure does not visually update to reflect the new min_border value

# Temporary workaround: update min_height at the same time as min_border, which succeeds in updating min_border
workaround_callback = CustomJS(args=dict(elem=p, min_border=custom_min_border),
                    code="""elem.min_border = min_border.value; elem.min_height = 1 - min_border.value / 200;""", # This succeeds in updating min_border when min_height is also updated
)
custom_min_border.js_on_change("value", workaround_callback)
show(p) # Workaround: moving the slider causes the min_border to update, and the figure visually updates to reflect the new min_border value
```

### Stack traceback or browser console output

_No response_

### Buggy Plot (first show(p))

Image

### Workaround (second show(p))

Image

### PR DESCRIPTION
**Pull request by nobody15p**
**Summary**
This PR fixes #15004 by connecting signal listeners for min_border and its directional variants (min_border_top, min_border_bottom, min_border_left, min_border_right) in PlotView.

Previously, while these properties could be updated on the Plot model (e.g., via CustomJS or a Bokeh server callback), the changes were not propagated to the layout engine. This resulted in the plot area remaining static until a manual window resize was triggered.

**Changes**
Modified bokehjs/src/lib/models/plots/plot_canvas.ts.

Updated _connect_signals() to watch for changes in all min_border properties.

Connected these signals to this.invalidate_layout(), ensuring the layout engine recalculates the plotting area (frame) immediately upon property changes.

**Testing**
Integration Test: Added a new test case in bokehjs/test/integration/regressions.ts that programmatically updates min_border and asserts that the inner_bbox (plotting frame) dimensions are updated.

Custom Verification: Verified using the reproduction script provided in the issue. The min_border now updates fluently via a Slider and CustomJS callback without requiring the min_height workaround.

Min_border = 0
Screenshot 2026-04-12 105939
Min_border = 164
Screenshot 2026-04-12 105954
These images show successful changes in the layout when user updates the min_border parameter.

- [ ] issues: fixes #15004 
- [ ] tests added / passed: Added a new test case in bokehjs/test/integration/regressions.ts that programmatically updates min_border and asserts that the inner_bbox (plotting frame) dimensions are updated.

### CODE REVIEW

**Comment by nobody15p** [comment]
The integration test for #15004 is passing locally, but failing in CI due to missing baselines. Could a maintainer please help generate the Linux baselines?

File: bokehjs/test/integration/regressions.ts [hunk 1]
```diff
@@ -4846,6 +4846,22 @@ describe("Bug", () => {
     })
   })
 
+  describe("in issue #15004", () => {
+    it("should recalculate layout when min_border properties are changed", async () => {
```
Comment (mattpap) [inline bokehjs/test/integration/regressions.ts]: This should say the opposite, because the full description starts with `Bug in issue #15004 ...`, so:
```suggestion
  describe("in issue #15004", () => {
    it("doesn't allow to recalculate layout when min_border property is changed", async () => {
```

**Comment by mattpap** [comment]
> The integration test for https://github.com/bokeh/bokeh/issues/15004 is passing locally, but failing in CI due to missing baselines. Could a maintainer please help generate the Linux baselines?

The procedure is described [here](https://docs.bokeh.org/en/latest/docs/dev_guide/writing_tests.html#contributor-guide-writing-tests) in section "Generate CI baselines and commit test". In short, download and unzip the artifact, commit new and changed (if relevant) baselines, and push. If there are any issues with this, then let me know.

File: bokehjs/test/integration/regressions.ts (hunk 1 above)
Comment (mattpap) [reply bokehjs/test/integration/regressions.ts]: You will have to update `*.png` and `*.blf` file names after this change.

**Comment by nobody15p** [comment]
I have updated the test description and committed the Linux baseline images as requested.
My integration test for #15004 is now passing! I am unable to find issue which is causing CI checks to fail.

**Comment by mattpap** [comment]
> I am unable to find issue which is causing CI checks to fail.

All failures seem to be unreliable tests.

**Comment by mattpap** [comment]
@nobody15p, let's undo the last commit (normal distribution example) and see if that helps with CI.

**Review by mattpap — APPROVED** [review]

**Comment by mattpap** [comment]
@nobody15p, thanks.

**Comment by mosc9575** [comment]
I think this should be added to `3.9.1` - see #15089.
