### PR TITLE
Flatpickr

### LINKED ISSUE #6728: DatePicker not updating enabled/disabled
this seems to just be a case of missing plumbing (I don't see any change handlers hooked up) 

ref: https://groups.google.com/a/continuum.io/forum/#!topic/bokeh/frzcAhV7zYw

test code:

```
from bokeh.layouts import widgetbox
from bokeh.models import widgets
from bokeh.plotting import curdoc

def change_time():
    print('previous values: ', time.value, time.min_date, time.max_date)
    time.value = '2015-11-10'
    time.min_date = '2015-10-01'
    time.max_date = '2015-12-30'
    print('changed values: ', time.value, time.min_date, time.max_date)

time = widgets.inputs.DatePicker(title="Intervention", value='2015-11-02', min_date='2015-11-01', max_date='2015-12-01')
button = widgets.Button(label="Change time", button_type="success")
button.on_click(change_time)
layout = widgetbox([time,button])

curdoc().add_root(layout)
```

### LINKED ISSUE #8917: [FEATURE] Optional valid values list attribute for DatePicker
It would be nice to be able to give the DatePicker widget a list of valid dates, such that within the minimum and maximum date range only the dates in the list are able to be selected.  Ideally this would also grey out the invalid dates just like dates outside the range given are marked now (example below).

image

I'd imagine this involves the JavaScript/TypeScript side of things which I have no experience in, but if someone in the know thinks this is would be a smaller job and could point me in the right direction I'd be happy to take a crack at it.

### LINKED ISSUE #9494: [BUG] DatePicker display off-by-one in non-GMT timezone after upgrade to 1.4.0
Versions:

- Bokeh: 1.4.0
- Python: 3.7.3
- Chrome: 78.0.3904.108 (Official Build) (64-bit)
- O/S: Windows 7 Pro SP1
- **TimeZone**: EST (Issue observed in EST but not in GMT)

After the fix of [this issue](https://github.com/bokeh/bokeh/pull/9232/commits/472e4770d363b3914bb478f0a6c3a83787b20c0d#) in 1.4, I observe the following issue;

In the EST timezone, if I update a DatePicker based on the value of another DatePicker, I get a different date (1 day previous to the selected date).  If the browser is located in a GMT timezone then I do not observe the issue.  Minimal example below.

**Expected behavior**: On selecting a date from the first DatePicker, the second DatePicker displays that same date;

image

**Observed behavior**: On selecting a date from the first DatePicker, the second DatePicker shows a date one day previous to the selected date;

image

```
from bokeh.layouts import column
from bokeh.models import DatePicker
from bokeh.plotting import curdoc


def a_changed(attr, old, new):
    date_picker_b.value = new


date_picker_a = DatePicker()
date_picker_b = DatePicker()

# When we pick a date in date_picker_a, set the date in date_picker_b
date_picker_a.on_change('value', a_changed)

curdoc().add_root(column(date_picker_a, date_picker_b))

```

In our application, we have a date slider and some fixed date-range buttons (year-to-date, month-to-date etc) coupled to two date pickers, which is how we observed the issue, but the above example seems to minimally demonstrate the issue that dates don't round-trip from the DatePickers.

### PR DESCRIPTION
**Pull request by bryevdv**
Replace the current date picker with Flatpickr and also make the `Date` property more strict. 

* [x] issues: fixes #9494 
* [x] issues: fixes #6728
* [x] issues: fixes #8917 
* [x] tests pass
* [x] docs udpated

### CODE REVIEW

File: bokehjs/src/lib/models/widgets/date_picker.ts [hunk 1]
```diff
@@ -1,51 +1,17 @@
...
-}
+import "styles/widgets/flatpickr"
 
 export class DatePickerView extends InputWidgetView {
   model: DatePicker
 
   protected input_el: HTMLInputElement
 
-  private _picker: Pikaday
+  private _picker: any
```
Comment (mattpap) [inline bokehjs/src/lib/models/widgets/date_picker.ts]: `flatpickr` has type declarations, so this and other `any`s can be replaced with more precise types.

File: bokehjs/src/lib/models/widgets/date_picker.ts [hunk 2]
```diff
@@ -61,36 +27,14 @@ export class DatePickerView extends InputWidgetView {
...
-    //Then multiply to get the offset in ms.
-    //This way it can be used to recreate the user specified date, agnostic to their local systems's timezone.
-    const timeOffsetInMS = date.getTimezoneOffset() * 60000
-    date.setTime(date.getTime() - timeOffsetInMS)
-
-    const datestr = date.toISOString().substr(0, 10)
-    const tup = datestr.split('-')
-    return new Date(Number(tup[0]), Number(tup[1])-1, Number(tup[2]))
+    this._picker = flatpickr(this.input_el, {
+      onChange: (selectedDates, dateStr, instance) => this._on_change(selectedDates, dateStr, instance),
```
Comment (mattpap) [inline bokehjs/src/lib/models/widgets/date_picker.ts]: Argument names aren't meaningful in JS, as they are e.g. in Python, so they can be safely renamed to snake-case to match bokeh's naming convention.

Comment (bryevdv) [reply bokehjs/src/lib/models/widgets/date_picker.ts]: I  know :) This is very early wip

**Comment by bryevdv** [comment]
As an aside I have realized half the issue is that  our handing of date values (by forcing them to be datetimes) is half the problem. It did not help that is what pikaday expected. But Flatpick can handle actual date values with no no time, e.g. "2019-12-06", so I cam going to fix our `Date` property and serialization to no longer use timestamps.

**Comment by bryevdv** [comment]
@mattpap I'm not actually seeing what JS tests fail:
```
       ✓ should should leave message null
        ✓ should throw an error on binary data
[18:03:12] failed: Error: tests failed
[18:03:12]     at ChildProcess.proc.on (/Users/bryan/work/bokeh/bokehjs/make/tasks/test.ts:99:16)
[18:03:12]     at ChildProcess.emit (events.js:182:13)
[18:03:12]     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
```
Is there something I need to do or does this need a separate issue?

**Comment by mattpap** [comment]
>  I'm not actually seeing what JS tests fail

Test failures are currently showed only inline. We already discussed this, though there may not be an issue for this, and I'm going to improve reporting as time permits. If you don't see any errors inline and tests fail, then report a new issue.

**Comment by bryevdv** [comment]
@mattpap @philippjfr this is still WIP but I would like some feedback. First, things to do:

* expose further features of flatpickr
* add more selenium tests

Both of those will be fairly easy/straightforward. I'd like some input on the properties changes. The current code around serializing dates and datetimes is a mess, so the current changes are also a mess, and that is what I would like input on.

I think ideally what should happen is for scalar `datetime.date` values to render as ISO datestrings. These would be for individual `Date` properties, e.g. the value of the picker. But for everything else (i.e. `date` objects in arrays/series/columns) to transform as timestamps. Does this seem reasonable? 

Currently this is not quite true -- series/arrays transform as timestamps but plain lists of dates become iso strings:
```
In [6]: serialize_json(df.Date[:5])
Out[6]: '[1356998400000.0,1357084800000.0,1357171200000.0,1357257600000.0,1357344000000.0]'

In [7]: serialize_json(list(df.Date[:5]))
Out[7]: '["2013-01-01","2013-01-02","2013-01-03","2013-01-04","2013-01-05"]'
```

I think the list case can be made consistent, though.

**Comment by bryevdv** [comment]
> I think the list case can be made consistent, though.

Well, I was wrong about this, but I think we just document it and live with it.

**Comment by bryevdv** [comment]
@philippjfr can you test this with HV/Panel when you get a chance?

**Comment by bryevdv** [comment]
@mattpap  @philippjfr  OK I think everything except plumbing to hook up whatever set of flatpickr features we want, is done. I think the Date/Datetime property situation is generally better. To summarize:

* `Date` accepts `dt.date` values and ISO date strings ("2020-01-11")

* `Datetime` accepts:
  - python, pandas, numpy datetime objects (including dt.time)
  - dt.date and date strings
  - ms since epoch timestamps
 
One weird but anavoidable corner case: lists of `dt.date` get serialized as ISO strings, arrays and series `dt.date` get serialized as datetime/timestamp

Weird stuff I noticed but did not touch: timedeltas and pandas Period values are serialized as datetimes. I think this is not the right thing to do, in general.

**Comment by bryevdv** [comment]
OK I still need to add more integration tests, but I am done hooking up plumbing. @mattpap any suggestions for typescript improvements welcome.  Some new features:

* calendar can be inline
* calendar position can be given (non-inline)
* enabled/disabled dates and date ranges can be provided

For later:

* multiple date range selection

Here is a test case to play with:
```
from bokeh.io import curdoc
from bokeh.layouts import column
from bokeh.models.widgets import DatePicker, Div, Button
from datetime import date, datetime

dp = DatePicker(title='Select start of sync date',
    value=datetime(2019, 9, 20),
    min_date=datetime(2019, 9, 1),
    max_date=datetime.utcnow(),
    # inline=True,
    # position="above",
    # enabled_dates=["2019-09-12", ("2019-09-18", datetime(2019, 9, 26))],
    # enabled_dates=["2019-09-24"],
    css_classes=["foo"])

def callback(attr,old,new):
    print('old was {} and new is {}'.format(old,new))

dp.on_change('value', callback)

button = Button()
def cb(): dp.min_date = "2019-09-15"
button.on_click(cb)

curdoc().add_root(column(button, *[Div(text="foo") for _ in range(10)], dp, *[Div(text="foo") for _ in range(10)], width=150))
```

cc @philippjfr still encourage to make sure `Date` property changes do not impact upstream.

**Comment by bryevdv** [comment]
@mattpap there are a couple of now failing js baselines, any thoughts welcome:
```
+Select bbox=[0, 0, 300, 31]

  ✓ should allow MultiSelect
  ✓ should allow Slider
  ✓ should allow DateSlider
  ✓ should allow RangeSlider
  ✓ should allow DateRangeSlider
  ✓ should allow DatePicker
  ✓ should allow Div
diff --git a/bokehjs/test/baselines/Widgets__should_allow_Div b/bokehjs/test/baselines/Widgets__should_allow_Div
index f36611e..2125ac4 100644
--- a/bokehjs/test/baselines/Widgets__should_allow_Div
+++ b/bokehjs/test/baselines/Widgets__should_allow_Div
@@ -1 +1 @@
-Div bbox=[0, 0, 61, 19]
+Div bbox=[0, 0, 60, 19]

```

**Comment by bryevdv** [comment]
Actually I guess running the unit tests locally updated the baseline values and I unintentionally checked them in. Have reverted them.

File: bokehjs/src/lib/models/widgets/date_picker.ts [hunk 3]
```diff
@@ -1,96 +1,75 @@
...
-  this.el.style.top = top + 'px'
+function _convert_date_list(value: DatesList): any[] {
+  const result: any[] = []
+  for (const item of value) {
+    if (isString(item))
+      result.push(item)
+    else if (isArray(item) && item.length == 2)
+      result.push({from: item[0], to: item[1]})
+  }
+  return result
```
Comment (mattpap) [inline bokehjs/src/lib/models/widgets/date_picker.ts]: > `type DatesList = (string | string[])[]`

Based on the above code the type should be `(string | [string, string])[]`. The second condition is unnecessary. The return type should be `(string | DateLimit<string>)[]`.

Comment (mattpap) [reply bokehjs/src/lib/models/widgets/date_picker.ts]: It would be very meaningful to `type DateType = string`, primarily for readability, even if that doesn't change anything from static typing perspective (TypeScript doesn't have nominal types unfortunately).

File: bokehjs/src/lib/models/widgets/date_picker.ts [hunk 4]
```diff
@@ -1,96 +1,75 @@
...
 
 export class DatePickerView extends InputWidgetView {
   model: DatePicker
 
   protected input_el: HTMLInputElement
 
-  private _picker: Pikaday
+  private _picker: flatpickr.Instance
+
+  private _set(key: string, value: any): void {
```
Comment (mattpap) [inline bokehjs/src/lib/models/widgets/date_picker.ts]: `key: keyof Options`, then you won't need the cast below.

File: bokehjs/src/lib/models/widgets/date_picker.ts [hunk 5]
```diff
@@ -1,96 +1,75 @@
...
-    return new Date(Number(tup[0]), Number(tup[1])-1, Number(tup[2]))
   }
 
-  _on_select(date: Date): void {
-    // Always use toDateString()!
-    // toString() breaks the websocket #4965.
-    // toISOString() returns the wrong day (IE on day earlier) #7048
-    // XXX: this should be handled by the serializer
-    this.model.value = date.toDateString()
+  _on_change(_selected_dates: any, date_string: string, _instance: flatpickr.Instance): void {
```
Comment (mattpap) [inline bokehjs/src/lib/models/widgets/date_picker.ts]: https://github.com/flatpickr/flatpickr/blob/master/src/types/options.ts#L11 to get rid of the `any` type.

Comment (bryevdv) [reply bokehjs/src/lib/models/widgets/date_picker.ts]: @mattpap the only way I can get those types to import is to do
```
import {Options as FlatpickrOptions, DateLimit} from "flatpickr/dist/types/options"
``` 
which does seem safe/good (importing from dist). Tried installing `@types/flatpickr` but trying to import that also yields an error. The only thing exported from standard `flatpickr` seems to be the `flatpickr` instance.

File: bokehjs/src/lib/models/widgets/date_picker.ts (hunk 3 above)
Comment (mattpap) [reply bokehjs/src/lib/models/widgets/date_picker.ts]: > `type DateType = string`

Actually, I will introduce that later, because there's an opportunity here to introduce pseudo nominal types.

File: bokehjs/src/lib/models/widgets/date_picker.ts (hunk 5 above)
Comment (mattpap) [reply bokehjs/src/lib/models/widgets/date_picker.ts]: This is a common mistake that library author make, i.e. not exporting publicly enough type information. Let's leave it for now.

File: bokehjs/src/lib/models/widgets/date_picker.ts [hunk 6]
```diff
@@ -1,96 +1,76 @@
...
+      this._picker.set(key as any, value)
+    }
+  }
 
   connect_signals(): void {
     super.connect_signals()
-    this.connect(this.model.change, () => this.render())
+
+    const {value, min_date, max_date, disabled_dates, enabled_dates, position, inline} = this.model.properties
+    this.connect(value.change, () => this._set("defaultDate", value.value()))
```
Comment (p-himik) [inline bokehjs/src/lib/models/widgets/date_picker.ts]: @bryevdv This sets only the initial date. The current date will not be changed. See the report at https://discourse.bokeh.org/t/datepicker-ui-not-updating-in-bokeh-2-0/5021

Comment (bryevdv) [reply bokehjs/src/lib/models/widgets/date_picker.ts]: @p-himik OK we should get a fix in for 2.0.1 (with a test) can you make an issue and I will take a look tomorrow.
