### PR TITLE
Protected against out of sync CDS view and selections

### LINKED ISSUE #14565: DataTable source update broken
### Software versions

Python version        :  3.10.12 (main, May 27 2025, 17:12:29) [GCC 11.4.0]
IPython version       :  (not installed)
Tornado version       :  6.4.2
NumPy version         :  2.0.2
Bokeh version         :  3.7.3
BokehJS static path   :  .../venv/lib/python3.10/site-packages/bokeh/server/static
node.js version       :  (not installed)
npm version           :  (not installed)
jupyter_bokeh version :  (not installed)
Operating system      :  Linux-6.8.0-64-generic-x86_64-with-glibc2.35

### Browser name and version

Firefox 140.0.4, Chromium 138.0.7204.157 

### Jupyter notebook / Jupyter Lab version

_No response_

### Expected behavior

The DataTable component does not update correctly when removing the last entry of the table.
The last entry should be removed from the table when the CDS does not contain it anymore.

### Observed behavior

The table still shows the entry which is not in the CDS anymore. When sorting the table, the entry is not shown anymore, however, the table seems to be in a strange state where adding items to CDS via `stream` does not show the new items in the table. 

### Example code

```Python
from typing import Callable
import numpy as np
from bokeh.document import Document
from bokeh.models import DataTable, ColumnDataSource, TableColumn, Button
from bokeh.server.server import Server

def start_server(setup_callable: Callable[[Document], None]):
    server = Server(setup_callable)
    # start timers and services and immediately return
    server.start()
    server.io_loop.add_callback(server.show, "/")
    server.io_loop.start()

def main(doc: Document):
    cds = ColumnDataSource(dict(my_col=[]))
    btn_add = Button(label="Add")
    btn_del = Button(label="Delete")
    columns = [
        TableColumn(field="my_col", title="My Column")
    ]
    table = DataTable(source=cds, columns=columns)

    def add_item():
        new_item = np.random.rand()
        cds.stream(dict(my_col=[new_item]))

    def delete_selected_items():
        num_items = len(cds.data["my_col"])
        to_remove = set(cds.selected.indices)
        to_keep = [i for i in range(num_items) if i not in to_remove]
        # give new data dict that only contains items to be kept
        cds.data = dict(my_col=np.array(cds.data["my_col"])[to_keep].tolist())

    btn_add.on_click(add_item)
    btn_del.on_click(delete_selected_items)

    doc.add_root(table)
    doc.add_root(btn_add)
    doc.add_root(btn_del)

if __name__ == '__main__':
    start_server(main)
```

### Stack traceback or browser console output

_No response_

### Screenshots

Here is a video showing the problem:

https://github.com/user-attachments/assets/9e3b85ed-23ff-4888-8367-741c9db7b7a5

### PR DESCRIPTION
**Pull request by mattpap**
fixes #14565

### CODE REVIEW

File: bokehjs/src/lib/core/util/bitset.ts [hunk 1]
```diff
@@ -84,16 +84,30 @@ export class BitSet implements Equatable {
...
+    return this._get(k)
+  }
+
+  protected _get(k: number): boolean {
     const i = k >>> 5  // Math.floor(k/32)
     const j = k & 0x1f // k % 32
     return ((this._array[i] >> j) & 0b1) == 0b1
   }
 
+  get_no_except(k: number): boolean {
```
Comment (mattpap) [inline bokehjs/src/lib/core/util/bitset.ts]: I'm tempted to just rename this to `get()` and make this the default behavior.

File: bokehjs/src/lib/core/util/bitset.ts [hunk 2]
```diff
@@ -83,23 +83,13 @@ export class BitSet implements Equatable {
     return bits
   }
 
-  private _check_bounds(k: number): void {
-    assert(0 <= k && k < this.size, `Out of bounds: 0 <= ${k} < ${this.size}`)
```
Comment (mattpap) [inline bokehjs/src/lib/core/util/bitset.ts:87]: One thing to point out about inefficiency of `_check_bounds()`, is that string interpolation is the main contributor, not the bounds check by itself.

File: bokehjs/src/lib/core/util/bitset.ts [hunk 3]
```diff
@@ -110,6 +100,20 @@ export class BitSet implements Equatable {
...
+    } else {
+      return false
+    }
+  }
+
+  set(k: number, v: boolean = true): void {
+    if (0 <= k && k < this.size) {
+      this._set(k, v)
+    }
+  }
```
Comment (muendlein) [inline bokehjs/src/lib/core/util/bitset.ts]: Do we need to have some kind of warning in case trying to set a value out of bounds or is that something the caller should take care of?

**Review by muendlein — APPROVED** [review]

File: bokehjs/src/lib/core/util/bitset.ts (hunk 2 above)
Comment (muendlein) [reply bokehjs/src/lib/core/util/bitset.ts:87]: @mattpap The latest commits seem to add some inefficiencies to the spatial method. I think for the spatial part calling the currently protected `_set` method is still the way to go in this case.

Comment (mattpap) [reply bokehjs/src/lib/core/util/bitset.ts:87]: I restored unchecked variants of `set()` and `get()`.

**Comment by mattpap** [comment]
@muendlein, thanks for review.
