### PR TITLE
Fix Legend's inactive visuals in CSS mode

### LINKED ISSUE #14442: Regression in legend and plot interaction behaviour
### Software versions

Python version        :  3.11.10 (main, Oct 16 2024, 04:38:48) [Clang 18.1.8 ]
Tornado version       :  6.4.2
NumPy version         :  1.26.0
Bokeh version         :  3.7.0
BokehJS static path   : .venv/lib/python3.11/site-packages/bokeh/server/static
node.js version       :  v20.16.0
npm version           :  10.8.1
Operating system      :  Linux-6.8.0-52-generic-x86_64-with-glibc2.35

### Browser name and version

Google Chrome 128.0.6613.114 (Official Build) (64-bit)

### Expected behavior

Thank you for this great library.

There appears to be a regression in legend behavior in 3.7 from version 3.6.
The behavior in 3.6 matches expectations.

### Observed behavior

How to reproduce:

- go to https://docs.bokeh.org/en/latest/docs/user_guide/interaction/legends.html
- repeat the following instructions using versions 3.6.3 and 3.7.2:
  - go to the plot in the "Hiding glyphs" sections
  - hover over and click on legend labels for each rendered line 

Behavioral differences:
- hover
  - 3.6.3: hover shows a mouse pointer over legend label and marker
  - 3.7.2: hover shows a text selection cursor over legend label and mouse pointer over marker
- interaction
  - 3.6.3: clicking to hide greys out the label and marker and hides line
  - 3.7.2: clicking to hide leaves label and marker unchanged and hides line (see screenshot)
- selection
  - 3.6.3: clicking on plot does not select the plot
  - 3.7.2: clicking on plot seems to select the plot element (notice the blue border in the screenshot)

### Screenshots

Image

### PR DESCRIPTION
**Pull request by mattpap**
fixes #14442

### CODE REVIEW

File: bokehjs/test/integration/regressions.ts [hunk 1]
```diff
@@ -4407,4 +4407,37 @@ describe("Bug", () => {
...
+      const r4 = p.line(x, f`3*${y}`, {line_color: "green"})
+
+      const legend = new Legend({
+        items: [
+          new LegendItem({label: "sin(x)",   renderers: [r0, r1]}),
+          new LegendItem({label: "2*sin(x)", renderers: [r2]}),
+          new LegendItem({label: "3*sin(x)", renderers: [r3, r4]}),
+        ],
+        location: "top_right",
+        click_policy: "mute",
```
Comment (hoxbro) [inline bokehjs/test/integration/regressions.ts:4436]: Maybe have a parameterized test, where click_policy has mute and hide.

Not sure if the BokehJS test framework can easily do this; if it can't, then just ignore this.

**Review by hoxbro — APPROVED** [review]
LGTM.

In the issue, you wrote:

> In 3.7 there's partial support for selectable text on the canvas, thus the cursor. We may introduce a mode for toggling text selectablity in the future.

Have you opened an issue/discussion about this?

File: bokehjs/test/integration/regressions.ts (hunk 1 above)
Comment (mattpap) [reply bokehjs/test/integration/regressions.ts:4436]: > Not sure if the BokehJS test framework can easily do this; if it can't, then just ignore this.

Typically we would add a function with a single argument for this.

> Maybe have a parameterized test, where click_policy has mute and hide.

Visual behavior is the same for all interactive policies.

**Comment by mattpap** [comment]
> Have you opened an issue/discussion about this?

https://github.com/bokeh/bokeh/issues/14449

**Review by hoxbro — APPROVED** [review]
