### PR TITLE
Fix FactorRange bounds on initial render

### LINKED ISSUE #14815: Bounds using FactorRanges aren't respected in the first visualization
When using a `FactorRange` with defined bounds, this bounds are only applied after the first interaction with a tool and therefor aren't always respected in the initial visualization.

In the MRE below the bounds are set in a way, that the first factor is excluded.

```python
from bokeh.models import FactorRange, Range1d
from bokeh.plotting import figure, show, output_notebook
output_notebook()

factors = ['a', 'b', 'c']

p = figure(width=300, height=300, tools="reset,pan", x_range=FactorRange(*factors, bounds=(1,3)))
p.line(factors, [1,2,3])
show(p)
```

https://github.com/user-attachments/assets/36375f2c-e7b5-40b1-ae00-313af56945fc

This issue documents the behavior after solving #14568.

### PR DESCRIPTION
**Pull request by it-education-md**
- [x] issues: fixes #14815
- [x] tests added / passed
- [x] release document entry (if new feature or API change)

### CODE REVIEW

File: bokehjs/test/unit/regressions.ts [hunk 1]
```diff
@@ -2004,4 +2004,27 @@ describe("Bug", () => {
       expect(x_range.interval).to.be.equal([0, 3])
     })
   })
+
+  describe("in issue #14815", () => {
+    it("applies explicit bounds on initial render for FactorRange", async () => {
```
Comment (mosc9575) [inline bokehjs/test/unit/regressions.ts]: @it-education-md Thanks a lot for your contribution. This looks very good.

The test fails as expected without your changes, but the error message reads currently

Image.

Maybe change it to 
```suggestion
    it("doesn't apply explicit bounds on initial render when using FactorRange", async () => {
```

And please add a comment to the [3.9 release notes](https://github.com/bokeh/bokeh/blob/branch-3.9/docs/bokeh/source/docs/releases/3.9.0.rst).

Before we can merge, we will wait for the approval of a core member of the bokeh team.

Comment (it-education-md) [reply bokehjs/test/unit/regressions.ts]: @mosc9575 Perfect, thanks for your feedback. Fixed all in the below commit.

**Review by mosc9575 — APPROVED** [review]

File: bokehjs/test/unit/regressions.ts [hunk 2]
```diff
@@ -2004,4 +2004,27 @@ describe("Bug", () => {
...
+
+  describe("in issue #14815", () => {
+    it("doesn't apply explicit bounds on initial render when using FactorRange", async () => {
+      const factors = ["a", "b", "c"]
+      const x_range = new FactorRange({factors, bounds: [1, 3]})
+      const p = fig([200, 200], {tools: "reset,pan", x_range})
+      p.line(factors, [1, 2, 3])
+
+      const {view} = await display(p)
+      await view.ready
```
Comment (mattpap) [inline bokehjs/test/unit/regressions.ts]: This line should be removed, because `await display()` already awaits the ready promise. It would be useful to `await view.ready` if you made any changes to the plot after displaying it.
```suggestion
      await display(p)
```

**Review by mattpap — CHANGES_REQUESTED** [review]

File: bokehjs/test/unit/regressions.ts (hunk 2 above)
Comment (it-education-md) [reply bokehjs/test/unit/regressions.ts]: @mattpap Cool, pushed a fix commit.

**Review by mattpap — APPROVED** [review]
@it-education-md, thanks.
