### PR TITLE
Set crossorigin on images to allow save tool to work

### LINKED ISSUE #8976: [BUG] Geographical plots cannot be saved with the save tool
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)

OS: Ubuntu 18.04
Browser: Chrome (74.0.3729.169) and Firefox (67.0)
Python: 3.7.3 (Anaconda)
Bokeh: 1.2.0 (Installed via default channel)
Jupyter: 4.4.0

#### Description of expected behavior and the observed behavior

Bokeh plots generated with geospatial tile providers cannot be saved when pressing on the save button in the bokeh toolbar.

Expected a pop up to download the current plot after clicking on the button but instead nothing appeared to happen. Inspecting the browser console output shows an **error being logged each time the save button is clicked**.

#### Complete, minimal, self-contained example code that reproduces the issue

Ran inside a Jupyter notebook.

``` python
from bokeh.plotting import figure, show, output_file, output_notebook
from bokeh.tile_providers import get_provider, Vendors
from bokeh.models import WMTSTileSource

#output_notebook()
output_file("tile.html")

tile_provider = get_provider(Vendors.CARTODBPOSITRON)
#url = 'http://localhost:8080/styles/klokantech-basic/{z}/{x}/{y}.png'
#tile_provider = WMTSTileSource(url=url)

TOOLS = 'pan,wheel_zoom,save'

# range bounds supplied in web mercator coordinates
p = figure(x_range=(-2000000, 6000000), y_range=(-1000000, 7000000),
           x_axis_type="mercator", y_axis_type="mercator", tools=TOOLS)
p.add_tile(tile_provider)
# Add a red circle onto the map
p.circle(0, 0, radius=100000, fill_color='red')

show(p)
```

Experienced the same error with both `output_notebook()` and `output_file('tile.html')`.

Experienced the same error when using `Vendors.CARTODBPOSITRON`, `Vendors.STAMEN_TERRAIN` and `Vendors.STAMEN_TONER` as the tile provider.

Experienced the same error when using custom `WMTSTileSource` using tiles from an OpenMapTiles server running locally.

I was able to successfully use the save tool when the `p.add_tile(tile_provider)` line was removed.

#### Stack traceback and/or browser JavaScript console output

Console output for Chrome:

```
bokeh-1.2.0.min.js:31 Uncaught DOMException: Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.
    at i.save (https://cdn.pydata.org/bokeh/release/bokeh-1.2.0.min.js:31:399569)
    at e.doit (https://cdn.pydata.org/bokeh/release/bokeh-1.2.0.min.js:31:483536)
    at e.<anonymous> (https://cdn.pydata.org/bokeh/release/bokeh-1.2.0.min.js:31:479970)
    at e.t.emit (https://cdn.pydata.org/bokeh/release/bokeh-1.2.0.min.js:31:69491)
    at e.emit (https://cdn.pydata.org/bokeh/release/bokeh-1.2.0.min.js:31:69678)
    at e._clicked (https://cdn.pydata.org/bokeh/release/bokeh-1.2.0.min.js:31:479672)
    at HTMLDivElement.<anonymous> (https://cdn.pydata.org/bokeh/release/bokeh-1.2.0.min.js:31:487001)
```

Console output for Firefox:

```
SecurityError: The operation is insecure. bokeh-1.2.0.min.js:31
    save https://cdn.pydata.org/bokeh/release/bokeh-1.2.0.min.js:31
    doit https://cdn.pydata.org/bokeh/release/bokeh-1.2.0.min.js:31
    connect_signals https://cdn.pydata.org/bokeh/release/bokeh-1.2.0.min.js:31
    emit https://cdn.pydata.org/bokeh/release/bokeh-1.2.0.min.js:31
    emit https://cdn.pydata.org/bokeh/release/bokeh-1.2.0.min.js:31
    _clicked https://cdn.pydata.org/bokeh/release/bokeh-1.2.0.min.js:31
    initialize https://cdn.pydata.org/bokeh/release/bokeh-1.2.0.min.js:31
```

I believe you should be able to get the same error when clicking on the save button on the first example in the [Mapping Geo Data User Guide](https://bokeh.pydata.org/en/latest/docs/user_guide/geo.html).

### PR DESCRIPTION
**Pull request by mattpap**
fixes #8976

### CODE REVIEW

File: bokehjs/src/lib/models/textures/image_url_texture.ts [hunk 1]
```diff
@@ -30,6 +30,7 @@ export abstract class ImageURLTexture extends Texture {
   initialize(): void {
     super.initialize()
     this.image = new Image()
+    this.image.crossOrigin = "Anonymous"
```
Comment (bryevdv) [inline bokehjs/src/lib/models/textures/image_url_texture.ts]: Unlike other places, this one has a capitalized "A" not sure if that is intentional / matters

Comment (mattpap) [reply bokehjs/src/lib/models/textures/image_url_texture.ts]: It doesn't matter, but this reminds me that the mechanism implemented in `ImageURL` should be generalized and used here and other places.

**Comment by bryevdv** [comment]
@mattpap this PR breaks the airport map example for me:

> [Error] Cannot load image http://tile.stamen.com/terrain/5/9/13.png due to access control checks.
[Error] Failed to load resource: Origin null is not allowed by Access-Control-Allow-Origin. (13.png, line 0)
