### PR TITLE
Use underscore map function in ColorBar

### LINKED ISSUE #5056: ColorBar not working in Safari
```console
TypeError: major_coords[i].map is not a function. (In 'major_coords[i].map(function(coord) {
        return scale_length - coord;
      })', 'major_coords[i].map' is undefined)
```

screen shot 2016-08-30 at 10 53 27 pm

### PR DESCRIPTION
**Pull request by birdsarah**
Fixes #5056

I've opened a separate issue about testing for this: #5058

### CODE REVIEW

File: bokehjs/src/coffee/models/annotations/color_bar.coffee [hunk 1]
```diff
@@ -497,8 +497,8 @@ class ColorBar extends Annotation.Model
 
     # Because we want the scale to be reversed
     if @orientation == 'vertical'
-      major_coords[i] = major_coords[i].map((coord) -> return scale_length - coord)
-      minor_coords[i] = minor_coords[i].map((coord) -> return scale_length - coord)
+      major_coords[i] = _.map(major_coords[i], (coord) -> return scale_length - coord)
+      minor_coords[i] = _.map(minor_coords[i], (coord) -> return scale_length - coord)
```
Comment (mattpap) [inline bokehjs/src/coffee/models/annotations/color_bar.coffee]: Using array comprehension would be even better (one less function call per iteration).

**Comment by canavandl** [comment]
LGTM

File: bokehjs/src/coffee/models/annotations/color_bar.coffee (hunk 1 above)
Comment (birdsarah) [inline bokehjs/src/coffee/models/annotations/color_bar.coffee]: Thanks @mattpap! Really appreciate it.

cc @canavandl
