### PR TITLE
Fix label heuristic when `orient == 0`

### LINKED ISSUE #10042: [BUG] Bad label rendering with hbar / subgroup_label_orientation
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)

bokeh 2.0.2
python 3.8.2
macOS 10.15.4
chrome 81.0.4044.138 

#### Description of expected behavior and the observed behavior

When plotting hbar with multiple groups, setting `p.yaxis[0].subgroup_label_orientation` to `0` or `0.0` the label is moved to a weird place. The problem is not occuring with the orientation is to set to a very small value (e.g. `1e-16`).

#### Complete, minimal, self-contained example code that reproduces the issue

```python
import bokeh.palettes as bpa
import bokeh.plotting as bp
import bokeh.transform as bt
from bokeh.sampledata.autompg import autompg_clean as df

df.cyl = df.cyl.astype(str)
df.yr = df.yr.astype(str)
indices = ["cyl", "origin", "mfr"]
index_column = "_".join(indices)
group = df.groupby(indices)

cmap = bt.factor_cmap(
    index_column,
    palette=bpa.Category10_10,
    factors=sorted(df[indices[0]].unique()),
    end=1,
)

p = bp.figure(y_range=group)
p.hbar(
    y=index_column,
    right="mpg_mean",
    source=group,
    height=0.9,
    line_color=None,
    fill_color=cmap,
)
p.x_range.start = 0
p.yaxis[0].subgroup_label_orientation = 0
# p.yaxis[0].subgroup_label_orientation = 1e-16

bp.output_file("tmp/hbar.html")
bp.show(p)
```

##### `p.yaxis[0].subgroup_label_orientation = 0`

Screenshot 2020-05-20 at 1 16 58 PM

##### `p.yaxis[0].subgroup_label_orientation = 1e-16`

Screenshot 2020-05-20 at 1 17 13 PM

### PR DESCRIPTION
**Pull request by mattpap**
- [x] add a integration test

fixes #10042

### CODE REVIEW

File: bokehjs/src/lib/core/layout/side_panel.ts [hunk 1]
```diff
@@ -233,10 +233,7 @@ export class SidePanel extends ContentLayoutable {
       baseline = _baseline_lookup[side][orient]
       align = _align_lookup[side][orient]
     } else {
-      if (orient === 0) {
-        baseline = "whatever" as any // XXX: _baseline_lookup[side][orient]
-        align = "whatever" as any // XXX: _align_lookup[side][orient]
-      } else if (orient < 0) {
```
Comment (mattpap) [inline bokehjs/src/lib/core/layout/side_panel.ts:239]: @bryevdv, I don't recall why this special case is here, but this has been broken since I can remember. Maybe there are better defaults for this case?

Comment (bryevdv) [reply bokehjs/src/lib/core/layout/side_panel.ts:239]: I'd love to know what the rationale was but it was the better part of a decade ago and I really have no idea. The original CS (at least as far back as I can find) does this:
```
     else if orient == 0
        baseline = _baseline_lookup[side][orient]
        align = _align_lookup[side][orient]
```
which is clearly just broken unless CS does something magical with `obj[0]` when there is no `0` key in the object. Seems safe to remove with some minimal smoke testing.
