### PR TITLE
Change jitter caching to only cache offsets instead of values

### LINKED ISSUE #10756: [BUG] Jitter caching too aggressively
#### Versions
bokeh 2.2.3 (via conda 4.8.3); Mac OS X 10.15.7 

#### Description of expected behavior and the observed behavior
Scatter points jittered on a categorical axis don't move when the categorical factor range (provided as `range` parameter) is modified. In a [Discourse thread](https://discourse.bokeh.org/t/6848), Bryan put this down to a "deficiency in the current caching behavior of the jitter transform".

Below is a brief example where a button reverses a categorical axis: red jittered points move, blue jittered ones don’t.

#### Example

```python
from bokeh.transform import jitter
from bokeh.models import ColumnDataSource, FactorRange, CustomJS
from bokeh.models.widgets import Button
from bokeh.layouts import column
from bokeh.plotting import figure
from bokeh.io import show

source = ColumnDataSource({
    'name': ['a', 'a', 'a', 'a', 'a'],
    'val': [1, 1, 1, 1, 1],
})

p = figure(x_range=FactorRange(factors=['a', 'b']),  
           y_range=(0, 2), plot_width=200, plot_height=200)

p.scatter(x=jitter('name', 0.5, range=p.x_range), y='val', size=5, alpha=0.5, color='blue', source=source)
p.scatter(x='name', y=jitter('val', 0.5), size=5, color='red', alpha=0.5, source=source)

button = Button(label='Reorder factors')
button.js_on_click(CustomJS(args={'x_range': p.x_range}, code="""
    const factors = [...x_range.factors];
    const reversed = factors.reverse();
    x_range.factors = reversed;
"""))
column = column(button, p)
show(column)
```

#### Screenshots or screencasts of the bug in action
Before click (original x axis):
before_click
After click (x axis factors reversed):
after_click

### PR DESCRIPTION
**Pull request by Ariel-Yeung**
All pull requests must have an associated issue in the issue tracker. If there
isn't one, please go open an issue describing the defect, deficiency or desired
feature. You can read more about our issue and PR processes in the
[wiki](https://github.com/bokeh/bokeh/wiki/BEP-1:-Issues-and-PRs-management).

- [ ] issues: fixes #10756
- [ ] tests added / passed
- [ ] release document entry (if new feature or API change)

### CODE REVIEW

**Comment by Ariel-Yeung** [comment]
I believe my changes fixes the issue of ["Jitter should cache the offsets, not the final values with offsets baked in."](https://github.com/bokeh/bokeh/issues/10756#issuecomment-739067304). But it doesn't fix the problem in the example script of issue #11400 . Perhaps this is not giving the expected behavior because of another reason?

File: bokehjs/src/lib/models/transforms/jitter.ts [hunk 1]
```diff
@@ -35,10 +36,28 @@ export class Jitter extends RangeTransform {
   }
 
   override v_compute(xs0: Arrayable<number | Factor>): Arrayable<number> {
-    if (this.previous_values != null && this.previous_values.length == xs0.length)
-      return this.previous_values
-    this.previous_values = super.v_compute(xs0)
-    return this.previous_values
+    let xs: Arrayable<number>
+    if (super.range instanceof FactorRange)
+      xs = super.range.v_synthetic(xs0)
```
Comment (mattpap) [inline bokehjs/src/lib/models/transforms/jitter.ts:41]: `range` attribute is inherited, so there's no reason to use `super` here. Just use `this`.

File: bokehjs/src/lib/models/transforms/jitter.ts [hunk 2]
```diff
@@ -35,10 +36,28 @@ export class Jitter extends RangeTransform {
...
+    else if (isArrayableOf(xs0, isNumber))
+      xs = xs0
+    else
+      throw new Error("unexpected")
+
+    if (this.previous_offsets != null && this.previous_offsets.length == xs.length) {
```
Comment (mattpap) [inline bokehjs/src/lib/models/transforms/jitter.ts:47]: This could be simplified to `if (this.previous_offsets?.length == xs.length)`. Also, `previous_offsets` is implicitly undefined, but we would prefer this to be explicit, so change the type to `previous_offsets: Arrayable<number> | undefined`.

File: bokehjs/src/lib/models/transforms/jitter.ts [hunk 3]
```diff
@@ -35,10 +36,28 @@ export class Jitter extends RangeTransform {
...
+      const result = new (infer_type(xs))(xs.length)
+      for (let i = 0; i < xs.length; i++) {
+        result[i] = this.previous_offsets[i] + xs[i]
+      }
+      return result
```
Comment (mattpap) [inline bokehjs/src/lib/models/transforms/jitter.ts:52]: This whole block could be simplified with:
```ts
return map(xs, (xsi, i) => this.previous_offsets[i] + xsi)
```
from `core/util/arrayable`. `map()` preserves the length and type of the container. Similarly the code below could be simplified.

File: bokehjs/src/lib/models/transforms/jitter.ts [hunk 4]
```diff
@@ -35,10 +36,28 @@ export class Jitter extends RangeTransform {
...
+    }
+
+    const computed_values = super.v_compute(xs)
+    this.previous_offsets = new (infer_type(xs))(xs.length)
+    for (let i = 0; i < xs.length; i++) {
+      this.previous_offsets[i] = computed_values[i] - xs[i]
```
Comment (mattpap) [inline bokehjs/src/lib/models/transforms/jitter.ts:58]: Calling super like this will result in double synthetic encoding in the case of of `FactorRange`. This will, however, work because synthetic coordinates are passed through `FactorRange.v_compute()`. Instead drop `super.v_compute()` and use `this._compute(xs[i])` directly. Then by using `map()`, you would get something like:
```ts
this.previous_offsets = map(xs, (xsi) => this._compute(xsi) - xsi)
````

File: bokehjs/src/lib/models/transforms/jitter.ts [hunk 5]
```diff
@@ -35,10 +36,28 @@ export class Jitter extends RangeTransform {
...
-      return this.previous_values
-    this.previous_values = super.v_compute(xs0)
-    return this.previous_values
+    let xs: Arrayable<number>
+    if (super.range instanceof FactorRange)
+      xs = super.range.v_synthetic(xs0)
+    else if (isArrayableOf(xs0, isNumber))
+      xs = xs0
+    else
+      throw new Error("unexpected")
```
Comment (mattpap) [inline bokehjs/src/lib/models/transforms/jitter.ts:45]: This would be better replaced with `unreachable()` from `core/util/assert`. The code in the parent class wasn't updated when this utility function was added.

File: bokehjs/src/lib/models/transforms/jitter.ts (hunk 1 above)
Comment (Ariel-Yeung) [reply bokehjs/src/lib/models/transforms/jitter.ts]: Changed to `this`

File: bokehjs/src/lib/models/transforms/jitter.ts (hunk 2 above)
Comment (Ariel-Yeung) [reply bokehjs/src/lib/models/transforms/jitter.ts]: Changed

File: bokehjs/src/lib/models/transforms/jitter.ts (hunk 5 above)
Comment (Ariel-Yeung) [reply bokehjs/src/lib/models/transforms/jitter.ts]: Changed to using `unreachable()`

File: bokehjs/src/lib/models/transforms/jitter.ts (hunk 3 above)
Comment (Ariel-Yeung) [reply bokehjs/src/lib/models/transforms/jitter.ts]: Using `this` in arrow function didn't work, so I assigned `previous_offsets` to another variable to pass it into the arrow function.

File: bokehjs/src/lib/models/transforms/jitter.ts (hunk 4 above)
Comment (Ariel-Yeung) [reply bokehjs/src/lib/models/transforms/jitter.ts]: Changed to using `this._compute` and using `map`. Thanks for the explanation.

File: bokehjs/src/lib/models/transforms/jitter.ts (hunk 5 above)
Comment (Ariel-Yeung) [reply bokehjs/src/lib/models/transforms/jitter.ts]: Also changed in other files that is throwing the same error

File: bokehjs/src/lib/models/transforms/jitter.ts [hunk 6]
```diff
@@ -35,10 +38,22 @@ export class Jitter extends RangeTransform {
...
+    else
+      unreachable()
+
+    if (this.previous_offsets?.length == xs.length) {
+      const cache_offsets = this.previous_offsets
+      return map(xs, (xs, i) => cache_offsets[i] + xs)
+    }
+
+    const computed_values = map(xs, (xs) => this._compute(xs))
+    this.previous_offsets = map(xs, (xs, i) => computed_values[i] - xs)
```
Comment (bryevdv) [inline bokehjs/src/lib/models/transforms/jitter.ts:55]: This subtraction is a little awkward to me. I think it would be cleaner if we change `_compute` to compute and return *only the offsets*, instead of the final values. The the logic can be more like:
```
 if (this.previous_offsets?.length != xs.length) {
    this.previous_offsets = this._compute(xs))
}

const {offsets} = this
return map(xs, (xs, i) => xs + offsets[i])
```

**Comment by bryevdv** [comment]
Hrm I guess I'd forgotten that `_compute` is required API to implement in subclasses. Perhaps that will need to be re-visited later. But for now you can just rename the method to `_compute`

**Comment by bryevdv** [comment]
I verified that this PR fixes the OP. I still think the code and use of `_compute` is a little wonky, since the original intent of `_compute` was to compute final values, but here it is simpler to use it to compute only the offsets. I think that points to a making a design improvement though, and we don't have to do that.  I'll plan to merge this end of day today unless there's a request for more time.

**Review by bryevdv — APPROVED** [review]

**Comment by bryevdv** [comment]
Thanks @Ariel-Yeung !
