### PR TITLE
Revert JLab integration changes

### LINKED ISSUE #6808: nbconverted static notebooks fail to render
After recent JLab work, running e.g. 
```
jupyter nbconvert --to html quickstart.ipynb
```
results in a JS console error:
```
TypeError: undefined is not an object (evaluating 'root.Jupyter.OutputArea')
```
and no plots displayed. 

Possible that the test just needs to be protected better to be skipped entirely in the static case.

Using `nbconvert 5.2.1` with
```
jupyter_client            5.1.0                    py36_0
jupyter_core              4.3.0                    py36_0
notebook                  5.0.0                    py36_0
```

cc @canavandl

### PR DESCRIPTION
**Pull request by canavandl**
This reverts commit e45e24f8e32534d64a386f5d36357bb5f351814b, reversing
changes made to c3ee83210d75ea0dbbb5ab92fe69dc4756ec2e88.

Revert "add mechanism to install external notebook display hooks (#6799)"

This reverts commit 33c2356663e5747296ac5576af74d4a1dad1b0c2.

Revert "Add mime message for jupyter lab load mime renderer (#6797)"

This reverts commit 6120d89d99d69b6f1756be6eb216b1ba1441683a.

Revert "Merge pull request #6774 from bokeh/canavandl/nb_register_mime"

This reverts commit 2788ce89fce47527d980c8ccbb83010e462023b0, reversing
changes made to e244cc4603f0bf7b50a43f2e91ddc562b93b5e0e.

Fix revert conflicts

All pull requests must have an associated issue in the issue tracker. If there
isn't one, please go open an issue describing the defect, deficiency or desired
feature. You can read more about our issue and PR processes in the
[wiki](https://github.com/bokeh/bokeh/wiki/BEP-1:-Issues-and-PRs-management).

- [ ] issues: fixes #6808 
- [ ] tests added / passed
- [ ] release document entry (if new feature or API change)

### CODE REVIEW

File: bokeh/core/_templates/autoload_nb_js.js [hunk 1]
```diff
@@ -140,13 +25,18 @@
...
       var el = document.getElementById({{ elementid|json }});
-      if (el != null) {
-        el.textContent = "BokehJS " + Bokeh.version + " successfully loaded.";
-      }
+      el.textContent = "BokehJS " + Bokeh.version + " successfully loaded.";
     } else if (Date.now() < root._bokeh_timeout) {
       setTimeout(display_loaded, 100)
     }
   }
+
```
Comment (canavandl) [inline bokeh/core/_templates/autoload_nb_js.js]: this is dead code that needs to be deleted.

File: bokeh/core/_templates/autoload_nb_js.js [hunk 2]
```diff
@@ -140,13 +25,18 @@
   function display_loaded() {
     if (root.Bokeh !== undefined) {
       var el = document.getElementById({{ elementid|json }});
-      if (el != null) {
```
Comment (canavandl) [inline bokeh/core/_templates/autoload_nb_js.js]: This should probably be unchanged also.
