### PR TITLE
Ship `*.js` and `*.d.ts` together under `build/js/lib`

### LINKED ISSUE #12617: [BUG]  Runtime error of incorrect option name crashes webapp (Angular)
### Software versions

node.js : 14.21.1 (lts/fermium)

### Browser name and version

Firefox 102.4

### Jupyter notebook / Jupyter Lab version

_No response_

### Expected behavior

I am building a webapp in Angular 14 using `npx ng serve`, which is normally a typescript project. If I create a figure with an object with an incorrect parameter, *e.g.,* Line, I would expect the compiler to yell about an incorrect option being passed and fail to build, or expect that figure object wouldn't render.

### Observed behavior

The project builds fine, but the webapp renders absolutely nothing. As the console spits out an error on runtime that the argument passed is invalid. See screenshots section shows an example of passing `apple: 3` to a Line object, but this could be easily mistaken by a mistype of an option such as `linewidth` when it should be `line_width`.

### Example code

You can get a system up and going from [here](https://discourse.bokeh.org/t/angular-10-bokeh-bokehjs-not-compiling-or-with-webpack/9469/6) and [here](https://discourse.bokeh.org/t/angular-14-bokeh-bokehjs-3/9742/2)

```Python
/* angular14/bokehdemo/src/app/plot/plot.component.ts */
import { Component, OnInit } from '@angular/core';
import * as Bokeh from '@bokeh/bokehjs/build/js/lib/api';

@Component({
  selector: 'app-plot',
  templateUrl: './plot.component.html',
  styleUrls: ['./plot.component.scss']
})
export class PlotComponent implements OnInit {

  constructor() { 
    const plt = Bokeh.Plotting;
    const la = Bokeh.LinAlg;
    
    let x = la.linspace(0, 10, 20);
    let y = x.map(function(v: number) { return v**2 });

    let source = new Bokeh.ColumnDataSource({
      data: {x: x, y: y}
    });
    
    let tools = "pan,crosshair,wheel_zoom,box_zoom,reset,save";
    let p = plt.figure({title: "Test", tools: tools});
    
    let line = p.line(
      {field: 'x'},
      {field: 'y'},
      {source: source, linewidth: 2}, /*WARN incorrect parameter should be line_width */
    );

    plt.show(p, '#bokeh-chart');
  }

  ngOnInit(): void {
  }

}
```

### Stack traceback or browser console output

See the screenshots, but compilation shows no errors. **Whether or not this is an issue with how the Angular build system works with javascript libraries is to be determined on my end.** However, handling incorrect parameters so that build systems see them would be useful.

This may be something related to creating a angular specific package that uses the typescript of bokehjs. 

### Screenshots

image

### PR DESCRIPTION
**Pull request by mattpap**
This isn't any specific reason to keep them separate, but keeping them together makes it easier to use type declarations.

fixes #12617

### CODE REVIEW

**Comment by bryevdv** [comment]
I think this will cause these files to be included under `server/static`, unless we exclude them in the manifest or similar. How big are they?

**Comment by mattpap** [comment]
A few megabytes total. I removed them from package data.

**Comment by mattpap** [comment]
This PR achieves two main goals:

1. `*.d.ts` files are now stored together with `*.js` files under `bokehjs/build/js/lib`, which simplifies `tsconfig.json` in extensions, because second entry for types in `paths: {"@bokehjs/": ...}` is not needed anymore.
2. Issues with updating `MANIFEST.in` prompted me to review what we include there, which resulted in the size of bokeh's sdist package being reduced from 16 MB to 7.5 MB, due to removal of unnecessary bokehjs' build products, like ESM bundles (not usable yet), individual `*.js` files (not useful for anything in a Python package) and especially huge `bokeh.json` (I use `*.d.ts` files to recover the need information). `*.d.ts` files have to be included, otherwise TypeScript compilation will fail (we already include TypeScript's standard library).

The rest of the changes is fiddling with CI, because previously extensions' examples and tests relied on bokehjs installed from npm, but that's impossible to keep in sync in PRs like this one and in general. So I reverted to using local bokehjs installation.  However, instead of using the build directory of bokehjs directly, I'm using npm-generated (by `npm pack`) bokehjs package, which is equivalent to what's published to npm. One caveat is making sure that the package is available for testing (https://github.com/bokeh/bokeh/pull/12635/commits/1ea6550a429bde1c0ecfe8706d178e4ee448954a), which will required update of the docker image (docker tests are failing right now). Otherwise this PR is ready for review.

**Comment by philippjfr** [comment]
Very, very happy to see the reduction in the size of the bundle.

**Comment by ianthomas23** [comment]
> One caveat is making sure that the package is available for testing (https://github.com/bokeh/bokeh/commit/1ea6550a429bde1c0ecfe8706d178e4ee448954a), which will required update of the docker image (docker tests are failing right now).

Noted.

**Comment by mattpap** [comment]
Just to note, I'm still trying to figure out what's the best approach, because I don't like what I'm doing in https://github.com/bokeh/bokeh/commit/1ea6550a429bde1c0ecfe8706d178e4ee448954a. It would be better to just pack once in the build step, which is done anyway, and propagate that to subsequent jobs. Though I support that will also require a rebuild of the image.

**Comment by mattpap** [comment]
This is now fully ready. Docker workflow fails, because of missing bokehjs package artifact (see last commit).

**Comment by bryevdv** [comment]
@ianthomas23 asked for a chance to look at this first thing tomorrow

File: bokehjs/make/tasks/pack.ts [hunk 1]
```diff
@@ -0,0 +1,35 @@
...
+  if (!fs.existsSync(dist)) {
+    fs.mkdirSync(dist, {recursive: true})
+  }
+
+  const npm = process.platform != "win32" ? "npm" : "npm.cmd"
+  const {status, stdout, stderr} = cp.spawnSync(npm, ["pack", `--pack-destination=${dist}`], {stdio: "pipe", encoding: "utf-8"})
+  if (status !== 0) {
+    console.error(stdout)
+    console.error(stderr)
+    throw new BuildError("pack", `faild to run '${npm} pack'`)
```
Comment (ianthomas23) [inline bokehjs/make/tasks/pack.ts]:
```suggestion
    throw new BuildError("pack", `failed to run '${npm} pack'`)
```

File: .github/workflows/bokehjs-ci.yml [hunk 2]
```diff
@@ -97,6 +97,13 @@ jobs:
             cp ${SRC}/report.{json,out} ${CHANGED} ${DST}
           fi
 
+      - name: Upload package
+        if: runner.os == 'Linux' && (success() || failure())
+        uses: actions/upload-artifact@v3
+        with:
+          name: bokehjs-package
+          path: bokehjs/build/dist/bokeh-bokehjs-*.tgz
```
Comment (ianthomas23) [inline .github/workflows/bokehjs-ci.yml:105]: Is this right to be different to that used in `bokeh-ci.yml`?:
```
path: bokehjs/build/dist/bokeh-bokehjs.tgz
```

**Review by ianthomas23 — APPROVED** [review]
Looks like a rebase is needed.

File: .github/workflows/bokehjs-ci.yml (hunk 2 above)
Comment (mattpap) [reply .github/workflows/bokehjs-ci.yml:105]: This was intentional, but I changed this to have the same artifact layout in bokeh-ci and bokehjs-ci. Now I create a symbolic link to the versioned package, so that tests can resolve it without a version specification.

Comment (ianthomas23) [reply .github/workflows/bokehjs-ci.yml:105]: Thanks for clarifying.

**Comment by muendlein** [comment]
@mattpap With this update I am running into some issues on Windows when doing the dev setup: `pip install -e .`  errors with the following exception:

```
          [19:13:56] failed: Error: EPERM: operation not permitted, symlink 'bokeh-bokehjs-3.1.0-dev.5.tgz' -> 'build\dist\bokeh-bokehjs.tgz'
          [19:13:56]     at Object.symlinkSync (node:fs:1713:3)
          [19:13:56]     at npm_pack (..\bokehjs\make\tasks\pack.ts:30:6)
```

**Comment by mattpap** [comment]
What versions of Windows and nodejs do you use? In this case we can copy instead of symlinking.

**Comment by muendlein** [comment]
> What versions of Windows and nodejs do you use? In this case we can copy instead of symlinking.

Windows: Windows 10 - 19045.2604
Nodejs Version: v18.12.1

**Comment by mattpap** [comment]
> Windows 10

I think that Windows 10 requires special permissions to create symlinks. In any case, we can "hard" link when symlinking isn't possible.
