### PR TITLE
Don't allow `.` in `UIElement`'s CSS classes

### LINKED ISSUE #12797: There are dots in HTML class names
### Software versions

Bokeh version: 3.1.0.dev2
Panel: main branch

### Browser name and version

edge

### Jupyter notebook / Jupyter Lab version

_No response_

### Expected behavior

HTML class names should not have dots `.` in their names.

### Observed behavior

HTML class names have dots in their names

### Example code

```Python
import panel as pn

pn.extension()

pn.pane.Markdown("Header").servable()
```

### Stack traceback or browser console output

@philippjfr asked me to create this issue as a reminder for @mattpap .

### Screenshots

image

### PR DESCRIPTION
**Pull request by mattpap**
fixes #12797

### CODE REVIEW

File: bokehjs/src/lib/models/ui/ui_element.ts [hunk 1]
```diff
@@ -91,7 +91,7 @@ export abstract class UIElementView extends DOMComponentView {
   }
 
   public *_classes(): Iterable<string> {
-    yield `bk-${this.model.type}`
+    yield `bk-${this.model.type.replace(/\./g, "__")}`
```
Comment (bryevdv) [inline bokehjs/src/lib/models/ui/ui_element.ts]: Why not just `-`

Comment (philippjfr) [reply bokehjs/src/lib/models/ui/ui_element.ts]: +1, I don't think there's much risk of collision.

Comment (MarcSkovMadsen) [reply bokehjs/src/lib/models/ui/ui_element.ts]: +1 here on using "-".

**Review by bryevdv — APPROVED** [review]
