### PR TITLE
Fix _hit_point in VAreaStep (#13293)

### LINKED ISSUE #13293: [BUG] _hit_point() is broken in VAreaStep
### Software versions

Python version      :  3.10.7 (main, Jan  1 1970, 00:00:01) [GCC 11.3.0]
IPython version     :  8.5.0
Tornado version     :  6.3.2
Bokeh version       :  3.3.0.dev1+21.gd5ce3ec0
BokehJS static path :  /home/user/.local/lib/python3.10/site-packages/bokeh/server/static
node.js version     :  (not installed)
npm version         :  (not installed)
Operating system    :  Linux-6.3.13-x86_64-with-glibc2.35

### Browser name and version

Firefox 115.0.2 (64-bit)

### Jupyter notebook / Jupyter Lab version

_No response_

### Expected behavior

Using HoverTool with VAreaStep should show tooltips for the right glyph.

### Observed behavior

Tooltips mix up the values between glyphs for step modes "before" (the default), showing information for the previous glyph, and "center", where the first half of the glyph shows information for the previous glyph.

### Example code

```Python
from bokeh.plotting import figure, output_file, save
from bokeh.models import HoverTool
from bokeh.io import output

p = figure(width=400, height=400)
glyphs = p.varea_step(
    x=[1, 2, 3, 4, 5],
    y1=[12, 16, 14, 13, 15],
    y2=[1, 4, 2, 1, 3],
    step_mode='before')
p.add_tools(HoverTool(tooltips=[("", "@x: @y1, @y2")]))
output_file("varea_step_test_before.html")
save(p)

p = figure(width=400, height=400)
glyphs = p.varea_step(
    x=[1, 2, 3, 4, 5],
    y1=[12, 16, 14, 13, 15],
    y2=[1, 4, 2, 1, 3],
    step_mode='center')
p.add_tools(HoverTool(tooltips=[("", "@x: @y1, @y2")]))
output_file("varea_step_test_center.html")
save(p)
```

### Stack traceback or browser console output

_No response_

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by solstag**
This fixes issue #13293 by providing a correct and simpler definition of glyph boundaries.

### CODE REVIEW

File: bokehjs/src/lib/models/glyphs/varea_step.ts [hunk 1]
```diff
@@ -92,28 +92,28 @@ export class VAreaStepView extends AreaView {
...
+        px = [sx[i], sx[i+1], sx[i+1], sx[i]]
+      else if (step_mode == "center") {
+        const mid_prev_x = (sx[i-1] + sx[i]) / 2
+        const mid_next_x = (sx[i] + sx[i + 1]) / 2
+        if (i == 0) {
+          px = [sx[i], mid_next_x, mid_next_x, sx[i]]
+        } else if (i == this.data_size - 1) {
+          px = [mid_prev_x, sx[i], sx[i], mid_prev_x]
+        } else {
+          px = [mid_prev_x, mid_next_x, mid_next_x, mid_prev_x]
```
Comment (bryevdv) [inline bokehjs/src/lib/models/glyphs/varea_step.ts]: `step_mode` is an enumeration, so we should really prefer a `switch` statement over and `if-elseif` chain, so that the compiler can validate that all cases are always covered. @solstag As long as this code is getting updated, it would be good to clean it up more thoroughly. Are you available to work on it a little more? 

As I see it the main complexity is that all three cases have different loop bounds, but we are trying to cram everyhing in one loop. So the best solution would seem to be to not do that, and use helper functions in each case, instead:
```typescript
    switch (this.model.step_mode) {
      case "before":
        [px, py, i] = this._hit_point_before()
      case "after":
        [px, py, i] = this._hit_point_after()
      case "center":
        [px, py, i] = this._hit_point_center()
```
Each helper function can have an appropriate loop inside, with the correct start/end for that case (so that no ugly checks like ` && i != this.data_size - 1` are needed). As a bonus there can just be an immediate return inside the loop when a match is found , so no mutable `let` variables or `break` would be needed either.

Comment (bryevdv) [reply bokehjs/src/lib/models/glyphs/varea_step.ts]: Actually maybe even better to define a `self._line_selection_for(i)` helper to create a `Selection` for a given indes, then just have the mode hit helpers return a selection directly. Something like:
```typescript
protected _hit_point_before(geometry: PointGeometry): Selection {
  for (let i = 1; i < this.data_size; i++) {
    const px = [sx[i-1], sx[i], sx[i], sx[i-1]]
    const py = [sy1[i], sy1[i], sy2[i], sy2[i]] 

    if (hittest.point_in_poly(geometry.sx, geometry.sy, px, py)) {
      return self._line_selection_for(i)

    return new Selection()
```

Then the switch can just become:

```typescript
    switch (this.model.step_mode) {
      case "before":
        return this._hit_point_before(geometry)
      case "after":
        return this._hit_point_after(geometry)
      case "center":
        return this._hit_point_center(geometr)
```
Let me know what you think.

**Comment by bryevdv** [comment]
@solstag do you expect to be able to continue working on this PR? We are planning to have a release in the next few weeks

**Comment by solstag** [comment]
Ni! Hi @bryevdv, I can take a look this week. Sorry for not responding to your previous messages, I left for travels and since my return I haven't touched the bokeh side of my projects.

**Comment by bryevdv** [comment]
Hi @solstag apologies, but I don't get notifs just for every commit. It looks like you added some commits two months ago that I never saw until now. Is this PR ready for a new round of review now?

**Comment by solstag** [comment]
Ni! Hi @bryevdv.
No problem, though I supposed that by mentioning you in the commit's description you'd get notified.
Yes, the updated patch incorporates all your suggestions now, and can be reviewed.
Cheers

**Comment by bryevdv** [comment]
👍 I should be able to take a close look over the next couple of days.

File: bokehjs/src/lib/models/glyphs/varea_step.ts [hunk 2]
```diff
@@ -90,43 +90,71 @@ export class VAreaStepView extends AreaView {
...
-          const mid_x = (sx[i] + sx[i+1]) / 2
-          px = [sx[i], mid_x, mid_x, sx[i+1], sx[i+1], mid_x, mid_x, sx[i]]
-          py = [sy1[i], sy1[i], sy1[i+1], sy1[i+1], sy2[i+1], sy2[i+1], sy2[i], sy2[i]]
-          break
-        }
+  protected _hit_point_center(geometry: PointGeometry): Selection {
+    const {sx, sy1, sy2} = this
+    for (let i = 0; i < this.data_size; i++) {
+      let px: number[]
+      const mid_prev_x = (sx[i-1] + sx[i]) / 2
```
Comment (bryevdv) [inline bokehjs/src/lib/models/glyphs/varea_step.ts]: @solstag this seems to be computing `sx[i-1]` even when `i==0` and `sx[i]` even when `i==this.data_size`? I think this will have to be handled a bit more carefully and realistically will entail some slight duplication between the conditional branches.

**Comment by bryevdv** [comment]
@solstag I just had one small comment about the implementation. The other comment would be that ideally this PR would come with some tests. I do think we have the machinery now to support pure BokehJS tests, but if you don't have the bandwidth to pursue that at this time then I would still support merging it as it is small, self-contained, and an evident improvement. 

@mattpap do you have any pointers to similar tests that could be quickly adapted for this case?

File: bokehjs/src/lib/models/glyphs/varea_step.ts (hunk 2 above)
Comment (solstag) [reply bokehjs/src/lib/models/glyphs/varea_step.ts]: It is, but that's the intended semantics: `mid_prev_x` for `i == 0` is undefined, and not used in that case. The same is true for `mid_next_x` on line 130 when `i == this.data_size - 1`.

**Comment by solstag** [comment]
@bryevdv @mattpap I haven't written any tests for bokeh and tbh I don't have a lot of experience writing tests. But yes, if you can provide some pointers and a good example I can make bandwidth for that.

File: bokehjs/src/lib/models/glyphs/varea_step.ts (hunk 2 above)
Comment (bryevdv) [reply bokehjs/src/lib/models/glyphs/varea_step.ts]: I do understand that it's harmless in the sense that subsequent code manually coordinates to not-use the undefined values at just the right times. My concern was that it seems potentially fragile from a maintenance POV. Someone in the future might rearrange or refactor the code and then the undefined cases end up accidentally being used when they should not. But two lines of duplication would also be a slight maintenance wart as well, so I suppose it is a toss-up.

Comment (solstag) [reply bokehjs/src/lib/models/glyphs/varea_step.ts]: Yeah, that was my take as well. And I don't think there's a real risk of messing up since those undefined values actually correspond to the semantics implied by the variable name (there is no previous for the first and no next for the last). But I guess a comment on the side saying `// undefined for {first,last}` won't hurt. I can add that when I deal with the tests.

**Comment by solstag** [comment]
Thanks!

**Review by bryevdv — APPROVED** [review]
