### PR TITLE
Don't escape raw strings in replace_placeholders() by default

### LINKED ISSUE #10604: quote (') from networkx index node are translated to (&#x27;)
### FOLLOW THESE INSTRUCTIONS CAREFULLY

*ISSUES THAT DO NOT CONTAIN NECESSARY INFORMATION MAY BE CLOSED, IMMEDIATELY*

The issue tracker is NOT the place for general support. For questions and technical assistance, come join the [Bokeh  Project Discourse](https://discourse.bokeh.org).

For defects or deficiencies, please provide *ALL OF THE FOLLOWING*:

#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
last version Bokeh 2.2.2 
python 3.8
networkx 2.5
holoview 1.13.3
OS 10.13.6
safari firefox

old version:
previous version Bokeh 2.0(?)  January 2020 example displayed
networkx 2.4
python 3.5

#### Description of expected behavior and the observed behavior
All quote(') are now translated as (&#x27;) in the node index. This did not happen in any other mix of older versions. I am not manipulating the index. I will make a minimum code later when possible.
#### Complete, minimal, self-contained example code that reproduces the issue

```
node_hover_tool = HoverTool(tooltips=[("Node", "@index")])
plot.add_tools(node_hover_tool)

```
#### Screenshots or screencasts of the bug in action
Screen Shot 2020-10-26 at 11 32 58 AM
Screen Shot 2020-10-26 at 11 33 14 AM

### PR DESCRIPTION
**Pull request by mattpap**
fixes #10604

### CODE REVIEW

File: bokehjs/test/unit/core/util/templating.ts [hunk 1]
```diff
@@ -173,7 +173,7 @@ describe("templating module", () => {
       expect(s3).to.be.equal("stuff a")
 
       const s4 = tmpl.replace_placeholders("stuff @bar", source, 1)
-      expect(s4).to.be.equal("stuff &lt;div&gt;b&lt;/div&gt;")
+      expect(s4).to.be.equal("stuff <div>b</div>")
```
Comment (bryevdv) [inline bokehjs/test/unit/core/util/templating.ts:176]: Can we add another row in the CDS with an apostrophe/single quote to make sure the exact case in the issue is exercised?

Comment (mattpap) [reply bokehjs/test/unit/core/util/templating.ts:180]: Added.

**Review by bryevdv — APPROVED** [review]

**Comment by bryevdv** [comment]
LGTM is having some problem fetching the commits, I am just going to go ahead and merge.
