### PR TITLE
Fix index rounding to display proper tooltips in CategoricalSlider

### LINKED ISSUE #14645: `CategoricalSlider` shows 'undefined' for some categories when a certain number of categories is given
### Software versions

Python version        :  3.13.5 (main, Jul 11 2025, 22:43:46) [Clang 20.1.4 ]
IPython version       :  (not installed)
Tornado version       :  6.5.2
NumPy version         :  2.3.2
Bokeh version         :  3.8.0
BokehJS static path   :  /home/username/project/.venv/lib/python3.13/site-packages/bokeh/server/static
node.js version       :  (not installed)
npm version           :  (not installed)
jupyter_bokeh version :  (not installed)
Operating system      :  Linux-6.6.87.1-microsoft-standard-WSL2-x86_64-with-glibc2.35

### Browser name and version

_No response_

### Jupyter notebook / Jupyter Lab version

_No response_

### Expected behavior

`CategoricalSlider` can be set to all the categories provided.

### Observed behavior

`CategoricalSlider`'s value turns into 'undefined' when sliding from left to right for certain categories and skips them altogether when sliding from right to left.

This was previously observed in #13965 but still seems to show up when there are exactly 10 categories. The 4th and 7th categories cannot be set on the slider going from left to right and will show 'undefined' when hovered. When sliding from right to left, the values are simply skipped.

### Example code

```Python
import bokeh.layouts as bl
import bokeh.models as bm
import bokeh.plotting as bp

categories = list(map(str, range(1, 11)))
slider = bm.CategoricalSlider(
    value=categories[0],
    categories=categories,
)

bp.show(bl.row(slider, styles={"margin": "10px"}))
```

### Stack traceback or browser console output

_No response_

### Screenshots

Here is a GIF of the observed behaviour:
Image

### PR DESCRIPTION
**Pull request by mosc9575**
- [x] issues: fixes #14645
- [x] tests adapted/ passed

https://github.com/user-attachments/assets/833b6d6d-69c2-44d1-8526-a1f1a5802099

Code of the example to reproduce.

```python
from bokeh.plotting import show, output_notebook
from bokeh.models import CategoricalSlider
output_notebook()


categories = list(map(str, range(1, 11)))
slider = CategoricalSlider(value="1", categories=categories)

show(slider)
```

### CODE REVIEW

File: bokehjs/src/lib/models/widgets/sliders/categorical_slider.ts [hunk 1]
```diff
@@ -25,19 +25,20 @@ export class CategoricalSliderView extends AbstractSliderView<string> {
...
-        to: (value: number) => categories[value],
+        to: (value: number) => categories[Math.round(value)], // value may not be an integer due to noUiSlider's FP math
         from: (value: string) => categories.indexOf(value),
       },
     }
   }
 
   protected _calc_from([value]: number[]): string {
     const {categories} = this.model
-    return categories[value | 0] // value may not be an integer due to noUiSlider's FP math
```
Comment (mosc9575) [inline bokehjs/src/lib/models/widgets/sliders/categorical_slider.ts:36]: The former implementation used floor for rounding. This caused some undocumented but still unwanted behavior. For example if the current value is `5` and I use a `left-arrow` action and the next given value from the slider is `3.999999999`, the the `calc_from` function returned `categories[3]` and one value is skipped. The skipped values are the same, which have the tooltip "undefined" when using the mouse to move the slider.

Using `Math.Round(value)` solves both issues.

**Review by bryevdv — APPROVED** [review]

**Review by mattpap — APPROVED** [review]
