### PR TITLE
Fix for log scale plotting bug

### LINKED ISSUE #3834: plot is empty when log scale is used
Bokeh incorrectly creates an empty plot with the following:

``` python
from bokeh.plotting import figure, output_file, show
ys = [4.471799184102565e-05, 0.0009856299875536934, 0.0011045119899790734]
xs = range(len(ys))
output_file("log.html")
p = figure(y_axis_type="log")
p.line(xs, ys)
show(p)
```

The problem only occurs if `y_axis_type="log"` is used.

It seems when the range of y values is too narrow bokeh fails to compute the y-axis range.  If I multiple the y values by 100, it plots properly.

Tested on bokeh version:  0.11.1 py34_0

### PR DESCRIPTION
**Pull request by clairetang6**
This PR is for fixing a bug in log plotting, where plots are empty or where axes use incorrect initial ranges under some circumstances (related to the minimum and maximum value of the data and the `range_padding`). This bug is caused when a DataRange1d determines that its `start` should be a negative value. This can happen even when all the data are positive values (necessary to be shown on a log plot since log(x) is only defined for x>0) because the `range_padding` calculation is done linearly. 

There are three main ways of approaching a fix. 
1. Have the DataRange1d (or something above it) check whether it's being used linearly or log-ly. 
2. Have the DataRange1d know whether it's linear or log. 
3. Delegate the range bounds calculation to the tickers. 

This PR implements approach 2. by adding a new property `mapper_type` to the DataRange1d. Then the range calculation can be done correctly whether linear or log by the DataRange1d. 

Cons for approach 1.
-It would be a little convoluted to figure out whether the DataRange1d is linear or log. The  DataRange1d doesn't know whether it is an x_range or y_range. The plot_canvas that updates the  DataRange1d knows which dimension the DataRange1d is, but then would need to find the matching Axis from its Plot's `renderers` to inspect that Axis's ticker. 

Cons for approach 3. 
-Ranges are currently in charge of figuring out data-derived bounds which are compared to user-supplied bounds to determine the bounds. If the ranges no longer take into account the padding into their data-derived bounds, then the comparison between data and user bounds will need to use logic moved into the ticker. 
-Range `start` and `end` values are set by pan/zoom tools. If the ticker defaults to adding padding, the ticker will need to know not to add padding when panning/zooming. 

Some other things to consider:
-When a user creates a DataRange1d to use in a log plot instead of using the default, they will need (not absolutely, but they will probably want) to supply `mapper_type="log"` if they don't supply a `start` and `end` and want the correct range padding. If they do supply a `start` and `end` (and they are both positive values), but don't supply a `mapper_type="log"`, then the plot will still be correct. This is because the ticker and mapper are still log and will produce the correct ticks and screen-mapped values. 

- [x] issues: fixes #3834 #5389 #2789
~~- [ ] support different exponential bases~~ (Log bases are all scaled the same, so my original thinking about supporting different bases is not needed. `default_span` could be made to span in terms of powers of `base` instead of only powers of 10, but that would minimally affect ux)
- [x] tests added / passed
~~- [ ] release document entry (if new feature or API change)~~

### CODE REVIEW

**Comment by bryevdv** [comment]
I might propose a slightly different approach. I am definitely not 100% keen on having `Ranges` know about mappers. But if we must, think it would be done more simply with just:
```
mapper = Instance(Mapper)
```
on the range. Since the can be `None` (and defaults to `None`) this property could be considered an optional hint to the range about the mapper type that will be using it. And by setting the actual mapper itself, we avoid an additional enum and all the indirect logic needed to process the enum (we can just inspect the optional mapper directly). 

Possibly taking this further (maybe later) the mapper could expose things like min bounds that that could be taken into account (i.e. a min bound of `"auto"` would mean, see if I have a hinted mapper, and ask it what if any min bound it requires).

**Comment by clairetang6** [comment]
Thinking about this more, the only reason the data_range1ds need to know about the "mapper_type" is to calculate the range-padded bounds, so that the range start/end are nice by default when the user doesn't supply a start/end. So, the "mapper_type" is less about any kind of mapping per se, but is more about how to think about padding the data values. There could a scenario where a user wants the mapping to be linear while the range padding is log or vice versa. Although those scenarios are unlikely, they at least illustrate that the two concepts are independent. So, it may be more correct for the range to have its own independent "mapper_type" (could be called something else). 

That said, the much more common scenario (probably close to 100% of the time) of having the range and mapper match could still be covered by either your proposed `mapper = Instance(Mapper)` or another solution described below. The problem with `mapper = Instance(Mapper)` is that it doesn't look like the LinearMapper and LogMapper are defined on the Python side.

So instead, I tried removing the property `mapper_type` (that I added to data range) and instead adding a private variable `_mapper_type`.  The `_mapper_type` is set to "auto" when a data_range1d is initialized and then is changed by the frame when the frame creates its mappers (and knows whether to create a Linear or Log mapper).

**Comment by bryevdv** [comment]
@clairetang6 Ah right, I'd forgotten. The current handling of mappers is an unfortunate holdover from very early days. We used to handle lots of things by sending string enums and assembling things on the BokehJS side. It became universally clear that assembling things on the python side was better for a variety of reasons, so we stopped doing that pretty much everywhere when our properties system became capable of handling `Instance` well. But mappers and frames are the holdouts that have not been refactored or fixed up yet. That's a larger task, so for this issue I think just forwarding the mapper type as a private var on the JS side is reasonable.

File: bokehjs/src/coffee/models/ranges/data_range1d.coffee [hunk 1]
```diff
@@ -125,9 +136,17 @@ export class DataRange1d extends DataRange
...
+          start = @_initial_start
+      else
+        start = @_initial_start
     if @_initial_end?
-      end = @_initial_end
+      if @_mapper_type == "log"
+        if @_initial_end > 0
+          end = @_initial_end
+      else
+        end = @_initial_end
```
Comment (bryevdv) [inline bokehjs/src/coffee/models/ranges/data_range1d.coffee]: The effect of these two blocks is to silently ignore any values less than zero in the presence of lag mappers, correct?  A log message is probably warranted

Comment (StevenCHowell) [inline bokehjs/src/coffee/models/ranges/data_range1d.coffee]: In my experience using matplotlib and matlab, plotting data on a log scale does silently ignore values less than zero.  This should be understood as part of the logarithm function.

Comment (bryevdv) [inline bokehjs/src/coffee/models/ranges/data_range1d.coffee]: Well MPL at least has `symlog` for which will linearize around zero and allow for negative values, but the regular `log` mode has both `clip` and `mask` options I thought, and in particular, that only applies to *values* AFAICT. You can still set range bounds < 0 if you like, and they are honored as best I can tell. If we are going to prevent *ranges* from extending to negative in the presence of a log mapper, that still seems worth a warning to me. Alternatively we can just let ranges extend below zero, but refuse to map negative values like MPL does.

Comment (bryevdv) [inline bokehjs/src/coffee/models/ranges/data_range1d.coffee]: You're right, it's ony `symlog` that does, I was mistaken. Sorry for the noise.

**Comment by bryevdv** [comment]
So after the above discussion I'm +0 on the warning, but am happy to merge the PR as-is. @clairetang6 the PR is still marked `WIP`, is there any other work or is this `ready`?

**Comment by clairetang6** [comment]
Hi @bryevdv, I'm planning to add some tests and maybe some text into documentation/docstrings that says that the range padding calculation will be linear or log based on whether the axis was linear or log. I'm traveling right now, so it still might be a few days before I can finish this up.

**Comment by bryevdv** [comment]
@clairetang6 great, thanks for the update!

**Comment by bryevdv** [comment]
I've moved all the related issues to the `0.12.4` milestone

**Comment by clairetang6** [comment]
Some screenshots and thoughts for reference for deciding on the data_range1d's `default_span` for log ranges. 

When only one point is plotted, the range determined by the data has a span set by the parameter `default_span`, which is set to 2 by default. When plotting is linear, this means that the `start` is the data value - 1 and the `end` is the data value + 1. 

Added in this PR, when plotting is log, this `default_span` of 2 means that the `start` is one order of magnitude (set to base 10, not determined by the base of the ticker/formatter) smaller than the data value and the `end` is one order of magnitude bigger. However, with larger values that are powers of 10 or close, you end up with rounding errors that make for slightly uglier defaults. 
image

Adding some small fraction, here 0.001, to the `default_span` fixes this. 
image

This is extremely minor as a detail, but is how I've made `default_span` work in the log case.

**Comment by bryevdv** [comment]
@clairetang6 thanks this looks great, will merge when green!
