### PR TITLE
Enforce consistent active state of gestures

### LINKED ISSUE #14218: [BUG] RangeTool start_gesture="pan" does not work with PanTool
### Software versions

Python version        :  3.13.1 (main, Dec 19 2024, 14:22:59) [Clang 18.1.8 ]
IPython version       :  8.31.0
Tornado version       :  6.4.2
NumPy version         :  2.2.1
Bokeh version         :  3.6.2
BokehJS static path   :  /Users/xzmeng/repos/bgrid/.venv/lib/python3.13/site-packages/bokeh/server/static
node.js version       :  v23.5.0
npm version           :  10.9.2
jupyter_bokeh version :  (not installed)
Operating system      :  macOS-15.1.1-arm64-arm-64bit-Mach-O

### Browser name and version

Chrome 131.0.6778.205

### Jupyter notebook / Jupyter Lab version

_No response_

### Expected behavior

1. Drag outside the overlay, PanTool works
2. Deactivate the PanTool, drag outside the overlay, start_gesture="pan" works

### Observed behavior

1. Drag outside the overlay, PanTool works
2. Deactivate the PanTool, drag outside the overlay, nothing happens
3. Deactivate the RangeTool, activate the RangeTool, start_gesture="pan" works

### Example code

```Python
from bokeh.layouts import column
from bokeh.models import RangeTool
from bokeh.plotting import figure, show

x = list(range(10))
y = list(range(10))

p = figure(x_range=(2, 4))
p.line(x, y)

select = figure()
select.line(x, y)

range_tool = RangeTool(x_range=p.x_range, start_gesture="pan")
select.add_tools(range_tool)

show(column(p, select))
```

### Stack traceback or browser console output

_No response_

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by muendlein**
- [x] issues: fixes #14218
- [x] tests added / passed

### CODE REVIEW

File: bokehjs/test/integration/regressions.ts [hunk 1]
```diff
@@ -4863,4 +4862,52 @@ describe("Bug", () => {
...
+
+      const tool1 = new BoxZoomTool()
+
+      p.add_tools(tool0, tool1)
+
+      p.toolbar.active_drag = tool0
+
+      const {view} = await display(p)
+      await view.ready
+      await paint()
```
Comment (mattpap) [inline bokehjs/test/integration/regressions.ts]: `await display()` already does this, so shouldn't be needed in this context, thus:
```suggestion
      await display(p)
```
should be sufficient. However, if this redundancy is really needed to improve robustness, then perhaps `view.ready` mechanism isn't robust by itself.

File: bokehjs/test/integration/regressions.ts [hunk 2]
```diff
@@ -4863,4 +4862,52 @@ describe("Bug", () => {
...
+      const tool0 = new RangeTool({
+        x_range: new Range1d({start: 1, end: 2}),
+        start_gesture: "pan",
+      })
+
+      const tool1 = new BoxZoomTool()
+
+      p.add_tools(tool0, tool1)
+
+      p.toolbar.active_drag = tool0
```
Comment (mattpap) [inline bokehjs/test/integration/regressions.ts]: Can we remove unnecessary empty lines, effectively creating logical blocks of code?
```suggestion
      const tool0 = new RangeTool({
        x_range: new Range1d({start: 1, end: 2}),
        start_gesture: "pan",
      })
      const tool1 = new BoxZoomTool()
      p.add_tools(tool0, tool1)
      p.toolbar.active_drag = tool0
```
Or perhaps even better in this context, add tools with `figure({..., tools: ["pan", range_tool, zoom_tool], ...})`.

File: src/bokeh/models/tools.py [hunk 3]
```diff
@@ -518,7 +518,7 @@ def __init__(self, *args: Any, **kwargs: Any) -> None:
     line_dash=[2, 2],
 )
 
-class RangeTool(Tool):
+class RangeTool(Drag):
```
Comment (mattpap) [inline src/bokeh/models/tools.py:521]: This may need to be propagated to `tools.pyi` and perhaps to bokehjs as well.

File: bokehjs/test/integration/regressions.ts (hunk 1 above)
Comment (muendlein) [reply bokehjs/test/integration/regressions.ts]: yeah removed that

File: bokehjs/test/integration/regressions.ts (hunk 2 above)
Comment (muendlein) [reply bokehjs/test/integration/regressions.ts]: yes

File: src/bokeh/models/tools.py (hunk 3 above)
Comment (muendlein) [reply src/bokeh/models/tools.py:521]: Stubs got updated on the Python side. As Drag does not exist within bokehjs a change should not be necessary there.

**Comment by muendlein** [comment]
I'm not sure why there is a mypy error, seems to be unrelated.

**Comment by mattpap** [comment]
> I'm not sure why there is a mypy error, seems to be unrelated.

There was mypy 1.20 release recently. It's fixed on `branch-3.10`.

**Review by mattpap — APPROVED** [review]
