### PR TITLE
Compile with whitespace in path

### LINKED ISSUE #14799: Compilation failing with whitespace in path
### Software versions

-

### Browser name and version

_No response_

### Jupyter notebook / Jupyter Lab version

_No response_

### Expected behavior

build should work

### Observed behavior

compilation error since the latest commits related to `tsc`

### Example code

```Python
pip install -e .
```

### Stack traceback or browser console output

_No response_

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by muendlein**
- [x] issues: fixes #14799
- [x] tests added / passed

### CODE REVIEW

File: bokehjs/make/tasks/compiler.ts [hunk 1]
```diff
@@ -9,7 +9,7 @@ import {src_dir, build_dir} from "../paths.js"
 task("compiler:ts", async () => {
   const is_windows = process.platform == "win32"
   const npx = is_windows ? "npx.cmd" : "npx"
-  const {status} = cp.spawnSync(npx, ["tsc", "--project", join(src_dir.compiler, "tsconfig.json")], {stdio: "inherit", shell: is_windows})
+  const {status} = cp.spawnSync(npx, ["tsc", "--project", `"${join(src_dir.compiler, "tsconfig.json")}"`], {stdio: "inherit", shell: true})
```
Comment (mattpap) [inline bokehjs/make/tasks/compiler.ts]: Is this a Windows specific problem? On Linux this works fine with spaces in paths, e.g.:
```
$ node make compiler:build
[22:33:25] Using nodejs v24.9.0 and npm 11.7.0
[22:33:25] Starting 'compiler:ts'...
/home/mateusz/repo/bokeh with spaces/bokehjs/src/compiler/tsconfig.json
[22:33:26] Finished 'compiler:ts' after 730 ms
[22:33:26] Starting 'compiler:build'...
[22:33:26] Finished 'compiler:build' after 593 ms
[22:33:26] Finished 'top-level'
```
I would prefer a solution that uses shell only when really necessary.

Comment (mattpap) [reply bokehjs/make/tasks/compiler.ts]: Also, this isn't the only place in the build system where this exact or equivalent code is run. Though in other places we use relative paths. So maybe that's the solution at least for now. In general we may need a helper function, because paths with spaces may appear in any invocation of `spawn` (etc.).

Comment (muendlein) [reply bokehjs/make/tasks/compiler.ts]: @mattpap Yes, it's a Windows specific problem. Using the shell seems to be necessary to get it working both on Linux (does not build without shell) & Windows. As you have mentioned this is an issue also in other places, one got fixed in the past already (https://github.com/bokeh/bokeh/pull/14575).

Comment (muendlein) [reply bokehjs/make/tasks/compiler.ts]: It seems like that my previous fix got adjusted in the meanwhile (#14680) to account for https://nodejs.org/api/deprecations.html#DEP0190
I have now applied the same here which means avoiding a windows specific treatment. However it seems like `shell: true` is required to get this running.

Comment (bryevdv) [reply bokehjs/make/tasks/compiler.ts]: considering this is just in a developer-facing tool that IIUC we might be looking to replace in the future anyway, perhaps we can let the `shell: true` slide in this case?

Comment (mattpap) [reply bokehjs/make/tasks/compiler.ts]: So apparently we already gave up on not using shell in such contexts, e.g. when compiling nearly grammars. I suppose we can proceed with this.

**Review by mattpap — APPROVED** [review]
