### PR TITLE
Correctly render brushed steps

### LINKED ISSUE #12430: [BUG] Step glyphs do not support linked brushing
### Software versions

Python version      :  3.9.13 | packaged by conda-forge | (main, May 27 2022, 16:56:21) 
IPython version     :  8.5.0
Tornado version     :  6.2
Bokeh version       :  3.0.0.dev18+15.gc0b9834e
BokehJS static path :  /home/iant/github/bokeh/src/bokeh/server/static
node.js version     :  v16.15.0
npm version         :  8.19.2
Operating system    :  Linux-5.11.0-37-generic-x86_64-with-glibc2.31

### Browser name and version

Not browser-specific

### Jupyter notebook / Jupyter Lab version

_No response_

### Expected behavior

Linked brushing (selection of indices to render) does not work at all for canvas or WebGL output backends. It is implemented incorrectly for canvas, and not at all for WebGL.

### Observed behavior

See screenshot below.

### Example code

```Python
from bokeh.models import ColumnDataSource
from bokeh.plotting import figure, row, show
import numpy as np

x = np.arange(-3, 4)
y = x**2
source = ColumnDataSource(data=dict(x=x, y=y))

ps = []
for backend in ["canvas", "webgl"]:
    p = figure(tools="box_select,reset", width=300, height=250, title=backend, output_backend=backend)
    p.step('x', 'y', source=source, mode="center", line_width=8, alpha=0.8)
    p.circle('x', 'y', source=source, fill_color="orange", line_color="black", size=10)
    ps.append(p)

show(row(ps))
```

### Stack traceback or browser console output

_No response_

### Screenshots

Screenshot 2022-09-27 at 09-45-04 Bokeh Plot

### PR DESCRIPTION
**Pull request by muendlein**
- [x] issues: fixes #12430
- [x] tests added / passed

### CODE REVIEW

**Comment by muendlein** [comment]
From the integration test:

Bug__in_issue_#12430__doesn't_correctly_show_selected_indices_of_Step_glyph

The failed test is caused by a 5px delta difference -> is it sufficient to update the baseline for this test?

**Comment by mattpap** [comment]
> The failed test is caused by a 5px delta difference -> is it sufficient to update the baseline for this test?

In this case it's sufficient.

File: bokehjs/src/lib/models/glyphs/step.ts [hunk 1]
```diff
@@ -43,7 +61,7 @@ export class StepView extends XYGlyphView {
     }
 
     for (const i of indices) {
-      const next_finite = isFinite(sx[i+1] + sy[i+1])
+      const next_finite = isFinite(sx[i+1] + sy[i+1]) && indices.includes(i+1)
```
Comment (ianthomas23) [inline bokehjs/src/lib/models/glyphs/step.ts]: The `indices.includes` call will walk the whole array which is potentially slow as `i+1` if present will always be the next value. So I think it would be better to change the loop to be over index not value of `indices` so that the look ahead can be constant-time.

**Review by ianthomas23 — CHANGES_REQUESTED** [review]
Thanks @muendlein this looks really good.

There is an argument that the non-selected line segments should be rendered right up to the selected ones, but I don't have a strong opinion on this so I would rather accept this as it is and we can modify it later if anyone does have a strong opinion.

I have just one comment about a performance improvement.

File: bokehjs/src/lib/models/glyphs/step.ts (hunk 1 above)
Comment (muendlein) [reply bokehjs/src/lib/models/glyphs/step.ts]: @ianthomas23 Agreed. I just added a fix for that.

**Review by ianthomas23 — APPROVED** [review]
Thanks @muendlein. CI failures are unrelated.

**Comment by muendlein** [comment]
> Thanks @muendlein this looks really good.
> 
> There is an argument that the non-selected line segments should be rendered right up to the selected ones, but I don't have a strong opinion on this so I would rather accept this as it is and we can modify it later if anyone does have a strong opinion.
> 
> I have just one comment about a performance improvement.

Yeah that is probably more visually pleasing. I guess this can be adressed once selection on line glyphs are supported in general (https://github.com/bokeh/bokeh/issues/10056) as a consistent behavior is obviously desired.

**Comment by ianthomas23** [comment]
Feel free to self-merge now that this has been approved.
