### PR TITLE
more robust checking for BokehJS load, enable re-rerun of output_note…

### LINKED ISSUE #3639: Bokeh occasionally not working with Jupyter Notebook
I'm not sure what's going on. I get this error occasionally and I may have gotten a reproducible example but I haven't confirmed just yet.

There are no errors in the python side. Instead of a plot I see ```<bokeh.io._CommsHandle at 0x109b1ec18>``` as the output. The javascript console shows:

```
Kernel: kernel_restarting (b738e19a-021b-47ef-9d08-076f696147c8)
main.min.js:22329 Kernel: kernel_created (b738e19a-021b-47ef-9d08-076f696147c8)
main.min.js:22673 Starting WebSockets: ws://localhost:8888/api/kernels/b738e19a-021b-47ef-9d08-076f696147c8
main.min.js:22329 Kernel: kernel_connected (b738e19a-021b-47ef-9d08-076f696147c8)
main.min.js:22329 Kernel: kernel_ready (b738e19a-021b-47ef-9d08-076f696147c8)
(program):67 Bokeh: BokehJS loaded, going straight to plotting
cdn.pydata.org/bokeh/release/bokeh-0.11.0.min.js:3 Bokeh: setting log level to: 'info'
(program):53 Bokeh: injecting CSS: https://cdn.pydata.org/bokeh/release/bokeh-0.11.0.min.css
(program):55 Bokeh: injecting CSS: https://cdn.pydata.org/bokeh/release/bokeh-widgets-0.11.0.min.css
(program):72 Bokeh: BokehJS loaded, going straight to plotting

Could not open comm  --  Error: Class 1854dd25-3916-46bd-aab3-1729f21a403a not found in registry
main.min.js:23119 Couldn't process kernel message WrappedError(anonymous function) @ main.min.js:23119

Couldn't process kernel message WrappedError(anonymous function) @ main.min.js:23119
```

### PR DESCRIPTION
**Pull request by bryevdv**
- [x] issues: fixes #3639
- [x] tests added / passed

This PR should prevent the notebook from becoming unusable without a complete re-start in the event that `show` is called when BokehJS is not truly loaded. It also allows for re-trying `output_notebook`

screen shot 2016-07-10 at 2 08 36 pm

### CODE REVIEW

**Comment by bryevdv** [comment]
I tested with WiFi off, and then re-ran `output_notebook` with WiFi re-enabled, and things were working.

**Comment by bryevdv** [comment]
ping @mattpap 

ping @damianavila I kept the cheesy kernel execution. I know it is not ideal, but this is far more robust that what we had before.

File: bokeh/core/_templates/autoload_js.js [hunk 1]
```diff
@@ -23,15 +23,17 @@ calls it with the rendered model.
...
 #}
 (function(global) {
   function now() {
     return new Date();
   }
 
-  if (typeof (window._bokeh_onload_callbacks) === "undefined") {
+  var force = "{{ force }}";
+
+  if (typeof (window._bokeh_onload_callbacks) === "undefined" || force !== "") {
```
Comment (bryevdv) [inline bokeh/core/_templates/autoload_js.js]: This empty string business seems pretty lame, but AFAIK there's no way to have a "default" value for a template param?

**Comment by bryevdv** [comment]
Of course, loading a saved notebook has this problem:

screen shot 2016-07-10 at 11 23 20 pm

I guess the only thing to do is fail quietly with a console message, assuming that its a saved notebook.

File: bokeh/util/notebook.py [hunk 2]
```diff
@@ -30,6 +30,12 @@ def load_notebook(resources=None, verbose=False, hide_banner=False):
     publish_display_data({'text/html': html})
     publish_display_data({'application/javascript': js})
 
+FINALIZE_JS = """
+Bokeh.$("#%s").text("BokehJS successfully loaded");
+var kernel = IPython.notebook.kernel
```
Comment (damianavila) [inline bokeh/util/notebook.py]: Use `Jupyter` insteadof `IPython`...

**Comment by damianavila** [comment]
>ping @damianavila I kept the cheesy kernel execution. I know it is not ideal, but this is a far more robust user experience than what we had before.

Yes, I agree it is a better experience for the user.

**Comment by bryevdv** [comment]
OK, I updated to check that `Jupyter.notebook.kernel.execute` is undefined. I didn't log anything on the assumption that this is normal in the static rendered notebook case. 

@bokeh/dev I think this is ready

**Comment by bryevdv** [comment]
Thoughts on adding: 
```
* re-run the `show()` cell (BokehJS may have finished loading by now)
```
to the list of possible remedies?

**Comment by damianavila** [comment]
> to the list of possible remedies? Maybe that's bordering on "too much" information

I prefer to give more info... it is just a line and can be a quicker solution before reloading the `output_notebook` which is more "drastic" measure...

**Comment by bryevdv** [comment]
I think I'm actually on the other side, after some thought. This is already a huge warning cell (by design, but still) and too much information can definitely be a problem.

**Comment by bryevdv** [comment]
Also I'd like to get a dev build out ASAP and ask for help testing it on the mailing list. Will merge after #4794 is merged, then cut dev build
