### PR TITLE
Fix bokehjs' legacy bundles

### LINKED ISSUE #10233: [BUG] bokeh js v2.x legacy libraries
Hello,

I posted a [more detailed version of this question](https://discourse.bokeh.org/t/bokeh-2-x-legacy-js/5862) on the Bokeh Discourse and it was suggested that I open an issue here.

*Main Issue*
Using Bokeh version 2.02 or version 2.1.1 I am unable to load the Bokeh legacy libraries. I tried
`>bokeh.resources.Resources(mode="cdn",legacy=True).render()`
which gives a list of libraries including links of the form
https://cdn.bokeh.org/bokeh/release/bokeh-2.1.1.legacy.min.js
These links do not appear to be valid (getting 403 error on access) for these two versions but they are accessible for v2.0.0.

*Additional Question*
I also asked an additional question about where to find documentation on the differences between the main versions of a Bokeh JS library and its corresponding legacy version (e.g. between `bokeh-2.1.1.legacy.min.js` and `bokeh-2.1.1.min.js`). How can one determine what functionality is lost using the legacy versions? Any help would be greatly appreciated.

Thanks very much: I really appreciate the continued support for the legacy versions - we have an audience that is restricted to IE11 and it's great to still have an option.

Andrew

### PR DESCRIPTION
**Pull request by mattpap**
addresses #10233

### CODE REVIEW

**Comment by mattpap** [comment]
At this point I restored support at least for basic plotting (testing on `color_scatter`). The next major issue to fix, is to get something done about ND arrays, which due to limitations of TypeScript compiler's code emitter, don't work after transpilation to ES5, e.g.:
```
✗ core/has_props module
 └┬─ materialize_dataspecs
  └── should collect shapes when they are present
TypeError: Constructor Float64Array requires 'new'
    at Float64NDArray.Float64Array (<anonymous>)
    at new Float64NDArray (http://localhost:5778/static/js/@@/build/js/lib/core/util/ndarray.js:130:1)
    at Object.ndarray (http://localhost:5778/static/js/@@/build/js/lib/core/util/ndarray.js:183:1)
    at http://localhost:5778/static/test/@@/build/test/unit/core/has_props.js:108:1
    at _run_test (http://localhost:5778/static/test/@@/build/test/framework.js:166:1)
    at Object.run (http://localhost:5778/static/test/@@/build/test/framework.js:130:1)
    at <anonymous>:1:7
```

File: bokehjs/src/lib/polyfill.ts [hunk 1]
```diff
@@ -23,6 +28,43 @@ if (typeof Object.values === "undefined") {
...
 
+if (typeof Uint8Array.prototype.fill === "undefined") {
+  (Uint8Array.prototype as any).fill = Array.prototype.fill;
+  (Int8Array.prototype as any).fill = Array.prototype.fill;
+  (Uint16Array.prototype as any).fill = Array.prototype.fill;
+  (Int16Array.prototype as any).fill = Array.prototype.fill;
+  (Uint32Array.prototype as any).fill = Array.prototype.fill;
+  (Int32Array.prototype as any).fill = Array.prototype.fill;
+  (Float32Array.prototype as any).fill = Array.prototype.fill;
+  (Float64Array.prototype as any).fill = Array.prototype.fill
```
Comment (bryevdv) [inline bokehjs/src/lib/polyfill.ts:39]: @mattpap missing semicolon here and below?

Comment (mattpap) [reply bokehjs/src/lib/polyfill.ts:39]: No. This is the minimal number of semicolons needed here, otherwise this code would be interpreted as:
```ts
(Uint8Array.prototype as any).fill = Array.prototype.fill(Int8Array.prototype as any).fill = Array.prototype.fill ...
```
Linter would complain if the last semicolon was added.
