### PR TITLE
fix path dependency when enforcing aspect ratio of tiles

### LINKED ISSUE #14207: [BUG] Toggling widget visibility triggers zoom in for unrelated figure
### Software versions

Python version : 3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:50:30) [MSC v.1933 64 bit (AMD64)]
IPython version : 8.12.0
Tornado version : 6.2
NumPy version : 1.24.2
Bokeh version : 3.6.2
node.js version : (not installed)
npm version : (not installed)
jupyter_bokeh version : (not installed)
Operating system : Windows-10-10.0.19045-SP0

### Browser name and version

_No response_

### Jupyter notebook / Jupyter Lab version

_No response_

### Expected behavior

Layout changes shall not trigger any zoom.

### Observed behavior

When toggling the visibility of a widget an unrelated figure will zoom in at the same time. Note: So far only observed in case of geo tiles.

### Example code

```Python
from bokeh.io import curdoc
from bokeh.layouts import column, row, layout
from bokeh.models import ColumnDataSource, Select, Switch
from bokeh.plotting import figure

import xyzservices.providers as xyz

doc = curdoc()


geo_map = figure(x_range=(-2000000, 6000000), y_range=(-1000000, 7000000),
                 x_axis_type="mercator", y_axis_type="mercator", sizing_mode="stretch_height")
geo_map.add_tile(xyz.OpenStreetMap.Mapnik)

switch = Switch(active=False)
select_1 = Select(value="foo", options=["foo", "bar", "baz", "quux"], sizing_mode="fixed", visible=False)

s1 = figure(x_axis_type="datetime")
s1.line(x="t", y="y", source=ColumnDataSource())

# make a grid
grid = layout([[select_1, s1]],
              sizing_mode="stretch_both")

layout = row(
    column(geo_map,
           sizing_mode="stretch_height"),
    column(row(switch), grid, sizing_mode="stretch_both"),
    sizing_mode="stretch_both"
)


def toggle(attr, old, new):
    if new:
        select_1.visible = True
    else:
        select_1.visible = False


switch.on_change("active", toggle)

doc.add_root(layout)
```

### Stack traceback or browser console output

_No response_

### Screenshots

Image

### PR DESCRIPTION
**Pull request by muendlein**
- [x] issues: fixes #14207 
- [x] tests added / passed

### CODE REVIEW

**Comment by mattpap** [comment]
It would be good to add an integration regression test based off the MRE in the issue (just simplified). A good starting point would be: https://github.com/bokeh/bokeh/blob/fd4a034d910a3b6642be98897e85b13258eff7d2/bokehjs/test/integration/regressions.ts#L1311-L1339 because we do not refer to remote resources in bokehjs' tests, thus you can only use what bokehjs' testing framework provides (in this case a few sets of tiles).

**Comment by muendlein** [comment]
@mattpap Any idea why the integration test fails with "Failed to load resource: the server responded with a status of 404 (Not Found)"?

File: bokehjs/src/lib/models/tiles/tile_renderer.ts [hunk 1]
```diff
@@ -152,7 +152,10 @@ export class TileRendererView extends RendererView {
     if (this._last_width !== width || this._last_height !== height) {
       const extent = this.get_extent()
       const zoom_level = this.model.tile_source.get_level_by_extent(extent, height, width)
-      const new_extent = this.model.tile_source.snap_to_zoom_level(extent, height, width, zoom_level)
+      let new_extent = this.model.tile_source.snap_to_zoom_level(extent, height, width, zoom_level)
+      if (this._last_width !== undefined && this._last_height !== undefined) {
+        new_extent = this.model.tile_source.rescale(extent, height, width, this._last_height, this._last_width)
+      }
```
Comment (bryevdv) [inline bokehjs/src/lib/models/tiles/tile_renderer.ts]:
```suggestion
      const {tile_source} = this.model
      const new_extent = (() => {
        {_last_width, _last_height} = this
        if (_last_width !== undefined && _last_height !== undefined) {
          return tile_source.rescale(extent, height, width, _last_height, _last_width)
        }
        return tile_source.snap_to_zoom_level(extent, height, width, zoom_level)
      })()
```

**Comment by mattpap** [comment]
> Failed to load resource: the server responded with a status of 404 (Not Found)"?

This is because there's a very limited set of tiles and this likely goes out of that region.

File: bokehjs/test/integration/regressions.ts [hunk 2]
```diff
@@ -4345,4 +4345,39 @@ describe("Bug", () => {
       await view.ready
     })
   })
+
+  describe("in issue #14207", () => {
+    it("has zoom in when visibility changes", async () => {
```
Comment (mattpap) [inline bokehjs/test/integration/regressions.ts]: The error:
```
 ✗ Bug
 └┬─ in issue #14207
  └── has zoom in when visibility changes
images differ by 1px (0.00%)
```
can be resolved with:
```suggestion
    it.allowing(1)("has zoom in when visibility changes", async () => {
```
This is typically due to CSS shadows. Or you can replace `Select` with something simpler, e.g. a `Spacer` or a `Pane` with a little bit of CSS for width, height and maybe background color.

**Review by mattpap — APPROVED** [review]

**Comment by mattpap** [comment]
Thanks @muendlein.
