### PR TITLE
Test bokehjs examples and run them on travis ci

### LINKED ISSUE #5882: Test bokehjs/examples and run them on travis ci
They are constantly broken due to not being continuously tested.

### PR DESCRIPTION
**Pull request by mattpap**
fixes #5882

### CODE REVIEW

File: bokehjs/examples/anscombe/anscombe.ts [hunk 1]
```diff
@@ -1,8 +1,8 @@
 namespace Anscombe {
   console.log(`Bokeh ${Bokeh.version}`);
-  Bokeh.set_log_level("debug");
+  Bokeh.set_log_level("info");
 
-  const anscombe_quartet = Bokeh.LinAlg.transpose([
+  const anscombe_quartet = Bokeh.Utils.transpose([
```
Comment (mattpap) [inline bokehjs/examples/anscombe/anscombe.ts]: This will require a migration note, just I'm still not sure if this is the final API.

Comment (bryevdv) [inline bokehjs/examples/anscombe/anscombe.ts]: This seems "OK" to me. Whatever we end up with for 0.12.5 should be considered final.

File: bokehjs/examples/anscombe/.gitignore [hunk 2]
```diff
@@ -1 +1,2 @@
 anscombe.js
+anscombe-*.png
```
Comment (bryevdv) [inline bokehjs/examples/anscombe/.gitignore]: can't we just add a single `.gitignore` at the top with `*.js` an `*.png` ?

Comment (bryevdv) [inline bokehjs/examples/anscombe/.gitignore]: Can't we just add a single `.gitignore` one level up with `*.js` an `*.png` ? Having those definitely seems like the exception. If we need to add a `.js` we can make git do that on a case by case basis, instead of having to remember to add a custom `.gitignore` to every new example.

File: bokehjs/examples/anscombe/anscombe.ts (hunk 1 above)
Comment (bryevdv) [inline bokehjs/examples/anscombe/anscombe.ts]: This seems "OK" to me. Whatever we end up with for 0.12.5 should be considered final, and my preference would be to decide that now and add the migration note now.

File: bokehjs/examples/anscombe/.gitignore (hunk 2 above)
Comment (mattpap) [inline bokehjs/examples/anscombe/.gitignore]: I'm actually going to save files generated by `test_examples` in a dot directory, e.g. `.tests`. Then we can exclude all in one place and don't risk interfering with committed files.

File: bokehjs/examples/anscombe/anscombe.ts (hunk 1 above)
Comment (mattpap) [inline bokehjs/examples/anscombe/anscombe.ts]: There are a few more things that have to be exposed through this API, that's why I would like to defer this to another PR.

Comment (bryevdv) [inline bokehjs/examples/anscombe/anscombe.ts]: Then there is no point in changing it from `LinAlg` in this PR. A PR should have both a decision and a change, or neither.
