### PR TITLE
Fix for spurious client events 

### LINKED ISSUE #3313: selections are broken on app/stocks
The recent work on the server probably broke selection for this app.. they just don't work for me on Python 3 with no meaningful error either on the JS or Python side

### PR DESCRIPTION
**Pull request by bryevdv**
OK, this PR supercedes #3401 (reverted) and some of #3414 (which will be closed with the branch kept for now)

There were several scenarios where properties were set or instances were created initially on the BokehJS side, and this was causing a huge number of events to be sent back to the server. Basically every mouse move and render:
 
* `DataRange1d` recomputed its `renderers` every single update (render). Now it does only once
* Tools with box and polygon overlays now just use actual box and poly annotations, configured from python. Bonus: now these overlays are user-configurable
* `Span` and `Tooltip` did not have python models, which caused huge spamming of the console

All `plotting/server` and `app` examples were tested on OSX/Safari and work very well, including the `selection_histogram.py` which now works perfectly! I added an app version of it to `app` directory.  I also cleaned up the `stocks.py` app example a bit, and it is working well now too. (minus the histograms, for now)

It is clear that soon after `0.11` we must design a proper system to specify and manage things like private browser state, client-only models, and configurable event suppression options in a proper way. 

ping @mattpap @havocp 

Fixes #3313 and part of #3390

### CODE REVIEW

**Comment by bryevdv** [comment]
re-marking WIP, I want to add more tests and docs, but please review as soon as is practical

File: bokehjs/src/coffee/renderer/annotation/box_annotation.coffee [hunk 1]
```diff
@@ -48,14 +82,25 @@ class BoxAnnotation extends HasParent
...
 
+  nonserializable_attribute_names: () ->
+    super().concat(['silent_update'])
+
+  update:({left, right, top, bottom}) ->
+    if @get('silent_update')
+      @attributes['left'] = left
+      @attributes['right'] = right
+      @attributes['top'] = top
+      @attributes['bottom'] = bottom
```
Comment (havocp) [inline bokehjs/src/coffee/renderer/annotation/box_annotation.coffee]: I think `@set` has a flag that makes it silent that could be used here

Comment (bryevdv) [inline bokehjs/src/coffee/renderer/annotation/box_annotation.coffee]: It does. :) I tried that, it still triggered patch events to the server. I figured this would do for now until we work on a more ambitious solution after `0.11`

**Comment by bryevdv** [comment]
I'd like to merge this at some point on the 26th. AFAICT this branch is the most stable yet.

**Comment by birdsarah** [comment]
I think the example `plotting/server/geojson_points.py` is not working on this branch.

**Comment by bryevdv** [comment]
Try everything on #3420

**Comment by birdsarah** [comment]
brilliant, thanks, sorry for the noise!

**Comment by bryevdv** [comment]
No noise, we don't have PRs that stack this much very often.

File: bokehjs/src/coffee/renderer/annotation/box_annotation.coffee (hunk 1 above)
Comment (havocp) [inline bokehjs/src/coffee/renderer/annotation/box_annotation.coffee]: something needs investigating here... the patch events are from the change notification, and silent mode should suppress change notification... not sure the patch events you saw were caused by this? must be something going on

**Comment by havocp** [comment]
Hard to review here, because some things are really hard to do "right" without tackling the has_properties.py/properties.py/backbone overall picture. I'm fine with landing this as an improvement for now because I don't think we should tackle the overall picture pre-0.11, just have to do the best we can.
