### PR TITLE
Convert DateRangeSlider/DateSlider step to days

### LINKED ISSUE #12033: [BUG] Incorrect handling of step by DateRangeSlider
### Software versions

Python version      :  3.10.2 | packaged by conda-forge | (main, Jan 14 2022, 08:02:09) [GCC 9.4.0]
IPython version     :  8.0.0
Tornado version     :  6.1
Bokeh version       :  3.0.0dev5+2.gf990664e5.dirty
BokehJS static path :  /home/iant/github/bokeh/bokeh/server/static
node.js version     :  v16.12.0
npm version         :  8.3.1
Operating system    :  Linux-5.13.0-30-generic-x86_64-with-glibc2.34

### Browser name and version

Same in all browsers

### Jupyter notebook / Jupyter Lab version

_No response_

### Expected behavior

In `DateRangeSlider` the `start` and `end` kwargs are dates, and the `step` is an integer. I expect the units of the `step` to be days therefore. However internally in JS the dates, i.e. slider positions, are stored as POSIX time (in milliseconds since 1970 UTC) so a `step` of 1 is interpreted as 1 millisecond rather than 1 day. If one of the sliders is on a particular date and the `step` is the default of 1, I expect when I drag the handle to the right that the next valid position is the next day.

### Observed behavior

There are many more valid slider positions per day than I expect (86400*1000 to be precise).

### Example code

```Python
# Taken from DateRangeSlider example in docs, but only over 5 days.
from datetime import date
from bokeh.io import show
from bokeh.models import CustomJS, DateRangeSlider

date_range_slider = DateRangeSlider(value=(date(2016, 1, 1), date(2016, 1, 5)),
                                    start=date(2016, 1, 1), end=date(2016, 1, 5))
date_range_slider.js_on_change("value", CustomJS(code="""
    console.log('date_range_slider: value=' + this.value, this.toString())
"""))

show(date_range_slider)
```

### Stack traceback or browser console output

_No response_

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by g-parki**
- [x] issues: fixes #12033
- [x] TODO: apply same treatment to `DateSlider` as requested by @bryevdv 
- [x] tests added / passed
- [ ] release document entry (if new feature or API change)

### Notes
- Updated `_calc_to()` in `DateRangeSliderView` as suggested by @ianthomas23
- In  `AbstractBaseSliderView` I exposed `steps` from the noUiSlider API so we could unit test down to the slider level
- I don't have selenium on my machine at the moment, so I'll wait and see if integration tests break in CI. May be useful to add a new integration test to demonstrate fewer change events as the slider is dragged?

### CODE REVIEW

**Comment by g-parki** [comment]
> can this be marked `ready` ?

Yep, ready for review @bryevdv

File: bokehjs/src/lib/models/widgets/abstract_slider.ts [hunk 1]
```diff
@@ -33,6 +33,10 @@ abstract class AbstractBaseSliderView extends OrientedControlView {
 
   private _noUiSlider: API
 
+  get _steps(): API["steps"] {
```
Comment (bryevdv) [inline bokehjs/src/lib/models/widgets/abstract_slider.ts:36]: this seems a little awkward, @mattpap any other improvement possible?  This is my only comment about the PR otherwise

Comment (g-parki) [reply bokehjs/src/lib/models/widgets/abstract_slider.ts:36]: Agreed. And just to clarify - I only put this in here so I could validate the slider step in tests. Alternative I considered was removing the private protection on `_noUiSlider`

Comment (bryevdv) [reply bokehjs/src/lib/models/widgets/abstract_slider.ts:36]: @g-parki does `API.steps` work here? That would be slightly preferable, if so.

Comment (g-parki) [reply bokehjs/src/lib/models/widgets/abstract_slider.ts:36]: That's what I first tried. It errored in my editor:
` Cannot access 'API.steps' because 'API' is a type, but not a namespace. Did you mean to retrieve the type of the property 'steps' in 'API' with 'API["steps"]'?ts(2713)`

**Comment by bryevdv** [comment]
@mattpap I will plan to merge this tomorrow afternoon (PST) unless more time is requested.

**Review by bryevdv — APPROVED** [review]

**Comment by bryevdv** [comment]
Thanks @g-parki !
