### PR TITLE
Bryanv/webgl copies

### LINKED ISSUE #5589: Some WebGL not working on Safari
Hi,

I'm trying to run the example in models/map_cities.py to see a plot of cities. However, when I run it using the `python map_cities.py` command, I see the html output in browser as below - 

screen shot 2016-12-19 at 4 04 39 pm

Is this expected behavior? Basically, I am trying to use this example to plot/fill states/countys with a desired color and hover information.

Here is my `bokeh info` output - 

    Python version      :  2.7.12 |Anaconda 2.0.1 (x86_64)| (default, Jun 29 2016, 11:09:23)
    IPython version     :  4.1.2
    Bokeh version       :  0.12.3
    BokehJS static path :  //anaconda/lib/python2.7/site-packages/bokeh/server/static

### PR DESCRIPTION
**Pull request by bryevdv**
This PR incidentally fixes #5589 but also makes a number of other incremental changes to webgl:

* currently we always blit the GL canvas if "webgl" backend is specified, even if a glyph decides not to do any gl rendering. This makes blits contingent on actual gl draws having happened

* no more coordinate transforms in webgl for now. All screen coords come from standard `map_data` as a result, *several* uneccessary array copies coudl be removed, also all the gorpy "linearity testing" and "baked offset" code was removed

* The current code does not handle uniform/vector colors properly, deleted the optimization for that and now a full RGBA array is constructed for line and fill every time (this is the fix for #5589)

This version probably updates all the buffers more often than the previous code, but also reduces array copies. In my local testing performance was still very good. In any case things are now more correct/working. 

- [x] issues: fixes #5589

### Issues discovered

I noticed two issues that seem to exist already (checked 2.1.1), so no need to try and fix them now: 

* zooming in on circles with `radius` stop zooming properly at some point, and stay a fixed size

* lines zoomed in look like garbage:

Screen Shot 2020-08-07 at 10 15 02 AM

### CODE REVIEW

**Comment by bryevdv** [comment]
FYI I think this would be good to get into 2.2 if possible, but I am not pressed about it. 

As a next step I think I'd like to see about constructing typed RGBA arrays for colors in the regular `map_data` path, so that all color mapping can come out of the webgl code, and also those color buffers could just be passed directly as now with coordinates. 

At this point I think the current webgl code will be stripped down enough that a migration to using ReGL can be contemplated, with the more careful buffer/uniform handling that I was prototyping outside Bokeh.

File: bokehjs/src/lib/models/glyphs/glyph.ts [hunk 1]
```diff
@@ -306,6 +307,7 @@ export abstract class GlyphView extends View {
     }
 
     this._map_data()
+    this.glglyph?.set_data_changed()
```
Comment (bryevdv) [inline bokehjs/src/lib/models/glyphs/glyph.ts:310]: This is necessary since we are no longer mapping data coordinates in gl, we need to pick up the new screen mapped coordinates.

**Comment by bryevdv** [comment]
Looks like the webgl lines are slightly wider now, but only slightly. We're going ot have to re-do all the line algo anyway since it produces such bad results zoomed in so I am not going to worry about it.

**Comment by mattpap** [comment]
I will review this evening or tomorrow morning.

**Comment by bryevdv** [comment]
Incidentally, here is the implementation of instanced line rendering wit ReGL, including caps and joins, that I intend to eventually follow:

https://wwwtyro.net/2019/11/18/instanced-lines.html

File: bokehjs/src/lib/models/glyphs/webgl/markers.ts [hunk 2]
```diff
@@ -137,17 +131,12 @@ export abstract class MarkerGL extends BaseGLGlyph {
...
     // Upload data if we must. Only happens for main glyph.
     if (mainGlGlyph.data_changed) {
-      if (!(isFinite(trans.dx) && isFinite(trans.dy))) {
-        return  // not sure why, but it happens on init sometimes (#4367)
-      }
-      mainGlGlyph._baked_offset = [trans.dx, trans.dy]  // float32 precision workaround; used in _set_data() and below
       mainGlGlyph._set_data(nvertices)
+      if (this.glyph instanceof CircleView && this.glyph._radius != null) {
+        // Keep screen radius up-to-date for circle glyph. Only happens when a radius is given
+        this.vbo_s.set_data(0, new Float32Array(map(this.glyph.sradius, (s) => s*2)))
```
Comment (mattpap) [inline bokehjs/src/lib/models/glyphs/webgl/markers.ts:137]: `new Float32Array()` should be unnecessary, given that `sradius` is of the same type and `map()` is a type preserving transform.

Comment (mattpap) [reply bokehjs/src/lib/models/glyphs/webgl/markers.ts:137]: Well, I see the code is full of this kind of quirks, so this will have to be cleaned up at some point.

File: bokehjs/src/lib/models/glyphs/webgl/base.ts [hunk 3]
```diff
@@ -32,35 +31,13 @@ export abstract class BaseGLGlyph {
...
-    wx = 100 / Math.min(Math.max(Math.abs(dx[1] - dx[0]), 1e-12), 1e12)
-    wy = 100 / Math.min(Math.max(Math.abs(dy[1] - dy[0]), 1e-12), 1e12)
-    ;[dx, dy] = this.glyph.renderer.coordinates.map_to_screen([a*wx, b*wx, c*wx], [a*wy, b*wy, c*wy])
-    // Test how linear it is
-    if ((Math.abs((dx[1] - dx[0]) - (dx[2] - dx[1])) > 1e-4) ||
-        (Math.abs((dy[1] - dy[0]) - (dy[2] - dy[1])) > 1e-4)) {
-      logger.warn(`WebGL backend (${this.glyph.model.type}): falling back to canvas rendering`)
-      return false
-    }
-    const [sx, sy] = [(dx[1]-dx[0]) / wx, (dy[1]-dy[0]) / wy]
```
Comment (mattpap) [inline bokehjs/src/lib/models/glyphs/webgl/base.ts:58]: Does this mean we can use non-linear scales already at this point? If so, a test would be useful to see a test to confirm.

File: bokehjs/src/lib/models/glyphs/webgl/markers.ts (hunk 2 above)
Comment (bryevdv) [reply bokehjs/src/lib/models/glyphs/webgl/markers.ts:137]: Definitely, ultimately I would like to just always map ssize for circles as part of the "set data" work so that it can just be put straight into a buffer on the gl side (like everything else). I will remove the extra `Float32Array` here tho

File: bokehjs/src/lib/models/glyphs/webgl/base.ts (hunk 3 above)
Comment (bryevdv) [reply bokehjs/src/lib/models/glyphs/webgl/base.ts:58]: Yes this works tho at least in this particular example interactive panning is a bit laggy 

Screen Shot 2020-08-12 at 8 32 17 AM

I'll add a test though before merging

Comment (bryevdv) [reply bokehjs/src/lib/models/glyphs/webgl/base.ts:58]: test added. It does not verify that webgl is used but then again we don't have any fallback conditions anymore
