### PR TITLE
respect global table.sortable flag

### LINKED ISSUE #9266: [BUG] DataTable sorting broken
**ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)**
```
Python version      :  3.7.2 (default, Mar 15 2019, 01:06:31) 
IPython version     :  (not installed)
Tornado version     :  6.0.3
Bokeh version       :  1.3.0
BokehJS static path :  /usr/local/lib/python3.7/site-packages/bokeh/server/static
node.js version     :  v10.15.1
npm version         :  6.10.0
```
OS: Mac OS X Mojave 10.14.6
Browser: Google Chrome Version 76.0.3809.100 (Official Build) (64-bit)

**Description of expected behavior and the observed behavior**
Expected behavior: table columns should remain unsorted when accidentally clicking on the column header and then editing a value in the same column

Observed behavior: After clicking the column header "Downloads" nothing happens (as expected) but after editing a value in the same column and hitting ENTER the sort action is still being executed

**Complete, minimal, self-contained example code that reproduces the issue**

main.py
```py
from datetime import date
from random import randint

from bokeh.io import show
from bokeh.models import ColumnDataSource
from bokeh.models.widgets import DataTable, DateFormatter, TableColumn

data = dict(dates=[date(2014, 3, i+1) for i in range(10)], 
            downloads=[randint(0, 100) for i in range(10)], )

columns = [TableColumn(field="dates", title="Date", formatter=DateFormatter()),
           TableColumn(field="downloads", title="Downloads"), ]

data_table = DataTable(source=ColumnDataSource(data), columns=columns, width=400, height=280, editable=True, sortable=False)

show(data_table)
```

**Reproduction steps**

1) Click the column header "Downloads"
2) Edit any value in the same column

**Additional Info**
JavaScript error after clicking on a column header:
```js
bokeh-tables-1.3.0.js:1048 Uncaught TypeError: Cannot read property 'map' of undefined
    at TableDataProvider.sort (bokeh-tables-1.3.0.js:1048)
    at SlickGrid.<anonymous> (bokeh-tables-1.3.0.js:1198)
    at Event.notify (bokeh-tables-1.3.0.js:11377)
    at trigger (bokeh-tables-1.3.0.js:14514)
    at HTMLDivElement.<anonymous> (bokeh-tables-1.3.0.js:14154)
    at HTMLDivElement.dispatch (bokeh-tables-1.3.0.js:5635)
    at HTMLDivElement.$event.dispatch (bokeh-tables-1.3.0.js:10177)
    at HTMLDivElement.elemData.handle (bokeh-tables-1.3.0.js:5487)
```

### PR DESCRIPTION
**Pull request by bryevdv**
- [x] issues: fixes #9266
- [x] tests added / passed

I think I'd like to add some integration tests around table sorting but lets make sure the existing ones pass with this change

### CODE REVIEW

**Comment by mattpap** [comment]
> I think I'd like to add some integration tests around table sorting but lets make sure the existing ones pass with this change

We need to figure out how to make the existing tests reliable, otherwise it's far from obvious to tell if things still work or not.

File: bokehjs/src/lib/models/widgets/tables/data_table.ts [hunk 1]
```diff
@@ -134,14 +134,17 @@ export class DataTableView extends WidgetView {
...
+    if (this.model.sortable) {
+      const columns = this.grid.getColumns()
+      const sorters = this.grid.getSortColumns().map((x: any) => ({
+        sortCol: {
+          field: columns[this.grid.getColumnIndex(x.columnId)].field,
+        },
+        sortAsc: x.sortAsc,
+      }))
+
+        this.data.sort(sorters)
```
Comment (mattpap) [inline bokehjs/src/lib/models/widgets/tables/data_table.ts]: Indentation.

File: bokehjs/src/lib/models/widgets/tables/data_table.ts [hunk 2]
```diff
@@ -134,14 +134,17 @@ export class DataTableView extends WidgetView {
...
-    const sorters = this.grid.getSortColumns().map((x: any) => ({
-      sortCol: {
-        field: columns[this.grid.getColumnIndex(x.columnId)].field,
-      },
-      sortAsc: x.sortAsc,
-    }))
-    this.data.sort(sorters)
+    if (this.model.sortable) {
+      const columns = this.grid.getColumns()
+      const sorters = this.grid.getSortColumns().map((x: any) => ({
```
Comment (mattpap) [inline bokehjs/src/lib/models/widgets/tables/data_table.ts]: This `any` type can be safely removed, because `getSortColumns()` has a well defined type declaration.

**Comment by bryevdv** [comment]
> We need to figure out how to make the existing tests reliable, otherwise it's far from obvious to tell if things still work or not.

There are only a handful of tests, less than 5 out of 200+ that are flaky right now. That's not a reason not to create new tests.

**Comment by bryevdv** [comment]
@mattpap would like to merge this tomorrow
