### PR TITLE
Bugfix/3036 gulp build

### LINKED ISSUE #3036: gulp build script creates incorrect source map and gulp watch has bad path to LICENSE.txt
Two issues were generated by the addition of the LICENSE.txt PR.

1) The source map that is generated by the gulp build script is incorrect. The license comment section offsets the source map and needs to be appended to the bottom of bokeh.js (not the top).

2) When the gulp watch process calls setup.py from the bokehjs dir, the setup.py script has a bad path to the LICENSE.txt file that it tries to copy. Path should be modified to relative path.

### PR DESCRIPTION
**Pull request by canavandl**
issues: fixes #3036 

Fixes bug in source map generate caused by license by appending license to bottom of bokeh.js

Fixes bug where setup.py called by gulp watch process has bad path to LICENSE.txt

### CODE REVIEW

File: bokehjs/gulp/tasks/scripts.coffee [hunk 1]
```diff
@@ -130,6 +130,7 @@ gulp.task "scripts:build", (cb) ->
       .bundle()
       .pipe(source(paths.coffee.bokehjs.destination.full))
       .pipe(buffer())
+      # .pipe(insert.prepend(license))
```
Comment (bryevdv) [inline bokehjs/gulp/tasks/scripts.coffee]: commented code should be deleted

File: setup.py [hunk 2]
```diff
@@ -83,8 +83,11 @@ def yellow(text) : return text
 # -----------------------------------------------------------------------------
 # Classes and functions
 # -----------------------------------------------------------------------------
-
-copy("LICENSE.txt", "bokeh/")
+try:
+    copy("LICENSE.txt", "bokeh/")
+except FileNotFoundError:
+    # setup.py called from bokehjs dir by gulp watch process
+    copy("../LICENSE.txt", "../bokeh/")
```
Comment (bryevdv) [inline setup.py]: I can see that this would work, but I wonder if there isn't a better way to accomplish this. If not, there at least needs to be a comment explaining what's going on.

Comment (canavandl) [inline setup.py]: I knew this that wasn't a great solution. I'll figure out something better.

**Comment by canavandl** [comment]
ping @bryevdv

**Comment by bryevdv** [comment]
It seems the minified BokehJS is not retaining its own license? The end of the file:
```
{format:c}},{underscore:"underscore"}]},{},["main"])}();
//# sourceMappingURL=bokeh.min.js.map
```
If that's some simple fix maybe just include it here.

**Comment by canavandl** [comment]
So I appended the license to the bottom of the minified js files. I wasn't able to use the regex in the ``scripts:minify`` task because the license in the non-minified files is outside the function scope that the regex searches.

So with this PR, both the non-minified and minified JS sourcemaps are correct, the only downside is that if somebody else bundles BokehJS into their project, I don't think our license will show up in their JS files. I don't know how much we care about that.
