### PR TITLE
log error if multi-glyph gets invalid array

### LINKED ISSUE #10976: Wrong data shape for a glyph results in an exception
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
bokeh 2.3, python 3.7, OS windows, browser chromium

#### Description of expected behavior and the observed behavior
I expect the code below not to lead to an error in the front-end, which was the case up to Bokeh 2.1.1
Since Bokeh 2.2 it gives an error, see screenshot below.

@mattpap mentioned on the discourse page it should not give this error in any case: https://discourse.bokeh.org/t/bokeh-2-2-page-does-not-render-need-help-debugging/6221

When this error occurs it stops rendering the rest of the page.

I guess the dict does not have the structure that the columndatasource component expects, but I would expect an error on the backend side then.

#### Complete, minimal, self-contained example code that reproduces the issue

```
from bokeh.plotting import curdoc, figure
from bokeh.models import ColumnDataSource

source = ColumnDataSource(data={'xs': [1, 1, 1],
        'ys': [3, 3, 3],
        'labels': ['one', 'two', 'three']})

p = figure(title="Plot", name="p",
            match_aspect=False, sizing_mode="stretch_both")

p = figure(width=600, height=300)
p.multi_line(xs='xs', ys='ys', legend_group='labels', source=source)

curdoc().add_root(p)
```

#### Stack traceback and/or browser JavaScript console output & screenshots or screencasts of the bug in action
image

### PR DESCRIPTION
**Pull request by bryevdv**
- [x] issues: fixes #10976

Screenshot 2025-02-10 at 08 05 41

### CODE REVIEW

File: bokehjs/src/lib/models/glyphs/glyph.ts [hunk 1]
```diff
@@ -368,7 +368,17 @@ export abstract class GlyphView extends DOMComponentView {
...
   }
 
-  protected _transform_array<T>(prop: p.BaseCoordinateSpec<T>, array: Arrayable<unknown>) {
+  protected transform_array<T>(prop: p.BaseCoordinateSpec<T>, array: Arrayable<unknown>) {
+    // examine just the top level of a 2-d array to validate
+    // that every subitem is an array of some kind, as expected
+    if (prop instanceof p.CoordinateSeqSpec) {
+      for (let i = 0; i < array.length; i++) {
+        if (!isArrayable(array[i])) {
+          logger.error(`expected a 2-d array for ${this.model.type}.${prop.attr}`)
```
Comment (mattpap) [inline bokehjs/src/lib/models/glyphs/glyph.ts]: Note that `logger.error()` doesn't stop execution like throwing an exception does, so this may log a lot if every index is bad and then it will fail anyway at some point.

File: bokehjs/src/lib/models/glyphs/glyph.ts [hunk 2]
```diff
@@ -368,7 +368,17 @@ export abstract class GlyphView extends DOMComponentView {
     }
   }
 
-  protected _transform_array<T>(prop: p.BaseCoordinateSpec<T>, array: Arrayable<unknown>) {
+  protected transform_array<T>(prop: p.BaseCoordinateSpec<T>, array: Arrayable<unknown>) {
```
Comment (mattpap) [inline bokehjs/src/lib/models/glyphs/glyph.ts]: Why rename this? Protected and private members are prefixed with `_` by convention.

File: bokehjs/src/lib/models/glyphs/glyph.ts (hunk 1 above)
Comment (mattpap) [reply bokehjs/src/lib/models/glyphs/glyph.ts]: My previous suggestion for using `logger.error()` was to combine it with error recovery. If no recovery is performed, then I would throw an exception as originally proposed.

File: bokehjs/src/lib/models/glyphs/glyph.ts (hunk 2 above)
Comment (bryevdv) [reply bokehjs/src/lib/models/glyphs/glyph.ts]: I thought a benefit of having actual `private` and `protected` capability in the language was that typographic conventions became unnecessary. I wanted to keep `_some_name` out of the visible log messages.

Comment (mattpap) [reply bokehjs/src/lib/models/glyphs/glyph.ts]: This is still JavaScript underneath, so the convention applies to that. There is the new `#` prefix for private members (though that comes with a lot of baggage), but nothing for protected members.

> I wanted to keep _some_name out of the visible log messages.

That sounds reasonable, but I also doubt that it's a big concern for an average user, who is very likely not to know about the JS console at all. With issue #14252 resolved, 99% of users will never see that, maybe except when asked explicitly when submitting a bug report.

File: bokehjs/src/lib/models/glyphs/glyph.ts (hunk 1 above)
Comment (bryevdv) [reply bokehjs/src/lib/models/glyphs/glyph.ts]: Sure https://github.com/bokeh/bokeh/pull/14308/commits/dcf3f95a116a9a07c5749572847855533cff6128 though this appears a bit strangely redundant to me 

Screenshot 2025-02-10 at 08 39 08

Maybe there should be a "fatal" log level?

File: bokehjs/src/lib/models/glyphs/glyph.ts (hunk 2 above)
Comment (bryevdv) [reply bokehjs/src/lib/models/glyphs/glyph.ts]: [1baf82f](https://github.com/bokeh/bokeh/pull/14308/commits/1baf82f1c05ce80a3b7f02b4494038d4f0394325)

**Review by mattpap — APPROVED** [review]
