### PR TITLE
Fix WebGL scaling of antialising by pixel ratio 

### LINKED ISSUE #13692: [BUG] Blurry plots with WebGL
### Software versions

```
Python version        :  3.11.5 | packaged by conda-forge | (main, Aug 27 2023, 03:33:12) [Clang 15.0.7 ]
IPython version       :  8.15.0
Tornado version       :  6.3.3
Bokeh version         :  3.3.4
BokehJS static path   :  <MY CONDA ENV DIR>/lib/python3.11/site-packages/bokeh/server/static
node.js version       :  v21.1.0
npm version           :  10.2.0
jupyter_bokeh version :  (not installed)
Operating system      :  macOS-12.5-arm64-arm-64bit
```

### Browser name and version

Firefox 122.0.1

### Jupyter notebook / Jupyter Lab version

JupyterLab 4.1.1

### Expected behavior

The second plot should not be blurry

### Observed behavior

The second plot should is blurry

### Example code

```Python
import bokeh.plotting
import bokeh.palettes
import bokeh.io
import holoviews as hv

bokeh.io.output_notebook()
hv.extension('bokeh')

x = [0, 1, 2, 3]
y = [1, 2, 3, 2]
width = 500
height = 300
color = bokeh.palettes.Set1_3[1]

p1 = bokeh.plotting.figure(width=width, height=height)
p1.line(x, y, width=2, color=color)
bokeh.plotting.show(p1)

p2 = bokeh.plotting.figure(width=width, height=height, output_backend='webgl')
p2.line(x, y, width=2, color=color)
bokeh.plotting.show(p2)
```

### Stack traceback or browser console output

_No response_

### Screenshots

The first plot:

The second plot:

### PR DESCRIPTION
**Pull request by ianthomas23**
Fixes #13692, the incorrect scaling of WebGL antialiasing by pixel ratio.

The `width` and `height` of the canvas used for WebGL rendering is scaled by `pixel_ratio`:
https://github.com/bokeh/bokeh/blob/78d71c26208ca81fb151904cff25d7cbf01f5f1b/bokehjs/src/lib/core/util/canvas.ts#L71-L72

whereas the `antialias` width is constant regardless of `pixel_ratio`. Following this through the WebGL rendering pipeline shows that this means the rendered antialiasing scales with `pixel_ratio`, and so is too large for `pixel_ratio > 1` such as for retina screen or zooming (which is implemented in chrome dev tools using a larger pixel ratio).

The fix is to scale the antialiasing by dividing by `pixel_ratio`.

Test code:
```python
from bokeh.plotting import figure, row, show

ps = []
for backend in ("canvas", "webgl"):
    p = figure(width=200, height=150, output_backend=backend, title=backend)
    p.line(x=[0, 1, 2, 3], y=[1, 2, 3, 2], width=5)
    ps.append(p)

show(row(ps))
```
before the fix on a retina screen (pixel ratio 2) at zoom level 300% (so the pixel ratio seen is 6):
Screenshot 2024-03-25 at 15 52 08

and after this fix:
Screenshot 2024-03-25 at 15 25 29

The fix scales the antialising that is passed to the WebGL vertex shaders. It could be performed in the vertex shaders instead, but then the antialias would have to be a GLSL `attribute` rather than `uniform`. Whilst here I realised that the `pixel_ratio` is passed to the shaders but only used to scale the canvas size, i.e. to remove the `pixel_ratio` multiple added in `canvas.ts` above. So I have moved this scaling to `BaseGLGlyph` instead which means we no longer need to pass `pixel_ratio` into any of the shaders. It is not a big deal either way, but I think this implementation is a bit simpler and cleaner.

### CODE REVIEW

File: bokehjs/test/integration/regressions.ts [hunk 1]
```diff
@@ -3744,4 +3744,26 @@ describe("Bug", () => {
...
+
+      it.dpr(1)("with devicePixelRatio == 1", async () => {
+        await display(row([plot("canvas"), plot("svg"), plot("webgl")]))
+      })
+
+      it.dpr(2)("with devicePixelRatio == 2", async () => {
+        await display(row([plot("canvas"), plot("svg"), plot("webgl")]))
+      })
+
+      it.dpr(3)("with devicePixelRatio == 3", async () => {
```
Comment (mattpap) [inline bokehjs/test/integration/regressions.ts:3764]: I'm not sure if just using `.dpr(N)` is enough to produce a meaningful test. I think this needs scaling as well, but we don't have an API exposed for this currently, though it's possible at CDP (Chrome Devtools Protocol) level.

Comment (ianthomas23) [reply bokehjs/test/integration/regressions.ts:3764]: Yes, really we should also be scaling the canvas size along with the pixel ratio. But it is meaningful as it is, here is the dpr=3 test image before and after this PR:

before
after

The WebGL line is "too blurry" before this change, but one might have to enlarge the images to convince oneself.

Comment (ianthomas23) [reply bokehjs/test/integration/regressions.ts:3764]: I'd happily remove the new test and save the disk space. But if we keep it we can at least identify when it changes and it will lead us back here where there are instructions for a manual test.

**Comment by ianthomas23** [comment]
It looks to me like the test failures are unrelated.

File: bokehjs/test/integration/regressions.ts (hunk 1 above)
Comment (mattpap) [reply bokehjs/test/integration/regressions.ts:3764]: I would like to keep this test, but I would also like to establish if we can make the difference more obvious. I did a little bit of exploration myself and there is a difference when comparing generated images between `branch-3.5` and this PR, so this test is indeed valid, though hard on "the naked eye". I tried to enable scaling in CDP, but it doesn't seem to do anything useful. So I suppose this will have to do for now.

File: bokehjs/test/integration/regressions.ts [hunk 2]
```diff
@@ -3744,4 +3744,26 @@ describe("Bug", () => {
       await display(p, [p.width! + left + 50, p.height! + top + 50])
     })
   })
+
+  describe("in issue #13692", () => {
+    describe("doesn't scale webgl antialising by pixel ratio", () => {
```
Comment (mattpap) [inline bokehjs/test/integration/regressions.ts]:
```suggestion
    describe("doesn't scale webgl antialiasing by pixel ratio", () => {
```
Though this will require changes to baseline file names

**Review by mattpap — APPROVED** [review]

File: bokehjs/test/integration/regressions.ts (hunk 2 above)
Comment (ianthomas23) [reply bokehjs/test/integration/regressions.ts]: Done.
