### PR TITLE
Use circle centers for rect/poly hit testing

### LINKED ISSUE #12592: Rect hit testing on circles is overzealous, at least by the default
I think it's a stretch to consider this a valid selection, at least as the default:

image

I suppose rect hit testing should consider either centers of circles or require for circles to be full included or make it configurable. I think the original was to consider centers, but this may have changed when indexing of circles changed to improve auto-ranging of circles, so probably it's a regression.

### PR DESCRIPTION
**Pull request by mattpap**
fixes #12592

### CODE REVIEW

File: bokehjs/src/lib/models/glyphs/circle.ts [hunk 1]
```diff
@@ -161,22 +160,25 @@ export class CircleView extends XYGlyphView {
...
-      ;[y0, y1] = this.renderer.yscale.r_invert(sy0, sy1)
-    }
+    const [x0, x1, y0, y1] = (() => {
+      if (this.use_radius && this.model.properties.radius.units == "data") {
+        const dr = this.max_radius*hit_dilation
+        const x0 = x - dr
+        const x1 = x + dr
+        const y0 = y - dr
+        const y1 = y + dr
+        return [x0, x1, y0, y1]
```
Comment (bryevdv) [inline bokehjs/src/lib/models/glyphs/circle.ts:170]: just a suggestion, but these expressions are simple/small enough that this seems preferable:

```suggestion
        return [x - dr, x + dr, y - dr, y + dr]
```
(and similar in the calls to `r_invert` below)
