### PR TITLE
Hide cursor for non editable BoxAnnotation

### LINKED ISSUE #14869: BoxAnnotation shows resize cursor by default
### Browser name and version

Firefox and Chrome

### Jupyter notebook / Jupyter Lab version

_No response_

### Expected behavior

BoxAnnotation does not change mouse cursor by default.

### Observed behavior

When hovering at the border of a BoxAnnotation the mouse cursor changes to a resize one.
This is the case in the examples for dev and latest release: https://docs.bokeh.org/en/dev-3.9/docs/examples/basic/annotations/box_annotation.html (see screenshot below).
This was not the case for previous versions like 3.4.2: https://docs.bokeh.org/en/3.4.2/docs/examples/basic/annotations/box_annotation.html.
To me it was an unexpected change, so I thought it might be a bug? Also given that [use_handles is false by default](https://docs.bokeh.org/en/latest/docs/reference/models/annotations.html#bokeh.models.BoxAnnotation.use_handles). If this is expected, feel free to close the issue.

I was only able to disable that behavior by using `movable='none', resizable='none'`.

### Example code

```Python
# From the bokeh example:
from bokeh.models import BoxAnnotation
from bokeh.plotting import figure, show
from bokeh.sampledata.glucose import data

TOOLS = "pan,wheel_zoom,box_zoom,reset,save"

#reduce data size
data = data.loc['2010-10-06':'2010-10-13'].reset_index()

p = figure(x_axis_type="datetime", tools=TOOLS)

p.line("datetime", "glucose", source=data, color="gray", legend_label="glucose")

low_box = BoxAnnotation(top=80, fill_alpha=0.2, fill_color='#D55E00')
mid_box = BoxAnnotation(bottom=80, top=180, fill_alpha=0.2, fill_color='#0072B2')
high_box = BoxAnnotation(bottom=180, fill_alpha=0.2, fill_color='#D55E00')

p.add_layout(low_box)
p.add_layout(mid_box)
p.add_layout(high_box)

p.title.text = "Glucose Range"
p.xgrid.grid_line_color=None
p.ygrid.grid_line_alpha=0.5
p.xaxis.axis_label = 'Time'
p.yaxis.axis_label = 'Value'
p.legend.level = "overlay"
p.legend.location = "top_left"

show(p)
```

### Stack traceback or browser console output

_No response_

### Screenshots

Image

### PR DESCRIPTION
**Pull request by muendlein**
- [x] issues: fixes #14869
- [x] tests added / passed

### CODE REVIEW

File: bokehjs/src/lib/models/annotations/box_annotation.ts [hunk 1]
```diff
@@ -826,6 +826,10 @@ export class BoxAnnotationView extends AnnotationView implements Pannable, Pinch
       return null
     }
 
+    if (!this.model.editable && !this.model.is_handle) {
+      return null
+    }
```
Comment (mattpap) [inline bokehjs/src/lib/models/annotations/box_annotation.ts]: This should be handled in `_can_hit()`. `cursor()` shouldn't handle such logic, only selection of the right cursor glyph.

File: bokehjs/test/unit/regressions.ts [hunk 2]
```diff
@@ -2027,4 +2027,46 @@ describe("Bug", () => {
...
+      expect(get_cursor(view)).to.be.equal("default")
+
+      await ac.hover(xy(3, 1))
+      expect(get_cursor(view)).to.be.equal("default")
+
+      await ac.hover(xy(2, 1))
+      expect(get_cursor(view)).to.be.equal("default")
+
+      await ac.hover(xy(2, 2))
+      expect(get_cursor(view)).to.be.equal("default")
```
Comment (mosc9575) [inline bokehjs/test/unit/regressions.ts]: I think this can be shortened with a loop.

```suggestion

      for( x of [1, 2, 3] ){
          for( y of [1, 2, 3] ){
              await ac.hover(xy(x, y))
              expect(get_cursor(view)).to.be.equal("default")
          }
      }
```

Comment (mattpap) [reply bokehjs/test/unit/regressions.ts]: Shorter sure. Simpler, not necessarily. My personal preference is to create a function and then use that function for individual cases:
```ts
async function has_cursor_at(point: XY, cursor: string) {
  await ac.hover(point)
  expect(get_cursor(view)).to.be.equal(cursor)
} 

await has_cursor_at(xy(2, 2), "default")
await has_cursor_at(xy(2, 1), "default")
await has_cursor_at(xy(2, 0), "default")
...
```
Easier to debug and modify cases. Of course it depends on the number of cases.

File: bokehjs/src/lib/models/annotations/box_annotation.ts (hunk 1 above)
Comment (muendlein) [reply bokehjs/src/lib/models/annotations/box_annotation.ts]: Agreed.

File: bokehjs/test/unit/regressions.ts (hunk 2 above)
Comment (muendlein) [reply bokehjs/test/unit/regressions.ts]: I have proceeded with the second approach, mainly because a for loop tends to hides the intent here (as the xy combinations are not random but represent corners & edges of the box (+ one for the area)).

**Review by mattpap — APPROVED** [review]

**Comment by mosc9575** [comment]
I think this should be added to `3.9.1` - see #15089.
