### PR TITLE
Fix hover tooltip and selection for step glyph

### LINKED ISSUE #7419: Hover tooltip not showing for step line
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
Python 3.6
Bokeh 0.12.13

#### Description of expected behavior and the observed behavior
Using the default hover tool I do not see the tooltip when using the step line. Switching to circle or line will result to the correct behaviour.

#### Complete, minimal, self-contained example code that reproduces the issue

```
from bokeh.plotting import figure, output_file, show

# output to static HTML file
output_file("test.html")

p = figure(plot_width=400,
           plot_height=400,
           tools='hover')

# p.circle([1, 2, 3, 4, 5], [6, 7, 2, 4, 5],
#          size=20,
#          color="navy",
#          alpha=0.5,
#          )

p.step([1, 2, 3, 4, 5], [6, 7, 2, 4, 5],
         color="navy",
         alpha=0.5,
         )

# p.line([1, 2, 3, 4, 5], [6, 7, 2, 4, 5],
#        color="navy",
#        alpha=0.5,
#        )

# show the results
show(p)
```

### PR DESCRIPTION
**Pull request by henricryden**
Fixes #7419 

I decided to snap the tooltip to data points. I think this is the expected behavior when working with step plots, and it makes it clear which "mode" was used (after, center, before):

image
image

image

```py
from bokeh.io import show
from bokeh.plotting import figure

p = figure(width=600, height=400, tools="hover")

p.step(x=[10, 11, 12, 13], y=[3, 2, 1, 2], mode="before", line_width=2, line_color="blue")

p.hover.mode = 'vline'
p.hover.tooltips = [("x", "$snap_x"), ("y", "$snap_y")]
p.title.text = "before"

show(p)
```

### CODE REVIEW

**Comment by henricryden** [comment]
@mattpap this PR is next in line 🙂 since it also affects step, I'll incorporate #14743 once that is merged. What type of test is applicable here?

**Comment by henricryden** [comment]
I merged with bokeh:branch-3.9 and verified that it works. I don't know what type of tests are relevant here. Can someone point me in the right direction?

**Comment by henricryden** [comment]
The failed test is unrelated and [happens to other branches as well](https://github.com/bokeh/bokeh/actions/runs/22323105761)

**Comment by mattpap** [comment]
> The failed test is unrelated and [happens to other branches as well](https://github.com/bokeh/bokeh/actions/runs/22323105761)

Looks like a deprecation in mpmath 1.4, which is used by sympy in that example, causes this failure. We treat warnings, in particular deprecation warnings, as errors in our tests, but that really shouldn't apply to dependencies of our dependencies.

File: bokehjs/src/lib/models/glyphs/step.ts [hunk 1]
```diff
@@ -179,6 +182,113 @@ export class StepView extends XYGlyphView {
...
+  }
+
+  /**
+   * Convert a step between two data points into line segments.
+   * For "before" mode: vertical then horizontal.
+   * For "after" mode: horizontal then vertical.
+   * For "center" mode: horizontal to midpoint, vertical, then horizontal.
+   */
+  protected _get_step_segments(j: number, mode: StepMode): Array<[{x: number, y: number}, {x: number, y: number}]> {
+    const segments: Array<[{x: number, y: number}, {x: number, y: number}]> = []
```
Comment (mattpap) [inline bokehjs/src/lib/models/glyphs/step.ts]: It's more idiomatic to use `[]` for arrays:

```suggestion
  protected _get_step_segments(j: number, mode: StepMode): [{x: number, y: number}, {x: number, y: number}][] {
    const segments: [{x: number, y: number}, {x: number, y: number}][] = []
```
Given all this repetition, I would add a local type e.g.:
```ts
type XY = {x: number, y: number}
```
and then
```suggestion
  protected _get_step_segments(j: number, mode: StepMode): [XY, XY][] {
    const segments: [XY, XY][] = []
```

**Comment by mattpap** [comment]
Some integration regression tests are needed. Otherwise looks good.

File: bokehjs/src/lib/models/glyphs/step.ts (hunk 1 above)
Comment (henricryden) [reply bokehjs/src/lib/models/glyphs/step.ts]: Thanks, implemented

File: bokehjs/test/integration/tools/hover_tool.ts [hunk 2]
```diff
@@ -90,4 +90,27 @@ describe("HoverTool", () => {
...
+        ["x", "@x{0.00}"],
+        ["y", "@y{0.00}"],
+      ],
+      renderers: [r1, r2, r3],
+      mode: "vline",
+    })
+    p.add_tools(hover)
+    const {view} = await display(p)
+    await actions(view).hover(xy(1, 1))
+  })
```
Comment (mattpap) [inline bokehjs/test/integration/tools/hover_tool.ts:116]: I think this will need the following for completeness, especially if you are noticing robustness issues:
```suggestion
    await actions(view).hover(xy(1, 1))
    await view.ready
  })
```

Comment (henricryden) [reply bokehjs/test/integration/tools/hover_tool.ts:116]: Ok, you know best :)

**Review by mattpap — APPROVED** [review]
Preemptively approving this PR.

**Comment by mattpap** [comment]
@henricryden, thanks.
