### PR TITLE
no hover upon bbox change

### LINKED ISSUE #14549: Updating Div text from hover causes infinite loop
### Software versions

Python version        :  3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:50:30) [MSC v.1933 64 bit (AMD64)]
IPython version       :  (not installed)
Tornado version       :  6.4.2
NumPy version         :  2.2.0
Bokeh version         :  3.8.0.dev2
node.js version       :  v22.15.0
npm version           :  10.9.2
jupyter_bokeh version :  (not installed)
Operating system      :  Windows-10-10.0.26100-SP0

### Browser name and version

_No response_

### Jupyter notebook / Jupyter Lab version

_No response_

### Expected behavior

The Div text should be updated according to the current hover value.

### Observed behavior

The Div text is only updated once and gets stuck in infinite loop afterwards.
Note: This is only the case if no width is provided for the Div.

### Example code

```Python
import numpy as np
from bokeh.io import curdoc
from bokeh.layouts import gridplot, column, row
from bokeh.models import ColumnDataSource, HoverTool, CustomJS, CrosshairTool, Span, CDSView, IndexFilter, Div, \
    TabPanel, Tabs
from bokeh.plotting import figure, save

n_samples = 1000
x = np.linspace(0, 1000, n_samples)
y = np.random.rand(n_samples)

source = ColumnDataSource({"x": x, "y": y})

vline_span = Span(dimension="height", line_dash="solid", line_width=1, level="overlay")
TOOLS = [CrosshairTool(overlay=vline_span)]
p1 = figure(height=300, width=1000, tools=TOOLS, sizing_mode="stretch_both")
r_line = p1.line(x="x", y="y", source=source)

div_value = Div() # works with fixed width

hover_js_cb_code = '''
let idx = []
if (typeof cb_data.index !== 'undefined') {
    idx = cb_data.index.line_indices
}

const _y = src.data['y'][idx]

const y = new Intl.NumberFormat('en-IN', {
  minimumFractionDigits: 1,
  maximumFractionDigits: 2
}).format(_y)

div.text = `<p style="font-size:150%;">${y}<p>`

'''

callback = CustomJS(
    args={
        'div': div_value,
        'src': source,
    },
    code=hover_js_cb_code
)

hover_line = HoverTool(
    renderers=[r_line],
    mode="vline",
    tooltips=None,
)
hover_line.callback = callback
p1.add_tools(hover_line)

layout = column(row(div_value, p1, sizing_mode="stretch_both"), sizing_mode="stretch_both")

curdoc().add_root(layout)
```

### Stack traceback or browser console output

_No response_

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by muendlein**
- [x] issues: fixes #14549
- [x] tests added / passed

### CODE REVIEW

**Comment by muendlein** [comment]
~~Not sure how to test this properly.~~

File: bokehjs/test/integration/regressions.ts [hunk 1]
```diff
@@ -4699,4 +4699,68 @@ describe("Bug", () => {
...
     })
   })
+
+  describe("in issue #14549", () => {
+    it("doesn't prevent hover action upon bbox change", async () => {
+      function linspace(start: number, stop: number, num: number, endpoint = true) {
+        const div = endpoint ? (num - 1) : num
+        const step = (stop - start) / div
+        return Array.from({length: num}, (_, i) => start + step * i)
+      }
```
Comment (mattpap) [inline bokehjs/test/integration/regressions.ts]: There's `linspace()` in `core/util/array.ts`. Maybe it needs some changes though?

File: bokehjs/test/integration/regressions.ts [hunk 2]
```diff
@@ -4699,4 +4699,68 @@ describe("Bug", () => {
...
+
+      const div = new Div({text: "some text"})
+      const source = new ColumnDataSource({data: {x, y}})
+
+      function hover_cb(_model: HoverTool, options: any) {
+        const {index} = options
+        let idx = []
+        if (typeof index !== "undefined") {
+          idx = index.line_indices
+        }
```
Comment (mattpap) [inline bokehjs/test/integration/regressions.ts]:
```suggestion
        const idx = index?.line_indices ?? []
```

File: bokehjs/test/integration/regressions.ts [hunk 3]
```diff
@@ -4699,4 +4699,68 @@ describe("Bug", () => {
...
+
+        const _data: any = source.data
+        const _y = _data.x[idx]
```
Comment (mattpap) [inline bokehjs/test/integration/regressions.ts]: `idx` is of `number[]` type. You could use `subselect()` from `core/util/arrayable.ts`, to get an array of selected indices for formatting.

Comment (mattpap) [reply bokehjs/test/integration/regressions.ts]: You could also use `source.get_column<number>("y")` to avoid `_data: any`.

File: bokehjs/test/integration/regressions.ts [hunk 4]
```diff
@@ -4699,4 +4699,68 @@ describe("Bug", () => {
...
+      }
+
+      const n = 1000
+      const x = linspace(0, 20, n)
+      const y = x
+
+      const div = new Div({text: "some text"})
+      const source = new ColumnDataSource({data: {x, y}})
+
+      function hover_cb(_model: HoverTool, options: any) {
```
Comment (mattpap) [inline bokehjs/test/integration/regressions.ts]: `index` is always provided by the emitter:
```suggestion
      function hover_cb(_model: HoverTool, options: {index: Selection}) {
```

File: bokehjs/test/integration/regressions.ts (hunk 2 above)
Comment (mattpap) [reply bokehjs/test/integration/regressions.ts]: Given that `index` is always provided, this should actually be:

```suggestion
        const idx = index.line_indices
```

File: bokehjs/test/integration/regressions.ts (hunk 1 above)
Comment (muendlein) [reply bokehjs/test/integration/regressions.ts]: no changes need at first glance

**Review by mattpap — APPROVED** [review]
