### PR TITLE
Modifying a HoverTool tooltip leads to errors if the new tooltip list is bigger.

### LINKED ISSUE #10559: [BUG] Modifying a tooltip may result in errors
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
bokeh 2.2.1

#### Description of expected behavior and the observed behavior
Creating a tooltip with a list, then modifying the tooltip with a greater list size will lead to errors. This is because the bokehjs `_template_el` internal field is not updated when the tooltip is.

#### Complete, minimal, self-contained example code that reproduces the issue
I've corrected this, added a bokehjs test in  PR #10560

### PR DESCRIPTION
**Pull request by poldavezac**
All pull requests must have an associated issue in the issue tracker. If there
isn't one, please go open an issue describing the defect, deficiency or desired
feature. You can read more about our issue and PR processes in the
[wiki](https://github.com/bokeh/bokeh/wiki/BEP-1:-Issues-and-PRs-management).

- [x] issues: fixes  #10559
- [x] tests added / passed
- [ ] release document entry (if new feature or API change)

### CODE REVIEW

File: bokehjs/src/lib/models/tools/inspectors/hover_tool.ts [hunk 1]
```diff
@@ -70,7 +70,12 @@ export class HoverToolView extends InspectToolView {
 
   initialize(): void {
     super.initialize()
+    this._clear_ttfields()
+  }
+
+  protected  _clear_ttfields(): void {
     this._ttmodels = null
+    delete this._template_el
     this._ttviews = new Map()
```
Comment (mattpap) [inline bokehjs/src/lib/models/tools/inspectors/hover_tool.ts:79]: `_ttviews` must not be reinitialized, otherwise `build_views()` on line 127 will fail to do a clean up.

Comment (mattpap) [reply bokehjs/src/lib/models/tools/inspectors/hover_tool.ts:79]: For the sake of consistency change the type of `_template_el` to `| null` (instead of `?`) and use `null`.

File: bokehjs/test/unit/models/tools/inspectors/hover_tool.ts [hunk 2]
```diff
@@ -0,0 +1,75 @@
...
+
+  const glyph_renderer = new GlyphRenderer({glyph, data_source})
+  const glyph_renderer_view = await build_view(glyph_renderer, {parent: plot_view})
+
+  const hover_tool = new HoverTool({
+    active: true,
+    renderers: [glyph_renderer as any],
+  })
+  plot.add_tools(hover_tool)
+  await plot_view.ready
```
Comment (mattpap) [inline bokehjs/test/unit/models/tools/inspectors/hover_tool.ts:42]: Construct everything before `build_view()`, otherwise you're introducing unnecessary complexity and slowdown.

File: bokehjs/test/unit/models/tools/inspectors/hover_tool.ts [hunk 3]
```diff
@@ -0,0 +1,75 @@
...
+    x: {field: "x"},
+    y: {field: "y"},
+  })
+
+  const glyph_renderer = new GlyphRenderer({glyph, data_source})
+  const glyph_renderer_view = await build_view(glyph_renderer, {parent: plot_view})
+
+  const hover_tool = new HoverTool({
+    active: true,
+    renderers: [glyph_renderer as any],
```
Comment (mattpap) [inline bokehjs/test/unit/models/tools/inspectors/hover_tool.ts:39]: Don not use `any` type. If there's a type checking issue (there shouldn't be), leave this without a cast for us to figure this out.

File: bokehjs/test/unit/models/tools/inspectors/hover_tool.ts [hunk 4]
```diff
@@ -0,0 +1,75 @@
...
+
+async function make_testcase(): Promise<HoverToolTestCase> {
+  const plot = new Plot({
+    x_range: new Range1d({start: -1, end: 1}),
+    y_range: new Range1d({start: -1, end: 1}),
+  })
+
+  const plot_view = (await build_view(plot)).build()
+
+  const data = {x: [0, 0.5, 1], y: [0, 0.5, 1], z: [null, null, null]}
```
Comment (mattpap) [inline bokehjs/test/unit/models/tools/inspectors/hover_tool.ts:26]: Is `z` needed for anything? If no, remove it.

File: bokehjs/test/unit/models/tools/inspectors/hover_tool.ts [hunk 5]
```diff
@@ -0,0 +1,75 @@
...
+  }
+}
+
+describe("Hover Tool", () => {
+
+  describe("View", () => {
+
+    it("should update internals when changing the tooltips", async () => {
+      const testcase = await make_testcase()
+      testcase.hover_tool_view.initialize()
```
Comment (mattpap) [inline bokehjs/test/unit/models/tools/inspectors/hover_tool.ts:60]: `initialize()` is called by `build_view()` and you shouldn't call it on your own for any reasons.

File: bokehjs/test/unit/models/tools/inspectors/hover_tool.ts [hunk 6]
```diff
@@ -0,0 +1,75 @@
...
+import {Range1d} from "@bokehjs/models/ranges/range1d"
+
+import {HoverTool, HoverToolView} from "@bokehjs/models/tools/inspectors/hover_tool"
+
+export interface HoverToolTestCase {
+  data: {[key: string]: (number | null)[]}
+  data_source: ColumnDataSource
+  hover_tool_view: HoverToolView
+  glyph_view: CircleView
+}
```
Comment (mattpap) [inline bokehjs/test/unit/models/tools/inspectors/hover_tool.ts:16]: All this is unnecessary as you don't use anything expect `hover_tool_view`.

File: bokehjs/test/unit/models/tools/inspectors/hover_tool.ts [hunk 7]
```diff
@@ -0,0 +1,75 @@
...
+    it("should update internals when changing the tooltips", async () => {
+      const testcase = await make_testcase()
+      testcase.hover_tool_view.initialize()
+      let el        = (testcase.hover_tool_view as any)._template_el as HTMLElement
+      let value_els = el.querySelectorAll<HTMLElement>("[data-value]")
+      expect(value_els.length).to.be.equal(3)
+
+      testcase.hover_tool_view.model.tooltips = [["toto", "$x"]]
+      el        = (testcase.hover_tool_view as any)._template_el as HTMLElement
+      value_els = el.querySelectorAll<HTMLElement>("[data-value]")
```
Comment (mattpap) [inline bokehjs/test/unit/models/tools/inspectors/hover_tool.ts:67]: Don't reuse variables. Prefer `const` and enumerated names or split this test case into three.

Comment (mattpap) [reply bokehjs/test/unit/models/tools/inspectors/hover_tool.ts:67]: This indentation is unnecessary.

Comment (mattpap) [reply bokehjs/test/unit/models/tools/inspectors/hover_tool.ts:67]: We will also need to figure out how to test this without accessing protected/private members and performing `as any` casts. I know there are plenty of unit tests like this in our codebase, but that's an unfortunate historical artifact.

File: bokehjs/test/unit/models/tools/inspectors/hover_tool.ts [hunk 8]
```diff
@@ -0,0 +1,75 @@
...
+      expect(value_els.length).to.be.equal(1)
+
+      testcase.hover_tool_view.model.tooltips = "toto is $x"
```
Comment (mattpap) [inline bokehjs/test/unit/models/tools/inspectors/hover_tool.ts:70]: After each such change (that may trigger deferred callbacks) you have to use `await hover_tool_view.ready`

File: bokehjs/test/unit/models/tools/inspectors/hover_tool.ts (hunk 7 above)
Comment (poldavezac) [reply bokehjs/test/unit/models/tools/inspectors/hover_tool.ts:58]: Unfortunately almost all the code in the tool is protected. I'm not sure how to proceed without refactoring extensively, something I'm not comfortable with as I'm largely a python coder. 

The simpler solution would be to make one of the methods public. For example `_render_template` seems not to mutate the instance. would that be acceptable ?

 Another option could be to extract the code from `_update` which creates the tooltips without adding them to the html.
