### PR TITLE
fix promblems with render pause/unpause

### LINKED ISSUE #6328: GMap in Notebook unreliable again
I believe (but have not yet confirmed) that this happened in the `0.12.6dev2` to `dev3` time frame, which would possibly implicate the big layout PR. 

Behavior is for plot areas to render solid grey on the first `show` but often render correctly after a save and reload of the notebook. No out of the ordingary JS console messages or errors. 

ping @mattpap

### PR DESCRIPTION
**Pull request by bryevdv**
issues: fixes #6328

This fixes issues with `pause` and `unpause`. These functions were being called in the `PlotCanvasView` initializer, but *not* in the subclass `GMapPlotView` initializer. This could result in calls to `request_render` too early.  Specifically wrt to gmaps, this could cause `_build_map` to be called before the plot was otherwise initialized and ready to render, which in turn results in a blank gmap. 

To fix pause/unpause for now, needed to change from simple boolean to a condition counter to keep track of "pause level", so that on pause/unpause pair nested in side another (via a function call, say) would be handled correctly. Additionally, put an explicit guard in `render` itself to prevent any renders during a pause regardless of how they were triggered. I don't think this is strictly necessary, but seems like a reasonable preventative measure. 

With this change I am unable to reproduce any issues with gmaps inside or outside of notebooks, with either inline or server resources. 

I also fixed a problem with zoom range updates that could lead to unbalanced pause/unpause.

### CODE REVIEW

**Comment by bryevdv** [comment]
@mattpap I expect some day you will have a different but more robust solution but this seems like the conservative correct path for now.

File: bokehjs/src/coffee/models/plots/gmap_plot_canvas.coffee [hunk 1]
```diff
@@ -47,14 +52,15 @@ export class GMapPlotCanvasView extends PlotCanvasView
...
-      @pause()
 
       # The zoom count decreases the sensitivity of the zoom. (We could make this user configurable)
       if @zoom_count != 10
         @zoom_count += 1
         return
       @zoom_count = 0
 
+      @pause()
+
```
Comment (bryevdv) [inline bokehjs/src/coffee/models/plots/gmap_plot_canvas.coffee]: early return above could leave pause/unpause unbalance, moved after zoom count check

File: bokehjs/src/coffee/models/plots/gmap_plot_canvas.coffee [hunk 2]
```diff
@@ -17,7 +17,10 @@ load_google_api = (api_key) ->
 export class GMapPlotCanvasView extends PlotCanvasView
 
   initialize: (options) ->
+    @pause()
+
```
Comment (bryevdv) [inline bokehjs/src/coffee/models/plots/gmap_plot_canvas.coffee]: pause immediately, before anything else, in all canvas view initializers

File: bokehjs/src/coffee/models/plots/plot_canvas.coffee [hunk 3]
```diff
@@ -42,17 +42,21 @@ export class PlotCanvasView extends DOMView
...
+      @is_paused += 1
 
   unpause: (immediate=false) ->
-    @is_paused = false
-    if immediate
-      @render()
-    else
-      @request_render()
+    @is_paused -= 1
+    if @is_paused == 0
```
Comment (mattpap) [inline bokehjs/src/coffee/models/plots/plot_canvas.coffee]: Is there a realistic possibility for calling `unpause()` more often than `pause()`? If so, this code won't catch that. Also, later on you use a non-strict condition, which could indicate such possibility. I would keep all conditions in line, so either use `<= 0` for unpaused and `> 0` for paused, or `== 0` for unpaused and `!= 0` for paused. Also, I would rename `@is_paused` to something else and private, and use `@is_paused` for a getter, so that you don't have to repeat the condition multiple times later.

**Comment by mattpap** [comment]
I had a similar code floating around in earlier layout work, but didn't see a real need for it at the time.

File: bokehjs/src/coffee/models/plots/plot_canvas.coffee (hunk 3 above)
Comment (bryevdv) [inline bokehjs/src/coffee/models/plots/plot_canvas.coffee]: sounds reasonable I will do that and add tests as well

**Comment by bryevdv** [comment]
@mattpap I made the requested changes
