### PR TITLE
Adjust hidpi on browser zoom

### LINKED ISSUE #4345: When using the browser zoom the plot content becomes blurry
To reproduce:
* Show a plot
* Use in with browser -> line and text is blurry
* Resize plot (triggers recalculation of pixel ratio) -> text is crisp again

~~Will fix this while I'm dealing with a related issue with WebGL blurriness (#4293).~~

### LINKED ISSUE #4367: webgl issue on new layout with multiple plots - some plots are blank.
See the following two screengrabs, the only difference between them is the use of webgl=True.

Here is code to reproduce.

```python
import numpy as np

from bokeh.plotting import figure, show, output_file
from bokeh.models import GridPlot, ToolbarBox, Column, Row
output_file("color_scatter.html", title="color_scatter.py example")

N = 400
x = np.random.random(size=N) * 100
y = np.random.random(size=N) * 100
radii = np.random.random(size=N) * 1.5
colors = ["#%02x%02x%02x" % (int(r), int(g), 150) for r, g in zip(50 + 2 * x, 30 + 2 * y)]

TOOLS = "crosshair,pan,wheel_zoom,box_zoom,undo,redo,reset,tap,save,box_select,poly_select,lasso_select"

def p():
    p = figure(tools=TOOLS, webgl=True)
    p.scatter(x, y, radius=radii, fill_color=colors, fill_alpha=0.6, line_color=None)
    return p

layout = GridPlot(
    children=[
        [p(), p(), p(), p()],
        [p(), p(), p(), p()],
        [p(), p(), p(), p()],
        [p(), p(), p(), p()],
    ],
    toolbar_location='above',
    responsive='box'
)

show(layout)
```
The same issue exists for a smaller grid of say just 4 plots.

`webgl=True`
==========

screen shot 2016-05-25 at 11 15 43 am

`webgl=False`
==========

screen shot 2016-05-25 at 11 16 04 am

### PR DESCRIPTION
**Pull request by almarklein**
Supersedes #4378. Fixes #4345 and fixes #4367.

This makes the hidpi pixel ratio adapt when the browser zoom changes. This turned out to be easier than the original PR that I made against master earlier (#4346), because we already get an update now when the browser zoom changes.

I tested that all the HIDPI stuff works in embedded plots as well. This means that the document does an update when it gets a `window.resize` event, regardless whether the size did not actually change, and regardless whether the plot is embedded or not. In case someone ever tries to add efficiency here, please keep in mind this use-case.

### CODE REVIEW

File: bokehjs/src/coffee/models/plots/plot_canvas.coffee [hunk 1]
```diff
@@ -402,7 +402,12 @@ class PlotCanvasView extends Renderer.View
     # reach the frame in time (sometimes) so force an update here for now
     @model.get('frame')._update_mappers()
 
+    # Get context and restore to its initial state. The restoring
+    # Would stricly speaking not be necessary, but in case there is an error
+    # during drawing, restore() won't be called enough. This guards for that.
     ctx = @canvas_view.ctx
+    for i in [0..3]
+      ctx.restore()
```
Comment (bryevdv) [inline bokehjs/src/coffee/models/plots/plot_canvas.coffee]: I'm a little confused by this, can you elaborate more? This seems like it will unconditionally restore, regardless of whether there was an error or not. If not, in which case it will unexpectedly blow away any context `push` states? Or are you assuming / relying on the context state to otherwise be "zeroed" before getting to the code that might error out?

Comment (almarklein) [inline bokehjs/src/coffee/models/plots/plot_canvas.coffee]: The idea is that this will ensure that the context's state stack is empty. So that we have control (in each iteration) of the exact transformations, even if there where errors in the last draw iteration.

The reason that we now do the `scale(ratio, ratio)` into the draw iteration instead of only when the canvas is resized, it because when blitting the WebGL canvas, we need an unscaled canvas (this was causing the blurring). However, doing the scaling on each iteration introduced this vulnerability of blowing everything up when there is an error during the draw iteration. This fixes that vulnerability.

Comment (bryevdv) [inline bokehjs/src/coffee/models/plots/plot_canvas.coffee]: I understand the idea,  my question is this: how are we assured that previous intentional ctx `save` operations that might have happened prior to / outside this area of code aren't blown away. Let's say that code that calls this render does a `ctx.save`, and then calls this render, and there are no errors. Then this code calls `ctx.restore` three times, unconditionally? I don't see how that earlier `ctx.save` does not get blown away, even though it should not be.

Comment (bryevdv) [inline bokehjs/src/coffee/models/plots/plot_canvas.coffee]: If there are errors, do they raise exceptions? Then `try` / `catch` would seem to be a better option to keep `save` / `restore` pairs happening "in the same place"

Comment (almarklein) [inline bokehjs/src/coffee/models/plots/plot_canvas.coffee]: Right. Now I understand your concern. However, I think there has always been an implicit assumption that `plot.render()` was the "rendering entry point" and that there were no calls to `save()` before it, because `plot.render()` calls `@canvas_view.prepare_canvas()` (previously `@view_canvas.render()`) which may resize the canvas. And when a canvas is resized, the state of a context is reset. So we probably should add a comment about this assumption.

An alternative might be to always set the size of the canvas in `@canvas_view.prepare_canvas()` but I read somewhere that this might be unreliable in some browsers if the size is not changed. This silly for-loop is my version of `ctx.reset()`. I agree it does not look pretty, but it seemed the easiest way to get the job done, without having to change any other code.

Using `try` / `catch` could work, though I don't know what that would do to tracebacks, since there is no `finally` (right?).

Comment (bryevdv) [inline bokehjs/src/coffee/models/plots/plot_canvas.coffee]: AFAIK JS does support `finally`: http://www.w3schools.com/jsref/jsref_try_catch.asp So that would be my suggestion to try

**Comment by almarklein** [comment]
Fair enough. `try-finally`'s added.

**Comment by bryevdv** [comment]
OK, well this could be better, but is it really the case that all the places you added `try` blocks can fail? My assumption was that it was only webgl related paths that might have issues, and so we'd only need `try` blocks selectively around those areas. For instance, can the `Grid` render fail in the presence of webgl? If not, it already lines up `save`/`restore`

**Comment by almarklein** [comment]
I think probably most glyphs can potentially fail during rendering. This lining up of `save` and `restore` is not a WebGL specific issue. Though it's always hard to tell when JS fails with an error or breaks something and continues ...

Personally, I prefer the "reset" approach over all these try-finallies, for one because it also works in case of any new glyphs being added that might do `ctx.save()`. Though a better place for the "reset" would be the `prepare_canvas()` method (which already does a reset in case it resizes the canvas).

**Comment by bryevdv** [comment]
I've never once encountered an HTML5 canvas rendering operation fail. That's why I assumed it was webgl specific. Is there some what to reproduce or demonstrate the failure condition?

**Comment by almarklein** [comment]
Maybe I am just overly careful, but the plot blowing up looks really bad. It could well be that all `ctx` methods are safe, but there might be an error somewhere *during* the drawing algorithm, like trying to access an attribute of a nonexisting atribute. I tested by just adding `throw "foo"` in a render method.

**Comment by bryevdv** [comment]
OK I'm still not sure I understand the concern. Things like undefined attribute access are *bugs in our code* and we need to fix them, not paper over them. If that's the intent of this, I am -1 on it. I had thought there was something intrinsically unstable about webgl on some platforms that we simply had no better way to protect against at all. Since this particular aspect requires more discussion, I'd suggest this: a AP that *only* has the basic webgl fixes/improvements, and a separate issue to discuss when or where this sort of exception handling is appropriate.

**Comment by almarklein** [comment]
Ok, got rid of the context reset stuff and the try-finallies. Will create an issue to explain my case more clearly when this has merged.
