### PR TITLE
Make GMapPlotCanvas work in strict mode

### LINKED ISSUE #8733: GMap plots not working in the notebook and INLINE resources
The following code: 
```
from bokeh.io import output_notebook, show
from bokeh.models import GMapOptions
from bokeh.plotting import gmap
from bokeh.models import Label

output_notebook()

map_options = GMapOptions(lat=30.2861, lng=-97.7394, map_type="roadmap", zoom=13)

# replace with your google api key
p = gmap("API-KEY", map_options)

show(p)
```
Generates no output, and the following console error:

> ReferenceError: Can't find variable: _bokeh_gmaps_callback

This is on master but evidently at least on 1.0.4 as well

### PR DESCRIPTION
**Pull request by mattpap**
fixes #8733

### CODE REVIEW

File: bokehjs/src/lib/models/plots/gmap_plot_canvas.ts [hunk 1]
```diff
@@ -4,12 +4,16 @@ import {Context2d} from "core/util/canvas"
...
+  interface Window {
+    _bokeh_gmaps_callback: () => void
+  }
+}
 
 const gmaps_ready = new Signal0({}, "gmaps_ready")
 
 const load_google_api = function(api_key: string): void {
-  _bokeh_gmaps_callback = () => gmaps_ready.emit()
+  window._bokeh_gmaps_callback = () => gmaps_ready.emit()
```
Comment (mattpap) [inline bokehjs/src/lib/models/plots/gmap_plot_canvas.ts]: In strict mode naked (no `var`, `let`, `const` keyword) variables aren't allowed, resulting in `ReferenceError` exception. It's interesting why it started to fail just now, because this code was changed during transition to TypeScript which was like a year ago. Or maybe it was broken all along, just we didn't test this scenario.
