### PR TITLE
Protect against `document == null` in `_doc_detached()`

### LINKED ISSUE #14429: Replacing Plot in a layout fails due to detached Document
### Software versions

Bokeh: 3.7.0

### Browser name and version

_No response_

### Jupyter notebook / Jupyter Lab version

_No response_

### Expected behavior

I would expect the plot to be successfully replaced when updating a layout with a new Plot instance.

### Observed behavior

There is a JS error indicating that the `Document` on the replaced plot is set to null before `_doc_detached` is called.

### Example code

```Python
from bokeh.io import curdoc
from bokeh.layouts import column
from bokeh.plotting import figure
from bokeh.models import Button
import numpy as np

# Function to create a new plot
def create_plot():
    x = np.random.rand(10)
    y = np.random.rand(10)
    p = figure(width=400, height=400, title="Random Scatter Plot")
    p.circle(x, y, size=10, color="navy", alpha=0.6)
    return p

# Initial plot
plot = create_plot()

# Button to replace plot
button = Button(label="Replace Plot")

def update_plot():
    global plot
    new_plot = create_plot()
    layout.children[0] = new_plot  # Replace the plot in the layout

button.on_click(update_plot)

# Layout with initial plot and button
layout = column(plot, button)
curdoc().add_root(layout)
```

### Stack traceback or browser console output

```
Uncaught TypeError: Cannot read properties of null (reading 'event_manager')
    at u._doc_detached (bokeh.min.js?v=37028e125f65b3ece3d226d12ab3217aa654647f369078853d68b04333717df92e9d537a280a4b2b34cb46c66bf0d562ad964d384cb9f3419ceeffb6aa2d8d43:217:1712)
    at u.detach_document (bokeh.min.js?v=37028e125f65b3ece3d226d12ab3217aa654647f369078853d68b04333717df92e9d537a280a4b2b34cb46c66bf0d562ad964d384cb9f3419ceeffb6aa2d8d43:181:7770)
    at M._recompute_all_models (bokeh.min.js?v=37028e125f65b3ece3d226d12ab3217aa654647f369078853d68b04333717df92e9d537a280a4b2b34cb46c66bf0d562ad964d384cb9f3419ceeffb6aa2d8d43:166:3477)
    at M._invalidate_all_models (bokeh.min.js?v=37028e125f65b3ece3d226d12ab3217aa654647f369078853d68b04333717df92e9d537a280a4b2b34cb46c66bf0d562ad964d384cb9f3419ceeffb6aa2d8d43:166:3217)
    at O.setv (bokeh.min.js?v=37028e125f65b3ece3d226d12ab3217aa654647f369078853d68b04333717df92e9d537a280a4b2b34cb46c66bf0d562ad964d384cb9f3419ceeffb6aa2d8d43:181:6525)
    at O.set [as inspectors] (bokeh.min.js?v=37028e125f65b3ece3d226d12ab3217aa654647f369078853d68b04333717df92e9d537a280a4b2b34cb46c66bf0d562ad964d384cb9f3419ceeffb6aa2d8d43:181:1168)
    at O._init_tools (bokeh.min.js?v=37028e125f65b3ece3d226d12ab3217aa654647f369078853d68b04333717df92e9d537a280a4b2b34cb46c66bf0d562ad964d384cb9f3419ceeffb6aa2d8d43:467:6650)
    at O.initialize (bokeh.min.js?v=37028e125f65b3ece3d226d12ab3217aa654647f369078853d68b04333717df92e9d537a280a4b2b34cb46c66bf0d562ad964d384cb9f3419ceeffb6aa2d8d43:467:6446)
    at O.finalize (bokeh.min.js?v=37028e125f65b3ece3d226d12ab3217aa654647f369078853d68b04333717df92e9d537a280a4b2b34cb46c66bf0d562ad964d384cb9f3419ceeffb6aa2d8d43:181:4936)
    at p.decode (bokeh.min.js?v=37028e125f65b3ece3d226d12ab3217aa654647f369078853d68b04333717df92e9d537a280a4b2b34cb46c66bf0d562ad964d384cb9f3419ceeffb6aa2d8d43:213:765)
```

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by mattpap**
For now this work around the problem, but I will need to investigate why we detach a detached model in the first place.

fixes #14429

### CODE REVIEW

**Comment by philippjfr** [comment]
Seems high priority, can we backport to 3.7.1 and release relatively soon?

**Comment by bryevdv** [comment]
We can definitely have a 3.7.1 ASAP. If theres any handful of other tiny fix that can go in ~immediately, then that would be nice, but if not there's no reason to hold this up. Let's shoot for Monday at the latest? If any sort of test is possible that would be nice to have in place before a more in-depth follow-up.

**Comment by mattpap** [comment]
The underlying problem was that updating a figure means `setv()` in `Toolbar._init_tools()`, which triggers recomputation of all models. This happens during application of a patch, which interferes badly with the new partial eventual consistency of `Document.all_models`. Thus I finished the transition to full eventual consistency, which completes work started in 3.7. This way, adding new models will result in them being added to `all_models` and `attach_document()` called for all of them. However, removing models results in a deferred cleanup and calls to `detach_document()`. I need to update units tests, because there are a few that assume strong consistency when removing models.

File: bokehjs/src/lib/document/document.ts [hunk 1]
```diff
@@ -242,15 +250,30 @@ export class Document implements Equatable {
...
-  /*protected*/ _invalidate_all_models(): void {
-    logger.debug("invalidating document models")
-    // if freeze count is > 0, we'll recompute on unfreeze
-    if (this._all_models_freeze_count === 0) {
+  protected _recompute_timer: number | null = null
+
+  protected _cancel_recompute_all_models(): void {
+    if (this._recompute_timer != null) {
+      clearTimeout(this._recompute_timer)
+      this._recompute_timer = null
```
Comment (hoxbro) [inline bokehjs/src/lib/document/document.ts:258]: Could this lead to a raise condition? If `_cancel_recompute_all_models` is called multiple times before `clearTimeout` is finished?

File: bokehjs/src/lib/document/document.ts [hunk 2]
```diff
@@ -545,8 +581,17 @@ export class Document implements Equatable {
...
-    this._hold_models_freeze = true // try ... finally
+    const {_hold_models_freeze} = this
+    this._hold_models_freeze = true
+    try {
+      this._apply_json_patch(patch, buffers)
+    } finally {
+      this._hold_models_freeze = _hold_models_freeze
+    }
+    this._schedule_recompute_all_models()
+  }
```
Comment (hoxbro) [inline bokehjs/src/lib/document/document.ts:592]: Could this cause a raise condition?

**Review by hoxbro — COMMENTED** [review]
Left some comments. I'm unfamiliar with this code, so they may be a bit naive.

**Comment by bryevdv** [comment]
@mattpap what about putting the quick defensive "fix" in 3.7.1 and saving these more involved changes for 3.8?

File: bokehjs/src/lib/document/document.ts (hunk 1 above)
Comment (bryevdv) [reply bokehjs/src/lib/document/document.ts:258]: AFAIK calling `clearTimeout` multiple times for the same ID is just a no-op

File: bokehjs/src/lib/document/document.ts [hunk 3]
```diff
@@ -119,6 +126,7 @@ export class Document implements Equatable {
     this._idle_roots = new WeakSet()
     this._interactive_timestamp = null
     this._interactive_plot = null
+    this._recompute_timeout = options.recompute_timeout ?? 30_000 /* 30s */
```
Comment (bryevdv) [inline bokehjs/src/lib/document/document.ts:129]: I'm trying to understand where this number comes from, and what it translates to in terms of user experience. Does this imply there could be situations where things don't "settle" for half a minute?

Comment (mattpap) [reply bokehjs/src/lib/document/document.ts:129]: This effectively means that removed models won't be detached from the the document for 30s. Since changes introduced in 3.7, they wouldn't be detached at all in some scenarios. With the new approach, all new models will be attached immediately and then a full consistent state will be achieved after the timeout. This gives us ultimate performance and eventual consistency.

Comment (bryevdv) [reply bokehjs/src/lib/document/document.ts:129]: OK I had missed that this timeout mostly (only?) applies to removals. That seems more reasonable if so

**Review by bryevdv — APPROVED** [review]
I'll approve but I do think some quick manual testing of most/all the app examples is in order if that hasn't already been done. Also would good to know if this is the fix for https://discourse.bokeh.org/t/dynamically-create-tabs-with-figures-in-them/12368/2

**Comment by mattpap** [comment]
> what about putting the quick defensive "fix" in 3.7.1 and saving these more involved changes for 3.8?

That was my original goal. However, after spending time debugging the root cause, I can clearly see it's a mess what happens when a patch arrives that causes `setv()` during handling of the patch (e.g. document trying to detach freshly arrived models). Thus I think things could fail anyway in some other way, even with the workaround. This change effectively completes what was started in 3.7. I think the biggest mistake was to include those changes in 3.7 in the first place (incomplete and not well tested).

File: bokehjs/src/lib/document/document.ts (hunk 1 above)
Comment (mattpap) [reply bokehjs/src/lib/document/document.ts:258]: There is no async code involved where, so no. JavaScript will not stop execution mid a synchronous function.

File: bokehjs/src/lib/document/document.ts (hunk 2 above)
Comment (mattpap) [reply bokehjs/src/lib/document/document.ts:592]: I don't see any way. This is designed to allow multiple consecutive scheduling of recomputation of all models, by canceling the original task and rescheduling in another 30s. This way we allow consecutive updates to do expensive recomputation only one. Though there is a risk that for continuously updated state, this never happens, because it's constantly pushed back. I need to add a mechanism to force update once in a while.

**Comment by mattpap** [comment]
> https://discourse.bokeh.org/t/dynamically-create-tabs-with-figures-in-them/12368/2

I didn't verify this, but it clearly looks like it's the same problem.

File: bokehjs/src/lib/document/document.ts (hunk 3 above)
Comment (mattpap) [reply bokehjs/src/lib/document/document.ts:129]: Only removals, because additions are caught either during patch application or in `partially_update_all_models()`.

Comment (mattpap) [reply bokehjs/src/lib/document/document.ts:129]: The only situation I can image this wouldn't catch new models in `partially_update_all_models()` if a mutable value in an unrelated property was changed simultaneously with the property under change. Very unlikely and with the initial work around harmless until full state is recomputed.
