### PR TITLE
Handle empty files in FileInput and other fixes

### LINKED ISSUE #10887: [BUG] FileInput cancel operation throws error
**SUMMARY:** FileInput widget throws an error if the user cancels the input. NB: Requires a previously successfully executed file-input operation for error to manifest.

**VERSIONS:** Bokeh 2.2.3, Python 3.8.5, Mac OSX Big Sur

**Minimal Reproducible Example**

```
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
"""
from bokeh.models import FileInput
from bokeh.io import curdoc

def file_input_cb(attr, old, new):
    if new:
        print("INFO attr {:} old {:} new {:}".format(attr, old, new))

ui = FileInput(accept='.csv,.json.,.txt', multiple=False)
ui.on_change('value', file_input_cb)

curdoc().add_root(ui)

```

**STACK TRACE**

```
2021-02-03 10:07:00,217 Starting Bokeh server version 2.2.3 (running on Tornado 6.1)
2021-02-03 10:07:00,218 User authentication hooks NOT provided (default user enabled)
2021-02-03 10:07:00,220 Bokeh app running at: http://localhost:5006/file_inp
2021-02-03 10:07:00,220 Starting Bokeh server with process id: 49395
2021-02-03 10:07:28,470 WebSocket connection opened
2021-02-03 10:07:28,470 ServerConnection created
INFO attr value old  new TU5WUl9BCk1OVlJfQgpNTlZSX0MKTU5WUl9ECk1OVlJfRQpNTlZSX0YKTU5WUl9HCk1OVlJfSApNTlZSX0kKTU5WUl9KCk1OVlJfSwpNTlZSX0wKTU5WUl9NCk1OVlJfTgpNTlZSX08KTU5WUl9QCk1OVlJfUQpNTlZSX1IKTU5WUl9TCk1OVlJfVApNTlZSX1UKTU5WUl9WCk1OVlJfVwpNTlZSX1gKTU5WUl9ZCk1OVlJfWgo=
2021-02-03 10:07:47,776 error handling message
 message: Message 'PATCH-DOC' content: {'events': [{'kind': 'ModelChanged', 'model': {'id': '1001'}, 'attr': 'filename'}], 'references': []} 
 error: KeyError('new')
Traceback (most recent call last):
  File "/Users/x/opt/anaconda3/lib/python3.8/site-packages/bokeh/server/protocol_handler.py", line 90, in handle
    work = await handler(message, connection)
  File "/Users/x/opt/anaconda3/lib/python3.8/site-packages/bokeh/server/session.py", line 67, in _needs_document_lock_wrapper
    result = func(self, *args, **kwargs)
  File "/Users/x/opt/anaconda3/lib/python3.8/site-packages/bokeh/server/session.py", line 261, in _handle_patch
    message.apply_to_document(self.document, self)
  File "/Users/x/opt/anaconda3/lib/python3.8/site-packages/bokeh/protocol/messages/patch_doc.py", line 100, in apply_to_document
    doc._with_self_as_curdoc(lambda: doc.apply_json_patch(self.content, setter))
  File "/Users/x/opt/anaconda3/lib/python3.8/site-packages/bokeh/document/document.py", line 1169, in _with_self_as_curdoc
    return f()
  File "/Users/x/opt/anaconda3/lib/python3.8/site-packages/bokeh/protocol/messages/patch_doc.py", line 100, in <lambda>
    doc._with_self_as_curdoc(lambda: doc.apply_json_patch(self.content, setter))
  File "/Users/x/opt/anaconda3/lib/python3.8/site-packages/bokeh/document/document.py", line 409, in apply_json_patch
    value = event_json['new']
KeyError: 'new'
2021-02-03 10:07:47,779 error handling message
 message: Message 'PATCH-DOC' content: {'events': [{'kind': 'ModelChanged', 'model': {'id': '1001'}, 'attr': 'mime_type'}], 'references': []} 
 error: KeyError('new')
Traceback (most recent call last):
  File "/Users/x/opt/anaconda3/lib/python3.8/site-packages/bokeh/server/protocol_handler.py", line 90, in handle
    work = await handler(message, connection)
  File "/Users/x/opt/anaconda3/lib/python3.8/site-packages/bokeh/server/session.py", line 67, in _needs_document_lock_wrapper
    result = func(self, *args, **kwargs)
  File "/Users/x/opt/anaconda3/lib/python3.8/site-packages/bokeh/server/session.py", line 261, in _handle_patch
    message.apply_to_document(self.document, self)
  File "/Users/x/opt/anaconda3/lib/python3.8/site-packages/bokeh/protocol/messages/patch_doc.py", line 100, in apply_to_document
    doc._with_self_as_curdoc(lambda: doc.apply_json_patch(self.content, setter))
  File "/Users/x/opt/anaconda3/lib/python3.8/site-packages/bokeh/document/document.py", line 1169, in _with_self_as_curdoc
    return f()
  File "/Users/x/opt/anaconda3/lib/python3.8/site-packages/bokeh/protocol/messages/patch_doc.py", line 100, in <lambda>
    doc._with_self_as_curdoc(lambda: doc.apply_json_patch(self.content, setter))
  File "/Users/x/opt/anaconda3/lib/python3.8/site-packages/bokeh/document/document.py", line 409, in apply_json_patch
    value = event_json['new']
KeyError: 'new'
2021-02-03 10:07:47,780 error handling message
 message: Message 'PATCH-DOC' content: {'events': [{'kind': 'ModelChanged', 'model': {'id': '1001'}, 'attr': 'value'}], 'references': []} 
 error: KeyError('new')
Traceback (most recent call last):
  File "/Users/x/opt/anaconda3/lib/python3.8/site-packages/bokeh/server/protocol_handler.py", line 90, in handle
    work = await handler(message, connection)
  File "/Users/x/opt/anaconda3/lib/python3.8/site-packages/bokeh/server/session.py", line 67, in _needs_document_lock_wrapper
    result = func(self, *args, **kwargs)
  File "/Users/x/opt/anaconda3/lib/python3.8/site-packages/bokeh/server/session.py", line 261, in _handle_patch
    message.apply_to_document(self.document, self)
  File "/Users/x/opt/anaconda3/lib/python3.8/site-packages/bokeh/protocol/messages/patch_doc.py", line 100, in apply_to_document
    doc._with_self_as_curdoc(lambda: doc.apply_json_patch(self.content, setter))
  File "/Users/x/opt/anaconda3/lib/python3.8/site-packages/bokeh/document/document.py", line 1169, in _with_self_as_curdoc
    return f()
  File "/Users/x/opt/anaconda3/lib/python3.8/site-packages/bokeh/protocol/messages/patch_doc.py", line 100, in <lambda>
    doc._with_self_as_curdoc(lambda: doc.apply_json_patch(self.content, setter))
  File "/Users/x/opt/anaconda3/lib/python3.8/site-packages/bokeh/document/document.py", line 409, in apply_json_patch
    value = event_json['new']
KeyError: 'new'
```

### PR DESCRIPTION
**Pull request by mattpap**
fixes #10887

### CODE REVIEW

**Comment by bryevdv** [comment]
Suggest for a 2.3.1 release

File: bokehjs/src/lib/models/widgets/file_input.ts [hunk 1]
```diff
@@ -1,62 +1,65 @@
...
-      mime_type.push(mime)
+    const values: string[] = []
+    const filenames: string[] = []
+    const mime_types: string[] = []
+
+    for (const file of files) {
+      const data_url = await this._read_file(file)
+      const [, mime_type="",, value=""] = data_url.split(/[:;,]/, 4)
+
+      values.push(value)
```
Comment (mattpap) [inline bokehjs/src/lib/models/widgets/file_input.ts:46]: How much sense does it make to leave the value as base64 encoded? It would be good to change this, but that would be a solid backwards incompatible change.

Comment (bryevdv) [reply bokehjs/src/lib/models/widgets/file_input.ts:46]: I don't have a strong opinion except that if you want to change that, 3.0 is the place.

**Comment by bryevdv** [comment]
@mattpap do you object to landing this on `branch-2.3`? I would like to have a patch release in ~3 weeks

**Comment by mattpap** [comment]
Given the extent of changes, especially around testing, I would prefer this to be merged into 2.4 and backported.

File: bokehjs/src/lib/models/widgets/file_input.ts (hunk 1 above)
Comment (bryevdv) [reply bokehjs/src/lib/models/widgets/file_input.ts:46]: and to make an issue to track it and also so that we can telegraph it as an upcoming change

**Review by bryevdv — APPROVED** [review]
