### PR TITLE
Fix data_table sort performance

### LINKED ISSUE #14261: DataTable column sorting unacceptably slow
### Software versions

Python version        :  3.10.12 (main, Jan 17 2025, 14:35:34) [GCC 11.4.0]
IPython version       :  (not installed)
Tornado version       :  6.4.1
Bokeh version         :  3.5.1
BokehJS static path   :  /home/[...]/venv/lib/python3.10/site-packages/bokeh/server/static
node.js version       :  (not installed)
npm version           :  (not installed)
jupyter_bokeh version :  (not installed)
Operating system      :  Linux-6.8.0-51-generic-x86_64-with-glibc2.35

### Browser name and version

tested with Firefox 134.0.1 and Chromium 132.0.6834.83

### Jupyter notebook / Jupyter Lab version

_No response_

### Expected behavior

Using a `DataTable` with a dataset of 250,000 rows, sorting by a specific column via clicking the column name in the widget should take less than 5 seconds (less than a second IMHO).

### Observed behavior

Sorting takes several minutes. Here are some timings I did with my stopwatch:
25k rows take ~6 seconds
50k rows take ~27 seconds
75k rows take ~65 seconds
This is too slow, and probably something silly is happening which is only getting obvious when testing the widget for scalability.

### Example code

```Python
from bokeh.models import DataTable, ColumnDataSource, TableColumn
from bokeh.plotting import show
import numpy as np

if __name__ == '__main__':
    data = np.random.rand(6,250000)
    dataset = dict()
    for i in range(6):
        dataset[f"attr{i}"] = data[i,:]
    np.argsort(data[0,:])
    cds = ColumnDataSource(data=dataset)
    columns = [TableColumn(field=f"attr{i}", title=f"attr{i}") for i in range(6)]
    table = DataTable(source=cds, columns=columns)
    show(table)
```

### Stack traceback or browser console output

_No response_

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by bryevdv**
This PR removes unnecessary array scans in a tight inner loop that introduced quadratic runtime behavior for table sorts. 

- [x] issues: fixes #14261 
- [x] tests added / passed

Here is a chrome profile showing that a sort on the OP code with N=500000 now takes ~1s.

Screenshot 2025-01-28 at 21 11 18

I do actually wonder if `getRecords` could be improved, and also wonder why `sort` is called so many times for a single click. But I don't think it is worth investing much more effort until/unless we do an actual top-to-bottom evaluation of our slickgrid usage wrt to current best practices.

### Update

OK `argsort` is not quite the right solution here in general since in the presence of CDS views the indices may not be contiguous. I am beginning to see why I did things the way I did in 2017, even though I was surely aware of `argsort` at the time. However, I think constructing a manual reverse lookup will do just as well. @mattpap if there's any better typescript way to write this please let me know. I have gone ahead and left the `argsort` util since it is tiny and has tests and may be useful somewhere.

### CODE REVIEW

File: bokehjs/src/lib/core/util/array.ts [hunk 1]
```diff
@@ -150,6 +150,12 @@ export function argmax(array: number[]): number {
   return max_by(range(array.length), (i) => array[i])
 }
 
+export function argsort(array: number[]): number[] {
```
Comment (mattpap) [inline bokehjs/src/lib/core/util/array.ts:156]:
```suggestion
/**
 * Return the permutation indices for sorting an array.
 */
export function argsort(array: number[]): number[] {
```

File: bokehjs/src/lib/core/util/array.ts [hunk 2]
```diff
@@ -150,6 +150,12 @@ export function argmax(array: number[]): number {
...
+  const indices = Array.from(array.keys())
+  indices.sort((a, b) => array[a] - array[b])
```
Comment (mattpap) [inline bokehjs/src/lib/core/util/array.ts:158]: I think this may not be relevant anymore, but this doesn't produce a stable sort with certain underlying sorting algorithms. `sort_by()` considers the case when `array[a] == array[b]` and uses indices instead.

File: bokehjs/src/lib/models/widgets/tables/data_table.ts [hunk 3]
```diff
@@ -117,12 +117,15 @@ export class TableDataProvider implements DataProvider<Item> {
     }
 
     const records = this.getRecords()
-    const old_index = this.index.slice()
+
+    const lookup: { [key: number]: number} = {}
```
Comment (mattpap) [inline bokehjs/src/lib/models/widgets/tables/data_table.ts]:
```suggestion
    const lookup: {[key: number]: number} = {}
```

**Review by mattpap — APPROVED** [review]

**Comment by hageldave** [comment]
I'm not aware of the bokeh internals and where the argsort function is used, so this question may be irrelevant. But argsort only considers number arrays currently. Do you also allow sorting table columns of strings? And would it then not work because of `array[a] - array[b]`? So a more general comparator would be needed?

**Comment by bryevdv** [comment]
@hageldave It's not used at all currently. I added to use in this PR before realizing an explicit reverse-lookup was needed instead, due to the possibility of CDS views. But since it is very tiny and already includes tests, I decided to leave it in case its useful in the future to have a numeric argsort. If we were ever to need an argsort for more types we would need to generalize it, but no need to bother until a need is demonstrated.
