### PR TITLE
Avoid excessive rendering of toolbar panels

### LINKED ISSUE #10191: [BUG] Tools in toolbar flickering and occasionally ignores clicks when HoverTool and hover glyph used
## Software info
OS: Windows 10
Browser: Chrome 83.0.4103.97
Python: 3.8.3
Bokeh: 2.1.0 - also tested on 2.0.2

Initially reported at https://discourse.bokeh.org/t/toolbar-tools-difficult-to-toggle-when-hovertool-is-active/5790

## Issue
When plotting a circle while also supplying the renderer with a hover glyph, the HoverTool causes tools on the toolbar to flicker when hovering over them. This also occasionally results in my clicks not registering when clicking on a tool to toggle its state, which is the main burden.

A few things to note:
- This only happens if the HoverTool's renderers contains at least one GlyphRenderer with a hover glyph.
- I have also tested this with the Square and Line glyphs, and the issue is also present with those.
- I originally noticed this issue while working in a Django environment, but the issue also happens in standalone mode.

## Screen recording
In the screen recording below you can see the flickering, which stops as soon as I disable the HoverTool. The gif has a pretty low framerate, but on my screen it's much worse obviously.

0Tg4Et8GNm

## Code to reproduce the issue
```python
import numpy as np

from bokeh.plotting import figure, show
from bokeh.models import ColumnDataSource, HoverTool

x = np.random.randn(100)
y = np.random.randn(100)

data = dict(x=x, y=y)
source = ColumnDataSource(data=data)

p = figure(width=300, height=300)

r = p.circle(x='x', y='y', size=10, source=source, hover_fill_color='red')

h = HoverTool(renderers=[r])
p.add_tools(h)

show(p)
```

### PR DESCRIPTION
**Pull request by mattpap**
fixes #10191

### CODE REVIEW

File: bokehjs/src/lib/models/annotations/toolbar_panel.ts [hunk 1]
```diff
@@ -38,14 +41,26 @@ export class ToolbarPanelView extends AnnotationView {
...
+      this._previous_bbox = bbox
+    }
+
+    if (this._invalidate_toolbar) {
+      this.el.style.position = "absolute"
+      this.el.style.overflow = "hidden"
+      this._toolbar_view.render()
+      empty(this.el)
+      this.el.appendChild(this._toolbar_view.el)
+      this._invalidate_toolbar = false
```
Comment (bryevdv) [inline bokehjs/src/lib/models/annotations/toolbar_panel.ts:61]: is `_invalidate_toolbar` only signaling the first render, or are there circumstances that could cause it to become true again?
