### PR TITLE
Fix incomplete selection in DateTimePicker

### LINKED ISSUE #13616: [BUG] DateRangePicker value does not reflect value in browser when selection is aborted
### Software versions

Python version        :  3.10.13 (main, Dec 19 2023, 03:47:28) [GCC 12.2.0]
IPython version       :  (not installed)
Tornado version       :  6.4
Bokeh version         :  3.3.2
BokehJS static path   :  /usr/local/lib/python3.10/site-packages/bokeh/server/static
node.js version       :  (not installed)
npm version           :  (not installed)
jupyter_bokeh version :  (not installed)
Operating system      :  Linux-6.6.6-200.fc39.x86_64-x86_64-with-glibc2.36

### Expected behavior

If only one date is selected when the calendar is closed (_e.g._ if you click elsewhere), I would expect the value on the Python side to reflect what is displayed in the browser.

### Observed behavior

In practice the field in the browser is cleared, so you could expect the value to be reset to `None`. Instead, the previous value persists.

### Example code

```Python
from bokeh.models import DateRangePicker, Button, PreText
from bokeh.io import curdoc
from bokeh.layouts import column, row


def callback(_):
    col.children.append(PreText(text=str(date_range_picker.value)))


date_range_picker = DateRangePicker(
    title="Select date range",
    value=("2019-09-20", "2019-10-15"),
    min_date="2019-08-01",
    max_date="2019-10-30",
    width=400,
)

button = Button(label="Display date range")
button.on_click(callback)
col = column(button)

curdoc().add_root(row(date_range_picker, col))
```

### Screenshots

date_range

### PR DESCRIPTION
**Pull request by muendlein**
- [x] issues: fixes #13616
- [x] tests added / passed

### CODE REVIEW

File: bokehjs/src/lib/models/widgets/base_date_picker.ts [hunk 1]
```diff
@@ -91,6 +96,22 @@ export abstract class BaseDatePickerView extends PickerBaseView {
...
+      case 0:
+      case 1: {
+        // Incomplete selection, treat as no selection.
+        this.model.value = null
+        break
+      }
+      case 2:
+        break
+      default: {
+        assert(false, "invalid length")
```
Comment (bryevdv) [inline bokehjs/src/lib/models/widgets/base_date_picker.ts]: maybe `import {unreachable} from "core/util/assert"` instead

**Comment by bryevdv** [comment]
@muendlein if you update to merge or rebase `branch-3.8` then the codebase CI errors will resolve

File: bokehjs/src/lib/models/widgets/base_date_picker.ts [hunk 2]
```diff
@@ -91,6 +96,22 @@ export abstract class BaseDatePickerView extends PickerBaseView {
...
+        this.model.value = null
+        break
+      }
+      case 2:
+        break
+      default: {
+        unreachable("invalid length")
+      }
+    }
+  }
```
Comment (bryevdv) [inline bokehjs/src/lib/models/widgets/base_date_picker.ts:114]: Looking closer, could the switch just be replaced entirely by `if (selected.length < 2)` ?

Comment (muendlein) [reply bokehjs/src/lib/models/widgets/base_date_picker.ts:114]: Technically speaking yes, however the three different length options have a distinct semantic meaning which I prefer to keep in order to be consistent with dependent classes.

**Review by bryevdv — APPROVED** [review]
