### PR TITLE
fix rendering of filtered data sources for previously broken glyphs

### LINKED ISSUE #6820: CDSView not working with Text glyph
This code does not display the filtered text. Adding the filter to a circle does filter the circles, however. 

cc @clairetang6 

```
from __future__ import print_function

import yaml

from bokeh.document import Document
from bokeh.models import (Circle, ColumnDataSource, DataRange1d, Grid, HoverTool, Label, LabelSet,
                          LinearAxis, Plot, Range1d, SingleIntervalTicker, CDSView, IndexFilter, Text)
from bokeh.resources import INLINE
from bokeh.sampledata.sprint import sprint
from bokeh.themes import Theme

# Based on http://www.nytimes.com/interactive/2012/08/05/sports/olympics/the-100-meter-dash-one-race-every-medalist-ever.html

abbrev_to_country = {
    "USA": "United States",
    "GBR": "Britain",
    "JAM": "Jamaica",
    "CAN": "Canada",
    "TRI": "Trinidad and Tobago",
    "AUS": "Australia",
    "GER": "Germany",
    "CUB": "Cuba",
    "NAM": "Namibia",
    "URS": "Soviet Union",
    "BAR": "Barbados",
    "BUL": "Bulgaria",
    "HUN": "Hungary",
    "NED": "Netherlands",
    "NZL": "New Zealand",
    "PAN": "Panama",
    "POR": "Portugal",
    "RSA": "South Africa",
    "EUA": "United Team of Germany",
}

fill_color = { "gold": "#efcf6d", "silver": "#cccccc", "bronze": "#c59e8a" }
line_color = { "gold": "#c8a850", "silver": "#b0b0b1", "bronze": "#98715d" }

def selected_name(name, medal, year):
    return name if medal == "gold" and year in [1988, 1968, 1936, 1896] else ""

t0 = sprint.Time[0]

sprint["Abbrev"]       = sprint.Country
sprint["Country"]      = sprint.Abbrev.map(lambda abbr: abbrev_to_country[abbr])
sprint["Medal"]        = sprint.Medal.map(lambda medal: medal.lower())
sprint["Speed"]        = 100.0/sprint.Time
sprint["MetersBack"]   = 100.0*(1.0 - t0/sprint.Time)
sprint["MedalFill"]    = sprint.Medal.map(lambda medal: fill_color[medal])
sprint["MedalLine"]    = sprint.Medal.map(lambda medal: line_color[medal])
sprint["SelectedName"] = sprint[["Name", "Medal", "Year"]].apply(tuple, axis=1).map(lambda args: selected_name(*args))

source = ColumnDataSource(sprint)

xdr =Range1d(start=25, end=-0.5)
ydr = DataRange1d(range_padding=2, range_padding_units="absolute")

plot = Plot(plot_width=1000, x_range=xdr, y_range=ydr, toolbar_location=None)
plot.title.text = "Usain Bolt vs. 116 years of Olympic sprinters"

xticker = SingleIntervalTicker(interval=5, num_minor_ticks=0)
xaxis = LinearAxis(ticker=xticker, axis_label="Meters behind 2012 Bolt")
plot.add_layout(xaxis, "below")

xgrid = Grid(dimension=0, ticker=xaxis.ticker)
plot.add_layout(xgrid)

yticker = SingleIntervalTicker(interval=12, num_minor_ticks=0)
yaxis = LinearAxis(ticker=yticker, major_tick_in=-5, major_tick_out=10)
plot.add_layout(yaxis, "right")

filters = [IndexFilter(list(sprint.query('Medal == "gold" and Year in [1988, 1968, 1936, 1896]').index))]

medal = Circle(x="MetersBack", y="Year", size=10, fill_color="MedalFill", line_color="MedalLine", fill_alpha=0.5)
medal_renderer = plot.add_glyph(source, medal)

#sprint[sprint.Medal=="gold" * sprint.Year in [1988, 1968, 1936, 1896]]
plot.add_glyph(source, Text(x="MetersBack", y="Year", x_offset=10, text="Name"), view=CDSView(source=source, filters=filters))

plot.add_glyph(source, Text(x=7.5, y=1942, text=["No Olympics in 1940 or 1944"],
                            text_font_style="italic", text_color="silver"))

tooltips = """
<div>
    <span style="font-size: 15px;">@Name</span>&nbsp;
    <span style="font-size: 10px; color: #666;">(@Abbrev)</span>
</div>
<div>
    <span style="font-size: 17px; font-weight: bold;">@Time{0.00}</span>&nbsp;
    <span style="font-size: 10px; color: #666;">@Year</span>
</div>
<div style="font-size: 11px; color: #666;">@{MetersBack}{0.00} meters behind</div>
"""

hover = HoverTool(tooltips=tooltips, renderers=[medal_renderer])
plot.add_tools(hover)

theme = Theme(json=yaml.load("""
attrs:
    Plot:
        outline_line_color: None
    Axis:
        axis_line_color: None
        major_tick_line_color: None
        axis_label_text_font_style: "bold"
        axis_label_text_font_size: "10pt"
    Grid:
        grid_line_dash: "dashed"
    Text:
        text_baseline: "middle"
        text_align: "center"
        text_font_size: "9pt"
"""))

doc = Document(theme=theme)
doc.add_root(plot)

if __name__ == "__main__":
    from bokeh.embed import file_html
    from bokeh.util.browser import view

    doc.validate()
    filename = "sprint.html"
    with open(filename, "w") as f:
        f.write(file_html(doc, INLINE, plot.title.text))
    print("Wrote %s" % filename)
    view(filename)
```

### PR DESCRIPTION
**Pull request by clairetang6**
This PR fixes the rendering of glyphs that use a subset of data, through filtering with CDSView. It also fixes some bugs with the hover tool and filtered plots that were introduced with GraphRenderer work. 

The problem was at line 141 in bokehjs/src/coffee/models/renderers/glyph_renderer.coffee. I had mistakenly thought that `all_indices` was in subset space when it really is in full data space. `all_indices` contains the indices of the filtered data source (e.g. [1, 20, 45]) in the full data space. It needs to be converted to `indices` in subset space (i.e. [0, 1, 2]). This previously was working for the circle glyph, because `mask_data` using the spatial index would return the correct subset space `indices`. However, for glyphs that don't have `_mask_data`, `indices` was incorrectly in the full data space. The fix is just to convert `indices` to subset space if it wasn't converted by `mask_data`. 

I also made sure that the Line glyph was being handled properly. It needs special selected/non-selected handling ([PR where line selection rendering is improved](https://github.com/bokeh/bokeh/pull/6491)). I made it so that hovering when a line renderer has a hover_glyph displays the whole line (can be a subset using CDSView) using the hover style.

- [x] issues: fixes #6820 #6910 #6955
- [ ] tests added / passed

### CODE REVIEW

**Comment by clairetang6** [comment]
Script I used to test handling of Line and glyphs like Rect:
```python
from math import pi
from bokeh.plotting import figure, show, output_file
from bokeh.models import CDSView, IndexFilter, ColumnDataSource, Line
from bokeh.layouts import row

source = ColumnDataSource({'x': [1, 2, 3, 4, 5], 'y': [1, 2, 3, 4, 5]})
view = CDSView(source=source, filters=[IndexFilter([1, 2, 3, 4])])

p1 = figure(plot_width=400, plot_height=400, tools=['box_select', 'hover', 'reset'], x_range=(0, 6), y_range=(0, 6))
p1.rect(x='x', y='y', width=0.2, height=40, color="#CAB2D6", angle=pi/3, height_units="screen", source=source, view=view)

r = p1.line(x='x', y='y', source=source, view=view, line_width=6)
r.hover_glyph = Line(line_color="red", line_width=2)

p2 = figure(plot_width=400, plot_height=400, tools=['box_select', 'tap', 'reset'], x_range=(0, 6), y_range=(0, 6))
p2.rect(x='x', y='y', width=0.2, height=40, color="#CAB2D6", angle=pi/3, height_units="screen", source=source, view=view)

r = p2.line(x='x', y='y', source=source, view=view, line_width=6)
r.hover_glyph = Line(line_color="red", line_width=2)

show(row(p1, p2))
```

File: bokehjs/src/coffee/models/renderers/glyph_renderer.coffee [hunk 1]
```diff
@@ -137,8 +137,11 @@ export class GlyphRendererView extends RendererView
     dtmap = Date.now() - t0
 
     tmask = Date.now()
-    # all_indices and indices are in cdsview subset space
+    # all_indices is in full data space, indices is converted to subset space
+    # either by mask_data (that uses the spatial index) or manually
     indices = @glyph.mask_data(@all_indices)
+    if '' + indices == '' + @all_indices
+      indices = [0...@all_indices.length]
```
Comment (bryevdv) [inline bokehjs/src/coffee/models/renderers/glyph_renderer.coffee]: Is this testing equality by converting to strings? Wouldn't s length comparison suffice? They can't be equal unless they are the same length and (assuming duplicate entries are not possible) they will only be the same length when they are equal.

Comment (clairetang6) [reply bokehjs/src/coffee/models/renderers/glyph_renderer.coffee]: Yes, it is meant to see if mask_data was a no-op. So, I think the length comparison would result in the correct behavior, but the logic would be a little bit wrong. Right now, all of the glyphs that implement _mask_data use the spatial index, which will return the correctly masked data in subset space. So [1, 20, 45] -> [0, 1, 2]. Here the length is the same, but we don't need to convert the indices to subset space. That said, the conversion would simply result in the same [0, 1, 2]. If mask_data does return a shorter array, then it will correctly not run the additional conversion ([1, 20, 45] -> [0, 2] -/> [0, 1], that last arrow would be wrong to do). This code is not ideal because it's not clear that mask_data should convert from full data space to subset space, it just happens to do so.

Comment (bryevdv) [reply bokehjs/src/coffee/models/renderers/glyph_renderer.coffee]: I guess I am worried about performance implications. For scenarios that are currently just on the edge of possible (let's say 50k pts for a concrete plausible number), this means serializing two 50k element lists to strings and comparing on every render? I think that may push "currently just possible" cases into "no longer reasonable" territory. 

When you say "So, I think the length comparison would result in the correct behavior, but the logic would be a little bit wrong" do you mean that the logic is simply indirect and possibly confusing to anyone looking at it? Or that it only happens to be correct in this case, but will be wrong in other cases? If the former, I think that is solved with a comment explaining why the code is doing the comparison

**Comment by bryevdv** [comment]
@clairetang6 is this `ready` ?

File: bokehjs/src/coffee/models/renderers/glyph_renderer.coffee (hunk 1 above)
Comment (clairetang6) [reply bokehjs/src/coffee/models/renderers/glyph_renderer.coffee]: Yes, it would be the former, so I agree the length comparison would be the better way to go given the performance cost.

**Comment by clairetang6** [comment]
I was planning to add some tests to this PR, but I just created a new issue for them, so this PR is ready.
