### PR TITLE
numeric input and spinner fixes

### LINKED ISSUE #10367: [BUG] NumericInput and Spinner several bugs
First bug concern the modification of the input text when a key not allowed is pressed
The input value state is register only when a correct key is pressed so if we use the arrows to update the value the new state is not recorded
In the following gif, I use the input to enter the value 25, then I update this value using arrows and I press a wrong key.
The value is set to 25 instead of 44
ezgif com-video-to-gif

Incrementation using mouse click is too sensible as we can see in the following gif it's hard to increment only by 1:
ezgif com-video-to-gif (1)
It can be control by the `interval` property but I think I will implement an heuristic which start slowly and increase the speed of the increment function of the press duration

padding should be added to the input text to not overlap with arrows
image

### PR DESCRIPTION
**Pull request by xavArtley**
- [x] issues: fixes #10367

### CODE REVIEW

File: bokehjs/src/lib/models/widgets/numeric_input.ts [hunk 1]
```diff
@@ -69,14 +68,17 @@ export class NumericInputView extends InputWidgetView {
...
+    this.input_el = Object.assign(
+      input({
+        type: "text",
+        class: bk_input,
+        name: this.model.name,
+        value: this.format_value,
+        disabled: this.model.disabled,
+        placeholder: this.model.placeholder,
+      }),
+      {oldValue: this.format_value}
```
Comment (mattpap) [inline bokehjs/src/lib/models/widgets/numeric_input.ts:80]: I would avoid this kind of code, and just set `old_value` on `this` and incorporate `setInputFilter` into the class.

**Comment by mattpap** [comment]
@xavArtley, should I consider this ready?

**Comment by xavArtley** [comment]
Yes i think so

Le mar. 4 août 2020 à 23:20, Mateusz Paprocki <notifications@github.com> a
écrit :
