### PR TITLE
Replace tile range assertion with warning

### LINKED ISSUE #14280: Unintialized figure range triggers JS error when adding a tile
### Software versions

Python version : 3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:50:30) [MSC v.1933 64 bit (AMD64)]
IPython version : 8.12.0
Tornado version : 6.2
NumPy version : 1.24.2
Bokeh version : 3.6.2
node.js version : (not installed)
npm version : (not installed)
jupyter_bokeh version : (not installed)
Operating system : Windows-10-10.0.19045-SP0

### Browser name and version

_No response_

### Jupyter notebook / Jupyter Lab version

_No response_

### Expected behavior

Empty figure & no corrupted layout.

### Observed behavior

Incomplete/broken rendering; the contents of both tabs are initially present at the same time.

### Example code

```Python
from bokeh.io import curdoc
from bokeh.models import TabPanel, Tabs
from bokeh.plotting import figure

t1 = figure(x_axis_type="mercator", y_axis_type="mercator", sizing_mode="stretch_both", match_aspect=True)
t1.add_tile("CartoDB Positron", retina=True)

app_layout = Tabs(tabs=[
    TabPanel(child=t1, title="Rides"),
    TabPanel(child=figure(), title="Analytics"),
],
    sizing_mode="stretch_both",
)

curdoc().add_root(app_layout)
```

### Stack traceback or browser console output

Triggered by an isFinite assertion

```
Uncaught Error: Assertion failed
    a http://localhost:5006/static/js/bokeh.min.js?v=40ec286a43b4866674c993104e398c3c12eee68ee5ca62463f8d97b9f2af42937642cc02dfc7fa7784ad837b1be144310f8e69367ba74c519b01c9623261f99c:178
    c http://localhost:5006/static/js/bokeh.min.js?v=40ec286a43b4866674c993104e398c3c12eee68ee5ca62463f8d97b9f2af42937642cc02dfc7fa7784ad837b1be144310f8e69367ba74c519b01c9623261f99c:178
    get_extent http://localhost:5006/static/js/bokeh.min.js?v=40ec286a43b4866674c993104e398c3c12eee68ee5ca62463f8d97b9f2af42937642cc02dfc7fa7784ad837b1be144310f8e69367ba74c519b01c9623261f99c:664
    _set_data http://localhost:5006/static/js/bokeh.min.js?v=40ec286a43b4866674c993104e398c3c12eee68ee5ca62463f8d97b9f2af42937642cc02dfc7fa7784ad837b1be144310f8e69367ba74c519b01c9623261f99c:664
    _paint http://localhost:5006/static/js/bokeh.min.js?v=40ec286a43b4866674c993104e398c3c12eee68ee5ca62463f8d97b9f2af42937642cc02dfc7fa7784ad837b1be144310f8e69367ba74c519b01c9623261f99c:664
    paint http://localhost:5006/static/js/bokeh.min.js?v=40ec286a43b4866674c993104e398c3c12eee68ee5ca62463f8d97b9f2af42937642cc02dfc7fa7784ad837b1be144310f8e69367ba74c519b01c9623261f99c:249
    _paint_levels http://localhost:5006/static/js/bokeh.min.js?v=40ec286a43b4866674c993104e398c3c12eee68ee5ca62463f8d97b9f2af42937642cc02dfc7fa7784ad837b1be144310f8e69367ba74c519b01c9623261f99c:627
    _paint_primary http://localhost:5006/static/js/bokeh.min.js?v=40ec286a43b4866674c993104e398c3c12eee68ee5ca62463f8d97b9f2af42937642cc02dfc7fa7784ad837b1be144310f8e69367ba74c519b01c9623261f99c:627
    _actual_paint http://localhost:5006/static/js/bokeh.min.js?v=40ec286a43b4866674c993104e398c3c12eee68ee5ca62463f8d97b9f2af42937642cc02dfc7fa7784ad837b1be144310f8e69367ba74c519b01c9623261f99c:627
    paint http://localhost:5006/static/js/bokeh.min.js?v=40ec286a43b4866674c993104e398c3c12eee68ee5ca62463f8d97b9f2af42937642cc02dfc7fa7784ad837b1be144310f8e69367ba74c519b01c9623261f99c:627
    _after_layout http://localhost:5006/static/js/bokeh.min.js?v=40ec286a43b4866674c993104e398c3c12eee68ee5ca62463f8d97b9f2af42937642cc02dfc7fa7784ad837b1be144310f8e69367ba74c519b01c9623261f99c:627
    after_layout http://localhost:5006/static/js/bokeh.min.js?v=40ec286a43b4866674c993104e398c3c12eee68ee5ca62463f8d97b9f2af42937642cc02dfc7fa7784ad837b1be144310f8e69367ba74c519b01c9623261f99c:592
    after_layout http://localhost:5006/static/js/bokeh.min.js?v=40ec286a43b4866674c993104e398c3c12eee68ee5ca62463f8d97b9f2af42937642cc02dfc7fa7784ad837b1be144310f8e69367ba74c519b01c9623261f99c:592
    compute_layout http://localhost:5006/static/js/bokeh.min.js?v=40ec286a43b4866674c993104e398c3c12eee68ee5ca62463f8d97b9f2af42937642cc02dfc7fa7784ad837b1be144310f8e69367ba74c519b01c9623261f99c:592
    invalidate_layout http://localhost:5006/static/js/bokeh.min.js?v=40ec286a43b4866674c993104e398c3c12eee68ee5ca62463f8d97b9f2af42937642cc02dfc7fa7784ad837b1be144310f8e69367ba74c519b01c9623261f99c:592
    _after_render http://localhost:5006/static/js/bokeh.min.js?v=40ec286a43b4866674c993104e398c3c12eee68ee5ca62463f8d97b9f2af42937642cc02dfc7fa7784ad837b1be144310f8e69367ba74c519b01c9623261f99c:592
    after_render http://localhost:5006/static/js/bokeh.min.js?v=40ec286a43b4866674c993104e398c3c12eee68ee5ca62463f8d97b9f2af42937642cc02dfc7fa7784ad837b1be144310f8e69367ba74c519b01c9623261f99c:277
    r_after_render http://localhost:5006/static/js/bokeh.min.js?v=40ec286a43b4866674c993104e398c3c12eee68ee5ca62463f8d97b9f2af42937642cc02dfc7fa7784ad837b1be144310f8e69367ba74c519b01c9623261f99c:223
    _after_resize http://localhost:5006/static/js/bokeh.min.js?v=40ec286a43b4866674c993104e398c3c12eee68ee5ca62463f8d97b9f2af42937642cc02dfc7fa7784ad837b1be144310f8e69367ba74c519b01c9623261f99c:592
    after_resize http://localhost:5006/static/js/bokeh.min.js?v=40ec286a43b4866674c993104e398c3c12eee68ee5ca62463f8d97b9f2af42937642cc02dfc7fa7784ad837b1be144310f8e69367ba74c519b01c9623261f99c:277
    _resize_observer http://localhost:5006/static/js/bokeh.min.js?v=40ec286a43b4866674c993104e398c3c12eee68ee5ca62463f8d97b9f2af42937642cc02dfc7fa7784ad837b1be144310f8e69367ba74c519b01c9623261f99c:277
```

### Screenshots

Image

### PR DESCRIPTION
**Pull request by muendlein**
- [x] issues: fixes #14280

### CODE REVIEW

File: bokehjs/src/lib/models/tiles/tile_renderer.ts [hunk 1]
```diff
@@ -55,10 +55,9 @@ export class TileRendererView extends RendererView {
     const y_start = y_range.start
     const x_end = x_range.end
     const y_end = y_range.end
-    assert(isFinite(x_start))
-    assert(isFinite(y_start))
-    assert(isFinite(x_end))
-    assert(isFinite(y_end))
+    if (!(isFinite(x_start) && isFinite(y_start) && isFinite(x_end) && isFinite(y_end))) {
+        logger.warn("tile extent is (partially) undefined")
```
Comment (bryevdv) [inline bokehjs/src/lib/models/tiles/tile_renderer.ts]:
```suggestion
        logger.warn("tile extent is not fully defined")
```
IMO this slight change covers all the cases -- partially or fully undefined -- a little better. If you want to make this even more informative you could also include the four range start/end values in the message.

**Comment by bryevdv** [comment]
@muendlein just a linter issue
```
[22:32:39]   59:1  error  Expected indentation of 6 spaces but found 8  @typescript-eslint/indent
[22:32:39] 
[22:32:39] ✖ 1 problem (1 error, 0 warnings)
[22:32:39]   1 error and 0 warnings potentially fixable with the `--fix` option.
```

**Comment by muendlein** [comment]
@bryevdv I have just noticed that there is an additional possible side effect (browser freezing, see here: https://github.com/bokeh/bokeh/issues/13248) that needs to be considered (probably also why the assertions have been added in the first place).
As this not obvious I think this needs to be addressed with this PR as well.

MRE (browser freezes upon button click to add the data)

Note this is not triggered in certain sizing modes: e.g. using `row(t1, button, sizing_mode="stretch_both")` works fine

```
from bokeh.layouts import column, row
from bokeh.models import TabPanel, Tabs, ColumnDataSource, Button
from bokeh.plotting import figure

source = ColumnDataSource({"x": [0, 1e6, 2e6, 1e6],
                           "y": [8100000, 6100000, 4100000, 2100000]})

t1 = figure(x_axis_type="mercator", y_axis_type="mercator", sizing_mode="stretch_both", match_aspect=True)
t1.add_tile("CartoDB Positron", retina=True)

def add_data():
    t1.line(x="x", y="y", source=source, line_width=4, line_color="red")

button = Button(label="add data")
button.on_click(add_data)

app_layout = Tabs(tabs=[
    TabPanel(child=row(t1, button), title="Tab1"),
    TabPanel(child=figure(), title="Tab2"),
],
    sizing_mode="stretch_both"
)

curdoc().add_root(app_layout)
```

**Comment by bryevdv** [comment]
@muendlein right IIRC extents get coalesced together, so if one of them returns nans, etc. that would taint the entire result. Things will need to be handled more carefully, and ideally maybe `get_extent` changes to return an actual bbox or something besides a bare "tuple". @mattpap will probably have thoughts

**Comment by muendlein** [comment]
@bryevdv Reapplying the original PR for the freeze issue (early return inside `get_tiles_by_extent`) resolves the issue. But not sure if this is sufficient.

**Comment by mattpap** [comment]
This needs a rebase to clear mypy errors.

**Comment by mattpap** [comment]
This also needs a regression test (similar to what I suggested in PR #14305).

**Comment by muendlein** [comment]
@mattpap Regression test is now added. Let  me know if more is needed.

**Comment by mattpap** [comment]
A rebase is needed and you have to commit the generated baseline files (see point (3) [here](https://docs.bokeh.org/en/latest/docs/dev_guide/writing_tests.html#bokehjs-visual-tests)).

File: bokehjs/test/integration/regressions.ts [hunk 2]
```diff
@@ -4305,4 +4305,22 @@ describe("Bug", () => {
...
   })
+
+  describe("in issue #14280", () => {
+    it("triggers JS error when adding tile without defining range", async () => {
+      const osm = new TileRenderer({tile_source: osm_source.clone()})
+
+      const p0 = fig([300, 200], {
+        x_axis_type: "mercator",
+        y_axis_type: "mercator",
+        sizing_mode: "stretch_height",
```
Comment (mattpap) [inline bokehjs/test/integration/regressions.ts]: Unnecessary, because `fig()` creates a fixed size plot:
```suggestion
```

File: bokehjs/test/integration/regressions.ts [hunk 3]
```diff
@@ -4305,4 +4305,22 @@ describe("Bug", () => {
       await view.ready
     })
   })
+
+  describe("in issue #14280", () => {
+    it("triggers JS error when adding tile without defining range", async () => {
+      const osm = new TileRenderer({tile_source: osm_source.clone()})
+
+      const p0 = fig([300, 200], {
+        x_axis_type: "mercator",
```
Comment (mattpap) [inline bokehjs/test/integration/regressions.ts:4337]: Although `figure` has implicit `DataRange1d` ranges, I would state that explicitly, because that's actually important for the test to be meaningful:
```suggestion
        x_range: new DataRange1d(),
        y_range: new DataRange1d(),
        x_axis_type: "mercator",
```

**Review by mattpap — APPROVED** [review]
Looks good up to minor test improvements.

**Comment by mattpap** [comment]
@muendlein, thanks.
