### PR TITLE
Fix multiline inspection and reduce any type usage

### LINKED ISSUE #10458: [BUG]multi_line doesn't support hover.
bokeh 2.2.1

test code

```python
from bokeh.models import ColumnDataSource, HoverTool
from bokeh.plotting import figure
from bokeh.io import show

source = ColumnDataSource(data=dict(xs=[[1, 2], [3, 4]], ys=[[1, 2], [2, 1]], name=['A', 'B']))
fig = figure()
lines = fig.multi_line('xs', 'ys', source=source)
hover = HoverTool(tooltips=[('name', '@name')], renderers=[lines])
fig.add_tools(hover)
show(fig)
```

when hover a line, the follow exception raised in devtool console:

```
7VM425 bokeh-2.2.1.js:40248 Uncaught TypeError: Cannot read property '0' of undefined
    at HoverToolView._update (VM425 bokeh-2.2.1.js:40248)
    at HoverToolView.new_slot (VM425 bokeh-2.2.1.js:7546)
    at Signal.emit (VM425 bokeh-2.2.1.js:2699)
    at SelectionManager.inspect (VM425 bokeh-2.2.1.js:10912)
    at HoverToolView._inspect (VM425 bokeh-2.2.1.js:40164)
    at HoverToolView._move (VM425 bokeh-2.2.1.js:40149)
    at HoverToolView.<anonymous> (VM425 bokeh-2.2.1.js:34754)
    at HoverToolView.new_slot (VM425 bokeh-2.2.1.js:7546)
    at Signal.emit (VM425 bokeh-2.2.1.js:2699)
    at UIEvents.trigger (VM425 bokeh-2.2.1.js:34925)
```

Here is the code that raise the exception:

```javascript
let data_x = glyph._xs[i][j];
```

Here is some debug information in the console.

```
> glyph._xs
RaggedArray {offsets: Uint32Array(2), array: Float32Array(4)}

> glyph._xs[0]
undefined
```

### PR DESCRIPTION
**Pull request by mattpap**
fixes #10458

### CODE REVIEW

File: bokehjs/src/lib/models/tools/inspectors/hover_tool.ts [hunk 1]
```diff
@@ -376,11 +384,14 @@ export class HoverToolView extends InspectToolView {
...
     for (const r of this.computed_renderers) {
+      if (!(r instanceof GlyphRenderer))
+        continue
+
       const rv = this.plot_view.renderer_views.get(r)!
       const x = rv.coordinates.x_scale.invert(geometry.sx)
       const y = rv.coordinates.y_scale.invert(geometry.sy)
 
-      const index = (r as any).data_source.inspected
+      const index = r.data_source.inspected as any // XXX: Selection vs number
```
Comment (mattpap) [inline bokehjs/src/lib/models/tools/inspectors/hover_tool.ts:394]: @bryevdv, do you know what was the intent here? Either types are wrong or this code doesn't make sense.

Comment (bryevdv) [reply bokehjs/src/lib/models/tools/inspectors/hover_tool.ts:394]: I don't at all, my guess is this is a holdover of some change that happened then the proper `Selection` model was introduced.
