### PR TITLE
Touch events on iOS 13.x workaround

### LINKED ISSUE #9187: [BUG] Pinch Zoom and Panning not working correctly
I am using Bokeh standalone **1.3.4** on the back end (Django) and bokehjs on the front end. While scrolling to zoom and using the mouse to pan works well on desktop, the experience on mobile devices is ambiguous. In Chrome (**76.0.3809.111**) on mobile devices, nor panning, nor pinching to zoom work. Panning works great in Safari and Firefox on mobile devices, but pinching to zoom doesn't work there as well. 

This is the back end code:
```python
p = figure()

color_palette = Spectral11[0:num_lines]

source = ColumnDataSource(power_data)

p.add_layout(Legend(items=legend_items))
p.legend.click_policy = "hide"

p.add_tools(CrosshairTool(
        dimensions='height',
        line_color='red'
))

item_text = json.dumps(json_item(p, "myplot"))

return Response(item_text)
```

This is the front end code:
```javascript
declare var Bokeh: any

// some lines later, inside a request callback
Bokeh.embed.embed_item(JSON.parse(response))
```

I have found a website where the pinch to zoom and pan work well and they are using an older version of Bokeh(**1.0.4**), so I am not sure if it's something with my code or it no longer works.

Are these features still supported on mobile devices?

### PR DESCRIPTION
**Pull request by do1tgood**
Hammer.js has several issues related to Pointer Event implementation.
iOS 13 delivered built-in PointerEvents in Safari which made Hammer's touch recognisers (pan, pinch, swipe) behave incorrectly in certain cases.

However, most of problems may be addressed with Hammer's constructor options.
`Hammer.TouchMouseInput` does a trick for Pinch and Pan Tools in Bokeh.

- [x] issues: resolves #9187
- [ ] tests added / passed

### CODE REVIEW

File: bokehjs/src/lib/core/ui_events.ts [hunk 1]
```diff
@@ -105,7 +105,7 @@ export class UIEvents implements EventListenerObject {
   readonly keydown:      UISignal<KeyEvent>     = new Signal(this, 'keydown')
   readonly keyup:        UISignal<KeyEvent>     = new Signal(this, 'keyup')
 
-  private readonly hammer = new Hammer(this.hit_area, {touchAction: 'auto'})
+  private readonly hammer = new Hammer(this.hit_area, {touchAction: 'auto', inputClass: Hammer.TouchMouseInput})
```
Comment (mattpap) [inline bokehjs/src/lib/core/ui_events.ts]: Can you add a link to the issue, so that we know why that argument is there? Like this:
```ts
private readonly hammer = new Hammer(this.hit_area, {
  touchAction: 'auto',
  inputClass: Hammer.TouchMouseInput, // https://github.com/bokeh/bokeh/issues/9187
})
```

File: bokehjs/src/lib/core/ui_events.ts [hunk 2]
```diff
@@ -105,7 +105,10 @@ export class UIEvents implements EventListenerObject {
   readonly keydown:      UISignal<KeyEvent>     = new Signal(this, 'keydown')
   readonly keyup:        UISignal<KeyEvent>     = new Signal(this, 'keyup')
 
-  private readonly hammer = new Hammer(this.hit_area, {touchAction: 'auto'})
+  private readonly hammer = new Hammer(this.hit_area, {
+    touchAction: 'auto',
+    inputClass: Hammer.TouchMouseInput // https://github.com/bokeh/bokeh/issues/9187
```
Comment (mattpap) [inline bokehjs/src/lib/core/ui_events.ts]: Tests will fail without the trailing comma.

Comment (do1tgood) [reply bokehjs/src/lib/core/ui_events.ts]: Oh, sure. It's weird that linter hasn't notified me about it. I see a rule in there.

**Comment by bryevdv** [comment]
I will do my level best to hand-roll a dev build tonight so that this is easier to test with.
