### PR TITLE
A series of WebGL fixes (regression, precision, data update, miter limit)

### LINKED ISSUE #3464: maps_cities.py data disappears after pan/zoom
ping @almarklein 

Other WebGL examples work fine. 

Could consider a *very* short self-contained fix for `0.11`

```
examples/glyphs/maps_cities.py:
 data disappears after pan/zoom
```

### LINKED ISSUE #3795: datetime datapoints to pile up with webgl enabled
In Bokeh 0.11 there is some kind of truncation error in the rendering of a datetime axis when webgl=True. It causes the datapoints to pile up at discrete times.

Consider this minimal example:

```python
import numpy as np
import bokeh.plotting as bk
from datetime import datetime,timedelta

no_of_datapoints=10

base = datetime(2016, 2, 1, 9, 36, 0)
date_list = [base - timedelta(minutes=x) for x in range(0, no_of_datapoints)]
datapoints=np.arange(no_of_datapoints)

p=bk.figure(webgl=True,x_axis_type="datetime")
p.scatter(x=date_list,y=datapoints)
bk.show(p)
```

With webgl=True the diagram gets piled up datapoints:
qvm85ci

With webgl=False the diagram is rendered correctly 
wxt6mwa

See also this [stackoverflow discussion](http://stackoverflow.com/questions/35113105/visualizing-timeseries-with-bokeh-datapoints-overlap/35126714)

### LINKED ISSUE #3800: Bokeh 0.11: Enables webgl causes inconsistent update of scatter points
This problem might be related to this issue: https://github.com/bokeh/bokeh/issues/3795

Lets consider this minimal example:
```python
from bokeh.plotting import figure, show, ColumnDataSource
from bokeh.models import Select
from bokeh.models.widgets import RadioGroup
from bokeh.io import vform
import numpy as np

N = 100
x1 = np.random.normal(0.0, 1.0,N)
x2 = x1 * (1.0 + np.random.normal(0.0, 0.1,N))
y1 = 5.0*x1 + np.random.normal(0, 0.1, N)
y2 = 50.0*x2 + np.random.normal(0, 1, N)

source = ColumnDataSource({'x' : x1, 'y' : y1})

TOOLS = "box_select,box_zoom,lasso_select,help,reset,pan"
p = figure(tools=TOOLS, plot_width=400, plot_height=400, webgl=True)
p.circle(x='x', y='y', source=source)

x_radio_group = RadioGroup(labels=["x1", "x2"], active=0)
y_radio_group = RadioGroup(labels=["y1", "y2"], active=0)
controls = vform(x_radio_group, y_radio_group)

def update(attr, old, new):
    source.data["y"] = y1 if y_radio_group.active==0 else y2
    source.data["x"] = x1 if x_radio_group.active==0 else x2
    
    # Updating the source in one step does not change this behavior
    #data = dict(x=x1 if x_radio_group.active==0 else x2, y=y1 if y_radio_group.active==0 else y2)
    #source.data = data

source.on_change('selected', update)

def select_x(value):
    update('x-change', None, None)

def select_y(value):
    update('y-change', None, None)

x_radio_group.on_click(select_x)
y_radio_group.on_click(select_y)
```

You can reproduce this problem in the following way (using the bokeh server):

- Fire up the bokeh server (e.g. bokeh server file --show)
- Select a subset of the data points (using box select or lasso)
- Switch between y1 and y2 radio buttons
- Notice that even though the y-axis scaled as expected, the scatter points did not!

Now if you repeat this exercise with webgl=False, you should see that both the y-axis and the scatter points are updated as expected.

### PR DESCRIPTION
**Pull request by almarklein**
issues:
* fixes #3795
* fixes #3800 
* fixes part of #3635 
* might have fixed #3464

### CODE REVIEW

**Comment by bryevdv** [comment]
@almar is this still WIP or is it ready?

**Comment by almarklein** [comment]
@bryevdv still wip. I am going through the webgl issues ... more of this tomorrow

**Comment by bryevdv** [comment]
NP just checking :)

**Comment by almarklein** [comment]
@bryevdv its ready now

File: bokehjs/src/coffee/models/glyphs/bokehgl.coffee [hunk 1]
```diff
@@ -48,30 +48,34 @@ attach_float = (prog, vbo, att_name, n, visual, name) ->
...
     # then use this single color for all vertices (no VBO). Otherwise we
     # create an array and upload that to the VBO, which we attahce to the prog.
     m = 4
     vbo.used = true
-    if visual.color.spec.value? and visual.alpha.spec.value?
-      rgba = color2rgba(visual.color.spec.value, visual.alpha.spec.value)
+    colorname = prefix + '_color'
+    alphaname = prefix + '_alpha'
+    if visual[colorname].spec.value? and visual[alphaname].spec.value?
+      rgba = color2rgba(visual[colorname].spec.value, visual[alphaname].spec.value)
```
Comment (bryevdv) [inline bokehjs/src/coffee/models/glyphs/bokehgl.coffee]: could be e.g. `visual[colorname].value()` I think?

File: bokehjs/src/coffee/models/glyphs/bokehgl.coffee [hunk 2]
```diff
@@ -48,30 +48,34 @@ attach_float = (prog, vbo, att_name, n, visual, name) ->
...
+        prog.set_attribute(att_name, 'vec4', null, [0,0,0,0])
+        return
       # Get array of alphas
-      if visual.alpha.spec.value?
-        alphas = fill_array_with_float(n, visual.alpha.spec.value)
+      if visual[alphaname].spec.value?
+        alphas = fill_array_with_float(n, visual[alphaname].spec.value)
       else
-        alphas = visual.cache.alpha_array
+        alphas = visual.cache[alphaname+'_array']
```
Comment (bryevdv) [inline bokehjs/src/coffee/models/glyphs/bokehgl.coffee]: same comment as above, also `visual[alphaname].array()` when appropriate

**Comment by bryevdv** [comment]
two small comments otherwise LGTM

File: bokehjs/src/coffee/models/glyphs/bokehgl.coffee (hunk 2 above)
Comment (almarklein) [inline bokehjs/src/coffee/models/glyphs/bokehgl.coffee]: mmm, I get:
```js
>> visual.line_color.value()
X  Error: attempted to retrieve property value for property without value specification
// and
>> visual.line_color.array()
X  TypeError: source is undefined
// but ...
>> line.cache.line_color_array
   Array [ "#0f0", "#0f0", "#0f0", "#0f0", "#0f0", "#0f0", "#0f0", "#0f0", "#0f0", "#0f0", 140 meer… ]
```
Am I doing something wrong?

File: bokehjs/src/coffee/models/glyphs/line.coffee [hunk 3]
```diff
@@ -51,7 +51,7 @@ class LineView extends Glyph.View
       x: this.renderer.plot_view.canvas.vx_to_sx(geometry.vx)
       y: this.renderer.plot_view.canvas.vy_to_sy(geometry.vy)
     shortest = 9999
-    threshold = Math.max(2, @visuals.line.width.value() / 2)
+    threshold = Math.max(2, @visuals.line.line_width.value() / 2)
```
Comment (almarklein) [inline bokehjs/src/coffee/models/glyphs/line.coffee]: @bryevdv I came across this, and assumed it slipped through during earlier refactoring (because everything is `line_xxx` now). Can you confirm this is supposed to be `line_width`?

File: bokehjs/src/coffee/models/glyphs/bokehgl.coffee (hunk 2 above)
Comment (bryevdv) [inline bokehjs/src/coffee/models/glyphs/bokehgl.coffee]: The first one means the that the `spec` is configured for a data source column, or possibly is `null`. Are you relying on the color being `null` or `undefined` to not draw? If so I'd recommend testing the `doit` attribute to turn things on or off like the other renderers do. 

For the second I guess your usage actually differs a bit from the other renderers, `array` actually takes the data source to read from as an argument. Maybe this will have to do for now.

**Comment by almarklein** [comment]
@bryevdv ok, I changed how the visuals is used. Should be better now.

Also found that dashes are ugly due to the recent miter fixes. Looking into it now.

**Comment by almarklein** [comment]
Ok, fixed. Travis is also green, now that the flexx conda package is in the bokeh channel.

**Comment by almarklein** [comment]
Euhm. That last commit applies to another PR. Sorry about that. But this is ready, anyway.

File: bokehjs/src/coffee/models/glyphs/line.coffee (hunk 3 above)
Comment (bryevdv) [inline bokehjs/src/coffee/models/glyphs/line.coffee]: Yes it's a little verbose but easier to construct generically.
