### PR TITLE
Bug/2376 hover on discontinuous patches

### LINKED ISSUE #2376: Hover on discontinuous Patches
Hover does not work over discontinuous Patches - e.g. http://nbviewer.ipython.org/github/birdsarah/cge-tools/blob/share_interactive_map/interactive_map/Static%20map%20with%20data%20and%20hover.ipynb

### PR DESCRIPTION
**Pull request by birdsarah**
Fixes #2376

### CODE REVIEW

**Comment by birdsarah** [comment]
I started trying to write tests, but couldn't figure out how to instantiate a view to test the _set_index method. There didn't seem to be any similar tests to take a cue from.  The initial test commit (that doesn't work) is https://github.com/bokeh/bokeh/commit/c02b2a49738146e78addb8cb28f252a8f216e5e1

**Comment by birdsarah** [comment]
If anyone's testing - I used the following code to test this: https://github.com/birdsarah/bokeh-miscellany/blob/master/tests/2376_hover_on_discontinuous_patches.py

````python
import pandas as pd
from numpy import NAN

from bokeh.models import Plot, Range1d, ColumnDataSource, Patches, HoverTool, TapTool
from bokeh.properties import value
from bokeh.io import save, output_file

PLOT_FORMATS = dict(x_range=Range1d(0,100), y_range=Range1d(0,100), plot_width=500, plot_height=300, min_border=0, toolbar_location=None)

patches_dis_data = pd.DataFrame(
    {
        'xs': [[0, 49, 49, 0, NAN, 51, 89, 89, 51], [90, 100, 100, 90], [92, 98, 98, 92]],
        'ys': [[0, 0, 80, 80, NAN, 0, 0, 90, 90], [0, 0, 100, 100], [20, 20, 90, 90]],
        'value': ['I am sad', 'I can hover', 'Me too'],
        'fill_color': ['#FF2450', '#A4FF54', '#413F3D']
    },
)
plot_patches_dis = Plot(**PLOT_FORMATS)
plot_patches_dis.add_glyph(
    ColumnDataSource(patches_dis_data),
    Patches(
        xs='xs', ys='ys',
        fill_color='fill_color',
        line_color=value('#413F3D'),
    )
)
plot_patches_dis.add_tools(HoverTool(tooltips='@value'))
plot_patches_dis.add_tools(TapTool())

output_file('2376_hover_on_discontinuous_patches.html', title='Discontinuous Patches', mode='relative-dev')
save(plot_patches_dis)
````

I also tested on some real data. You can see http://nbviewer.ipython.org/github/mit-jp/cge-tools/blob/master/interactive_map/Static%20map%20with%20data%20and%20hover.ipynb provinces like Zhejiang & Guangdong (both on south cost with lots of islands) now have hover - if you run the code with 0.9 they don't.

**Comment by bryevdv** [comment]
ran example successfully, code LGTM

File: bokehjs/src/coffee/renderer/glyph/patches.coffee [hunk 1]
```diff
@@ -31,6 +71,10 @@ class PatchesView extends Glyph.View
     return (x[4].i for x in @index.search([x0, y0, x1, y1]))
 
   _render: (ctx, indices, {sxs, sys}) ->
+    # @sxss and @syss are used by _hit_point and sxc, syc
```
Comment (damianavila) [inline bokehjs/src/coffee/renderer/glyph/patches.coffee]: I feel this explanation need an end...

File: bokehjs/src/coffee/renderer/glyph/patches.coffee [hunk 2]
```diff
@@ -85,24 +129,48 @@ class PatchesView extends Glyph.View
...
+      # We don't have discontinuous objects so we're ok
+      return @_get_snap_coord(@sys[i])
+    else
+      # We have discontinuous objects, so we need to find which 
+      # one we're in, we can use point_in_poly again
+      sxs = @sxss[i]
+      sys = @syss[i]
+      for j in [0...sxs.length]
+        if hittest.point_in_poly(sx, sy, sxs[j], sys[j])
+          return @_get_snap_coord(sys[j])
```
Comment (damianavila) [inline bokehjs/src/coffee/renderer/glyph/patches.coffee]: We should eventually refactor this to avoid duplication, but for now it is enough...

**Comment by damianavila** [comment]
Minor comments, otherwise LGTM...

File: bokehjs/src/coffee/renderer/glyph/patches.coffee (hunk 1 above)
Comment (birdsarah) [inline bokehjs/src/coffee/renderer/glyph/patches.coffee]: Like a '.' or more sentence?

File: bokehjs/src/coffee/renderer/glyph/patches.coffee (hunk 2 above)
Comment (birdsarah) [inline bokehjs/src/coffee/renderer/glyph/patches.coffee]: Agree.

File: bokehjs/src/coffee/renderer/glyph/patches.coffee (hunk 1 above)
Comment (damianavila) [inline bokehjs/src/coffee/renderer/glyph/patches.coffee]: more sentence... but I am not the better to judge that :wink:

Comment (birdsarah) [inline bokehjs/src/coffee/renderer/glyph/patches.coffee]: Would it be better to just remove it? It may be stating the obvious. The method docstring explains what's going on.

Comment (damianavila) [inline bokehjs/src/coffee/renderer/glyph/patches.coffee]: Let's go ahead and merge it as is... re-reading, I am not against that anymore...
