### PR TITLE
Fix arrow clipping in plots in complex layouts

### LINKED ISSUE #9522: [BUG] Arrow lines do not render completely if figure is placed below some div
#### software version info
- Bokeh 1.4.0
- Python 3.7.5
- Tornado 6.0.3
- nodejs 12.12.0
- Firefox 71.0 (32-Bit) on Windows 10

#### Description of expected behavior and the observed behavior
Arrow lines should render fully.
They actually do, but in the setting Spacer + Figure + Slider they are being cropped.

**Expected**
arrow_render_bug_expected
Up to some specific position the arrow lines are rendered.

**Observed**
arrow_render_bug_shown
At some point the lines are not rendered anymore but the arrow heads are still visible.

arrow_render_bug_little_spacer
When using a smaller Spacer, the cropping starts later.
I would guess that the div above the plot uses twice the height which is actually needed, but I could not validate this assumption.

The same problem also appears when including a Div or widgets instead of a Spacer.

#### Complete, minimal, self-contained example code that reproduces the issue

```python
from bokeh.io import curdoc
from bokeh.models import ColumnDataSource, Arrow, OpenHead, NormalHead, Slider
from bokeh.plotting import figure
from bokeh.layouts import column, row, Spacer

a1_cds = ColumnDataSource(data=dict(xS=[0], xE=[4], yS=[-2], yE=[-2]))
a2_cds = ColumnDataSource(data=dict(xS=[7], xE=[7], yS=[-3], yE=[-2.9]))

def change_arrows(attr,old,new):
    a1_cds.stream(dict(xS=[0], xE=[4], yS=[new], yE=[new]), rollover=1)
    a2_cds.stream(dict(xS=[7], xE=[7], yS=[-3], yE=[new]),rollover=1)
    

f = figure(tools="", x_range=(-1,10), y_range=(-4,10))

a1_glyph = Arrow(end=NormalHead(), x_start='xS', y_start='yS', x_end='xE', y_end='yE', source=a1_cds)

a2_glyph = Arrow(end=OpenHead(), x_start='xS', y_start='yS', x_end='xE', y_end='yE', source=a2_cds)

f.add_layout(a1_glyph)
f.add_layout(a2_glyph)

s_arrows = Slider(title="change arrows", value=-2, start=-3, end=10, step=0.2)
s_arrows.on_change('value', change_arrows)

curdoc().add_root(column(Spacer(height=50),f,s_arrows))
```

#### Current Workaround and Trials
Setting the level attribute to `level="overlay"` or any other alternative level property does not help.
Lines via `f.line(...)` are rendered correctly.

If the sliders (or other widgets) are not positioned below the plot but next to the plot, i.e. `curdoc().add_root(column(Spacer(height=100),row(f,s_arrows)))`, the bug does not appear.

**Workaround** if the sliders really need to be positioned under the plot:
Adding an extra column.
`curdoc().add_root(column(Spacer(height=50), column(f,s_arrows) ))` 
So in general the figure should be the first object inside a column to avoid this bug.

#### Related Issues:
#9436  (that's why in the minimal example .stream with rollover=1 is used instead of direct assignment to data)

### PR DESCRIPTION
**Pull request by p-himik**
All pull requests must have an associated issue in the issue tracker. If there
isn't one, please go open an issue describing the defect, deficiency or desired
feature. You can read more about our issue and PR processes in the
[wiki](https://github.com/bokeh/bokeh/wiki/BEP-1:-Issues-and-PRs-management).

- [x] issues: fixes #9522
- [ ] tests added / passed
- [ ] release document entry (if new feature or API change)

### CODE REVIEW

**Comment by mattpap** [comment]
@p-himik, can you turn the example from #9522 into a "test" under `examples/integration/annotations`? This isn't ideal, especially that visual testing is broken right now, but will be a good starter for writing tests as soon as PR #9624 is finished.

File: bokehjs/src/lib/models/annotations/arrow.ts [hunk 1]
```diff
@@ -83,7 +83,7 @@ export class ArrowView extends AnnotationView {
     // Next we call .clip on all the arrow heads, inside an initial canvas sized
     // rect, to create an "inverted" clip region for the arrow heads
     ctx.beginPath()
-    const {x, y, width, height} = this.plot_view.layout.bbox
+    const {x, y, width, height} = this.plot_view.layout.inner_bbox
```
Comment (mattpap) [inline bokehjs/src/lib/models/annotations/arrow.ts]: I think it would be better to use `this.plot_view.frame.bbox`, though currently frame's outer box and plot's inner box are the same thing.

**Comment by p-himik** [comment]
@mattpap I could just add something similar to the `arrow.py`.
However, it seems strange. This particular issue is because of how there can potentially be a mismatch between different kinds of bounding boxes. Arrows have nothing to do with that, and adding a specific example for arrows seems to just mud the waters.
IMO a proper thing to do would be to create complex layouts automatically for all examples and other similar tests, if there are any. This would automatically cover every other glyph/annotation.

What do you think?

File: bokehjs/src/lib/models/annotations/arrow.ts (hunk 1 above)
Comment (p-himik) [reply bokehjs/src/lib/models/annotations/arrow.ts]: Sure thing.

BTW is there any issue/PR about documenting all these fields? E.g. even with your comment it's hard to figure out what `layout` and `frame` truly are and when and why one should use one or the other.

Comment (mattpap) [reply bokehjs/src/lib/models/annotations/arrow.ts]: There is none currently and this is under another redesign right now to allow more flexible positioning within canvas (for 3.0), so I will hopefully document this when the design finally settles.

**Comment by mattpap** [comment]
At minimum we need to test for regressions, but you are right that we should be testing things in more broader scope. This is where PR #9624 commes in, which creates a better environment for large scale visual testing. Before that we need to at least keep track of changes that need this kind of testing. I created issue #9771 for this purpose, so we can skip a "test" in this PR for now.
