### PR TITLE
remove extraneous ctx.fill for bands

### LINKED ISSUE #8599: grid bands broken when cross grid lines disabled
This code:
```
from bokeh.plotting import figure, output_file, show

output_file("gridbands.html")

p = figure(plot_width=400, plot_height=400)
p.circle([1,2,3,4,5], [2,5,8,2,7], size=10)

# change just some things about the x-grid
p.xgrid.grid_line_color = None

# change just some things about the y-grid
p.ygrid.band_fill_alpha = 0.1
p.ygrid.band_fill_color = "navy"

show(p)
```
results in this output:

screen shot 2019-01-30 at 20 21 04

If the xgrid setting is commented out, it displays correctly.

### PR DESCRIPTION
**Pull request by bryevdv**
There was an unnecessary `ctx.fill()` after the `ctx.fillRect(...)` to draw the bands. When the cross grid line color is `None` this actually supresses stroking and resetting some paths, and presumably this allowed a bad path accumulate for the `ctx.fill()`.

- [x] issues: fixes #8599

### CODE REVIEW

File: bokehjs/src/lib/models/grids/grid.ts [hunk 1]
```diff
@@ -227,7 +226,6 @@ export class Grid extends GuideRenderer {
 
     const cmin = cross_range.min
     const cmax = cross_range.max
-
```
Comment (mattpap) [inline bokehjs/src/lib/models/grids/grid.ts]: I would prefer not to remove this line.

**Comment by bryevdv** [comment]
sure, done
