### PR TITLE
Fix memory leak when updating panel constraints

### LINKED ISSUE #6311: Spectrogram performance regression
Sometime between `0.12.6dev2` and`0.12.6dev3`, a serious performance regression was introduced. The spectrogram becomes unusably slow, and CPU jumps to 100+% after 30-45 seconds or so. 

I believe this is the list of commits in that time period:
```
(py27) ❯ git log --pretty=oneline 0.12.6dev2...0.12.6dev3
febb9de55c6fd391e947e2084ad8d0d40c872107 (HEAD, tag: 0.12.6dev3) 'Merge branch release_0.12.6dev3'
eaba461f75cc21b195cb77ac1385e348045b1b6f 'Updating for version 0.12.6dev3'
f932004af4434fd63d10c929a2ffba9e1115ea42 'Updating for version 0.12.6dev3'
3224d8e8a362574096df6a2a5ba47db6f5802533 Provide richer formatting options for tooltip fields (#6183)
cebcabe7b4851b6401c5aa930b75942e06645614 Another attempt to make layout more reliable (#5976)
15575b5e4b298fbd0e64b0c711d2f48cf4f91f66 better validation for font size values (#6179)
81ec5ec99e83bc822d2406b250b7daef85dd5e43 be more strict about valid dataspec keys (#6176)
10ed8126e34a2a3c21085b9e358af963d23959ce Merge pull request #6181 from bokeh/bryanv/1482_fixed_range_padding
5416c461d4061da91c34096e8c9304dfe7e2cd71 properly trigger events on del m.foo (#6182)
2de18a46a508354e3054cb037f4991cfe78c9d6d (origin/bryanv/1482_fixed_range_padding) Add support for absolute range padding amounts
9f015809f25e8609c539f506f1c86b3d14b26ad6 (bryanv/5950_json_spec) Merge pull request #6178 from bokeh/ryanv/5914_vertical_labels
86ff46ad9f118ee8fa47aae7460e3eac7329bb15 (origin/ryanv/5914_vertical_labels) use proper alignment for vertical ticks below a plot
ab1156e928f28ca223206810e9e5ef573cacd009 Optimized python execution fails due to missing __doc__ instantiation. (#6157)
b2e41f6819333c8032fffc1063d093665eba71a9 Merge pull request #6168 from bokeh/bryanv/6130_line_width_hit_test
d7b4c95a57ab7cb1c674c7ce17fa116b79aa8592 Merge pull request #6166 from bokeh/bryanv/6161_segment_hit_test
4d6ff1ed9992295db4e994147490b689b4249147 Merge pull request #6169 from bokeh/bryanv/5907_marker_hit_span
80976fa8ace6ff9a8ba5cfb64e65bef75dc929b5 (origin/bryanv/6161_segment_hit_test) remove log statement
4699dd69140cad6d1967e54d38cd4a10e430bc84 remove deprecations up to 0.12.3 (#6164)
592d4e6e5adfab43a8cba885fea765d47c52e278 (origin/bryanv/5907_marker_hit_span) implement _hit_span for all markers
0530f20b6831a4f265771a90d068b1b68dda171c correctly handle scalar or vectorized line widths
043fc599abcc7946e544c7973d9be9af8f393565 (origin/bryanv/6130_line_width_hit_test) Use cache select to get line_widths correctly in all cases
4b3f428d726f429467d1c2376c057531c5970ad5 Add support for Toolbar.active_inspect property (#6131)
1e93df7b5b4b14f3591f7d876cb56019423df90c remove trailing whitespace
cade057e7e7ab1d9004adb21a08d3451d27df6c9 Fix callback docs errors (#6167)
14d3244689ee533c2060719ab7eeb628f073c33a Add hover tool support for Segment
4891466005a28896f131ffd8b6bf08213f60cac1 Enable TS' strict options and fix errors (#6136)
394f22693e744d617394545ac4a45530f42a7e00 Make invisible glyph renderers not participate in hit testing (#6137)
5d2866005f67a129261c243cc9ca74da57efecf3 Properly configure vectorized properties of overlays (#6138)
```

@mattpap I have not had a chance to do a bisection yet, but if I read the above output correctly, the extremely large layout PR was merged in this time frame. I guess without other input that would be my first suspect due to its size and scope.

### PR DESCRIPTION
**Pull request by mattpap**
fixes #6311

### CODE REVIEW

File: bokehjs/src/coffee/core/layout/side_panel.coffee [hunk 1]
```diff
@@ -158,12 +158,24 @@ export update_constraints = (view) ->
...
+    s.remove_constraint(view._full_constraint)
+
+  view._full_constraint = switch view.model.panel.side
     when 'above', 'below' then EQ(view.model.panel._width,  [-1, view.plot_model.canvas._width])
     when 'left', 'right'  then EQ(view.model.panel._height, [-1, view.plot_model.canvas._height])
 
-  if not s.has_constraint(constraint)
-    s.add_constraint(constraint)
+  s.add_constraint(view._full_constraint)
+  ###
```
Comment (mattpap) [inline bokehjs/src/coffee/core/layout/side_panel.coffee]: This code should work and does in practice, but not in tests.

**Comment by mattpap** [comment]
Either github or travis ci is sluggish today. Tests finished 10 minutes ago and status is still work in progress.

**Comment by bryevdv** [comment]
Tested locally with spectrogram, CPU usage in line with previous levels (and remain there over time).  

@mattpap if there is an underlying other issue to resolve or look into, I'd suggest and issue to keep track of it.
