### PR TITLE
Zooming with WheelZoomTool should respect bounds when using FactorRanges

### LINKED ISSUE #14568: [BUG] Wheel Zoom Tool and Categorical Axis Range
### Software versions

Python version        :  3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0]
IPython version       :  8.22.2
Tornado version       :  6.4
NumPy version         :  1.26.4
Bokeh version         :  3.7.3
BokehJS static path   :  /home/gzang/.local/lib/python3.10/site-packages/bokeh/server/static
node.js version       :  v20.9.0
npm version           :  10.1.0
jupyter_bokeh version :  (not installed)
Operating system      :  Linux-4.18.0-513.18.1.el8_9.x86_64-x86_64-with-glibc2.28

### Browser name and version

_No response_

### Jupyter notebook / Jupyter Lab version

3.6.7

### Expected behavior

Hello! I am trying to add a wheel zoom tool to my bokeh boxplot, but for some reason I can’t get the range to be constrained. I’m using the bokeh documentation with the cars as an example:

p.x_range = FactorRange(factors = kinds, bounds = 'auto')
wheel_zoom = WheelZoomTool(maintain_focus=False)
pan = PanTool()
p.add_tools(wheel_zoom, pan)
p.toolbar.active_scroll = wheel_zoom
p.toolbar.active_drag = pan
p.add_tools(ResetTool())
I expected the wheel zoom to be constrained within the defined FactorRange. But it does not.

### Observed behavior

Even though I’ve set the bounds to be automatically assigned according to the labels, I am still able to zoom out beyond the range of the categorical axis. Is there something I can do to constrain the range of the x-axis between the first label and the last label when using Wheel Zoom? Thanks!

### Example code

```Python
import pandas as pd

from bokeh.models import ColumnDataSource, Whisker, WheelZoomTool, ResetTool, PanTool, FactorRange
from bokeh.plotting import figure, show
from bokeh.sampledata.autompg2 import autompg2
from bokeh.transform import factor_cmap

df = autompg2[["class", "hwy"]].rename(columns={"class": "kind"})

kinds = df.kind.unique()

# compute quantiles
grouper = df.groupby("kind")
qs = grouper.hwy.quantile([0.25, 0.5, 0.75]).unstack().reset_index()
qs.columns = ["kind", "q1", "q2", "q3"]

# compute IQR outlier bounds
iqr = qs.q3 - qs.q1
qs["upper"] = qs.q3 + 1.5*iqr
qs["lower"] = qs.q1 - 1.5*iqr

# update the whiskers to actual data points
for kind, group in grouper:
    qs_idx = qs.query(f"kind=={kind!r}").index[0]
    data = group["hwy"]

    # the upper whisker is the maximum between p3 and upper
    q3 = qs.loc[qs_idx, "q3"]
    upper = qs.loc[qs_idx, "upper"]
    wiskhi = group[(q3 <= data) & (data <= upper)]["hwy"]
    qs.loc[qs_idx, "upper"] = q3 if len(wiskhi) == 0 else wiskhi.max()

    # the lower whisker is the minimum between q1 and lower
    q1 = qs.loc[qs_idx, "q1"]
    lower = qs.loc[qs_idx, "lower"]
    wisklo = group[(lower <= data) & (data<= q1)]["hwy"]
    qs.loc[qs_idx, "lower"] = q1 if len(wisklo) == 0 else wisklo.min()

df = pd.merge(df, qs, on="kind", how="left")

source = ColumnDataSource(qs)

p = figure(x_range=kinds, tools="", toolbar_location=None,
           title="Highway MPG distribution by vehicle class",
           background_fill_color="#eaefef", y_axis_label="MPG")

# outlier range
whisker = Whisker(base="kind", upper="upper", lower="lower", source=source)
whisker.upper_head.size = whisker.lower_head.size = 20
p.add_layout(whisker)

# quantile boxes
cmap = factor_cmap("kind", "TolRainbow7", kinds)
p.vbar("kind", 0.7, "q2", "q3", source=source, color=cmap, line_color="black")
p.vbar("kind", 0.7, "q1", "q2", source=source, color=cmap, line_color="black")

# outliers
outliers = df[~df.hwy.between(df.lower, df.upper)]
p.scatter("kind", "hwy", source=outliers, size=6, color="black", alpha=0.3)

p.xgrid.grid_line_color = None
p.axis.major_label_text_font_size="14px"
p.axis.axis_label_text_font_size="12px"

p.toolbar_location = None

p.x_range = FactorRange(factors = kinds, bounds = 'auto')
wheel_zoom = WheelZoomTool(maintain_focus=False)
pan = PanTool()
p.add_tools(wheel_zoom, pan)
p.toolbar.active_scroll = wheel_zoom
p.toolbar.active_drag = pan
p.add_tools(ResetTool())

show(p)
```

### Stack traceback or browser console output

_No response_

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by mosc9575**
This PR tries to solve the violated bound when using a FactorRange and zooming with the WheelZoomTool.

- [x] issues: fixes #14568
- [x] tests added / passed

Using a FactorRange can give a value for the `new_interval` in `_update_ranges_individually` in the "range_manager" which is larger than the difference between the given bounds.

In the current implementation this can lead to values for `start` and `end` of a range, which do not respect the given values by a user.

```python
from bokeh.models import FactorRange, WheelZoomTool
from bokeh.plotting import figure, show, output_notebook
output_notebook()

factors = ['a', 'b', 'c']

p=figure(tools="reset,pan", x_range=FactorRange(*factors, bounds=(0,3)))
p.line(factors, [1,2,3])
p.add_tools(WheelZoomTool(maintain_focus=False))
show(p)
```

https://github.com/user-attachments/assets/e5244503-b717-473b-a049-3e82b918a1eb

### CODE REVIEW

File: bokehjs/test/unit/regressions.ts
Comment (mosc9575) [inline bokehjs/test/unit/regressions.ts:1]: I am not sure it this test is sufficient. @mattpap It would be nice to get your opinion.

Comment (bryevdv) [reply bokehjs/test/unit/regressions.ts:1]: @mosc9575 The issue concerns a case when there are bounds set, no? IIUC the OP sets `bounds="auto"` in the issue. But the test does not seem to exercise that case (or any case with `bounds` set) explicitly.

Comment (mosc9575) [reply bokehjs/test/unit/regressions.ts:1]: Thanks for the hint with the bounds. I adapted the test. But I am still worried that the test is somehow not complete.

Here is a screen cast of my changes running the devtool server.

https://github.com/user-attachments/assets/ad9bdcf4-5533-4688-a710-47938238ddec

It shows that the bounds are now respected with my changes.

But the added test was passed without and with the bounds set. This shouldn't be the case. I have the feeling that no scrolling event was done on the test figure. E.g. the lines

```typescript
const actions1 = new PlotActions(view)
await actions1.scroll_down(xy(2, 2), 1)
await view.ready
```

aren't doing the any zoomin. Is there something missing or do I use the wrong command?

Comment (bryevdv) [reply bokehjs/test/unit/regressions.ts:1]: @mattpap can you comment on the question immediately above?

Comment (mattpap) [reply bokehjs/test/unit/regressions.ts:1]: There were a few issues with that test:

1. Key modifiers on the tool, which were not reflected in `scroll_down`.
2. The tool wasn't active by default.

I went ahead and fixed this while verifying this PR and robustness of this test.

@mosc9575, let's add another test without bounds as a comparison of the expected behavior. Move the test to a function under `describe`, parameterized by `x_range`, and verify results in `it`s.

File: bokehjs/test/unit/regressions.ts [hunk 1]
```diff
@@ -1981,4 +1982,27 @@ describe("Bug", () => {
       expect(source.selected.indices).to.be.equal([0, 3])
     })
   })
+
+  describe("in issue #14568", () => {
+    it("should support zooming with respect to bounds when using FactorRanges", async () => {
```
Comment (mattpap) [inline bokehjs/test/unit/regressions.ts]: This currently reads `Bug in issue #14568 should support ...`. It should read something like `Bug in issue #14568 doesn't allow zooming to respect bounds when using FactorRange`.

File: bokehjs/test/unit/regressions.ts
Comment (mosc9575) [reply bokehjs/test/unit/regressions.ts:1]: Thanks a lot for your help and your explanation.

I added 3 tests to `axis.ts`. Please tell me if this is the correct place for the tests.

**Review by mattpap — APPROVED** [review]

**Comment by mattpap** [comment]
I will go ahead and merge to get a dev release out.
