### PR TITLE
Fix rotated `Rect` point hit testing

### LINKED ISSUE #9752: [BUG] Hover tool not working correctly for rotated rectangles
#### Software version info
 BokehJS 1.4.0 successfully loaded (I am using Jupyter notebooks)
Python 3.7.5
The version of the notebook server is: 6.0.3
IPython 7.10.1
Linux 5.3.0-40-generic # 32~18.04.1-Ubuntu
Firefox 73.0.1 (64-bit) / same behaviour also in Chromium Version 80.0.3987.122

#### Description of expected behavior and the observed behavior
Hover tool should raise a tooltip whenever the mouse cursor enters the region of a rect glyph. Unfortunately, if there are some rect glyphs in a plot with non-zero rotation (e.g. angle=90, angle_units='deg'), the tooltips show up in a weird manner (I was unable to decipher the dependency) - some regions work, some do not work, the tooltip sometimes pops-up even when outside of the glyph. Most probably it's related to rotation because if I set angle=0 for all rectangles, it works as expected.

- The behaviour is deterministic
- Also affects stand-alone HTML pages rendered using output_file()
- I tried the same example also with oval glyphs and in that case, there seems to be no such problem
- The problem goes away if I do not use ColumnDataSource and call `p.rect()` multiple times for each point. But then I can't use tooltip formatters to display various metadata, so such workaround is not good for me.

#### Complete, minimal, self-contained example code that reproduces the issue
```
from bokeh.plotting import figure, output_notebook, show, ColumnDataSource
output_notebook()
p = figure(tools='hover')

rects={}
rects['xx'] = [1,2,3]
rects['yy'] = [1,2,3]
rects['width'] = [1,2,3]
rects['height'] = [1,2,3]
rects['angle'] = [90,90,90]
source = ColumnDataSource(data=rects)

p.rect('xx', 'yy', 'width', 'height', 'angle', fill_alpha=0.5,source=source,angle_units='deg')
show(p)
```

#### Stack traceback and/or browser JavaScript console output
```
Bokeh: BokehJS not loaded, scheduling load and callback at 
Date Mon Mar 02 2020 21:43:48 GMT+0100 (Central European Standard Time)
main.min.js:199:13
Bokeh: injecting script tag for BokehJS library:  https://cdn.pydata.org/bokeh/release/bokeh-1.4.0.min.js main.min.js:233:15
Bokeh: injecting script tag for BokehJS library:  https://cdn.pydata.org/bokeh/release/bokeh-widgets-1.4.0.min.js main.min.js:233:15
Bokeh: injecting script tag for BokehJS library:  https://cdn.pydata.org/bokeh/release/bokeh-tables-1.4.0.min.js main.min.js:233:15
Bokeh: injecting script tag for BokehJS library:  https://cdn.pydata.org/bokeh/release/bokeh-gl-1.4.0.min.js main.min.js:233:15
[bokeh] document idle at 29 ms bokeh-1.4.0.min.js:242:1545
Bokeh: all BokehJS libraries/stylesheets loaded main.min.js:205:17
Bokeh: BokehJS plotting callback run at 
Date Mon Mar 02 2020 21:43:49 GMT+0100 (Central European Standard Time)
main.min.js:289:15
[bokeh] setting log level to: 'info' bokeh-1.4.0.min.js:317:2257
Bokeh: all callbacks have finished main.min.js:183:13
Source map error: Error: request failed with status 403
Resource URL: https://cdn.pydata.org/bokeh/release/bokeh-1.4.0.min.js
Source Map URL: bokeh.min.js.map
```
#### Screenshots or screencasts of the bug in action
rect_glyph_hover

Thanks a lot!

### PR DESCRIPTION
**Pull request by mattpap**
Supersedes PR #10772.

fixes #9752

### CODE REVIEW

File: bokehjs/src/lib/core/util/affine.ts [hunk 1]
```diff
@@ -1,12 +1,13 @@
 import {Arrayable} from "../types"
+import {type XY} from "./bbox"
```
Comment (ianthomas23) [inline bokehjs/src/lib/core/util/affine.ts]: TypeScript question: `import {XY}` would work OK here, so is `import {type XY}` considered better practice?

File: bokehjs/src/lib/core/util/affine.ts [hunk 2]
```diff
@@ -144,3 +156,14 @@ export class AffineTransform {
     return this.scale(-1, 1)
   }
 }
+
+export function rotate_around(p: XY, c: XY, angle: number): XY {
```
Comment (ianthomas23) [inline bokehjs/src/lib/core/util/affine.ts]: It might be better to use `center` instead of `c` here for increased clarity.

**Review by ianthomas23 — APPROVED** [review]
I've manually confirmed this fixes the original issue, so I'm approving with one question and one recommendation.

File: bokehjs/src/lib/core/util/affine.ts (hunk 1 above)
Comment (mattpap) [reply bokehjs/src/lib/core/util/affine.ts]: It would be OK there. In fact it's unnecessary to indicate `type` import here. Type imports, so either `import {type XY}` or `import type {XY}` (same thing different granularity) are useful or even required if you have a type and an object (e.g. a class is an object) of the same name. Then you either can indicate that an import is for type purpose only, or you have to indicate if otherwise there would be a risk of introducing a value import. This is important, because type imports are erased, but value imports are not. Thus to avoid cyclic dependencies on the value-level or break JS bundle separation, it may be required to use type imports. A good example are glyphs and GL glyphs, where GL glyphs have to use type imports to not allow accidental cyclic dependency on glyphs (except for types), where glyphs already depend on GL glyphs through dynamic value imports.

Additionally, type re-exports (`export {type XY}`) are also necessary whenever re-exporting a name associated solely with a type, since recent switch to isolated modules in TypeScript. Though this is something you will rarely encounter on your own, and I'm trying to reduce unnecessary re-exports.
