### PR TITLE
Fix rendering on JupyterHub 4.1: respect `absolute_url` for protocol determination, support `data-absolute-url`

### LINKED ISSUE #7039: Panel preview does not work on JupyterHub 4.1+ hosted on a single domain
JupyterHub [4.1](https://jupyterhub.readthedocs.io/en/stable/reference/changelog.html#id20) was released on 20th of March 2024 fixing https://github.com/jupyterhub/jupyterhub/security/advisories/GHSA-7r3h-4ph8-w38g. The fix included a restriction to the Content Security Policy set by default on headers of all jupyter-server responses. This in turn silently broke all applications which relied on embedding the content in an IFrame, including `viola` and `panel` (https://github.com/jupyterhub/jupyterhub/issues/4823).

I think this was first reported on Holoviz Discourse on 12th of April as a comment in [this thread](https://discourse.holoviz.org/t/widget-updates-appear-blocked-by-python-until-process-in-complete-in-deployed-app/7103/7).

#### ALL software version info

- panel: latest  (tested with `main` branch)
- bokeh: latest (tested with `branch-3.6` branch)
- pyviz_comms: latest (tested with `main` branch)
- jupyterhub: 4.1 or 5.0
- browser: all modern browsers (Chrome/Firefox/Safari/Edge); not Internet Explorer in which it works because it does not respect CSP

#### Description of expected behavior and the observed behavior

The "Preview with Panel" button works but after the loading screen an error screen is shown instead of the preview.

#### Complete, minimal, self-contained example code that reproduces the issue

```py
import numpy as np
import pandas as pd
import holoviews as hv
import panel as pn
pn.extension()

n = pn.widgets.IntSlider(name='n', start=1, end=100, value=50)

def scatter(n):
    data = {"group": np.random.randint(0, 10, n), "value": np.random.randn(n)}
    return hv.Scatter(data, kdims="group", vdims="value").sort().opts()

dashboard = pn.template.MaterialTemplate(
    title="Test",
    sidebar=[pn.WidgetBox(pn.Column("""Description""", n))],
    main=[pn.pane.HoloViews(pn.bind(scatter, n))],
)

dashboard.servable()
```

#### Stack traceback and/or browser JavaScript console output

```
Refused to frame 'https://an.up-to-date.jupyterhub.deployment/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'none'".
```

#### Screenshots or screencasts of the bug in action

Initially the loading screen shows up ok:

image

But afterwards once the `src` has completed loading, the error screen is revealed:

image

- [x] I may be interested in making a pull request to address this

### LINKED ISSUE #14002: [BUG] Embedded server websocket cannot be used in `srcdoc` iframe
### Software versions

Python version        :  3.10.10 (main, Feb 18 2023, 16:54:09) [GCC 12.2.0]
IPython version       :  8.26.0
Tornado version       :  6.4.1
Bokeh version         :  3.6.0.dev1+20.ga8e63cac.dirty
BokehJS static path   :  ~/bokeh/src/bokeh/server/static
node.js version       :  v18.13.0
npm version           :  10.5.0
jupyter_bokeh version :  (not installed)
Operating system      :  Linux-6.5.0-44-generic-x86_64-with-glibc2.38

### Browser name and version

_No response_

### Jupyter notebook / Jupyter Lab version

_No response_

### Expected behavior

Bokeh can connect the websocket even when run in an `srcdoc` iframe, and thus can work on JupyterHub 4.1+ in the Panel preview (https://github.com/holoviz/panel/issues/7039) - once PR https://github.com/holoviz/pyviz_comms/pull/125 is merged.

### Observed behavior

Bokeh assumes that it always works in the context of a standalone page, not considering that it may be running in an `srcdoc` iframe:

1. It uses `window.location` to determine the protocol, even if an absolute URL is given:
   https://github.com/bokeh/bokeh/blob/b902fb51d8f832e6634192cc793a7329dd7da0ce/bokehjs/src/lib/embed/server.ts#L10-L14
    however, in an `srcdoc` iframe there is no `location.href` so the correct protocol cannot be determined in. One solution would be using `window.parent.location`, as it points to the top-level window even in an iframe. Another is to respect the `absolute_url`.
2. while `absolute_url` can be passed as an argument; `srcdoc` iframe cannot pass arguments easily other than via data attributes.

### Example code

```Python
-
```

### Stack traceback or browser console output

_No response_

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by krassowski**
- [x] issues: fixes #14002
   - which together with https://github.com/holoviz/pyviz_comms/pull/125
   - helps to fix https://github.com/holoviz/panel/issues/7039
- [x] tests passed (see below for manual testing instructions)
- [ ] release document entry (if new feature or API change)

This PR:
-  fixes `ws`/`wss` determination when `absolute_url` is passed
- supports reading the absolute URL from `data-absolute-url` of an iframe as `srcdoc` iframes cannot pass it otherwise (e.g. there is no motion of URL parameters for these)

| Before | After |
|--|--|
| Screenshot from 2024-07-29 17-16-06 | Screenshot from 2024-07-29 17-29-59 |

<details>

<summary>How to test without installing JupyterHub</summary>

1. Install pyviz_comms with https://github.com/holoviz/pyviz_comms/pull/125 applied
2. Run `jupyter --paths` and choose a writable config path from the `config:` section, e.g. `/home/username/my-env/etc/jupyter`
3. Open (create if needed) a `/home/username/my-env/etc/jupyter/jupyter_server_config.py`, paste the following:
   ```py
    c.LabApp.tornado_settings = {
        'hub_prefix': '/hub',
        'hub_host': 'test',
        'user': 'test',
        'headers': {'Content-Security-Policy': "frame-ancestors 'none'"}
    }
   ```
4. Start `jupyter lab`
5. Open dev tools Network tab, click on a request and expand Response Headers, verify that CSP for frame ancestors is set to none:
   image
6. Ensure that page data includes `hubPrefix` by viewing the source of JupyterLab page
   Screenshot from 2024-07-30 10-06-57
7. Follow reproduction steps in https://github.com/holoviz/panel/issues/7039

</details>

### CODE REVIEW

File: bokehjs/src/lib/embed/server.ts [hunk 1]
```diff
@@ -8,9 +8,10 @@ import type {EmbedTarget} from "./dom"
 
 // @internal
 export function _get_ws_url(app_path: string | undefined, absolute_url: string | undefined): string {
-  let protocol = "ws:"
-  if (window.location.protocol == "https:") {
-    protocol = "wss:"
+  // if in an `srcdoc` iframe, try to get the absolute URL
+  // from the `data-absolute-url` attribute if not passed explicitly
+  if (absolute_url === undefined && frameElement !== null && (frameElement as HTMLIFrameElement).dataset.absoluteUrl !== undefined) {
+    absolute_url = (frameElement as HTMLIFrameElement).dataset.absoluteUrl
```
Comment (mattpap) [inline bokehjs/src/lib/embed/server.ts]: Let's remove all this casting with:
```suggestion
  if (absolute_url === undefined && frameElement instanceof HTMLElement && frameElement.dataset.absoluteUrl !== undefined) {
    absolute_url = frameElement.dataset.absoluteUrl
  }
```
or alternatively use `HTMLIFrameElement` instead of `HTMLElement`, though I'm not sure if we need to be that specific.

File: bokehjs/src/lib/embed/server.ts [hunk 2]
```diff
@@ -21,6 +22,11 @@ export function _get_ws_url(app_path: string | undefined, absolute_url: string |
     loc = window.location
   }
 
+  let protocol = "ws:"
+  if (loc.protocol == "https:") {
+    protocol = "wss:"
+  }
+
```
Comment (mattpap) [inline bokehjs/src/lib/embed/server.ts]: Also let's get rid of a mutable variable:
```suggestion
  const protocol = loc.protocol == "https:" ? "wss:" : "ws:"
```

File: bokehjs/src/lib/embed/server.ts (hunk 1 above)
Comment (krassowski) [reply bokehjs/src/lib/embed/server.ts]: My thinking was the same here! But it does not work. This is because `frameElement` is an `HTMLElement`, but not `window.HTMLElement`. It is an `HTMLElement` from the context of the parent frame. I can make this work without type cast by checking for the right instance - which is just a bit more code - but `frameElement` by definition is an `HTMLElement` ("element" is in the name).

Comment (krassowski) [reply bokehjs/src/lib/embed/server.ts]: Do you still think I should modify it here or do you agree with the type cast here?

**Comment by mattpap** [comment]
We need to be able to test this somehow, preferably outside of jupyter. Perhaps an example showing `<iframe>` embedding would suffice (under `examples/server`).

File: bokehjs/src/lib/embed/server.ts (hunk 1 above)
Comment (krassowski) [reply bokehjs/src/lib/embed/server.ts]: For example, using `frameElement instanceof window.parent.HTMLElement` can result in:

```
DOMException: Failed to read a named property 'HTMLElement' from 'Window': Blocked a frame with origin "http://localhost:5151" from accessing a cross-origin frame.
```

Comment (krassowski) [reply bokehjs/src/lib/embed/server.ts]: Resolved in https://github.com/bokeh/bokeh/pull/14003/commits/c639a85a7a571d0075e78b6804613d9af6ecea99

**Comment by krassowski** [comment]
@mattpap thank you for your review (dziękuję!) - I've added an example which both demonstrates the problem and a solution under `examples/server/embed`:

image

I also added a dedicated type guard to remove the explicit type cast (I do not like them either!).

**Comment by bryevdv** [comment]
`examples/server` should only contain subdirectories to match the docs structure, not individual examples. Also "embed" by itself is too general, there are lots of concepts about embedding. Possible suggestions:

* `examples/server/app/iframe_embed`
* somewhere under `examples/integration`

**Comment by krassowski** [comment]
Thank you @bryevdv, I moved it to `examples/server/app/iframe_embed` following your suggestion.

**Comment by bryevdv** [comment]
@mattpap will have to comment on the test screenshot error 
```
ERROR: Path for Bokeh server application does not exist: /home/runner/work/bokeh/bokeh/bokeh_server.py
tests/test_examples.py::test_server_examples[/home/runner/work/bokeh/bokeh/examples/server/app/iframe_embed-example12-config12] 
[FAIL] Unhandled rejection at:  ProtocolError: Cannot take screenshot with 0 width.
    at /home/runner/work/bokeh/bokeh/bokehjs/node_modules/chrome-remote-interface/lib/chrome.js:94:35
    at Chrome._handleMessage (/home/runner/work/bokeh/bokeh/bokehjs/node_modules/chrome-remote-interface/lib/chrome.js:272:17)
    at WebSocket.<anonymous> (/home/runner/work/bokeh/bokeh/bokehjs/node_modules/chrome-remote-interface/lib/chrome.js:240:22)
    at WebSocket.emit (node:events:518:28)
    at Receiver.receiverOnMessage (/home/runner/work/bokeh/bokeh/bokehjs/node_modules/chrome-remote-interface/node_modules/ws/lib/websocket.js:1070:20)
    at Receiver.emit (node:events:518:28)
    at Receiver.dataMessage (/home/runner/work/bokeh/bokeh/bokehjs/node_modules/chrome-remote-interface/node_modules/ws/lib/receiver.js:517:14)
    at Receiver.getData (/home/runner/work/bokeh/bokeh/bokehjs/node_modules/chrome-remote-interface/node_modules/ws/lib/receiver.js:435:17)
    at Receiver.startLoop (/home/runner/work/bokeh/bokeh/bokehjs/node_modules/chrome-remote-interface/node_modules/ws/lib/receiver.js:143:22)
    at Receiver._write (/home/runner/work/bokeh/bokeh/bokehjs/node_modules/chrome-remote-interface/node_modules/ws/lib/receiver.js:78:10) {
  request: {
    method: 'Page.captureScreenshot',
    params: { format: 'png', clip: [Object] },
    sessionId: undefined
  },
  response: { code: -32000, message: 'Cannot take screenshot with 0 width.' }
}

FAILED
```

**Comment by krassowski** [comment]
Looking at:

https://github.com/bokeh/bokeh/blob/54252f8ba722a01a249df0aa603899cc1bbb2349/tests/examples.yaml#L18-L31

It seems that similar examples (e.g. examples `server_document`, `json_item`) are skipped. Should this one be skipped too?

**Comment by bryevdv** [comment]
> Should this one be skipped too?

Let's just go with that option for now

**Comment by krassowski** [comment]
It did not help. I think this is because the top-level file is not an example of Bokeh server with a single handler, but a flask application which embeds code which connects to the server running in a subprocess.

I am not sure how to proceed, possibly moving it elsewhere would be better. If a maintainer would prefer to rehash it please do push to my branch.

**Comment by krassowski** [comment]
Sorry, I was wrong it did help, another job failed which appears unrelated. I will restart CI by pushing an empty commit to see if it helps.

**Comment by krassowski** [comment]
Previously `Bokeh-CI / unit-test (macos-latest, 3.12)` failed and now `Bokeh-CI / unit-test (macos-latest, 3.11)` failed - it looks like the macos tests are flaky, is this correct?

**Comment by bryevdv** [comment]
Yes there is one server test that probably ought to get a retry policy or similar.

**Comment by bryevdv** [comment]
@krassowski I really appreciate your patience, I have one more request. After thinking about it, I would prefer this live under `examples/server/api` instead of `app`. All the examples under `app` are meant to be run with `bokeh serve` by the user, this example is much more like the embedding examples under `api`.  I don't want to create confusion where someone tries to run `bokeh serve iframe_embed` (like all the other directory examples there) and it does not work.

**Comment by krassowski** [comment]
@bryevdv make sense - done, and it looks all tests passed!

**Review by bryevdv — APPROVED** [review]

**Comment by bryevdv** [comment]
Thanks @krassowski !

**Comment by krassowski** [comment]
Amazing, thank you! Is there a chance for backporting this PR or will it be only available in 3.6?

**Comment by bryevdv** [comment]
It seems like it would be easy to backport, so I have added the label. However, that just means that _if_  there is a new release on previous branches, then this is a candidate to go in it. It's reasonably likely there will end up being more earlier point releases, but I can't guarantee it.

Edit: though looking at other PRs marked for backport, it seems fairly like there will be at some point.

**Comment by bryevdv** [comment]
@krassowski this fix is available now in 3.5.2
