### PR TITLE
Fix bug in draw legend method of text glyph

### LINKED ISSUE #2698: plot.text(legend="") results in console traceback and clipped legend rendering
```python
plot.line(x, y1, legend="Change", line_width=2)
plot.circle(x, y2, legend="Peaks", fill_color="white", size=8)
plot.text(x3, y2, text=y3_data, text_color="blue", legend="x")
plot.text(x3, y2, text=y3_data, text_color="red", legend="y")
```

The legend should have two text glyph entries; x and y. If I render a text glyph before other (normal) glyphs, then all of the legend entries are blank, though space is allocated for them.
image

```python
plot.text(x3, y2, text=y3_data, text_color="blue", legend="x")
plot.text(x3, y2, text=y3_data, text_color="red", legend="y")
plot.line(x, y1, legend="Change", line_width=2)
plot.circle(x, y2, legend="Peaks", fill_color="white", size=8)
```
image

```
bokeh-0.9.2.js:53135
Uncaught TypeError: text_props.font is not a function
114.TextView.draw_legend @ bokeh-0.9.2.js:53135
87.GlyphRendererView.draw_legend @ bokeh-0.9.2.js:50016
77.LegendView.render @ bokeh-0.9.2.js:48049
50.PlotView._render_levels @ bokeh-0.9.2.js:44183
50.PlotView.render @ bokeh-0.9.2.js:44148
53.later @ bokeh-0.9.2.js:44617
```

The line that I commented here causes the legend to render correctly:
image

But also, sadly, does not show 'txt' in the color I specified for the glyph:
image

### PR DESCRIPTION
**Pull request by canavandl**
issues: fixes #2698 

Fix bug in draw legend method of text glyph.

### CODE REVIEW

File: bokehjs/src/coffee/renderer/glyph/text.coffee [hunk 1]
```diff
@@ -21,15 +25,10 @@ class TextView extends Glyph.View
...
-      glyph_settings = reference_point
-    else
-      glyph_settings = @props
-    text_props = @visuals.text
-    text_props.set(ctx, glyph_settings)
+    @text_props.set_value(ctx)
     # override some features so we fit inside the legend
-    ctx.font = text_props.font(12)
+    ctx.font = @text_props.font_value()
+    ctx.font = ctx.font.replace(/\b[\d\.\d]+[\w]+\b/, '10pt')
```
Comment (bryevdv) [inline bokehjs/src/coffee/renderer/glyph/text.coffee]: is the second `\d` necessary in the square brackets?

Comment (canavandl) [inline bokehjs/src/coffee/renderer/glyph/text.coffee]: It's meant to cover the case that somebody passes the ".5pt" as a text_font_size. Otherwise, it can't hurt I think?

Comment (bryevdv) [inline bokehjs/src/coffee/renderer/glyph/text.coffee]: Can't hurt, but superfluous (so it might confuse someome). It will match "3.5pt" without it (square brackets imply no order)

screen shot 2015-08-10 at 10 02 38 pm

**Comment by canavandl** [comment]
Example
screenshot 2015-08-11 at 12 03 51 am

```python
from bokeh.plotting import output_file, show, figure
output_file("legend.html")
plot = figure()
x1 = (1, 2, 3)
y1 = (1, 2, 3)
plot.line(x1, y1, legend="Change", line_width=2)
plot.text(1.5, 1, text=['hello'], text_color="blue", legend="x", text_font_style='italic', text_font='helvetica', text_font_size='50px')
plot.text(2.5, 2, text=['world'], text_color="red", legend="y", text_font_style='bold', text_font='roboto', text_font_size='2.5em')
show(plot)
```

**Comment by bryevdv** [comment]
This is good, only suggestion maybe "text" instead of "txt"
