### PR TITLE
Fix Surface3D example type errors

### LINKED ISSUE #14300: Surface3d example is broken
The extension currently fails to compile cc @mattpap 
```
dev312 ❯ bokeh serve --show surface3d
2025-02-08 17:12:40,641 Starting Bokeh server version 3.7.0.dev5+28.g65e644fd (running on Tornado 6.4.2)
2025-02-08 17:12:40,642 User authentication hooks NOT provided (default user enabled)
2025-02-08 17:12:40,643 Bokeh app running at: http://localhost:5006/surface3d
2025-02-08 17:12:40,643 Starting Bokeh server with process id: 42504
Compilation failed:

surface3d/surface3d.ts:86:12 - error TS7053: Element implicitly has an 'any' type because expression of type 'string' can't be used to index type 'Data'.
  No index signature with a parameter of type 'string' was found on type 'Data'.

86         x: source.data[this.model.x][i],
              ~~~~~~~~~~~~~~~~~~~~~~~~~
surface3d/surface3d.ts:87:12 - error TS7053: Element implicitly has an 'any' type because expression of type 'string' can't be used to index type 'Data'.
  No index signature with a parameter of type 'string' was found on type 'Data'.

87         y: source.data[this.model.y][i],
              ~~~~~~~~~~~~~~~~~~~~~~~~~
surface3d/surface3d.ts:88:12 - error TS7053: Element implicitly has an 'any' type because expression of type 'string' can't be used to index type 'Data'.
  No index signature with a parameter of type 'string' was found on type 'Data'.

88         z: source.data[this.model.z][i],
              ~~~~~~~~~~~~~~~~~~~~~~~~~
surface3d/surface3d.ts:138:34 - error TS2345: Argument of type '({ Unknown, Str, Dict, Ref }: typeof import("/Users/bryan/work/bokeh/src/bokeh/server/static/js/lib/core/kinds")) => { x: [Str]; y: [Str]; z: [Str]; data_source: [Ref<ColumnDataSource>]; options: [Dict<unknown>, { width: string; height: string; style: string; showPerspective: boolean; showGrid: boolean; keepAspectRatio: boolean; verticalRatio: number; legendLabel: string; cameraPosition: { horizontal: number; vertical: number; distance: number; }; }]; }' is not assignable to parameter of type 'Partial<DefineOf<Props, HasProps>> | ((types: typeof import("/Users/bryan/work/bokeh/src/bokeh/server/static/js/lib/core/kinds")) => Partial<DefineOf<Props, HasProps>>)'.
  Type '({ Unknown, Str, Dict, Ref }: typeof import("/Users/bryan/work/bokeh/src/bokeh/server/static/js/lib/core/kinds")) => { x: [Str]; y: [Str]; z: [Str]; data_source: [Ref<ColumnDataSource>]; options: [Dict<unknown>, { width: string; height: string; style: string; showPerspective: boolean; showGrid: boolean; keepAspectRatio: boolean; verticalRatio: number; legendLabel: string; cameraPosition: { horizontal: number; vertical: number; distance: number; }; }]; }' is not assignable to type '(types: typeof import("/Users/bryan/work/bokeh/src/bokeh/server/static/js/lib/core/kinds")) => Partial<DefineOf<Props, HasProps>>'.
    Call signature return types '{ x: [Str]; y: [Str]; z: [Str]; data_source: [Ref<ColumnDataSource>]; options: [Dict<unknown>, { width: string; height: string; style: string; showPerspective: boolean; showGrid: boolean; keepAspectRatio: boolean; verticalRatio: number; legendLabel: string; cameraPosition: { horizontal: number; vertical: number; distance: number; }; }]; }' and 'Partial<DefineOf<Props, HasProps>>' are incompatible.
      Type at position 0 in source is not compatible with type at position 0 in target.
        The types of 'options' are incompatible between these types.
          Type 'Dict<unknown>' is not assignable to type 'PropertyAlias | PropertyConstructor<{ [key: string]: unknown; }> | Kind<{ [key: string]: unknown; }>'.
            Type 'Dict<unknown>' is not assignable to type 'Kind<{ [key: string]: unknown; }>'.
              Types of property '__type__' are incompatible.
                Type 'Dict<unknown>' is not assignable to type '{ [key: string]: unknown; }'.
                  Type 'Map<string, unknown>' is not assignable to type '{ [key: string]: unknown; }'.
                    Index signature for type 'string' is missing in type 'Map<string, unknown>'.

138     this.define<Surface3d.Props>(({Unknown, Str, Dict, Ref}) => ({
                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
139       x:           [ Str ],
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~
...
143       options:     [ Dict(Unknown), OPTIONS ],
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
144     }))
    ~~~~~~
```

### PR DESCRIPTION
**Pull request by RamiDarwiche**
This fixes surface3d by resolving a couple typescript errors. Please let me know if I should make any additional changes.

fixes #14300 

Edit: Sorry! I hadn't realized my branch wasn't synced before opening the PR. I'm not sure what the best course of action is for removing the extra commits.

### CODE REVIEW

File: examples/server/app/surface3d/surface3d.ts [hunk 1]
```diff
@@ -81,11 +81,12 @@ export class Surface3dView extends LayoutDOMView {
   get_data(): vis.DataSet {
     const data = new vis.DataSet()
     const source = this.model.data_source
+    const data_dict = source.data as Record<string, number[]>
```
Comment (mattpap) [inline examples/server/app/surface3d/surface3d.ts]: You can't just assume this. Depending on the context, `data` may be provided as a plain object (`Record<K, V>`) or a mapping (`Map<K, V>`). You have to use appropriate APIs to deal with this. In this situation you can either use `ColumnarDataSource.get()` like this:
```ts
const x = source.get(this.model.x)
//
x[i]
```
or
```ts
import {dict} from "core/util/object"
const data_dict = dict(source.data)
//
data_dict.get(this.model.x)[i]
```

File: examples/server/app/surface3d/surface3d.ts [hunk 2]
```diff
@@ -81,11 +81,12 @@ export class Surface3dView extends LayoutDOMView {
...
     for (let i = 0; i < source.get_length()!; i++) {
       data.add({
-        x: source.data[this.model.x][i],
-        y: source.data[this.model.y][i],
-        z: source.data[this.model.z][i],
+        x: (data_dict[this.model.x])[i],
+        y: (data_dict[this.model.y])[i],
+        z: (data_dict[this.model.z])[i],
```
Comment (mattpap) [inline examples/server/app/surface3d/surface3d.ts]: Parentheses are unnecessary.

File: examples/server/app/surface3d/surface3d.ts [hunk 3]
```diff
@@ -135,12 +136,12 @@ export class Surface3d extends LayoutDOM {
...
     // ``p.String`` in the JS implementation. Where the JS type system is not yet
     // as rich, you can use ``p.Any`` as a "wildcard" property type.
-    this.define<Surface3d.Props>(({Unknown, Str, Dict, Ref}) => ({
+    this.define<Surface3d.Props>(({Str, Any, Ref}) => ({
       x:           [ Str ],
       y:           [ Str ],
       z:           [ Str ],
       data_source: [ Ref(ColumnDataSource) ],
-      options:     [ Dict(Unknown), OPTIONS ],
+      options:     [ Any, OPTIONS ],
```
Comment (mattpap) [inline examples/server/app/surface3d/surface3d.ts]: You can't remove type information and hope for the best, because this will fail on run time in certain situations. Instead, you have to restore this and update the type of `options` in `Surface3d.Props` appropriately, i.e. use `Dict<T>` type from `core/util/types`. Then you have to adjust the use site of `options` to reflect this change (probably `to_object()` from `core/util/object` is the tool for this).

**Comment by mattpap** [comment]
Commit history needs fixing. You have remove the merge commit and then rebase your commits onto `origin/branch-3.7`. For this use `git rebase --onto origin/branch-3.7 f03b6b1~1` (SHA of you first commit).

**Comment by RamiDarwiche** [comment]
@mattpap This latest commit implements your suggestions and fixes the commit history. Thank you for your guidance, I'll be more thorough with my types moving forward!

**Review by mattpap — APPROVED** [review]

**Comment by mattpap** [comment]
@RamiDarwiche, thanks.
