### PR TITLE
Fix bug in LinearColorMapper.build_palette.

### LINKED ISSUE #2801: Bug in linear_color_mapper palette generation
Problem demonstrated [here](http://nbviewer.ipython.org/urls/gist.githubusercontent.com/dwf/3a1fe69fc287b600ad14/raw/bc41d84d44da84bf41fa7cf7df29dc26bd290e03/Bokeh%2520Image%2520Weirdness.ipynb). Basically some of the images get rendered as weird outlines by Bokeh but by nothing else, including matplotlib (see the matplotlib reference below). Looks like an overflow problem maybe? Except dividing by 255.0 and thus casting to float64 doesn't fix it, so I think it must be an overflow problem *after* it's converted back to uint8 for rasterization.

Here's a [self-contained example](http://nbviewer.ipython.org/urls/gist.githubusercontent.com/dwf/d6cb127fff520420da86/raw/d19c28a23c0b4340d65e03f97ae3dc3c4c56c083/Bokeh%2520Image%2520Weirdness%2520Self-Contained.ipynb) reproducing the problem, with the data included (rather than relying on a third party package).

### PR DESCRIPTION
**Pull request by dwf**
Fixes #2801, by correctly converting non-number values for the last value of the passed in palette when assigning to the last entry in the new palette.

Note that I am unclear on why extending the palette by one entry is necessary in the first place. It seems like a better solution to just make `new_palette.length` equal to `palette.length`, and delete the offending line after the loop.

### CODE REVIEW

**Comment by dwf** [comment]
@damianavila It would be great if this (or the proposed better fix in the description) made it into that dev release, too.

File: bokehjs/src/coffee/mapper/linear_color_mapper.coffee [hunk 1]
```diff
@@ -70,12 +70,14 @@ class LinearColorMapper extends HasProperties
...
+    _convert = (value) ->
+      if _.isNumber(value)
+        return value
       else
-        new_palette[i] = parseInt(palette[i].slice(1), 16)
-    new_palette[new_palette.length-1] = palette[palette.length-1]
+        return parseInt(value.slice(1), 16)
+    for i in [0...palette.length]
+      new_palette[i] = _convert palette[i]
+    new_palette[new_palette.length-1] = _convert palette[palette.length-1]
```
Comment (bryevdv) [inline bokehjs/src/coffee/mapper/linear_color_mapper.coffee]: we always use parens for function invocation.

Comment (dwf) [inline bokehjs/src/coffee/mapper/linear_color_mapper.coffee]: @bryevdv I've amended the commit as 3e3c392 (and amended my whining out of the commit message).

**Comment by bryevdv** [comment]
Thanks @dwf
