### PR TITLE
Start a BokehJS interface

### LINKED ISSUE #1515: Restore BokehJS interface
`Bokeh.plotting` is currently badly broken in 0.7. Propose to remove current interface completely, and replace with a new better interface that is built into a separate module `bokeh-api.js`

Note: going through and closing basically all old BokehJS issues. Rationale is to collect references to them here, so that the new JS interface can incorporate all of them (or what makes sense) in a holistic rather than piecemeal fashion.

### PR DESCRIPTION
**Pull request by bryevdv**
issues: closes #1515

### CODE REVIEW

**Comment by bryevdv** [comment]
Idea for basic interface, support different "APIs" through a `bokeh` function:
```
$('#foo').bokeh("figure", { ..... })   # similar to plotting.py, user adds glyphs

$('#foo').bokeh("histogram", { .... }) # higher level interface (later)
```
@bokeh/dev does this seem reasonable for a (simple) start, with React and/or Angular integrations later?

**Comment by damianavila** [comment]
This is looking good to me for now, but I guess this will not be ready to 0.8.0, maybe 0.8.1 is a better target? or you want to include it?

**Comment by bryevdv** [comment]
Let me see what I can get done in a few hours...

**Comment by bryevdv** [comment]
So I'd like to make a few more tweaks but I think this could be included basically as-is with an "alpha" disclaimer. Thoughts?

File: bokehjs/src/coffee/api/figure.coffee [hunk 1]
```diff
@@ -1,25 +1,212 @@
...
+  "./helpers"
+], (base, Logging, FactorRange, ColumnDataSource) ->
 
+  Collections = base.Collections
   logger = Logging.logger
 
-  class Figure extends Plot.Model
-    default_view: Plot.PlotView
+  if not Array.prototype.every
+    Array.prototype.every = (f) -> (x for x in @ when f(x)).length == @length
```
Comment (mattpap) [inline bokehjs/src/coffee/api/figure.coffee]: Use `_.every(arr, fn)`. Also, modifying built-ins is a very, very bad idea.

**Comment by bryevdv** [comment]
@mattpap can you spend the next 1-2 hours and just make any quick, isolated improvements you deem worthy?

File: bokehjs/src/coffee/api/plugin.coffee [hunk 2]
```diff
@@ -0,0 +1,27 @@
...
+], (_, $, Logging, figure, helpers) ->
+
+  logger = Logging.logger
+  show = helpers.show
+
+  _api = {
+    "figure": figure
+  }
+
+  $.fn.bokeh = (type, args) ->
```
Comment (mattpap) [inline bokehjs/src/coffee/api/plugin.coffee]: Given that this module uses bokeh's jquery, not the possibly available global one, this code isn't going to do what's expected (this will modify `Bokeh.$`).

Comment (mattpap) [inline bokehjs/src/coffee/api/plugin.coffee]: On a side note. I universally hate creating APIs this way. If, for some reason, we really want to have a jquery plugin, then we should first create a in-bokeh well defined API, like `Bokeh.figure({...})` (or `Bokeh.API.figure({...})`) and then we can expose a jquery plugin, by making user include a special/additional javascript file, say `jquery.bokeh.js`.

**Comment by bryevdv** [comment]
@damianavila this is as done as it will be

**Comment by mattpap** [comment]
@bryevdv, unless you want to test each commit individually, I suggest stopping unwanted travis-ci jobs and/or push commits in bulk. Currently we have 12 open travis-ci jobs, which will be about half a day of running time.

**Comment by mattpap** [comment]
> can you spend the next 1-2 hours and just make any quick, isolated improvements you deem worthy?

Anything specific? It's rather inefficient to get in the way of someone else's major changes.

**Comment by bryevdv** [comment]
@mattpap I will stop the jobs. Don't worry about this PR am going to merge it as-is with an "alpha" admonition in the docs.

**Comment by damianavila** [comment]
As far as I tested, all the example left here are working...

File: bokehjs/src/coffee/api/plugin.coffee (hunk 2 above)
Comment (bryevdv) [inline bokehjs/src/coffee/api/plugin.coffee]: There is an in-bokeh well defined API, it's the three lines that comprise the definition of the plugin. If you want to split the plugin out, It think that's great, in fact splitting off `bokehjs-api.js` into a separate package was the first thing I was going to ask for your help will after 0.8.

Comment (bryevdv) [inline bokehjs/src/coffee/api/plugin.coffee]: @mattpap I see what you are saying, however it is that case that all the examples do work using `$().bokeh)`, regardless of whether they use `require` or are a bare script. I am not sure why that should be the case, though, given what you have mentioned. Are there any immediate changes you would propose?

Comment (mattpap) [inline bokehjs/src/coffee/api/plugin.coffee]: > it is that case that all the examples do work using $().bokeh

So this should actually be true because jquery isn't a true/at all an AMD module, we just fake it with `noConflict` if jquery was already included in a page. The current approach doesn't make any harm, maybe besides confusing users. As this is alpha/experimental API, I would just leave it as-is and figure out it for the next release (so basically what you were saying in previous comment).

**Comment by damianavila** [comment]
OK, green, let's merge it as alpha...
