### PR TITLE
Fix image hover values in custom hover templates

### LINKED ISSUE #14054: [BUG] Custom hover tooltip on image plot shows all the image data.
### Software versions

Python version 3.11.4| Bokeh version 3.5.2

### Browser name and version

_No response_

### Jupyter notebook / Jupyter Lab version

_No response_

### Expected behavior

When I hover over an image plot (heatmap) using custom tooltip, I expect to get a tooltip like that I get with the code below (without custom tooltip):

```
import numpy as np
from bokeh.plotting import figure, show
from bokeh.models import ColumnDataSource,HoverTool

x = np.linspace(0, 10, 300)
y = np.linspace(0, 10, 300)
xx, yy = np.meshgrid(x, y)
d = np.sin(xx) * np.cos(yy)

s1 = ColumnDataSource(data=dict(x=[xx], y=[yy], image=[d]))
p = figure(width=400, height=400)
p.x_range.range_padding = p.y_range.range_padding = 0
p.image(image='image',source=s1, x=0, y=0, dw=10, dh=10, palette="Sunset11", level="image")
hover = HoverTool(tooltips=[
    ("index", "$index"),
    ("(x,y)", "($x, $y)"),
    ("Temperature", "@image"),],
    mode='mouse',)
p.add_tools(hover)
show(p)
```
Screenshot_20240907_042606

### Observed behavior

However, the custom tooltip for @image shows all the data instead of a specific number. The code with the custom tooltip is below.
Screenshot_20240907_042305

### Example code

```Python
import numpy as np
from bokeh.plotting import figure, show
from bokeh.models import ColumnDataSource,HoverTool

x = np.linspace(0, 10, 300)
y = np.linspace(0, 10, 300)
xx, yy = np.meshgrid(x, y)
d = np.sin(xx) * np.cos(yy)

s1 = ColumnDataSource(data=dict(x=[xx], y=[yy], image=[d]))
p = figure(width=400, height=400)
p.x_range.range_padding = p.y_range.range_padding = 0
p.image(image='image',source=s1, x=0, y=0, dw=10, dh=10, palette="Sunset11", level="image")
p.add_tools(HoverTool(tooltips="""<div style="background-color: #f0f0f0; padding: 5px; border-radius: 5px; box-shadow: 0px 0px 5px rgba(0,0,0,0.3);">        <font size="5" style="background-color: #f0f0f0; padding: 5px; border-radius: 5px;">
            <i>x:</i> <b>$x</b> <br> 
            <i>y:</i> <b>$y</b> <br>
            <i>image:</i> <b>@image</b> <br>
        </font> </div> <style> :host { --tooltip-border: transparent;  /* Same border color used everywhere */ --tooltip-color: transparent; --tooltip-text: #2f2f2f;} </style> """,
    ))
show(p)
```

### Stack traceback or browser console output

The issue reported initially here: https://discourse.bokeh.org/t/custom-hover-tooltip-over-image-plot-not-work-as-expected/11802.

I would appreciate it if you could give me any idea how to increase the font size of the default tooltip.

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by bryevdv**
fixes #14054 
 
I'm not going to have time to finish the swatch deprecation before the release, and it probably needs some discussion in any case. But I did want to include this small fix for image index handling in hover templates. 

With the OP code:

```python
import numpy as np
from bokeh.plotting import figure, show
from bokeh.models import ColumnDataSource,HoverTool

x = np.linspace(0, 10, 300)
y = np.linspace(0, 10, 300)
xx, yy = np.meshgrid(x, y)
d = np.sin(xx) * np.cos(yy)

s1 = ColumnDataSource(data=dict(x=[xx], y=[yy], image=[d]))
p = figure(width=400, height=400)
p.x_range.range_padding = p.y_range.range_padding = 0
p.image(image='image',source=s1, x=0, y=0, dw=10, dh=10, palette="Sunset11", level="image")
p.add_tools(HoverTool(tooltips="""<div style="background-color: #f0f0f0; padding: 5px; border-radius: 5px; box-shadow: 0px 0px 5px rgba(0,0,0,0.3);">        <font size="5" style="background-color: #f0f0f0; padding: 5px; border-radius: 5px;">
            <i>x:</i> <b>$x</b> <br>
            <i>y:</i> <b>$y</b> <br>
            <i>image:</i> <b>@image</b> <br>
        </font> </div> <style> :host { --tooltip-border: transparent;  /* Same border color used everywhere */ --tooltip-color: transparent; --tooltip-text: #2f2f2f;} </style> """,
    ))
show(p)
```

The hover now renders only a single value

Screenshot 2024-09-23 at 20 36 09

### CODE REVIEW

File: bokehjs/src/lib/core/util/templating.ts [hunk 1]
```diff
@@ -199,13 +199,12 @@ export function replace_placeholders(content: string | {html: string}, data_sour
...
 
-type PlaceholderReplacer = (type: PlaceholderType, name: string, format: string | undefined, i: number, spec: string) => string | null | undefined
+type PlaceholderReplacer = (type: PlaceholderType, name: string, format: string | undefined, spec: string) => string | null | undefined
 
 export function process_placeholders(text: string, fn: PlaceholderReplacer): string {
-  let i = 0
   return text.replace(regex, (_match, spec: string, format: string | undefined) => {
     const type = spec[0] as "@" | "$"
     const name = spec.substring(1).replace(/^{/, "").replace(/}$/, "").trim()
-    return fn(type, name, format, i++, spec) ?? MISSING
```
Comment (mattpap) [inline bokehjs/src/lib/core/util/templating.ts]: This `i` is used in tests. There are a few failures related to this.

File: bokehjs/src/lib/models/tools/inspectors/hover_tool.ts [hunk 2]
```diff
@@ -543,21 +546,15 @@ export class HoverToolView extends InspectToolView {
     return rows
   }
 
-  _render_template(template: HTMLElement, tooltips: [string, string][], ds: ColumnarDataSource, vars: TooltipVars): HTMLElement {
+  _render_template(template: HTMLElement, tooltips: [string, string][], ds: ColumnarDataSource, i: Index | null, vars: TooltipVars): HTMLElement {
```
Comment (mattpap) [inline bokehjs/src/lib/models/tools/inspectors/hover_tool.ts]: Let's call this by its full name `index` instead of `i`.

**Review by mattpap — APPROVED** [review]
