### PR TITLE
Rebuild GridBox when cols or rows change

### LINKED ISSUE #10498: [BUG] GridBox not rebuilt when changing cols or rows attributes
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
bokeh 2.2.1 with python 3.8

#### Description of expected behavior and the observed behavior
In an app, if a button allows changing a GridBox.cols attribute, nothing happens on the browser.
The typescript code is missing some connect calls. I'll create  a PR with the code.

#### Complete, minimal, self-contained example code that reproduces the issue
When the bug is corrected, pressing "Foo" changes the gridbox aspect.
Without corrections, one needs to press "Foo" then "Foo2"

```
from bokeh.io import curdoc
from bokeh.layouts import gridplot, column
from bokeh.models import Button
from bokeh.plotting import figure

x = list(range(11))
y0 = x
y1 = [10 - i for i in x]
y2 = [abs(i - 5) for i in x]

# create three plots
s1 = figure(plot_width=250, plot_height=250, background_fill_color="#fafafa", sizing_mode = "fixed")
s1.circle(x, y0, size=12, color="#53777a", alpha=0.8)

s2 = figure(plot_width=250, plot_height=250, background_fill_color="#fafafa", sizing_mode = "fixed")
s2.triangle(x, y1, size=12, color="#c02942", alpha=0.8)

button = Button(label="Foo", button_type="success")
@button.on_click
def _click():
    x.children[0].children[1].update(cols = {0: 100, 1: 200}, width = 300)

button2 = Button(label="Foo2", button_type="success")
@button2.on_click
def _click():
    x.children[0].children[1].update(children = x.children[0].children[1].children[::-1])

# put the results in a column and show
x = column([
    gridplot([s1, s2], ncols = 2, sizing_mode="fixed"),
    button, button2
])
x.children[0].children[1].update(cols = {0: 200, 1: 100}, width= 300)

curdoc().add_root(x)
```

### PR DESCRIPTION
**Pull request by poldavezac**
All pull requests must have an associated issue in the issue tracker. If there
isn't one, please go open an issue describing the defect, deficiency or desired
feature. You can read more about our issue and PR processes in the
[wiki](https://github.com/bokeh/bokeh/wiki/BEP-1:-Issues-and-PRs-management).

- [x] issues: fixes  #10498
- [x] tests added / passed
- [x] release document entry (if new feature or API change)

### CODE REVIEW

**Comment by bryevdv** [comment]
@poldavezac thanks for the PR, as long as you are updating this file, it seems like adding event hander for `spacing` property would make things complete.

@mattpap what is the relation between rows/cols and children? I guess I would have exepcted one to be derived from the the other but that does not seem to be the case. Is there currently any good system for adding tests for work like this?

**Comment by mattpap** [comment]
> what is the relation between rows/cols and children?

`rows` and `cols` allow to create a grid of the desired shape without altering children or even pre-populating a grid with children.

> Is there currently any good system for adding tests for work like this?

bokehjs' unit or visual integration tests. E.g. https://github.com/bokeh/bokeh/blob/603ccc5ab8ebdebb9d21e16aee135a6e780faf13/bokehjs/test/integration/regressions.ts#L303-L311
In fact my personal recent policy is that every PR fixing a bug must have a regression test committed. One can take the above test case and adapt it for the purpose of this PR, i.e. create a layout, await display, modify `rows`/`cols` and finally await ready.

File: bokehjs/src/lib/models/layouts/grid_box.ts [hunk 1]
```diff
@@ -9,6 +9,8 @@ export class GridBoxView extends LayoutDOMView {
   connect_signals(): void {
     super.connect_signals()
     this.connect(this.model.properties.children.change, () => this.rebuild())
+    this.connect(this.model.properties.rows.change, () => this.rebuild())
+    this.connect(this.model.properties.cols.change, () => this.rebuild())
```
Comment (mattpap) [inline bokehjs/src/lib/models/layouts/grid_box.ts:13]: This could be shortened and made more meaningful with (indicate that it's the same action in all cases):
```ts
const {children, rows, cols} = this.model.properties
this.on_change([children, rows, cold], () => this.rebuild())
```

Comment (bryevdv) [reply bokehjs/src/lib/models/layouts/grid_box.ts:13]: Add `spacing` as well?

Comment (mattpap) [reply bokehjs/src/lib/models/layouts/grid_box.ts:13]: Yes.

Comment (poldavezac) [reply bokehjs/src/lib/models/layouts/grid_box.ts:13]: I'll add spacing and the regression test

Comment (poldavezac) [reply bokehjs/src/lib/models/layouts/grid_box.ts]: done

**Comment by poldavezac** [comment]
As I understand it, failures are due to my not providing the regression test baselines for macos and windows. Unfortunately, I don't have the means to produce those.

File: bokehjs/test/integration/regressions.ts [hunk 2]
```diff
@@ -574,6 +574,23 @@ describe("Bug", () => {
     })
   })
 
+  describe("in issue #10498", () => {
+    it("rebuild GridBox when rows or cols properties are modified", async () => {
```
Comment (mattpap) [inline bokehjs/test/integration/regressions.ts:578]: This needs to read as a complete sentence. Currently it's:
```
Bug in issue #10498 rebuild GridBox when rows or cols properties are modified"
```
Preferably it should read:
```
Bug in issue #10498 prevents GridBox from rebuilding when rows or cols properties are modified
```

File: bokehjs/test/integration/regressions.ts [hunk 3]
```diff
@@ -574,6 +574,23 @@ describe("Bug", () => {
...
+      const p1 = fig([300, 300])
+      const p2 = fig([300, 300])
+      p1.circle({x: [0, 1], y: [0, 1], color: "red"})
+      p2.circle({x: [1, 0], y: [0, 1], color: "green"})
+      const box = new GridBox({
+        children: [[p1, 0, 0], [p2, 0, 1]],
+        cols: {0: 300, 1: 300},
+        sizing_mode: "fixed",
+      })
+      const {view}  = await display(box, [600, 300])
```
Comment (mattpap) [inline bokehjs/test/integration/regressions.ts:588]: Extra whitespace before `=`.

**Comment by mattpap** [comment]
> As I understand it, failures are due to my not providing the regression test baselines for macos and windows. Unfortunately, I don't have the means to produce those.

You need to follow https://docs.bokeh.org/en/latest/docs/dev_guide/bokehjs.html#ci-and-visual-testing, especially steps 7, 8 and 10 in this case (i.e. download and unzip the artifact, commit two *.png files for macos and windows respectively and repush).

**Comment by mattpap** [comment]
Commit history needs to be cleaned up as well, as there are duplicate commits with `branch-2.3`. A quick and dirty way to do this is to:
```
git reset --hard 488e3bf81f9077c705155831bcbd5a867f5ce336
git rebase branch-2.3
git cherry-pick a2a7d554cf7b09217fb4e6592aabccc1ad5a17d1
```
