### PR TITLE
Run inline js in individual functions in autoload_js

### LINKED ISSUE #8713: Displaying plot in notebook quickly after output_notebook raises JS error
Since https://github.com/bokeh/bokeh/pull/8682 was merged displaying a plot in a notebook environment raises a JS error if it is run before ``output_notebook`` has had time to initialize Bokeh properly. A simple way to reproduce this is by simply putting ``output_notebook`` and ``show`` in the same cell in a clean notebook and running it:

```python
from bokeh.io import output_notebook, show
from bokeh.plotting import figure
from bokeh.resources import INLINE

output_notebook(resources=INLINE)

p = figure()
p.circle([1, 2, 3], [1, 2, 3])

show(p)
```

>Javascript error adding output!
>TypeError: Cannot read property 'set_log_level' of undefined
>See your browser Javascript console for more details.

### PR DESCRIPTION
**Pull request by mattpap**
fixes #8713

### CODE REVIEW

File: bokeh/core/_templates/autoload_js.js [hunk 1]
```diff
@@ -115,16 +115,17 @@ calls it with the rendered model.
...
+    {%- for js in js_raw %}
     function(Bokeh) {
-      {%- for js in js_raw %}
-        {{ js|indent(6) }}
-      {% endfor -%}
-    }
+      {{ js|indent(6) }}
+    },
+    {% endfor -%}
+    function(Bokeh) {}
```
Comment (bryevdv) [inline bokeh/core/_templates/autoload_js.js]: What's the purpose of this last no-op function?

Comment (mattpap) [reply bokeh/core/_templates/autoload_js.js]: To make sure there's no trailing comma (for IE). Otherwise I would have to use some jinja's magic loop variables.

Comment (bryevdv) [reply bokeh/core/_templates/autoload_js.js]: Comment to that effect would be helpful I think

**Comment by philippjfr** [comment]
I can confirm that this fixes the error I was seeing.

**Comment by gkanarek** [comment]
test comment requested by @bryevdv

**Comment by gkanarek** [comment]
another test comment requested by @bryevdv

**Comment by bryevdv** [comment]
only failure is appveyor, just merging on top of the appveyor fix PR
