### PR TITLE
Fix logic error in UI event emit code

### LINKED ISSUE #14058: [BUG] Clearing selection with ESC only works on first selection tool
### Software versions

Python version        :  3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
IPython version       :  8.26.0
Tornado version       :  6.4.1
Bokeh version         :  3.5.1
BokehJS static path   :  C:\Users\\...\\.venv\Lib\site-packages\bokeh\server\static
node.js version       :  (not installed)
npm version           :  (not installed)
jupyter_bokeh version :  (not installed)
Operating system      :  Windows-10-10.0.19045-SP0

### Browser name and version

Google Chrome 128.0.6613.138

### Expected behavior

The user guide on configuring plot tools such as the BoxSelectTool and LassoSelectTool suggests that pressing the ESC key will clear the selection.

### Observed behavior

When using both `'box_select'` and `'lasso_select'` by setting the `tools` argument of `bokeh.plotting.figure`, clearing a selection using the ESC key only works for the first tool listed, but not for the second one, i.e. when setting `tools=['box_select', 'lasso_select']` then the ESC key will work for `'box_select'`, but not `'lasso_select'`, and vice versa.

Below, I modified an example from the documentation to provide both selection tools, and clearing the selection with the ESC key works for `'box_select'`, but not `'lasso_select'`.

### Example code

```Python
from bokeh.plotting import figure, show

# prepare some data
x = [1, 2, 3, 4, 5]
y = [4, 5, 5, 7, 2]

# create a new plot with a specific size
p = figure(
    title="Plot sizing example",
    width=350,
    height=250,
    x_axis_label="x",
    y_axis_label="y",
    tools=['box_select', 'lasso_select']
)

# add scatter renderer
p.scatter(x, y, fill_color="red", size=15)

# show the results
show(p)
```

### Stack traceback or browser console output

_No response_

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by mattpap**
Operator in `result ||= emit(tool)` is short circuiting, thus if the first emit returned `true`, which is always for key event handlers, then no other would emit.

fixes #14058

### CODE REVIEW

File: bokehjs/src/lib/core/ui_events.ts [hunk 1]
```diff
@@ -634,7 +634,8 @@ export class UIEventBus {
     } else {
       let result = false
       for (const tool of this._tools.keys()) {
-        result ||= emit(tool)
+        const emitted = emit(tool)
+        result ||= emitted
```
Comment (bryevdv) [inline bokehjs/src/lib/core/ui_events.ts:639]: worth a line comment explaining that this split needs to be preserved in order to prevent short-circuiting

**Review by bryevdv — APPROVED** [review]
