### PR TITLE
Redesign SVG backend

### LINKED ISSUE #6775: SVG backend not correctly coloring glyphs in legends
In bokeh 0.12.6, trying to use the svg backend with a legend of multiple glyph colors sets all the glyphs to use the color of the last glyph loaded into the legend. What should happen is that I should see a red diamond and blue square, but instead when using the svg backend, you see a blue diamond and square in the legend. 

```
import bokeh.plotting as bp
import bokeh.models as bm
fig = bp.figure(output_backend='svg')
cross = fig.diamond(x=1,y=1,color='red')
square = fig.square(x=2,y=1)
legends = [['circle',[cross]],['square',[square]]]
legend = bm.Legend(items=legends)
fig.add_layout(legend,'left')
bp.show(fig)
```
gives 
image

whereas 
```
import bokeh.plotting as bp
import bokeh.models as bm
fig = bp.figure(output_backend='canvas')
cross = fig.diamond(x=1,y=1,color='red')
square = fig.square(x=2,y=1)
legends = [['circle',[cross]],['square',[square]]]
legend = bm.Legend(items=legends)
fig.add_layout(legend,'left')
bp.show(fig)
```
gives 
image

as expected. I'm running this in a jupyter notebook, with python3.5.2, installed using conda4.3.24 on Firefox on RHEL7

### LINKED ISSUE #7883: Weird transparency/plot size interaction in svgs
bokeh 0.12.15
python 3.6.4
macOS 10.13.4
npm@5.6.0
phantomjs@2.1.7

#### Description of expected behavior and the observed behavior

When exporting to svgs, transparency of the background is respected if the plot width and height is 500, but not in (some) other cases, for instance 600 or 400.  

#### Complete, minimal, self-contained example code that reproduces the issue

```
from bokeh import plotting
from bokeh.io import export_png, export_svgs

fig = plotting.figure()
fig.background_fill_color = None
fig.border_fill_color     = None
fig.line(range(3), range(3))
export_png(fig, filename='fig.png')
fig.output_backend = 'svg'
export_svgs(fig, filename='fig.svg')


fig2 = plotting.figure(plot_width=500, plot_height=500)
fig2.background_fill_color = None
fig2.border_fill_color     = None
fig2.line(range(3), range(3))
export_png(fig2, filename='fig2.png')
fig2.output_backend = 'svg'
export_svgs(fig2, filename='fig2.svg')


fig3 = plotting.figure(plot_width=400, plot_height=400)
fig3.background_fill_color = None
fig3.border_fill_color     = None
fig3.line(range(3), range(3))
export_png(fig3, filename='fig3.png')
fig3.output_backend = 'svg'
export_svgs(fig3, filename='fig3.svg')
```

So in these examples, fig.png, fig2.png and fig3.png should all have a transparent background. However, while fig2.svg has a transparent background, fig.svg and fig3.svg don't. One can check that by looking for the string `<rect fill="#FFFFFF"` in the svg file, present in fig.svg and fig3.svg but not in fig2.svg.

### LINKED ISSUE #8046: Extra whitespace with SVG export
This was initially reported in the Google groups channel and was encouraged to open an issue here

#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
Ubuntu 16.04
Python 3.6 (Conda env)
Jupyter notebook 5.5
Bokeh 0.13.0
Firefox (although shouldn't matter)

#### Description of expected behavior and the observed behavior
When exporting a multilevel categorical barchart to SVG it seems to introduce extra whitespace between the levels. This extra whitespace is also apparent in the legend. The effect is worse for longer labels as though the padding is linked to the number of characters in the label.

#### Complete, minimal, self-contained example code that reproduces the issue

```
fruits = ['Apples', 'Pears', 'Nectarines', 'Plums', 'Grapes', 'Strawberries']
years = ['2015-01-01', '2016-01-01', '2017-01-01']

data = {'fruits' : fruits,
        '2015-01-01'   : [2, 1, 4, 3, 2, 4],
        '2016-01-01'   : [5, 3, 3, 2, 4, 6],
        '2017-01-01'   : [3, 2, 4, 4, 5, 3]}

# this creates [ ("Apples", "2015"), ("Apples", "2016"), ("Apples", "2017"), ("Pears", "2015), ... ]
x = [ (fruit, year) for fruit in fruits for year in years ]
counts = sum(zip(data['2015-01-01'], data['2016-01-01'], data['2017-01-01']), ()) # like an hstack

year = [i[1] for i in x]

# Normal output
source = ColumnDataSource(data=dict(x=x, counts=counts, year=year))
p = figure(x_range=FactorRange(*x), plot_height=400, plot_width=800, title="Fruit Counts by Year",
           toolbar_location=None, tools="")

p.vbar(x='x', top='counts', width=0.9, source=source, legend='year')

p.y_range.start = 0
p.x_range.range_padding = 0.1
p.xaxis.major_label_orientation = 1.2
p.xgrid.grid_line_color = None

show(p)

#SVG output
source = ColumnDataSource(data=dict(x=x, counts=counts,year=year))
p = figure(x_range=FactorRange(*x), plot_height=400, plot_width=800, title="Fruit Counts by Year",output_backend="svg",
           toolbar_location=None, tools="")

p.vbar(x='x', top='counts', width=0.9, source=source, legend='year')

p.y_range.start = 0
p.x_range.range_padding = 0.1
p.xaxis.major_label_orientation = 1.2
p.xgrid.grid_line_color = None

export_svgs(p, filename="plot.svg")
```

A notebook and the html output of the notebook can be found here:
[https://gist.github.com/msalvaris/3bebd4027a2fe9ba7b428f18ac310ced](https://gist.github.com/msalvaris/3bebd4027a2fe9ba7b428f18ac310ced)

### LINKED ISSUE #8446: SVG not displaying scatter output
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
Bokeh: 1.0.1
IPython: 6.5.0

#### Description of expected behavior and the observed behavior
I expect the chart below to contain both navy and red circles. The red circles are displayed, but the navy circles created by the .scatter method do not appear.

#### Complete, minimal, self-contained example code that reproduces the issue

```
from bokeh.plotting import figure, show
from bokeh.io.export import get_svgs
from IPython.display import SVG

p = figure(plot_width=400, plot_height=400)
p.scatter([-1, -2, -3, -4, -5], [6, 7, 2, 4, 5], size=20, color="navy", alpha=0.5, marker='circle')
p.circle([1, 2, 3, 4, 5], [6, 7, 2, 4, 5], size=20, color="red", alpha=0.5)
p.output_backend = 'svg'
# show the results
SVG(get_svgs(p)[0])
```

#### Screenshots or screencasts of the bug in action
image

### LINKED ISSUE #8744: Plots containing arrows fail to render correctly with svg output backend.
Also exporting a plot with output_backend='svg' when it contains arrows throws the following warning/exception:

WARNING:bokeh.io.export:The webdriver raised a TimeoutException while waiting for a bokeh:idle' event to signify that the layout has rendered. Something may have gone wrong.

It does not matter wether it is exported as svg or png, and the resulting image looks the same. Plot looks the same when using show() but no exception is shown.

Minimal example
```
from bokeh.io import export_svgs, export_png
from bokeh.models import Plot, Arrow, VeeHead, Range1d

plot = Plot( output_backend='svg',y_range=Range1d(-1,2),x_range=Range1d(-1,2))

plot.add_layout(Arrow(end=VeeHead(),
                      x_start=0, y_start=0,
                      x_end=1,   y_end=1))

plot.add_layout(Arrow(end=VeeHead(),
                      x_start=0, y_start=0,
                      x_end=0,   y_end=1))

export_png(plot,filename='svg_arrow.png')
export_svgs(plot,filename='arrow.svg')

```

Output with canvas backend.
canvas_arrow

Output with svg backend.
svg__arrow

Version Info
python: 3.6.8
bokeh: 1.0.4
selenium: 3.141.0
phantomjs: 2.1.1

### LINKED ISSUE #9001: hatch_pattern and svg
When I use output_backend='svg' and a hatch_pattern, the html file never loads (as if it was too many points). The same is with exporting.

Example:
```
f = figure(width=1000, height=500, output_backend='svg')
f.varea(x=[0, 100], y1=[0, 0], y2=[1, 1], alpha=0,
            hatch_pattern="/", hatch_scale=150)
show(f)  # or export_svgs(f, "some.svg") or export_png(f, "some.png")
```

### LINKED ISSUE #9169: [FEATURE] SVG export for gridplot
Currently export of a gridplot works for export png but not for svg. 

With svg you get a series of plots back and have to manually compile.

User jcacbelos on discourse seems to have a start at something that works: https://discourse.bokeh.org/t/generate-svg-images-from-bokeh-plots-and-include-them-in-a-pdf-report-with-using-svglib-and-reportlab/3889

### LINKED ISSUE #9213: Svg backend cannot draw annular_wedge correctly [BUG]
Here is the code:

```
from bokeh.plotting import figure, show

p = figure(plot_width=400, plot_height=400, output_backend="svg")
p.annular_wedge(x=[1, 2, 3], y=[1, 2, 3], inner_radius=0.1, outer_radius=0.25,
                start_angle=0.4, end_angle=4.8, color="green", alpha=0.6)

show(p)
```

and the output:

chrome_2019-09-05_11-31-37

### LINKED ISSUE #9551: [BUG] ```export_svg``` shifting x-axis upward and overlapping with ticks in Bokeh v1.4
I'm working in bokeh v1.4 on Fedora29 and have been running into an issue that I hadn't seen before in ```export_svgs``` where the x-axis labels are getting shifted over the x-axis itself making it messy/illegible. This problem is not replicated in either show(p) or save_svg (I've attached an example of both the svg and png to demonstrate the problem -- both saved/imported here as pngs, but the file from the svg export is labeled as such). For some reason, this is worse in other plots (attached an example from my data -- I can provide more example code but I can't provide the data necessary to reproduce it).

Here's some example code for a couple of the provided plots:

```
from bokeh.plotting import figure, show
from bokeh.sampledata.iris import flowers
from bokeh.transform import factor_cmap, factor_mark

SPECIES = ['setosa', 'versicolor', 'virginica']
MARKERS = ['hex', 'circle_x', 'triangle']

p = figure(title = "Iris Morphology")
p.xaxis.axis_label = 'Petal Length'
p.yaxis.axis_label = 'Sepal Width'

p.scatter("petal_length", "sepal_width", source=flowers, legend_field="species", fill_alpha=0.4, size=12,
          marker=factor_mark('species', MARKERS, SPECIES),
          color=factor_cmap('species', 'Category10_3', SPECIES))

p.output_backend = "svg"
export_svgs(p, filename = 'test_scatter.svg')
export_png(p, filename = 'test_scatter.png')

```
test_scatter
test_scatter_svg
svg_export_example

Thanks a bunch for any help!

### PR DESCRIPTION
**Pull request by mattpap**
This is a major redesign of SVG backend. All issues with broken glyphs, annotations, clip paths, hatch patterns, element spacing, etc. were fixed. I also added support for proper SVG layout export, so that now `export_svg()` outputs one SVG file per root in `Bokeh.index` and layouts of all shapes (grid plots in particular) are preserved as a single SVG. I also added `LayoutDOM.export()` method in bokehjs that allows API-level composing of plots.

image

- [x] fixes #9213
- [x] fixes #9551
- [x] fixes #8744
- [x] fixes #8446
- [x] fixes #6775
- [x] fixes #9001
- [x] fixes #8046
- [x] fixes #9169

### CODE REVIEW

**Comment by mattpap** [comment]
This PR is feature complete. I still need to clean up the implementation (remove commented out code) and add tests.

**Comment by bryevdv** [comment]
Looking in detail now but the only thing that catches my eye is:

>  I also added support for proper SVG layout export, so that now export_svgs() outputs one SVG file per root in Bokeh.index and layouts of all shapes (grid plots in particular) are preserved as a single SVG. 

This would be a breaking change, it seems like it should either be put behind a flag that's off by default or in to a new `export_svg` (no plural) function.

**Comment by bryevdv** [comment]
Unless it's impossible to preserve the current behavior, in which case, OK, but we need a big giant message about it on the release notes.

**Comment by mattpap** [comment]
I restored the original `export_svgs()` and added `export_svg()`.

File: bokehjs/src/lib/core/visuals.ts [hunk 1]
```diff
@@ -128,8 +123,6 @@ function create_hatch_canvas(hatch_pattern: mixins.HatchPattern, hatch_color: Co
       ctx.stroke()
       ctx.stroke()
```
Comment (mattpap) [inline bokehjs/src/lib/core/visuals.ts:124]: @bryevdv, why double stroke this path?

**Comment by mattpap** [comment]
I tested this on Chrome, Firefox, new Edge and IE, and everything looks good, with the minor exception of IE, which doesn't support text baselines, so labels are off (can be worked around but with font dependent hacks).

File: bokehjs/src/lib/core/visuals.ts (hunk 1 above)
Comment (bryevdv) [reply bokehjs/src/lib/core/visuals.ts:124]: If I didn't leave a comment it was probably just a mistake. That said, I'd make an issue to investigate rather than remove here, just in case

**Comment by bryevdv** [comment]
OK I will look over this once more in the next few hours then merge  and get rc2 out

**Comment by bryevdv** [comment]
@mattpap is there a test or example for this? I can't get `export_svg` to work:
```
(22pip) ❯ python vector.py
Traceback (most recent call last):
  File "vector.py", line 203, in <module>
    export_svg(gridplot([[p1,p2]], plot_width=400, plot_height=400))  # open a browser
  File "/Users/bryan/anaconda/envs/22pip/lib/python3.8/site-packages/bokeh/io/export.py", line 143, in export_svg
    svgs = get_svg(obj, width=width, height=height, driver=webdriver, timeout=timeout)
  File "/Users/bryan/anaconda/envs/22pip/lib/python3.8/site-packages/bokeh/io/export.py", line 246, in get_svg
    svgs = cast(List[str], web_driver.execute_script(_SVG_SCRIPT))
  File "/Users/bryan/anaconda/envs/22pip/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 634, in execute_script
    return self.execute(command, {
  File "/Users/bryan/anaconda/envs/22pip/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/bryan/anaconda/envs/22pip/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.JavascriptException: Message: javascript error: e.export is not a function
  (Session info: headless chrome=84.0.4147.135)
```
`export_svgs` still seems fine though. Also `export_svg` was not added to the top level `bokeh.io` module

**Comment by mattpap** [comment]
There are unit tests for `get_svg()`. The problem is with `ToolbarBox`, which tries to export `ToolbarBase`, which doesn't inherit `export()` method.

**Comment by mattpap** [comment]
And here's the reason for not catching that earlier:
https://github.com/bokeh/bokeh/blob/9c19e1c40a4fb883ed628629c5ab4da9c320af28/bokehjs/src/lib/models/tools/toolbar_box.ts#L160-L162
