### PR TITLE
Restore line_policy=none for HoverTool

### LINKED ISSUE #12585: [BUG] line_policy='none' for HoverTool does not generate any tooltip in 3.0.1
### Software versions

Python version      :  3.10.6 | packaged by conda-forge | (main, Aug 22 2022, 20:35:26) [GCC 10.4.0]
IPython version     :  8.6.0
Tornado version     :  6.2
Bokeh version       :  3.0.1
BokehJS static path :  /home/alsamii/conda3/envs/ml/lib/python3.10/site-packages/bokeh/server/static
node.js version     :  v18.11.0
npm version         :  8.19.2
Operating system    :  Linux-5.15.0-1022-azure-x86_64-with-glibc2.31

### Browser name and version

Google Chrome Version 107.0.5304.87 (Official Build) (64-bit)

### Jupyter notebook / Jupyter Lab version

3.5.0

### Expected behavior

In version 2.4.3 I was able to use `line_policy='none'` in HoverTool, to get a tooltip that followed the mouse. But after I upgraded to 3.0.1, the following code does not generate any tooltip.

### Observed behavior

By running the example code, the tooltip does not show up in version 3.0.1, but I am able to get the tooltip in v2.4.3.

### Example code

```Python
import bokeh.plotting as bokplt
import bokeh.models as bokm
import bokeh.io as bokio

bokio.reset_output()
bokio.output_notebook()

p = bokplt.figure(width=800, height=200)

coord_hover_line = p.line(x=[0,100], y=[10, 5], alpha=0.0)

p.add_tools(bokm.HoverTool(
    tooltips=[("x ", "$x{0.0}")],
    renderers=[coord_hover_line],
    mode='vline',
    line_policy='none',
))

p.add_tools(bokm.CrosshairTool(dimensions="height", line_alpha=0.2))

bokio.show(p)
```

### Stack traceback or browser console output

_No response_

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by bryevdv**
- [x] issues: fixes #12585
- [x] tests added / passed
- [x] release document entry (if new feature or API change)

https://user-images.githubusercontent.com/1078448/200987295-991c4221-8968-43cd-b138-b319fe825883.mov

@mattpap is there any mechanism for test selection / filtering for js unit tests yet? It would be really nice to be able to run just to one or few tests of interest.

### CODE REVIEW

File: bokehjs/test/unit/models/tools/inspectors/hover_tool.ts [hunk 1]
```diff
@@ -74,6 +76,32 @@ describe("HoverTool", () => {
...
+      const {left, top} = offset_bbox(ui.hit_area)
+      const ev = new MouseEvent("mousemove", {clientX: left + sx, clientY: top + sy})
+      ui.hit_area.dispatchEvent(ev)
+
+      await view.ready
+
+      const hover_view = view.tool_views.get(hover)! as HoverTool["__view_type__"]
+      const tt = hover_view.ttmodels.values().next().value as Tooltip
+
+      expect(tt.position).to.be.equal([sx|0, sy|0])
```
Comment (bryevdv) [inline bokehjs/test/unit/models/tools/inspectors/hover_tool.ts:101]: I'm assuming based on vague recollection that this truncation is what happens internally. If there are better comparisons to make, I am open to suggestion.

**Comment by mattpap** [comment]
> is there any mechanism for test selection / filtering for js unit tests yet? It would be really nice to be able to run just to one or few tests of interest.

There always has been `-k` argument for keyword filtering (see https://docs.bokeh.org/en/latest/docs/dev_guide/testing.html).

File: bokehjs/test/unit/models/tools/inspectors/hover_tool.ts [hunk 2]
```diff
@@ -74,6 +76,32 @@ describe("HoverTool", () => {
     })
   })
 
+  describe("line_policy", () => {
+    it("should support 'none' line_policy with mode=vline", async () => {
+      const tooltips: [string, string][] = [["x", "$x"], ["y", "$y"]]
+      const hover = new HoverTool({mode: "vline", line_policy: "none", tooltips})
+      const p = fig([200, 200], {toolbar_location: null, min_border: 0, x_range: [1, 3], y_range: [0, 2]})
```
Comment (mattpap) [inline bokehjs/test/unit/models/tools/inspectors/hover_tool.ts:83]: `fig()` already sets `toolbar_location: null`. `min_border` is unnecessary if the rest of the test is rewritten using `PlotActions`. Are ranges actually relevant to this test?

File: bokehjs/test/unit/models/tools/inspectors/hover_tool.ts [hunk 3]
```diff
@@ -74,6 +76,32 @@ describe("HoverTool", () => {
...
+      p.add_tools(hover)
+
+      const {view} = await display(p)
+
+      const crv = view.renderer_views.get(r)!
+      const [[sx], [sy]] = crv.coordinates.map_to_screen([1.8], [1.5])
+      const ui = view.canvas_view.ui_event_bus
+      const {left, top} = offset_bbox(ui.hit_area)
+      const ev = new MouseEvent("mousemove", {clientX: left + sx, clientY: top + sy})
+      ui.hit_area.dispatchEvent(ev)
```
Comment (mattpap) [inline bokehjs/test/unit/models/tools/inspectors/hover_tool.ts:94]: Use `PlotActions` instead of this. There are integration tests and possibly some unit tests to take inspiration from.

File: bokehjs/test/unit/models/tools/inspectors/hover_tool.ts [hunk 4]
```diff
@@ -74,6 +76,32 @@ describe("HoverTool", () => {
...
+
+      await view.ready
+
+      const hover_view = view.tool_views.get(hover)! as HoverTool["__view_type__"]
```
Comment (mattpap) [inline bokehjs/test/unit/models/tools/inspectors/hover_tool.ts:98]: Use `ViewManager` instead like this `view.owner.get_one(hover)`.

File: bokehjs/test/unit/models/tools/inspectors/hover_tool.ts [hunk 5]
```diff
@@ -74,6 +76,32 @@ describe("HoverTool", () => {
...
+      const tt = hover_view.ttmodels.values().next().value as Tooltip
```
Comment (mattpap) [inline bokehjs/test/unit/models/tools/inspectors/hover_tool.ts:99]: Give or take, use this:
```ts
const [[, tt]] = hover_view.ttmodels
```
or
```ts
const [tt] = hover_view.ttmodels.values()
```

**Comment by bryevdv** [comment]
> There always has been -k argument for keyword filtering (see https://docs.bokeh.org/en/latest/docs/dev_guide/testing.html).

FWIW it would be more ergonomic for me to be able to run the tests in a single file, as it is possble with `pytest`. For that I can rely on tab completion rather than manually remembering and typing however many test name patterns. i.e. this usage:
```
dev-311 ❯ node make test:unit test/unit/models/tools/inspectors/hover_tool.ts
BuildError: can't resolve test/unit/models/tools/inspectors/hover_tool.ts task
    at _resolve_task (/Users/bryan/work/bokeh/bokehjs/make/task.ts:113:13)
    at _resolve_dep (/Users/bryan/work/bokeh/bokehjs/make/task.ts:102:27)
    at Array.map (<anonymous>)
    at task (/Users/bryan/work/bokeh/bokehjs/make/task.ts:123:39)
    at main (/Users/bryan/work/bokeh/bokehjs/make/main.ts:15:27)
    at Object.<anonymous> (/Users/bryan/work/bokeh/bokehjs/make/main.ts:32:1)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Module.m._compile (/Users/bryan/work/bokeh/bokehjs/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/bryan/work/bokeh/bokehjs/node_modules/ts-node/src/index.ts:1621:12) {
  component: 'tasks'
}
```

File: bokehjs/test/unit/models/tools/inspectors/hover_tool.ts (hunk 5 above)
Comment (bryevdv) [reply bokehjs/test/unit/models/tools/inspectors/hover_tool.ts]: https://github.com/bokeh/bokeh/pull/12586/commits/757f67a325cf11702c68e2e4e273252409fad968

File: bokehjs/test/unit/models/tools/inspectors/hover_tool.ts (hunk 4 above)
Comment (bryevdv) [reply bokehjs/test/unit/models/tools/inspectors/hover_tool.ts]: https://github.com/bokeh/bokeh/pull/12586/commits/757f67a325cf11702c68e2e4e273252409fad968

File: bokehjs/test/unit/models/tools/inspectors/hover_tool.ts (hunk 3 above)
Comment (bryevdv) [reply bokehjs/test/unit/models/tools/inspectors/hover_tool.ts]: https://github.com/bokeh/bokeh/pull/12586/commits/757f67a325cf11702c68e2e4e273252409fad968 (docs for these utilities are needed if they are to be expected for newcomers)

**Comment by mattpap** [comment]
> FWIW it would be more ergonomic for me to be able to run the tests in a single file, as it is possble with pytest. For that I can rely on tab completion rather than manually remembering and typing however many test name patterns. i.e. for this usage to work:

It's a long standing issue with bokehjs' tests (perhaps there may be even an issue open for this). The problem is with communicating file names to modules and then to the test framework, which is far from obvious. I have some ideas how to solve this, but this requires more time to implement than I can afford. Thus I've been structuring tests in a particular way, so that's fairly easy to find a keyword or a set of keywords (multiple `-k` are supported) to select tests (e.g. issue numbers), though that doesn't always work.

**Comment by bryevdv** [comment]
I'll plan to merge this tomorrow morning PST unless there is further comment.

File: bokehjs/test/unit/models/tools/inspectors/hover_tool.ts (hunk 1 above)
Comment (mattpap) [reply bokehjs/test/unit/models/tools/inspectors/hover_tool.ts:99]: `map_to_screen()` produces `Float32Array` so truncation of `sx` and `sy` shouldn't be necessary. If anything, it's `position` it should be truncated. I need to look closer into this.

Comment (bryevdv) [reply bokehjs/test/unit/models/tools/inspectors/hover_tool.ts:99]: > I need to look closer into 

Do you mean in the future, or in the context of this PR? It would be helpful for me in cases like this if you would speak explicitly to the open decision: are you asking that merging this PR be delayed?

Comment (mattpap) [reply bokehjs/test/unit/models/tools/inspectors/hover_tool.ts:99]: I want to do it here. Hopefully it won't take too long.

Comment (mattpap) [reply bokehjs/test/unit/models/tools/inspectors/hover_tool.ts]: So it's actually not guaranteed that `tt.position` is whole pixels, thus both sides should be truncated, although in this particular setup `tt.position` is pixels. I changed that and converted this test into visual regression test.

**Comment by bryevdv** [comment]
@mattpap  I will resolve the comments above here for expediency but FYI I would like to adopt a workflow where whoever makes a comment on a PR is responsible for resolving once a confirmation of changes is given.

**Comment by bryevdv** [comment]
Also, FYI I did choose a basic unit test over a visual tests on purpose. In general I think we are over-rotating to those in cases where a basic unit test is sufficient or preferable. As it is we have hundreds of duplicative [1] baselines for the same basic "frame plus two axes" that often has nothing to do with the thing that is actually under test. I will open a separate discussion for this, though. 

[1] There are over 800 `.blf files and barely 100 unique ones.
