### PR TITLE
Fix SpatialIndex.bounds

### LINKED ISSUE #14339: SpatialIndex.bounds is broken
The current `SpatialIndex.bounds` code iterates over the internal Flatbush boxes like this:
```typescript
    for (const i of this.indices(rect)) {
      const x0 = boxes[4*i + 0]
      const y0 = boxes[4*i + 1]
      const x1 = boxes[4*i + 2]
      const y1 = boxes[4*i + 3]
```
But this is not the correct index to iterate over the boxes. The index returned by `this.indices` corresponds to the index of the inserted item, i.e. the value returned by `Flatbush.add`. More plainly, if N items are added to the index, the highest index returned would be N-1, but the number of boxes is greater than N. 

This can also be seen by the fact that the original Flatbush logic for iterating over boxes (largely copied into `search_indices` as well) is more complicated:
```typescript
        let nodeIndex = this._boxes.length - 4;
        const queue = [];
        const results = [];

        while (nodeIndex !== undefined) {
            // find the end index of the node
            const end = Math.min(nodeIndex + this.nodeSize * 4, upperBound(nodeIndex, this._levelBounds));

            // search through child nodes
            for (let /** @type number */ pos = nodeIndex; pos < end; pos += 4) {
                // check if node bbox intersects with query bbox
```

Here is a quick diff that adds a `search_bounds` with the proper box iteration logic, that fixes this problem:
```diff
diff --git a/bokehjs/src/lib/core/util/spatial.ts b/bokehjs/src/lib/core/util/spatial.ts
index a6ed334e81..0d6e40ce79 100644
--- a/bokehjs/src/lib/core/util/spatial.ts
+++ b/bokehjs/src/lib/core/util/spatial.ts
@@ -63,6 +63,59 @@ class _FlatBush extends FlatBush {

     return results
   }
+
+  search_bounds(minX: number, minY: number, maxX: number, maxY: number): Rect {
+    if (this._pos !== this._boxes.length) {
+      throw new Error("Data not yet indexed - call index.finish().")
+    }
+
+    let nodeIndex: number | undefined = this._boxes.length - 4
+    const queue = []
+    const result = empty()
+
+    while (nodeIndex !== undefined) {
+      // find the end index of the node
+      const end = Math.min(nodeIndex + this.nodeSize * 4, upperBound(nodeIndex, this._levelBounds))
+
+      // search through child nodes
+      for (let pos: number = nodeIndex; pos < end; pos += 4) {
+        const index = this._indices[pos >> 2] | 0
+
+        const nodeMinX = this._boxes[pos + 0]
+        const nodeMinY = this._boxes[pos + 1]
+        const nodeMaxX = this._boxes[pos + 2]
+        const nodeMaxY = this._boxes[pos + 3]
+
+        if (maxX < nodeMinX || maxY < nodeMinY || minX > nodeMaxX || minY > nodeMaxY) {
+          continue
+        }
+
+        if (nodeIndex >= this.numItems * 4) {
+          queue.push(index) // node; add it to the search queue
+        } else {
+          // debugger
+          if (nodeMinX >= minX && nodeMinX < result.x0) {
+            result.x0 = nodeMinX
+          }
+          if (nodeMaxX <= maxX && nodeMaxX > result.x1) {
+            result.x1 = nodeMaxX
+          }
+          if (nodeMinY >= minY && nodeMinY < result.y0) {
+            result.y0 = nodeMinY
+          }
+          if (nodeMaxY <= maxY && nodeMaxY > result.y1) {
+            result.y1 = nodeMaxY
+          }
+        }
+
+      }
+
+      nodeIndex = queue.pop()
+    }
+
+    return result
+  }
+
 }

 export class SpatialIndex {
@@ -128,31 +181,10 @@ export class SpatialIndex {
   }

   bounds(rect: Rect): Rect {
-    const bounds = empty()
     if (this.index == null) {
-      return bounds
-    }
-
-    const {boxes} = this.index
-    for (const i of this.indices(rect)) {
-      const x0 = boxes[4*i + 0]
-      const y0 = boxes[4*i + 1]
-      const x1 = boxes[4*i + 2]
-      const y1 = boxes[4*i + 3]
-      if (x0 >= rect.x0 && x0 < bounds.x0) {
-        bounds.x0 = x0
-      }
-      if (x1 <= rect.x1 && x1 > bounds.x1) {
-        bounds.x1 = x1
-      }
-      if (y0 >= rect.y0 && y0 < bounds.y0) {
-        bounds.y0 = y0
-      }
-      if (y1 <= rect.y1 && y1 > bounds.y1) {
-        bounds.y1 = y1
-      }
+      return empty()
     }
-
-    return bounds
+    const {x0, y0, x1, y1} = this._normalize(rect)
+    return this.index.search_bounds(x0, y0, x1, y1)
   }
 }
```

I think things "worked" until now because we were only really searching with infinite search areas. The problem showed up when I tried to actually use finite search areas. 

@mattpap do you have any comments on this approach or a different preferred approach before I submit a PR?

### PR DESCRIPTION
**Pull request by bryevdv**
The PR abstracts out the internal Flatbush boxes traversal in `search_indices` to a new method `search_apply` that applies a given function to all the found nodes. This new function is used to re-implement `search_indices` and a new `seach_bounds` that correctly computes bounds for all types of input rects. 

- [x] issues: fixes #14339
- [x] tests added / passed

@mattpap @gabalafou I do want to add quite a lot more tests. But I would appreciate any early feedback on either the index refactor or better ways to automate / parametrize the tests. 

This fix is is the first step to support [[FEATURE] Windowed Auto-ranging. #10020](https://github.com/bokeh/bokeh/issues/10020)

### CODE REVIEW

File: bokehjs/test/unit/core/util/spatial.ts [hunk 1]
```diff
@@ -4,16 +4,119 @@ import {SpatialIndex} from "@bokehjs/core/util/spatial"
...
+  //   const index = new SpatialIndex(6)
+  //   index.add_rect(0, 1, 1, 2)
+  //   index.add_rect(0.0001, 1, 1, 2)
+  //   index.add_rect(0, 100, 1, 200)
+  //   index.add_rect(0.0001, -100, 1, 200)
+  //   index.add_rect(0, 10, 1, 20)
+  //   index.add_rect(-0.0001, 10, 1, 20)
+  //   index.finish()
+  //   expect(index.bounds(bbox.empty())).to.be.equal(bbox.empty())
+  // })
```
Comment (bryevdv) [inline bokehjs/test/unit/core/util/spatial.ts]: This test fails and I don't quite understand why yet

File: bokehjs/src/lib/core/util/spatial.ts [hunk 2]
```diff
@@ -51,18 +43,59 @@ class _FlatBush extends FlatBush {
...
+        if (node.y1 <= maxY && node.y1 > result.y1) {
+          result.y1 = node.y1
+        }
+      }
+    }
+    this.search_apply(minX, minY, maxX, maxY, fn(result))
+
+    if (!isFinite(result.x0 + result.y0 + result.x1 + result.y1)) {
+      return empty()
+    }
```
Comment (bryevdv) [inline bokehjs/src/lib/core/util/spatial.ts]: I'm not 100% confident that this condition should be needed. Some `x_range` inputs that did not intersect results seemed to come back with e.g. `x0: Infinity` which I think could only happen if some internal boxes can have `Infinity` values. Is that the case?

**Comment by bryevdv** [comment]
I updated the one baseline image that changed for the log case, in order to see the diff side by side. The new image seems to have looser bounds than desired so will need to investigate further.

File: bokehjs/src/lib/core/util/spatial.ts [hunk 3]
```diff
@@ -51,18 +43,55 @@ class _FlatBush extends FlatBush {
...
+
+  search_indices(minX: number, minY: number, maxX: number, maxY: number): Indices {
+    const result = new Indices(this.numItems)
+
+    function fn(result: Indices) {
+      return (index: number, _node: Rect) => { result.set(index) }
+    }
+    this.search_apply(minX, minY, maxX, maxY, fn(result))
+
+    return result
```
Comment (mattpap) [inline bokehjs/src/lib/core/util/spatial.ts]: Maybe I'm missing something, but all of this complexity is unnecessary:
```suggestion
    const result = new Indices(this.numItems)
    this.search_apply(minX, minY, maxX, maxY, (index) => result.set(index))
    return result
```

File: bokehjs/src/lib/core/util/spatial.ts [hunk 4]
```diff
@@ -51,18 +43,55 @@ class _FlatBush extends FlatBush {
...
+  }
+
+  search_bounds(minX: number, minY: number, maxX: number, maxY: number): Rect {
+    const result = empty()
+
+    function fn(result: Rect) {
```
Comment (mattpap) [inline bokehjs/src/lib/core/util/spatial.ts]: Same here.

File: bokehjs/src/lib/core/util/spatial.ts [hunk 5]
```diff
@@ -51,18 +43,55 @@ class _FlatBush extends FlatBush {
...
+          result.y1 = node.y1
+        }
+      }
+    }
+    this.search_apply(minX, minY, maxX, maxY, fn(result))
 
-    return results
+    return result
   }
+
```
Comment (mattpap) [inline bokehjs/src/lib/core/util/spatial.ts]:
```suggestion
```
and elsewhere.

File: bokehjs/src/lib/core/util/spatial.ts [hunk 6]
```diff
@@ -20,28 +20,20 @@ function upperBound(value: number, arr: ArrayLike<number>): number {
...
 
     while (nodeIndex !== undefined) {
       // find the end index of the node
       const end = Math.min(nodeIndex + this.nodeSize * 4, upperBound(nodeIndex, this._levelBounds))
 
       // search through child nodes
       for (let pos: number = nodeIndex; pos < end; pos += 4) {
-        const index = this._indices[pos >> 2] | 0
-
-        // check if node bbox intersects with query bbox
```
Comment (mattpap) [inline bokehjs/src/lib/core/util/spatial.ts:44]: In the long term we shouldn't maintain this code altogether, especially given this is already fixed upstream. I would submit a PR to flatbush to add a second argument `node: Rect` to the current `search(..., filterFn(indices: number))`. We would use `filterFn` that returns `false` to avoid collecting results in an array. Then we would be able to remove all of this logic. flatbush is an active project for once, so let's take advantage of this.

Comment (bryevdv) [reply bokehjs/src/lib/core/util/spatial.ts:44]: That sounds like a good idea but realistically I am not sure when I'd be able to do that myself.

File: bokehjs/test/unit/core/util/spatial.ts (hunk 1 above)
Comment (bryevdv) [reply bokehjs/test/unit/core/util/spatial.ts]: @mattpap do you agree that searching the index with an empty bbox should return empty restults (i.e. no indices or empty bounds)? I want to make sure I am not misunderstanding what and "empty" bbox is intended to represent.

**Comment by bryevdv** [comment]
@mattpap updating the baseline code to also show markers, it actually seems that the new baseline image could be the correct one:
Screenshot 2025-02-18 at 15 45 21

i.e. for some reason previously the points of the line that were "invisible" because they were next to a "0" on the log scale were not being factored in (I don't have any speculation why that was, maybe just some pure coincidence). But it seems to me, to be consistent, that all non-zero points *should* factor in. 

If you agree then perhaps we add a scatter to the test to make this clear in the baseline image.

File: bokehjs/test/unit/core/util/spatial.ts (hunk 1 above)
Comment (bryevdv) [reply bokehjs/test/unit/core/util/spatial.ts]: Oh, this is failing because the call to `this._normalize(rect)` turns `empty()` into `full()` @mattpap is this what you intended? Presumably `_normalize` could be made to operate on finite values, but should it?

Comment (bryevdv) [reply bokehjs/test/unit/core/util/spatial.ts]:
```diff
diff --git a/bokehjs/src/lib/core/util/spatial.ts b/bokehjs/src/lib/core/util/spatial.ts
index 5bfa292587..7f093d518a 100644
--- a/bokehjs/src/lib/core/util/spatial.ts
+++ b/bokehjs/src/lib/core/util/spatial.ts
@@ -118,10 +118,10 @@ export class SpatialIndex {

   protected _normalize(rect: Rect): Rect {
     let {x0, y0, x1, y1} = rect
-    if (x0 > x1) {
+    if ((x0 > x1) && isFinite(x0 + x1)) {
       [x0, x1] = [x1, x0]
     }
-    if (y0 > y1) {
+    if ((y0 > y1) && isFinite(y0 + y1)) {
       [y0, y1] = [y1, y0]
     }
     return {x0, y0, x1, y1}
```
if that's what makes sense. Alternatively `_normalize(rect)` seems like a kludge, maybe it would be better to be able to assume all inputs are given as intended.

Comment (mattpap) [reply bokehjs/test/unit/core/util/spatial.ts]: That makes sense. `_normalize()` is unfortunately necessary for the time being. It was easier to normalize in one place than trying to make sure all invocations provide coordinates in the correct order.

**Comment by mattpap** [comment]
> If you agree then perhaps we add a scatter to the test to make this clear in the baseline image.

Let's do that.

**Comment by bryevdv** [comment]
baseline will need updating after the linux BokehJS job completes, but this is otherwise ready

File: bokehjs/test/integration/regressions.ts [hunk 7]
```diff
@@ -1238,6 +1238,7 @@ describe("Bug", () => {
 
       const p = fig([200, 200], {y_axis_type: "log"})
       p.line(x, y, {line_width: 2})
+      p.scatter(x, y, {size: 15})
```
Comment (mattpap) [inline bokehjs/test/integration/regressions.ts:1241]: Given the small size of the plot, these scatter markers overlap each other and cover the line completely. I would make them smaller and perhaps use `fill_color=None` for transparency.

**Review by mattpap — APPROVED** [review]
Looks good, except for the one comment I made regarding scatter marker size.

File: bokehjs/test/integration/regressions.ts (hunk 7 above)
Comment (bryevdv) [reply bokehjs/test/integration/regressions.ts:1241]: Oops missed this will try to update in the follow on PR that uses this for ranging
