### PR TITLE
Have StringFormatter respect nan_format

### LINKED ISSUE #14014: [BUG] StringFormatter `nan_format` seems broken
### Software versions

``` yaml
Python version        :  3.12.4 | packaged by conda-forge | (main, Jun 17 2024, 10:23:07) [GCC 12.3.0]
IPython version       :  8.26.0
Tornado version       :  6.4.1
Bokeh version         :  3.5.1
BokehJS static path   :  /home/shh/miniconda3/envs/holoviz/lib/python3.12/site-packages/bokeh/server/static
node.js version       :  v22.5.1
npm version           :  10.8.2
jupyter_bokeh version :  4.0.5
Operating system      :  Linux-6.9.3-76060903-generic-x86_64-with-glibc2.35
```

### Browser name and version

_No response_

### Jupyter notebook / Jupyter Lab version

_No response_

### Expected behavior

I would expect `NaN` values to be changed to `-`.

### Observed behavior

It does not. 

### Example code

```Python
import numpy as np
from bokeh.io import show
from bokeh.models import ColumnDataSource, DataTable, StringFormatter, TableColumn

formatter = StringFormatter(nan_format="-")
source = ColumnDataSource(dict(a=["1", "2", "3", np.nan, float("nan")]))
columns = [TableColumn(field="a", formatter=formatter)]
data_table = DataTable(source=source, columns=columns)
show(data_table)
```

### Stack traceback or browser console output

_No response_

### Screenshots

image

### PR DESCRIPTION
**Pull request by bryevdv**
- [x] issues: fixes #14014
- [x] tests added / passed

### CODE REVIEW

**Comment by bryevdv** [comment]
Well, presumably the `nan_format` test now fails because the output is `-` rather than `NaN` in the image... which makes me wonder, should the default `nan_format` actually be the string `"NaN"`? Why is it a single dash? I actually think it really should be `"NaN"` for the *default*.  cc @philippjfr for thoughts

**Comment by bryevdv** [comment]
@mattpap how can I run individual or subsets of BokehJS tests?

**Comment by bryevdv** [comment]
It looks like `nan_format` got changed in https://github.com/bokeh/bokeh/pull/12098 after a discussion, but in retrospect I think the decision is not ideal. I suppose perhaps we just make `StringFormatter` display `NaN` for these values?

Edit: honestly I rather think `null_format` and `nan_format` should be distinct as well...

**Comment by mattpap** [comment]
> how can I run individual or subsets of BokehJS tests?

E.g. `node make test -k StringFormatter`. The same applies to `test:unit` and other sub-commands.

File: bokehjs/src/lib/models/widgets/tables/cell_formatters.ts [hunk 1]
```diff
@@ -71,6 +71,11 @@ export class StringFormatter extends CellFormatter {
   override doFormat(_row: any, _cell: any, value: any, _columnDef: any, dataContext: any): string {
     const {font_style, text_align, text_color, background_color} = this
 
+    // unfortunately isNaN("foo") is true
+    if (value == null || (isNumber(value) && isNaN(value))) {
```
Comment (mattpap) [inline bokehjs/src/lib/models/widgets/tables/cell_formatters.ts]: I mentioned this in a recent PR that `isNaN()` must not be used without a type guard, because `isNaN("foo")` equivalent to `isNaN(Numer("foo"))` and `Number("foo")` is literal `NaN`. There's `Number.isNaN()` that behaves better, so you may want to use that to simplify the code and make the comment unnecessary. For completeness, one can also use `Object.is()` to compare with `NaN`, e.g.:
```ts
> Object.is(Number("foo"), NaN)
true
```
though I wouldn't prefer this over `Number.isNaN()`.

**Comment by philippjfr** [comment]
Agree with `NaN` for the default.

**Comment by philippjfr** [comment]
>honestly I rather think null_format and nan_format should be distinct as well...

Yes, that makes sense to me as well.

**Comment by bryevdv** [comment]
> Agree with NaN for the default.

@philippjfr Just clarifying, do you mean the new default for just `StringFormatter`? Or do mean change the existing default for the numeric formatters that currently specify `-` as well?

**Comment by bryevdv** [comment]
I split out `null_format` and made the defaults for StringFormatter be `"NaN"` and `"(null)"`. I left the defaults for the numeric formatters as-is, i.e. `"-"` for both. This seems like a reasonable compromise that avoids changing existing behavior.

File: bokehjs/src/lib/models/widgets/tables/cell_formatters.ts [hunk 2]
```diff
@@ -64,13 +65,20 @@ export class StringFormatter extends CellFormatter {
...
   }
 
   override doFormat(_row: any, _cell: any, value: any, _columnDef: any, dataContext: any): string {
     const {font_style, text_align, text_color, background_color} = this
 
+    if (Number.isNaN(value)) {
+      value = this.nan_format
+    } else if (value == null) {
+      value = this.null_format
+    }
```
Comment (bryevdv) [inline bokehjs/src/lib/models/widgets/tables/cell_formatters.ts:80]: FWIW I think this is slightly awkward with the other formatters inheriting from `StringFormatter`, since they also do the same checks and then often call `super.doFormat`. 

That said, things already seem a bit vague here: e.g. is StringFormatter a formatter *for string value inputs* or a formatter that formats anything, *to string values*? In seems like a name more like`TextPropertiesFormatter` would be more descriptive here.

**Review by mattpap — APPROVED** [review]
