### PR TITLE
Make glyph renderer respect subset indices of visuals

### LINKED ISSUE #9230: [BUG] WebGL + CDSView seems to use incorrect marker fill colours
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
bokeh 1.0.4 + 1.3.4
Python 3.7.4
Windows 10 + (Arch) Linux
Firefox Dev + Chrome Dev

#### Description of expected behavior and the observed behavior
I guess this is a pretty obscure issue, but it was leading to some problems with a bokeh server app I'm working on and so I spent a while trying to narrow down the cause. 

The app has a figure that displays a collection of circle markers. The data comes from a ColumnDataSource passed to ```circle()``` using the source keyword arg. There are two types of points in the collection, and I'm using a CDSView instance passed with the view keyword arg combined with a checkbox widget to allow the figure to be toggled between showing all the points, or just one specific type. The datasource has a 'fill' column with hex colour strings for each point, and so when calling circle() I just set ```fill_color='fill'``` to handle that. That all works as expected.

The problem appears when updating the CDSView instance so that it displays all or only some of the markers. I expected that I could simply use an IndexFilter containing the datasource indices of the subset of points I wanted to display, and that does indeed show the correct set of markers. But it didn't seem to be displaying them with the right fill colours for some reason. Eventually I realised that it was seemingly reading the fill colours consecutively from index 0 of the datasource, not picking out the values specified by the filter. The end result of this was that toggling back and forth between the two states caused the colours to toggle between two different mappings as well. 

What finally fixed it was simply removing ```output_backend='webgl'``` from my call to ```figure```. I'd added this to see if it improved performance as some of the plots have a few thousand points, and then forgot about it. With the same code and that parameter removed, I can now toggle back and forth and see the colours remain fixed as they should. 

The example script below should show two plots, one using the default backend and one using WebGL. It creates a simple dataset with points distributed between the left/right halves, colouring the first POINTS/2 markers red and the others green. As you can see in the screenshots, the "all points" state of both plots is identical, and as you'd expect there are a mix of colours on either side. After clicking the "toggle" button to hide half the points, the default backend plot retains both position and marker colours, while the WebGL plot retains position but colours all the markers red - since the red values are the first half of the 'fill' column in the datasource, this seems to indicate it's ignoring the IndexFilter indices and is reading the colours from the beginning of the 'fill' column instead. 

#### Complete, minimal, self-contained example code that reproduces the issue

```
from random import random

import bokeh
from bokeh.layouts import column
from bokeh.models import Button, CDSView, IndexFilter, ColumnDataSource
from bokeh.plotting import figure, curdoc

# bokeh serve example.py

POINTS = 100

data = {'x': [], 'y': [], 'fill': []}
for i in range(POINTS):
    # put half the points on either side of the plot
    data['x'].append(random() + (i % 2))
    data['y'].append(random())
    # colour the first POINTS//2 markers red and the rest green
    data['fill'].append('#ff0000' if (i < POINTS // 2) else '#00ff00')

# a filter which only shows the points on the left half
fil = IndexFilter([i for i in range(POINTS) if i % 2 == 0])

def callback():
    view.filters = [] if len(view.filters) == 1 else [fil]

ds = ColumnDataSource(data=data)
view = CDSView(source=ds, filters=[])

p_ok = figure(x_range=(-0.25, 2.25), y_range=(-0.25, 1.25), title='Using default backend')
p_ok.circle('x', 'y', radius=.05, source=ds, view=view, fill_color='fill')

p_bug = figure(x_range=(-0.25, 2.25), y_range=(-0.25, 1.25), title='Using WebGL backend', output_backend='webgl')
p_bug.circle('x', 'y', radius=.05, source=ds, view=view, fill_color='fill')

button = Button(label="toggle")
button.on_click(callback)
curdoc().add_root(column(button, p_ok, p_bug))
```
#### Screenshots or screencasts of the bug in action
Here's what the script should look like when started:
one_

And here is the toggled state showing the difference between default (top) and WebGL (bottom) backends:
two_

### PR DESCRIPTION
**Pull request by mattpap**
fixes #9230

### CODE REVIEW

File: bokehjs/src/lib/core/visuals.ts [hunk 1]
```diff
@@ -220,6 +222,15 @@ export abstract class ContextProperties {
...
   }
 
+  get_array(attr: string): Arrayable {
+    const array = this.cache[attr + "_array"] as Arrayable
+    if (this.all_indices != null) {
+      return map(this.all_indices, (i) => array[i])
+    } else {
+      return array
+    }
+  }
```
Comment (mattpap) [inline bokehjs/src/lib/core/visuals.ts:232]: Note this is a temporary solution until I get to a proper redesign of visuals (as briefly discussed in another PR).
