### PR TITLE
Canavandl/6909 notebook fixes

### LINKED ISSUE #6909: Notebook output generates console errors
Since introducing JupyterLab compatibility in bokeh master displaying bokeh plots in the classic notebook generates various JS errors in certain conditions (which I haven't yet narrowed down). Here's an example that reliable reproduces the issue:

```python
import math

from bokeh.io import show
from bokeh.plotting import figure
from bokeh.models import GraphRenderer, StaticLayoutProvider, Oval
from bokeh.palettes import Spectral8
from bokeh.layouts import row
from bokeh.io import output_notebook

output_notebook(hide_banner=False)


def create_graph():
    N = 8
    node_indices = list(range(N))

    plot = figure(title="Graph Layout Demonstration", x_range=(-1.1,1.1), y_range=(-1.1,1.1),
                  tools="", toolbar_location=None)

    graph = GraphRenderer()

    graph.node_renderer.glyph = Oval(height=0.1, width=0.2, fill_color="fill_color")
    graph.node_renderer.data_source.data = dict(
        index=node_indices,
        fill_color=Spectral8)

    graph.edge_renderer.data_source.data = dict(
        start=[0]*N,
        end=node_indices)

    ### start of layout code
    circ = [i*2*math.pi/8 for i in node_indices]
    x = [math.cos(i) for i in circ]
    y = [math.sin(i) for i in circ]

    graph_layout = dict(zip(node_indices, zip(x, y)))
    graph.layout_provider = StaticLayoutProvider(graph_layout=graph_layout)

    plot.renderers.append(graph)
    return plot

p1 = create_graph()
p2 = create_graph()

show(row(p1, p2))
```

This produces the following error on the console, which appears twice:

```
Exception in event handler for output_added.OutputArea TypeError: Cannot read property 'hasOwnProperty' of undefined
    at window._Events.handleAddOutput (eval at append_javascript (outputarea.js:727), <anonymous>:67:21)
    at window._Events.dispatch (jquery.min.js:5)
    at window._Events.y.handle (jquery.min.js:5)
    at Object.trigger (jquery.min.js:5)
    at window._Events.<anonymous> (jquery.min.js:5)
    at Function.each (jquery.min.js:4)
    at init.each (jquery.min.js:4)
    at init.trigger (jquery.min.js:5)
    at init.events.trigger (events.js:31)
    at OutputArea.append_output (outputarea.js:339) (2) ["output_added.OutputArea", {…}, callee: (...), Symbol(Symbol.iterator): ƒ]
```

This is presumable occurs due to an issue here in the autoload_nb_js template: https://github.com/bokeh/bokeh/blob/master/bokeh/core/_templates/autoload_nb_js.js#L59

### PR DESCRIPTION
**Pull request by canavandl**
Canavandl/6909 notebook fixes

- [ ] issues: fixes #6909 #6908 
- [ ] tests added / passed
- [ ] release document entry (if new feature or API change)

### CODE REVIEW

File: bokeh/core/_templates/autoload_js.js [hunk 1]
```diff
@@ -74,12 +74,10 @@ calls it with the rendered model.
       document.getElementsByTagName("head")[0].appendChild(s);
     }
   };
-
   {%- if elementid -%}
   var element = document.getElementById({{ elementid|json }});
   if (element == null) {
     console.log("Bokeh: ERROR: autoload.js configured with elementid '{{ elementid }}' but no matching script tag was found. ")
-    return false;
```
Comment (canavandl) [inline bokeh/core/_templates/autoload_js.js]: The issue is that we now optionally publish an html div for the banner, then publish the autoload script. When the banner isn't loaded, this elementid doesn't exist and the load script is returned before embedding the resources.

I need to think a little more about the impact of this change on other autoload situations.
