### PR TITLE
Fix computation of image indices for inverted ranges

### LINKED ISSUE #13555: [BUG] image hover value is wrong on inverted axes
### Software versions

Bokeh version: 3.2.2
Python version: 3.10.12

### Browser name and version

_No response_

### Jupyter notebook / Jupyter Lab version

_No response_

### Expected behavior

Showing image values should work on flipped and normal y_range. According to #9253 it should have been fixed a while ago, however I still experience the issue

### Observed behavior

The hover image Value is picked from the opposite end of the image when y_range is flipped (also if the figure is instantiated with y_range=(max_y, 0)

### Example code

```Python
import numpy as np
from bokeh.plotting import figure, output_file, show
from bokeh.models import ColorBar, LinearColorMapper, HoverTool

X,Y = np.meshgrid(np.linspace(0,10,10), np.linspace(0,10,10))

#Calculate the distance from origo:
Z = np.sqrt(X ** 2 + Y ** 2)

output_file(r"C:\Temp\deleme.html")

p = figure()

p.y_range.flipped = True

mapper = LinearColorMapper(palette='Viridis256')
img = p.image(image=[Z], x=0, y=0, dw=10, dh=10, color_mapper=mapper)
color_bar = ColorBar(color_mapper=mapper)
p.add_layout(color_bar, 'right')

hover = HoverTool(renderers=[img], tooltips=[("Value", "@image")])
p.add_tools(hover)
show(p)
```

### Stack traceback or browser console output

_No response_

### Screenshots

screenshot

### PR DESCRIPTION
**Pull request by mattpap**
Also fixes (includes) handling of image indices in `Selection`. This wasn't noticed before, because with inspections go through a different code path, which persists those indices. I will look more into this in PR #13439 or its follow-up.

image

fixes #13555

### CODE REVIEW

**Review by bryevdv — APPROVED** [review]

File: bokehjs/test/unit/regressions.ts [hunk 1]
```diff
@@ -1239,4 +1240,81 @@ describe("Bug", () => {
...
+
+      async function test(options: {x_flipped: boolean, y_flipped: boolean}) {
+        const {x_flipped, y_flipped} = options
+
+        const {view, img} = await plot(x_flipped, y_flipped)
+        const actions = new PlotActions(view)
+
+        await actions.tap({x: 1, y: 1})
+        await view.ready
+        await delay(500) // remove in PR #12831
```
Comment (mattpap) [inline bokehjs/test/unit/regressions.ts:1315]: I will wait with this PR till #12831 is merged, because otherwise I would either have to increase this number further or leave it, making the test unreliable.
