### PR TITLE
don't add a BBox if axis has fixed location

### LINKED ISSUE #14776: Don't add BBox if an axis has fixed position
### Software versions

(civa) C:\CIVA_RP\CIVA_ARQANE\src_python\bokeh\examples\advanced\extensions\parallel_plot>bokeh info
Python version        :  3.12.5 (main, Aug 14 2024, 04:23:18) [MSC v.1929 64 bit (AMD64)]
IPython version       :  9.4.0
Tornado version       :  6.5.1
NumPy version         :  2.2.6
Bokeh version         :  3.8.2
BokehJS static path   :  C:\CIVA_RP\CIVA_ARQANE\.venv\Lib\site-packages\bokeh\server\static
node.js version       :  v24.12.0

### Browser name and version

_No response_

### Jupyter notebook / Jupyter Lab version

_No response_

### Expected behavior

bokeh/examples/advanced/extensions/parallel_plot
without extra space between plot and toolbar

### Observed behavior

parallel_plot example has an extra space between the plot and the toolbar:

Image

### Example code

```Python
run bokeh/examples/advanced/extensions/parallel_plot
```

### Stack traceback or browser console output

_No response_

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by mosc9575**
- [x] issues: fixes #14776
- [x] tests added / passed
- [x] added baseline image

This baseline image will be added after generation.

Screenshot 2026-02-06 150207

### CODE REVIEW

**Comment by mosc9575** [comment]
This screenshot from the generated examples report shows the example from the original issue #14776 with and without the suggested changes.


|**new**|**old**|
|--|--|
|grafik|Image|

File: bokehjs/src/lib/models/axes/axis.ts [hunk 1]
```diff
@@ -71,10 +71,10 @@ export abstract class AxisView extends GuideRendererView {
   /*private*/ _major_label_views: Map<string | number, BaseTextView> = new Map()
 
   override get bbox(): BBox {
-    // TODO Fixed axes should not participate in layout at all.
     if (this.layout != null && this.model.fixed_location == null) {
       return this.layout.bbox
-    } else if (this.is_renderable) {
+    } else if (this.is_renderable && this.model.fixed_location == null) {
+      // Fixed axes return an empty BBox and do not effect the layout.
```
Comment (mattpap) [inline bokehjs/src/lib/models/axes/axis.ts]: I would rewrite this to make the case of fixed axes more apparent:
```ts
    if (this.model.fixed_location != null) {
      return new BBox()
    } else if (this.layout != null) {
      return this.layout.bbox
    } else if (this.is_renderable) {
      ...
    } else {
      return new BBox()
    }

File: bokehjs/test/integration/axes.ts [hunk 2]
```diff
@@ -265,6 +266,21 @@ import {radians} from "@bokehjs/core/util/math"
...
+      it("should be added without effecting the position of the toolbar", async () => {
+        const p = fig([300, 300], {toolbar_location: "right"})
+        p.scatter([1, 2, 3], [1, 2, 3])
+        p.extra_x_ranges = {["x"]: new Range1d({start: 0.9, end: 3.1})}
+        p.extra_y_ranges = {["y"]: new Range1d({start: 0.9, end: 3.1})}
+        p.add_layout(new LinearAxis({x_range_name: "x", fixed_location: 1.5}), "below")
+        p.add_layout(new LinearAxis({y_range_name: "y", fixed_location: 2.5}), "right")
+        p.add_layout(new Toolbar({tools: []}), "above")
+        p.add_layout(new Toolbar({tools: []}), "left")
+        p.add_layout(new Toolbar({tools: []}), "below")
```
Comment (mattpap) [inline bokehjs/test/integration/axes.ts]: A few tools would be useful, because it's hard too know what one is looking at in the generated image. If fact we should see nothing at all, and those three dots are an indicator of an unrelated bug in `Toolbar` rendering.

File: docs/bokeh/source/docs/releases/3.9.0.rst [hunk 3]
```diff
@@ -15,3 +15,4 @@ Bokeh version ``3.9.0`` (February 2026) is a minor milestone of Bokeh project.
 * Fixed issue where ``CategoricalSlider`` displayed "undefined" in the tooltip (:bokeh-pull:`14774`)
 * Added support for Markdown formatted contents display with ``Markdown`` widget (:bokeh-pull:`14780`)
 * Added support for binary protocol to all server messages types (:bokeh-pull:`14725`)
+* Fixed issue where axis with fixed location added an unnecessary BBox (:bokeh-pull:`14840`)
```
Comment (mattpap) [inline docs/bokeh/source/docs/releases/3.9.0.rst]: This is an information to the user, thus it should convey some high level meaning, but this tells nothing unless you're already deep into layouts and stuff. In fact the description of the new integration test would be better used here. Perhaps something along:
```suggestion
* Fixed a bug that caused manually positioned plot axes to shift position of toolbars (:bokeh-pull:`14840`)
```

File: bokehjs/test/integration/axes.ts (hunk 2 above)
Comment (mosc9575) [reply bokehjs/test/integration/axes.ts]: I planed to add some tools but I didn't know how to change the orientation and with tools it looks a bit odd.

```python
from bokeh.models import LinearAxis, Range1d, Toolbar
from bokeh.plotting import figure, show, output_notebook
output_notebook()

p = figure(width=300, height=300, toolbar_location='right')
p.line([1,2,3], [1,2,3])
p.extra_x_ranges['x'] = Range1d(0.9, 3.1)
p.extra_y_ranges['y'] = Range1d(0.9, 3.1)
p.add_layout(LinearAxis(y_range_name='y', fixed_location=1.5), 'right')
p.add_layout(LinearAxis(x_range_name='x', fixed_location=2.5), 'below')
p.add_layout(Toolbar(tools=[]), 'above')
p.add_layout(Toolbar(tools=p.tools[:1]), 'left')
p.add_layout(Toolbar(tools=p.tools[:2]), 'below')
show(p)
```
grafik


And a comment to the three little dots:

```python
from bokeh.models import PanTool, WheelZoomTool
from bokeh.layouts import row
from bokeh.plotting import show, output_notebook
output_notebook()

toolbar1 = Toolbar(tools=[])
toolbar2 = Toolbar(tools=[PanTool()])
toolbar3 = Toolbar(tools=[PanTool(), WheelZoomTool()])
```

The line

```
show(row([toolbar1, toolbar2, toolbar3]))
```

results in 

grafik

but 

```
show(toolbar1)
```

 gives 

grafik
,

```
show(toolbar2)
```

shows 

grafik

and 

```
show(toolbar3)
```

grafik

Comment (mattpap) [reply bokehjs/test/integration/axes.ts]: I didn't notice `p.add_layout(Toolbar(...))`, which won't work like that yet. Currently we need `ToolbarPanel` in between a `Plot` and `Toolbar`. Something like this should work:
```ts
plot.add_layout(new ToolbarPanel({toolbar: new Toolbar({..., location: "left"})}), "left")
```
This is what `PlotView` does internally with `Plot.toolbar` and `Plot.toolbar_location`. Of course `location` and second argument to `add_layout()` must match.

**Review by mattpap — APPROVED** [review]
