### PR TITLE
[BUG] Fix broken link to tools guide

### LINKED ISSUE #13108: [BUG] Fix broken link to tools guide
### Software versions

Python version      :  3.11.3 (main, Apr  7 2023, 19:30:05) [Clang 13.0.0 (clang-1300.0.29.30)]
IPython version     :  (not installed)
Tornado version     :  6.3.1
Bokeh version       :  3.1.0
BokehJS static path :  /usr/local/lib/python3.11/site-packages/bokeh/server/static
node.js version     :  (not installed)
npm version         :  (not installed)
Operating system    :  macOS-11.7.6-x86_64-i386-64bit

### Browser name and version

Firefox 112.0.2

### Jupyter notebook / Jupyter Lab version

_No response_

### Expected behavior

Clicking the question mark on a toolbar should open the tools guide.

### Observed behavior

Opens a broken link: https://docs.bokeh.org/en/latest/docs/user_guide/tools.html. The correct link is https://docs.bokeh.org/en/latest/docs/reference/models/tools.html.

### Example code

```Python
N/A
```

### Stack traceback or browser console output

Can be fixed by editing the following lines:
https://github.com/search?q=repo%3Abokeh%2Fbokeh%20%22https%3A%2F%2Fdocs.bokeh.org%2Fen%2Flatest%2Fdocs%2Fuser_guide%2Ftools.html%22&type=code

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by kshitiz305**
Issue: Fixes #13108 

All pull requests must have an associated issue in the issue tracker. If there
isn't one, please go open an issue describing the defect, deficiency or desired
feature. You can read more about our issue and PR processes in the
[wiki](https://github.com/bokeh/bokeh/wiki/BEP-1:-Issues-and-PRs-management).

- [X] issues: fixes #xxxx
- [X] tests added / passed
- [X] release document entry (if new feature or API change)

### CODE REVIEW

File: bokehjs/src/lib/models/tools/actions/help_tool.ts [hunk 1]
```diff
@@ -32,7 +32,7 @@ export class HelpTool extends ActionTool {
     this.prototype.default_view = HelpToolView
 
     this.define<HelpTool.Props>(({String}) => ({
-      redirect: [ String, "https://docs.bokeh.org/en/latest/docs/user_guide/tools.html"],
+      redirect: [ String, "https://docs.bokeh.org/en/latest/docs/reference/models/tools.html"],
```
Comment (mattpap) [inline bokehjs/src/lib/models/tools/actions/help_tool.ts]: This https://docs.bokeh.org/en/latest/docs/user_guide/interaction/tools.html is the correct link. Same in other cases.

**Review by mattpap — CHANGES_REQUESTED** [review]

File: bokehjs/src/lib/models/tools/actions/help_tool.ts (hunk 1 above)
Comment (kshitiz305) [reply bokehjs/src/lib/models/tools/actions/help_tool.ts]: Let me update it as the one mentioned in the issue was different

**Review by mattpap — APPROVED** [review]

**Comment by mattpap** [comment]
@kshitiz305, thanks for fixing this.
