### PR TITLE
Serialize definitions of only newly created objects

### LINKED ISSUE #11026: [BUG] Serialization of MessageSent document event includes all model references
Observed a drop in performance while upgrading from release 2.2.3 to 2.3.0, on a page using ```MouseMove``` events to update a line plot. Fast mouse movement causes events to 'queue' and complete after mouse has stopped.

Issue discussed on Discourse at [https://discourse.bokeh.org/t/mousemove-events-queuing-up-after-2-3-0-update/7361](https://discourse.bokeh.org/t/mousemove-events-queuing-up-after-2-3-0-update/7361).

From @mateusz on Discourse:

> Currently serialization of MessageSent document event includes all model references this event’s model field refers to, whereas it should include only previously unknown models. This is a regression since PR [https://github.com/bokeh/bokeh/pull/10602](https://github.com/bokeh/bokeh/pull/10602).

An MWE is available on the Discourse thread.

Versions:
Bokeh 2.3.0 (upgrading from 2.2.3)
Python 3.9.2 on Ubuntu 20.04 / Firefox 86.0

Video of behaviour:

https://user-images.githubusercontent.com/78845903/110388722-cb8c0180-8063-11eb-9ca3-323139880ff2.mp4

### PR DESCRIPTION
**Pull request by mattpap**
fixes #11026

### CODE REVIEW

File: bokehjs/test/codebase/size.ts [hunk 1]
```diff
@@ -6,12 +6,12 @@ const build_dir = normalize(`${__dirname}/../..`) // build/test/codebase -> buil
 
 const LIMITS = new Map([
   // es2017
-  ["js/bokeh.min.js",                 800],
+  ["js/bokeh.min.js",                 950],
```
Comment (bryevdv) [inline bokehjs/test/codebase/size.ts:9]: 👀

Comment (mattpap) [reply bokehjs/test/codebase/size.ts:9]: This is just to avoid rebasing between 2.3 and 2.4 due to webgl changes.

**Comment by bryevdv** [comment]
@mattpap Is there any update on the 2.3.1 regressions? FYI  it would be very good to have 2.3.1 before early April otherwise some downstream projects will not be able to adopt latest Bokeh before their current code freeze schedule.

**Review by bryevdv — APPROVED** [review]
