### PR TITLE
Fix missing vline hover hits for multi line

### LINKED ISSUE #8787: vline hover misses some multi-lines
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
Bokeh 1.0.4, but same issue in 0.13 and 1.0.1.
Python 2.7.15
Anaconda custom (64-bit) (default, Nov 13 2018, 23:04:45) 
[GCC 7.3.0] on linux2
Tested on latest Chrome and Opera.

#### Description of expected behavior and the observed behavior
When plotting the example below, a lot of hover events are triggered as seen in the console, even though the HoverTool is specified to trigger on specified multi_lines.

Many of these events have empty `cb_data.index['1d'].indices` field, and in the case with two multi-lines, it seems that both trigger the callback as seen by `cb_data.renderer.name`.

Perhaps unrelated, but setting HoverTool `mode='vline'` results in only the blue multi_line triggering. I'm uploading a gif on this behavior below as well.

#### Complete, minimal, self-contained example code that reproduces the issue
```
from bokeh.plotting import figure, output_file, show, save
from bokeh.models import ColumnDataSource, HoverTool, CustomJS
import bokeh

# Data
x = [[0,1,2],[4,5,6]] 
y = [[0,1,0],[1,2,1]]
time = [[-3,-3.5,-5], [-1,-2,-2.5]] 
amplitude = [[-1,-2,-1], [-1,-2,1]]

p = figure(plot_width=400, plot_height=400, tools="", toolbar_location=None, title='Hover (Bokeh ' + bokeh.__version__ + ')')

# CDS
linesource = ColumnDataSource({'x': x, 'y': x})
linesource2 = ColumnDataSource({'time': time, 'amplitude': amplitude})

# Renderers
mylines = p.multi_line(xs='x', ys='y', source=linesource, name='blue', color='darkblue', hover_color='darkblue')
myotherlines = p.multi_line(xs='time', ys='amplitude', name='red', source=linesource2, color='darkred', hover_color='darkred')
mylines.hover_glyph.line_width = 3
myotherlines.hover_glyph.line_width = 3
# HoverTool
code = """
console.log('1d ind: ' + cb_data.index['1d'].indices + ', cb_data.renderer.name = ' + cb_data.renderer.name)
fig.title.text = '1d ind: ' + cb_data.index['1d'].indices + ', cb_data.renderer.name = ' + cb_data.renderer.name + ' - ' + 'Bokeh '  + ver

"""
callback = CustomJS(
    args={
        'lines': mylines.data_source,
        'otherlines': myotherlines.data_source,
        'fig': p,
        'ver': bokeh.__version__},
    code=code)
p.add_tools(HoverTool(tooltips=None, names=['blue', 'red'], callback=callback))

# Save
output_file("hover_callback.html")
save(p)
```
#### Screenshots or screencasts of the bug in action
hover_manytrig

Here's the `mode='vline'` behavior:
hover_vline2

### PR DESCRIPTION
**Pull request by muendlein**
- [x] issues: fixes #8787
- [x] tests added / passed

Test will follow soon.

### CODE REVIEW

File: bokehjs/src/lib/models/glyphs/multi_line.ts [hunk 1]
```diff
@@ -125,7 +125,7 @@ export class MultiLineView extends GlyphView {
       const vsi = vs.get(i)
       const points: number[] = []
       for (let j = 0, endj = vsi.length - 1; j < endj; j++) {
-        if (vsi[j] <= val && val <= vsi[j + 1]) {
+        if ((vsi[j] <= val && val <= vsi[j + 1]) || (vsi[j] >= val && val >= vsi[j + 1])) {
```
Comment (mattpap) [inline bokehjs/src/lib/models/glyphs/multi_line.ts]: > `if ((vsi[j] <= val && val <= vsi[j + 1]) || (vsi[j] >= val && val >= vsi[j + 1])) {`

I wish we could just write:
```ts
if ((vsi[j] <= val <= vsi[j + 1]) || (vsi[j] >= val >= vsi[j + 1])) {
```
However, it would be an improvement in reading this code if all `<=` and `>=` were facing the same direction, i.e.:
```suggestion
        if ((vsi[j] <= val && val <= vsi[j + 1]) || (vsi[j + 1] <= val && val <= vsi[j])) {
```

**Comment by mattpap** [comment]
This fixes the problem. Of course some unit regression tests are needed for completion.

**Review by mattpap — APPROVED** [review]

**Comment by mosc9575** [comment]
I think this should be added to `3.9.1` - see #15089.
