### PR TITLE
Fix WebGL marker count change

### LINKED ISSUE #11679: [BUG] Parallel Plot example with output_backend="webgl" not working
From bokeh 2.4.0 if output_backend="webgl" is set on figure options (https://github.com/bokeh/bokeh/blob/664fc492b8a7ac5839424b04f63a351c06f38187/examples/custom/parallel_plot/parallel_plot.py#L34), the selection glyphs does not render correctly cf image below:
bug_webgl_backend

### PR DESCRIPTION
**Pull request by ianthomas23**
Fixes bug that occurs in WebGL when the number of markers/rects is changed under certain circumstances none of them are displayed. It was an error of omission in an `if..then` block.

Fix is the same for both markers and rects. This duplication will be removed when they are combined (WebGL roadmap discussion #11369 item 5).

I have added a test for `rect` only but manually checked `marker` too.

- [x] issues: fixes #11679
- [x] tests added / passed
- [ ] release document entry (if new feature or API change)

### CODE REVIEW

File: bokehjs/test/integration/glyphs/rect.ts [hunk 1]
```diff
@@ -27,4 +28,17 @@ describe("Rect glyph", () => {
 
     await display(row([make_plot("canvas"), make_plot("svg"), make_plot("webgl")]))
   })
+
+  it("should support adding new glyph", async() => {
+    const p = fig([200, 200], {
+      title: null,
+      toolbar_location: null,
```
Comment (mattpap) [inline bokehjs/test/integration/glyphs/rect.ts:35]: No need for both. `fig()` is there to create bare plots, while keeping the figure API.

File: bokehjs/test/integration/glyphs/rect.ts [hunk 2]
```diff
@@ -27,4 +28,17 @@ describe("Rect glyph", () => {
 
     await display(row([make_plot("canvas"), make_plot("svg"), make_plot("webgl")]))
   })
+
+  it("should support adding new glyph", async() => {
```
Comment (mattpap) [inline bokehjs/test/integration/glyphs/rect.ts:32]: Looking at the code, it's about changing data not glyphs? Suppose it should be adding a new data point to an existing glyph.

File: bokehjs/src/lib/models/glyphs/webgl/buffer.ts [hunk 3]
```diff
@@ -36,7 +36,7 @@ abstract class WrappedBuffer<ArrayType extends WrappedArrayType> {
   }
 
   get length(): number {
-    return this.array.length
+    return this.array != null ? this.array.length : 0
```
Comment (mattpap) [inline bokehjs/src/lib/models/glyphs/webgl/buffer.ts:39]: If `array` can be `null` (or I suppose `undefined`, uninitialized), then this has to be encoded in the type of `array`, possibly `array?: ArrayType` or `array: ArrayType | null = null`. We currently don't enforce `strictPropertyInitialization` (due to `initialize()` methods), so enforcing this has to be done manually.

File: bokehjs/test/integration/glyphs/rect.ts (hunk 1 above)
Comment (ianthomas23) [reply bokehjs/test/integration/glyphs/rect.ts:35]: This was a copy and paste of
https://github.com/bokeh/bokeh/blob/0cadaff30bc976a6fca39c07b538e891dc76651f/bokehjs/test/integration/regressions.ts#L93-L97
I'll remove both. Do you want me to similarly clean the original?

File: bokehjs/test/integration/glyphs/rect.ts (hunk 2 above)
Comment (ianthomas23) [reply bokehjs/test/integration/glyphs/rect.ts:32]: Yes, it is about changing the count of a single glyph. I'll change the `it` description.

File: bokehjs/src/lib/models/glyphs/webgl/buffer.ts (hunk 3 above)
Comment (ianthomas23) [reply bokehjs/src/lib/models/glyphs/webgl/buffer.ts:39]: It can be uninitialized. Up until now it has always been initialized before being used, but in this situation I need to check it before that.  I've opted for the `array?: ArrayType` approach.

File: bokehjs/test/integration/glyphs/rect.ts (hunk 1 above)
Comment (mattpap) [reply bokehjs/test/integration/glyphs/rect.ts]: Sure.
