### PR TITLE
Fix logic in plugin prelude

### LINKED ISSUE #10782: Typo in prelude.ts
There is a typo in prelude.ts which becomes part of `bokeh-[VERSION].min.js`. "lenght" should be replace with "length"

https://github.com/bokeh/bokeh/blob/90e83b256dafa1371cc90d4e03ffcdc006b8e172/bokehjs/src/compiler/prelude.ts#L65

### PR DESCRIPTION
**Pull request by mattpap**
Previously if bokeh wasn't available, but a plugin bundle was loaded, then it would result in `register_plugin()` doesn't exist on `undefined` error, instead of the expected error message.

fixes #10782

### CODE REVIEW

File: bokehjs/src/compiler/prelude.ts [hunk 1]
```diff
@@ -219,7 +219,7 @@ ${comment(license)}
 })(this, function(Bokeh, version) {
   let define;
   return (function(modules, entry, aliases, externals) {
-    const bokeh = typeof Bokeh !== "undefined" && (version != null ? Bokeh[version] : Bokeh);
+    const bokeh = (typeof Bokeh !== "undefined" && version != null ? Bokeh[version] : Bokeh;
```
Comment (bryevdv) [inline bokehjs/src/compiler/prelude.ts]: maybe I am missing something obvious, I don't see where this open paren is closed

Comment (mattpap) [reply bokehjs/src/compiler/prelude.ts]: Just a mistake, though that logic wasn't good anyway.

**Review by bryevdv — APPROVED** [review]
