### PR TITLE
Fix performance regressions introduced in 3.0

### LINKED ISSUE #12666: [BUG] Performance differences between v2 and v3
### Software versions

Python version : 3.11.0
IPython version : (not installed)
Tornado version : 6.2
Bokeh version : 2.4.3 and 3.0.2
BokehJS static path : ---
node.js version : (not installed)
npm version : (not installed)
Operating system : Fedora 37, Linux 6.0.11-300.fc37.x86_64

### Browser name and version

Firefox 108.0b9 (64-bit) and Chrome Version 108.0.5359.94

### Jupyter notebook / Jupyter Lab version

_No response_

### Expected behavior

Excited by the announcements about the great performance improvement of the Bokeh 3 layout system, I decided to make some comparisons with v2. The script creates nested tabs containing a 2x2 grid of scatter plots made of row and column elements.
Bokeh 3 should be faster or at least as fast as Bokeh 2

The tests were performed using python 3.11 and bokeh server from two virtual environments using the following requirements files:
```
# requirements_v2.txt
bokeh==2.4.3
pandas>=1.5.2
```
```
# requirements_v3.txt
bokeh==3.0.2
pandas>=1.5.2
```

### Observed behavior

Unfortunately, the performance I got was worse in v3 than in v2

### Example code

```Python
# main.py

import numpy as np
import pandas as pd

from bokeh.plotting import curdoc, figure
from bokeh.layouts import column, row
from bokeh.models import Tabs, Band, ColumnDataSource, Div
from bokeh.util import version

BOKEH_VERSION = int(version.base_version()[0])

if BOKEH_VERSION >= 3:
    from bokeh.models import TabPanel as Panel
else:
    from bokeh.models import Panel


def bk_version():
    return Div(
        text=f"""
        <h1>Bokeh { BOKEH_VERSION }</h1>
    """
    )


def scatter_plot():
    N = 200
    x = np.random.random(size=N) * 100
    y = np.random.random(size=N) * 100
    radii = np.random.random(size=N) * 1.5
    colors = np.array(
        [[r, g, 150] for r, g in zip(50 + 2 * x, 30 + 2 * y)], dtype="uint8"
    )

    TOOLS = "hover,crosshair,pan,wheel_zoom,zoom_in,zoom_out,box_zoom,undo,redo,reset,tap,save,box_select,poly_select,lasso_select,"

    p = figure(tools=TOOLS)
    p.scatter(x, y, radius=radii, fill_color=colors, fill_alpha=0.6, line_color=None)
    return p


def create_panel(id=None, ncols=2, plots_per_col=3):
    return Panel(
        child=create_grid(ncols=ncols, nrows=plots_per_col),
        title=f"Tab {id or np.random.rand()}",
    )


def create_grid(ncols=2, nrows=2):
    return row(*[column(*[scatter_plot() for k in range(nrows)]) for k in range(ncols)])


def create_tabs(n, parent=None, ncols=2, plots_per_col=3):
    return Tabs(
        tabs=[
            create_panel(id=f"{parent}.{i}", ncols=ncols, plots_per_col=plots_per_col)
            for i in range(n)
        ]
    )


def create_parent_tabs(n, subtabs=2, ncols=2, plots_per_col=3):
    return Tabs(
        tabs=[
            Panel(
                child=create_tabs(
                    subtabs, parent=i, ncols=ncols, plots_per_col=plots_per_col
                ),
                title=f"SuperTab {i}",
            )
            for i in range(n)
        ]
    )


if __name__.startswith("bokeh_app_"):

    tabs = create_parent_tabs(
        4,
        subtabs=3,
        ncols=2,
        plots_per_col=2,
    )

    curdoc().add_root(bk_version())
    curdoc().add_root(tabs)
```

### Stack traceback or browser console output

Both servers were launched from independent virtual environments with the following command:
```
$ bokeh serve ./ --allow-websocket-origin="*:5006"
```

### Screenshots

Here are the results I got:

V2:
Bokeh v2

V3:
Bokeh v3

### PR DESCRIPTION
**Pull request by mattpap**
TODO:

- [x] don't render twice in some cases (in `after_resize()`)
- [x] make `SlickGrid` comply with changes in this PR

fixes #12666

### CODE REVIEW

File: bokehjs/src/lib/models/layouts/layout_dom.ts [hunk 1]
```diff
@@ -433,13 +435,34 @@ export abstract class LayoutDOMView extends UIElementView {
...
+    this.render()
+    if (element != null)
+      element.appendChild(this.el)
+    this.r_after_render()
+    this._was_built = true
+
     this.notify_finished()
   }
 
+  r_after_render(): void {
```
Comment (bryevdv) [inline bokehjs/src/lib/models/layouts/layout_dom.ts:452]: What is the "r_" for?

Comment (mattpap) [reply bokehjs/src/lib/models/layouts/layout_dom.ts:452]: Recursive. I will likely eliminate this method in another round of changes.

**Review by bryevdv — APPROVED** [review]
I don't really have much to contribute review-wise but it looks ok at a glance
