### PR TITLE
clamp zoom factor to prevent axis flipping

### LINKED ISSUE #13504: [BUG] Zooming inverts axis
### Software versions

Python version      :  3.10.13 | packaged by conda-forge | (main, Oct 26 2023, 18:09:17) [Clang 16.0.6 ]
IPython version     :  8.17.2
Tornado version     :  6.3.3
Bokeh version       :  3.3.0
BokehJS static path : /Users/droumis/opt/miniconda3/envs/timeseries/lib/python3.10/site-packages/bokeh/server/static
node.js version     :  v20.4.0
npm version         :  9.7.2
Operating system    :  macOS-13.5.2-arm64-arm-64bit

### Browser name and version

_No response_

### Jupyter notebook / Jupyter Lab version

Observed in both Jupyter Lab 4 and VS Code

### Expected behavior

I don't expect zoom to invert an axis.

### Observed behavior

zooming occasionally inverts the x/y axes.

### Example code

```Python
from bokeh.plotting import figure, show
from bokeh.io import output_notebook

output_notebook()

x = [1, 2, 3, 4, 5]
y = [6, 7, 2, 4, 5]

p = figure(title="simple line example", x_axis_label='x', y_axis_label='y')

p.line(x, y, legend_label="Temp.", line_width=2)

show(p)
```

### Stack traceback or browser console output

_No response_

### Screenshots

https://github.com/bokeh/bokeh/assets/6613202/3cacb80b-877e-42da-bf3c-2db008e0d659

### PR DESCRIPTION
**Pull request by bryevdv**
- [x] issues: fixes #13504

I don't have any ideas for testing this with the current monolithic state of things in the `WheelZoomTool` logic. I'd like to make a follow-on issue to refactor some things and add more testing. But if there are any immediate things we can do I am not aware of please let me know @mattpap

### CODE REVIEW

**Comment by bryevdv** [comment]
@mattpap the baseline change seems minimal / appropriate, no doubt due to a slightly smaller value for `factor` than the test was previously using, but please double check.

File: bokehjs/src/lib/core/util/zoom.ts [hunk 1]
```diff
@@ -10,6 +11,7 @@ type ScaleRanges = RangeInfo & {
 }
 
 export function scale_interval(range: Interval, factor: number, center?: number | null): Bounds {
+  assert(Math.abs(factor) < 1)
   const [min, max] = minmax(range.start, range.end)
```
Comment (mattpap) [inline bokehjs/src/lib/core/util/zoom.ts:15]: Maybe this would be simpler then the assert and a clamp with somewhat arbitrary cutoff values:
```suggestion
  const {start, end} = range
  if (factor >= 1) {
    return [start, end]
  }
  const [min, max] = minmax(start, end)
```
Then you also don't have to change the baseline.

Comment (bryevdv) [reply bokehjs/src/lib/core/util/zoom.ts:15]: I guess I am missing something but this does not seem to be correct at all. If factor is greater-equal than one, we want to instead perform a scale with a factor near (but less than) one. But the change above is equivalent to setting factor equal to zero.

Comment (bryevdv) [reply bokehjs/src/lib/core/util/zoom.ts:15]: Additionally, though I suppose clamping the negative side may not strictly be required to avoid any bug, it does seem reasonable to apply the same clamp in both directions to maintain consistency.

**Comment by mattpap** [comment]
I suppose a quick unit test could be in the spirit of https://github.com/bokeh/bokeh/blob/604e6f801974cedd6000835923bfb9030b64d461/bokehjs/test/unit/models/tools/gestures/wheel_zoom_tool.ts#L197-L215 with `delta` equal to or greater than `WheelZoomTool.speed`, or both. A as side note, by default `delta` is provided in pixel units, though there are also line and page units, normalized to pixels.

**Comment by bryevdv** [comment]
>  A as side note, by default delta is provided in pixel units, though there are also line and page units, normalized to pixels.

Good to know, I had actually forgotten that speed is quite small on the order of 1/600, but that makes this also make more sense as to what circumstances evince the bug behavior better. I'll make an issue about refactoring the zoom codebase in general, but also specifically include to re-think this hacky `speed` property in general.

File: bokehjs/src/lib/core/util/zoom.ts (hunk 1 above)
Comment (bryevdv) [reply bokehjs/src/lib/core/util/zoom.ts:15]: I agree 0.95 is somewhat arbitrary, but it just needs to be strictly less than one (`factor=1` has its own issue with letting range `start == end` which blows up for different reasons). Happy to change it to 0.99 or anything else suggested. Can include re-thinking this in the follow-on issue.

**Comment by bryevdv** [comment]
@mattpap I added two basic unit tests to cover when either `speed` or `delta` is large in https://github.com/bokeh/bokeh/pull/14275/commits/aca1c18fc7337117b04bd44f849289edfc2d64ca

I'd like to leave anything else (including better tests) to a follow-on issue and get this merged for 3.6.3

**Review by mattpap — APPROVED** [review]
Looks good. Let's follow on this in a new issue.

**Comment by douglas-raillard-arm** [comment]
I gave a go at this PR (installed from github by running `npm ci` in bokehjs/ and then `pip install .`) and while it's a lot harder to get the axis flip than before, it still happens if trying long enough. So maybe there are multiple causes for it and you fixed the most common one ?

EDIT: here is the HTML plot I can reproduce the issue with:
[plot.zip](https://github.com/user-attachments/files/18655975/plot.zip)

EDIT2: And here is the screenshot of flipped axes when using it:
image

**Comment by bryevdv** [comment]
> I gave a go at this PR (installed from github by running npm ci in bokehjs/ and then pip install .

@douglas-raillard-arm You have to take more steps to [use a local BokehJS](https://docs.bokeh.org/en/latest/docs/dev_guide/setup.html#bokeh-resources), so if those are all the steps you took, then your browser was using the last previously released version from CDN (i.e. with the bug still there). 

If you can reproduce something with the actual 3.6.3 release today or tomorrow, then please open a *new* issue referencing the old one.

**Comment by bryevdv** [comment]
@douglas-raillard-arm I confirmed from your HTML file that your page was still using an old version (and not even a released one, perhaps your local checkout was also  not at branch-3.6 TOT?):
```
    <script type="text/javascript" src="static/extensions/panel/bundled/datatabulator/luxon/build/global/luxon.min.js"></script>
    <script type="text/javascript" src="https://cdn.bokeh.org/bokeh/dev/bokeh-3.6.0.dev1.min.js"></script>
    <script type="text/javascript" src="https://cdn.bokeh.org/bokeh/dev/bokeh-gl-3.6.0.dev1.min.js"></script>
    <script type="text/javascript" src="https://cdn.bokeh.org/bokeh/dev/bokeh-widgets-3.6.0.dev1.min.js"></script>
    <script type="text/javascript" src="https://cdn.bokeh.org/bokeh/dev/bokeh-tables-3.6.0.dev1.min.js"></script>
    <script type="text/javascript" src="https://cdn.bokeh.org/bokeh/dev/bokeh-mathjax-3.6.0.dev1.min.js"></script>
```
